webservices/setup/nginx_conf_default

fixes problems with rendering pages at https://fec.18f.us/eregs/

serve static files directly from openFEC directory

---

documentation/committee.md
webservices/rest.py
webservices/test_api.py

- Adds committee name to the candidate endpoint
- Adds candidate name and office_sought to the committee endpoint.
closes #246

Added the fields asked for in #246, with tests and documentaion

---

documentation/committee.md
documentation/committee_type.md
webservices/rest.py

the designation filtering was too tight so joint committees etc were not getting through

Show all related committees if all fields are asked for

---

webservices/rest.py
webservices/test_api.py

Fix a bug to show the candidate name on the committee endpoint.

Name field fix

---

documentation/totals.md
webservices/rest.py
webservices/test_api.py

Choose a cycle to filter on for the summary stuff
closes #280 
(Also standardized some of the names)

Cycle totals

---

documentation/candidates.md
documentation/committee.md
documentation/index.md
documentation/totals.md
webservices/rest.py

I tried to borrow from current FEC documentation when possible.

Fleshed out documentation to include a bit of context. 

---

documentation/notebooks/architecture.ipynb

Added names of FEC machines, so we can't lose them in the void again

---

webservices/resources.py

Cleaning up/consolidating parsing of `fields` param

---

webservices/setup/nginx_conf_default

Pretty sure this is how to do this. Can someone who is more comfortable in nginx config land verify? Fixes #267.

Enable CORS and set utf-8

---

data/sql_updates/create_candidates_vw.sql
webservices/resources/candidates.py

Uses cases to to the decoding in sql instead of using a dict. Updates the candidate models to reflect the new fields. Makes all the fields filterable.

Cases ici and status

---

webservices/totals/models.py

Added an inclusive list of pac and party codes.

quick fix for unqualified

---

data/ddl/calculated.sql
data/ddl/fulltext.sql
data/ddl/in_rds_ddl.sql
data/ddl/keys.sql
data/ddl/keys_processed.sql
data/ddl/materialized.sql
data/ddl/populate_bogus_expire_date.sql
data/ddl/processed_schema.in_rds.sql
data/ddl/processed_schema.to_rds.live.sql
data/ddl/processed_schema.to_rds.sql
data/ddl/psql_w_vars.sh
data/ddl/to_oracle_ddl.sql
data/ddl/to_rds_ddl.live.sql
data/ddl/to_rds_ddl.sql
data/synch/fill_cmte_dates.sql
data/synch/push_in_chunks.py
data/tuning/tuning_framework.sql

Hopefully these will help make Alison sense of the mess.

Adding documentation to data-handling scripts

---

webservices/resources/committees.py

For @LindsayYoung 
- API works but returns whole Candidate objects

Fixed link between Candidate and Committee

---

webservices/resources/committees.py

I think this may fix your date handling problem. Simplified it by extracting the year for comparison from the datetimes, and that made it clear that the operators were switched.

Fixed committee date handling for single years -- I think

---

data/sql_updates/create_committees_vw.sql
webservices/common/models.py
webservices/resources/committees.py

- Moving the join to the database eliminates a lot of sqlalchemy
headache

Added candidate_ids to committee view

---

data/sql_updates/create_totals_house_senate_view.sql
data/sql_updates/create_totals_pacs_parties_view.sql
data/sql_updates/create_totals_presidential_view.sql
webservices/resources/totals.py

This will add the earliest coverage date as `coverage_start_date` and the latest as `coverage_end_date`.

Added coverage dates to totals endpoint

---

data/sql_updates/create_linkage_names_vw.sql
data/sql_updates/run_all.sql
webservices/common/models.py

Renamed a table to be within our prefix "namespace".

Namespace view

---

webservices/resources/reports.py

Expire dates

---

webservices/common/util.py

Just added future candidates to the default for better results. This will fix Harry Reid not showing up because while he has not ran for election in the last 4 years. Now, he will show up because he is on the 2016 ticket.

This fixes #447 Reid bug.

---

CONTRIBUTING.md

Suggested change. The nice thing about this is that it makes the work-in-progress-ness explicit, as opposed to the more implicit assigned/unassigned convention. What do you all think?

Changed the PR procedure to include usage of '[WIP]' in the title.

---

README.md

Ran into this problem when setting up project.

Updated README about python3

---

data/sql_updates/create_candidate_detail_view.sql
data/sql_updates/create_candidates_view.sql
data/sql_updates/create_committee_detail_view.sql
data/sql_updates/create_committees_view.sql
data/sql_updates/create_linkage_names_view.sql
data/sql_updates/create_reports_house_senate_view.sql
data/sql_updates/create_reports_pacs_parties_view.sql
data/sql_updates/create_reports_presidential_view.sql
data/sql_updates/create_totals_house_senate_view.sql
data/sql_updates/create_totals_pacs_parties_view.sql
data/sql_updates/create_totals_presidential_view.sql
webservices/common/models.py

Columns that are going to be queried should probably have an index. This patch adds indices on all columns that are filtered on in `resources`. Depends on #541.

Index queried fields

---

webservices/resources/candidates.py
webservices/resources/committees.py
webservices/resources/reports.py
webservices/resources/totals.py

This removed the year defaulting on the singe resources, they can sill be filtered by year if the user requests a year.
fix #565
fix #567

Removed the year filering on singe resources.

---

run_api.py

- This version drives the DEBUG setting
- Fixes issue where having PRODUCTION defined at all would always make
DEBUG = False

Changed PRODUCTION env parsing

---

data/sql_updates/create_fulltext_table.sql
webservices/resources/candidates.py
webservices/resources/committees.py
webservices/rest.py

Based on discussion in #fec with @arowla and @LindsayYoung 
* Use materialized views instead of tables for fulltext search
* Drop fulltext search tables

Materialize fulltext tables.

---

manage.py

* Delete extra declaration of `update_schemas`
* Run files in `sql_prep` in parallel

Reconcile parallel changes to manage.py.

---

CONTRIBUTING.md

Aims to do justice to the document that @arowla, @LindsayYoung and I came up with and @rjmajma, @noahmanger and @micahsaul reviewed. Please make edits or suggestions as needed.

Adding dev issue and PR rules

---

webservices/rest.py

adding ips

---

manifest_prod.yml

- Wrong NR environment was specified

Fixed bug in production manifest

---

webservices/resources/totals.py

Soarting most recent total first. issue #631

---

data/sql_updates/create_candidate_history_view.sql

After the switch to Golden Gate, the meaning of the `load_date` column
no longer indicates the election year correctly. Currently, all load dates
in the `dimcandproperties` table fall within 2015. This patch uses the
`election_yr` column instead.
@LindsayYoung, this resolves the issue you caught earlier today about candidate histories only being found for the 2016 cycle. I wasn't sure which column to use instead of `load_date`, which now basically uninformative, but `election_yr` seemed like the only reasonable option in `dimcandproperties`. @LindsayYoung @arowla let me know if you have any concerns.

Use `election_yr` instead of `load_date`.

---

data/sql_updates/create_fulltext_table.sql

We currently build committee names different in the committee and
committee detail views versus the full-text search view. This means that
it's possible to find committee names in the typeahead search, click on
a name, and not find that name in the committee results page. This patch
updates the full-text search view to use the same logic to build
committee names as used in the other committee views. This also replaces
some indirection using `load_order` with `select distinct` plus `order
by`, which is more consistent with the rest of the import scripts.
Thanks @rdpiazza reporting!
attn @LindsayYoung @arowla
[Resolves #676]

Harmonize committee names across views.

---

data/sql_updates/create_totals_house_senate_view.sql
data/sql_updates/create_totals_presidential_view.sql
webservices/resources/totals.py

- Harmonized some totals field names between committee types
- Merged from `develop`, resolved conflicts

(Nesting refactor) Harmonized field names, resolved conflicts

---

data/sql_updates/create_candidate_detail_view.sql
data/sql_updates/create_candidates_view.sql

Getting election year for candidates from dimcandoffice election year, which seems like a more reliable place to get that.

Feature/better election years#657

---

webservices/tests/report_tests.py

These tests were meant to go into #694, but I forgot to check them in. Here they are!

Forgot to check in reports tests earlier.

---

data/sql_updates/create_linkage_names_view.sql

See #673 for description.
[Resolves #673]

Exclude unauthorized committees from linkage table.

---

data/sql_prep/create_years.sql

- this should fix the schema updates, which were failing right out of the gate

Added 'cascade' to drop of years table

---

tasks.py

Fix problems discovered by @arowla such that subsets can be created and imported regardless of environment. @arowla would you mind checking this out and verifying that it works on your machine when you have time? Thanks / sorry.
"But it worked on my laptop™"

Make subset work outside my environment.

---

README.md
bin/post-checkout
bin/post-merge
tasks.py

Parallel to
https://github.com/18F/openFEC-web-app/commit/9f33fe18f2187f8d6dfdbe3e41de0ccae2d1ee63

Add optional hooks for dependency management.

---

CONTRIBUTING.md

This is an attempt to clarify the workflow. Plz let me know what you think -- especially with the timeboxing part; that's just a stab in the dark.

Leah contributing

---

.buildpacks

Forgot to include this in the last PR.

Check in buildpacks.

---

data/sql_updates/create_totals_presidential_view.sql
webservices/common/models.py
webservices/schemas.py

adding total_offsets_to_operating_expenditures to presidential total API output.

One last variable for summary stats

---

data/sql_updates/create_fulltext_table.sql

This patch resolves some inconsistencies in the way we build full-text
search data across different views. Previously, the combined full-text
view used only the most recent candidate and committee properties, but
the separate views (`dimcand_fulltext_mv` and `dimcmte_fulltext_mv`)
aggregated across *all* properties per entity over time. This patch
modifies the separate views to build names in the same way as the
combined view.
[Resolves #753]

Use most recent data for full-text search.

---

data/sql_updates/create_committees_view.sql

Fix a typo in the committee list view that was fixed for the committee
detail view in #703. Should partially resolve #743.

Harmonize committee list and committee detail views.

---

.travis.yml
setup.cfg

Analagous to 18F/openFEC-web-app#171

Trying out codecov.io integration

---

data/sql_updates/create_candidate_detail_view.sql

there are some holes in this data so we want the lat time it was updated
The example we have been using for testing is Nancy Pelosi

Fixing incumbent

---

data/sql_updates/create_candidate_detail_view.sql
data/sql_updates/create_candidates_view.sql

Some rows in `dimcandproperties` have non-null values for `cand_ici_cd`
and null values for `cand_ici_desc`. We already build incumbent
description values manually in the candidate list view, but not in the
candidate detail view. The two views also pull incumbent status values
differently. This patch updates both views to use the correct logic.
@LindsayYoung, I completely forgot about this when I merged #767. My mistake! In other news, this appears to finally fix the incumbent status for Nancy Pelosi.

Harmonize incumbent status across views.

---

data/sql_updates/create_reports_house_senate_view.sql
data/sql_updates/create_reports_pacs_parties_view.sql
data/sql_updates/create_reports_presidential_view.sql
tests/test_integration.py

- Also had to add an explicit transaction to the test data subset to
override local psql settings (AUTOCOMMIT off)

Changed report views to exclude expired reports

---

requirements.txt

Useful for various fixes and API improvements. Most relevant: null
values will now be serialized as null, rather than 0, empty string, etc.

Upgrade marshmallow to development version.

---

data/sql_updates/create_candidate_history_view.sql
webservices/common/models.py
webservices/schemas.py

* Add election years and cycles to history table
* Needed to render cycle dropdown in webapp
* Restructure candidate models and schemas for code reuse

Backend updates to accommodate cycle filtering for candidates.

---

data/sql_updates/create_committee_history.sql
webservices/common/models.py
webservices/schemas.py

Add full addresses to committee history table.

---

webservices/rest.py

Just adding the url to the documention

updated help

---

webservices/common/models.py
webservices/schemas.py

Use `beginning_image_number` to generate PDF URL.

---

data/sql_updates/create_committee_detail_view.sql
data/sql_updates/create_committee_history.sql
data/sql_updates/create_committees_view.sql
data/sql_updates/create_fulltext_table.sql

See #877 for issue and reasoning.
[Resolves #877]

Calculate cycles from F1 and F3 filings.

---

webservices/spec.py

@LindsayYoung is working on actual text to replace the placeholders.
[Resolves #900]

Add placeholders for Swagger tag descriptions.

---

Procfile
README.md
manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
tasks.py
webservices/setenv.py

* Make blue and green copies of apps in manifests.
* Detect active version of app on push.
* Add route un/mapping after push.

Blue-green deploys.

---

manage.py

Fix the mysterious `SSL error: decryption failed or bad record mac` issue on data import.

Create new engine for each multiprocessing instance.

---

webservices/templates/swagger-ui.html

Update <title> for API docs.

---

webservices/docs.py

Add link to github fix in docs

---

manifest_base.yml
manifest_dev.yml
manifest_prod.yml
manifest_stage.yml

Self-explanatory. Tested on dev.

Smaller manifests with inheritance and promotion.

---

webservices/args.py

It looks better. I could not get the markdown to render lists in the table at all.

List of options now look like formatted code

---

data/sql_updates/create_totals_pacs_parties_view.sql
webservices/common/models.py

Was looking at the web app and saw we missed a total.

Added missing levin fund totals in API

---

README.md

Now with git-flow commands!
[Resolves #942]

Document git-flow and deployment workflow.

---

data/sql_updates/create_reports_pacs_parties_view.sql
data/sql_updates/create_totals_pacs_parties_view.sql

as total_individual_contributions_period it needed the _period.

Standardized the name of ttl_indv_contb

---

.buildpacks
Procfile
Staticfile
boot.sh
nginx.conf
webservices/rest.py
webservices/templates/swagger-ui-libs.html

Parallel changes to https://github.com/18F/openFEC-web-app/pull/276.

Deploy using nginx.

---

README.md

Self-explanatory, hopefully. @LindsayYoung and @arowla: the goal of the docs is to make sure that the team understands the changes I made to deployment in the event that I get hit by a bus or become a Jesuit or something, so please take a look and let me know if I should elaborate.

Update caching and deployment docs.

---

scripts/bootstrap/Vagrantfile
scripts/bootstrap/fec_bootstrap.sh
scripts/bootstrap/provision.sh
scripts/bootstrap/tmux/fec-local.yml

* Use postgres 9.4.
* Use sudo to install tmuxinator.
* Turn off password protection.

Update deploy script.

---

tests/test_api.py

Fixes failing tests due to a change in webargs.

Expect correct error code on invalid page queries.

---

webservices/resources/sched_a.py
webservices/resources/sched_b.py
webservices/spec.py

Slight ascetic improvement on the docs.

Separate filings from schedules.

---

tests/test_itemized.py
webservices/args.py

Fix image number range.

---

LICENSE.md

adding info & link about FEC data use restrictions

---

webservices/rest.py

[Resolves #1045]
h/t @gbinal
https://www.youtube.com/watch?v=8To-6VIJZRE

Add 301 redirect from `/developer` to canonical `/developers`.

---

tests/test_utils.py
webservices/args.py
webservices/resources/candidates.py
webservices/resources/committees.py
webservices/resources/totals.py
webservices/sorting.py
webservices/utils.py

And improve testing and documentation on sort utility.
This will be useful for hiding null values on sorted columns in the webapp--as @noahmanger discovered, sorting by fields with nulls can yield pages and pages of unwanted results. This is also a useful option for the API in general.

Allow hiding null values on sorted columns.

---

webservices/docs.py

added our variable name and we use a boolean

---

data/functions/acronyms.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_state.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_zip.sql
webservices/args.py
webservices/common/models.py
webservices/resources/aggregates.py

Add state labels to zip code aggregate.

---

tests/filings_tests.py
webservices/args.py
webservices/resources/filings.py

adding candidate_filering to filings

---

data/sql_incremental_aggregates/update_schedule_b_fulltext.sql
data/sql_setup/prepare_schedule_b.sql
webservices/args.py
webservices/common/models.py
webservices/resources/sched_b.py

Required for https://github.com/18F/openFEC-web-app/issues/343

Add full-text search on disbursement purpose.

---

CHANGELOG.rst

This is a small proposed release to production for the API only. I've documented the major differences in the changelog, which now exists here: https://github.com/18F/openFEC/blob/release/public-beta-20150722/CHANGELOG.rst.
Note: This shouldn't be merged through GitHub. Once the release is ready to go, I'll merge using git-flow.

[dontmerge] release/public-beta-20150722

---

tests/candidate_tests.py
tests/committee_tests.py
tests/factories.py
tests/filings_tests.py
tests/test_itemized.py
webservices/args.py

[Resolves https://github.com/18F/openFEC-web-app/issues/382]
[Resolves https://github.com/18F/openFEC-web-app/issues/383]

Use case-insensitive arguments where appropriate.

---

tasks.py

Map apps to 18f.gov instead of cf.18f.us. Will merge manually if approved.

[dontmerge] Hotfix/18f.gov

---

tests/test_elections.py
webservices/args.py
webservices/resources/elections.py

* Rename "presidential" to "president"
* Un-cap page size on election view
* Update tests

Miscellaneous updates for election pages.

---

data/sql_setup/prepare_schedule_a.sql
webservices/common/models.py
webservices/resources/sched_a.py

Required for https://github.com/18F/openFEC-web-app/pull/408.

Filter receipts on contributor occupation.

---

data/sql_updates/create_reports_presidential_view.sql
data/sql_updates/create_totals_house_senate_view.sql
data/sql_updates/create_totals_pacs_parties_view.sql
data/sql_updates/create_totals_presidential_view.sql
tests/test_elections.py
tests/totals_tests.py
webservices/common/models.py
webservices/resources/elections.py
webservices/schemas.py
webservices/utils.py

* Add fields to election endpoint
* Use totals rather than summed filings for financials
* Update tests

Improve election views.

---

data/sql_updates/create_committee_history.sql

Revert temporary workaround for missing receipt dates.

---

tests/test_elections.py
webservices/resources/elections.py
webservices/schemas.py

Necessary for https://github.com/18F/openFEC-web-app/issues/449.

Include committee IDs in election view endpoint.

---

manage.py
utils.py

To be used with the election lookup tool in the webapp. This will help us show the right number of district options for the selected state, as discussed with @noahmanger.

Add script to output district count per state.

---

tests/test_filings.py
webservices/resources/filings.py
webservices/rest.py

To be used for the candidate filings tab in the webapp.

Add candidate filings endpoint.

---

data/sql_updates/create_candidate_history_view.sql

Fixes office sorting in the webapp.
[Resolves https://github.com/18F/openFEC-web-app/issues/466]

Index `office_full`.

---

tests/test_elections.py
webservices/resources/elections.py

* Hide history entries between cycles
* Hide history entries for not-yet-a-candidate filers

Hide extraneous races from election lookup.

---

data/sql_updates/create_sched_e_aggregate_candidate.sql
tests/factories.py
tests/test_aggregates.py
tests/test_filters.py
tests/test_utils.py
webservices/args.py
webservices/common/models.py
webservices/common/views.py
webservices/filters.py
webservices/resources/aggregates.py
webservices/resources/elections.py
webservices/resources/filings.py
webservices/resources/sched_a.py
webservices/resources/sched_e.py
webservices/rest.py
webservices/schemas.py
webservices/utils.py

Prerequisite for https://github.com/18F/openFEC-web-app/issues/394.

Aggregate independent expenditures.

---

data/sql_updates/create_candidate_history_view.sql
webservices/common/models.py

Necessary for https://github.com/18F/openFEC-web-app/issues/587.

Include list of election districts in candidate summaries.

---

webservices/docs.py

This came up in #1177 and has been brought up by several users.

Adding the rate limit information, page limit and link to bulk data.

---

webservices/rest.py
webservices/templates/swagger-ui.html

Add web analytics to Swagger-UI.

---

data/sql_updates/create_candidate_history_view.sql
data/sql_updates/create_committee_history.sql

[Resolves https://github.com/18F/openFEC-web-app/issues/664]

Use all filings to get active committee years.

---

webservices/args.py
webservices/common/views.py
webservices/resources/aggregates.py
webservices/sorting.py
webservices/utils.py

Add sorting on related columns.

---

webservices/args.py
webservices/resources/sched_e.py

Used by candidate Schedule E filings tab in the webapp.

Add cycle filter on Schedule E resource.

---

webservices/docs.py

@leahbannon Adding the google group and stackexchange info

Added contact info back

---

data/sql_updates/create_sched_e_aggregate_candidate.sql

Here's the latest aggregation query for independent expenditures, based on discussion in #1227.
Many thanks @paulclark2, @jwchumley, @lindsayyoung for guidance here.

Combine transactions from `sched_e` and `form_57` tables.

---

data/sql_updates/create_candidate_history_view.sql

Pinging @LindsayYoung for review.

Restrict active elections and cycles to F2 filings.

---

data/sql_updates/create_candidate_history_view.sql

Revert "Restrict active elections and cycles to F2 filings."

---

webservices/rest.py
webservices/utils.py

Restore API key to docs in production.

---

webservices/docs.py

We have done some renaming without versioning.

Being up front about changes

---

.travis.yml

Update with new continuous deployment credentials.

Update travis secrets.

---

webservices/docs.py
webservices/spec.py

using fec text [http://www.fec.gov/finance/disclosure/electioneering.shtml](http://www.fec.gov/finance/disclosure/electioneering.shtml)

defined electioneering 

---

data/sql_incremental_aggregates/prepare_schedule_a_aggregate_contributor.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_employer.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_occupation.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_size.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_state.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_zip.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_purpose.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_recipient.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_recipient_committee.sql
data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql
data/sql_setup/prepare_schedule_e.sql
data/sql_updates/post_totals_create_totals_unitemized.sql
webservices/config.py

* Create aggregates from 2007-present.
* Separate aggregate and itemized year cutoffs.
[Resolves #1250]

Aggregate itemized reports back to 2007.

---

requirements.txt
tests/test_integration.py
webservices/resources/aggregates.py
webservices/resources/candidate_aggregates.py
webservices/resources/candidates.py
webservices/resources/committees.py
webservices/resources/dates.py
webservices/resources/elections.py
webservices/resources/filings.py
webservices/resources/reports.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py
webservices/resources/sched_e.py
webservices/resources/totals.py
webservices/rest.py
webservices/spec.py
webservices/utils.py

Now with args from the querystring.

Parse args from querystring.

---

webservices/resources/elections.py

Related to https://github.com/18F/openFEC-web-app/issues/766.

Sort election results by district.

---

data/sql_updates/create_candidate_history_view.sql

Partial revert of #1252
Resolves #1275

Remove candidate status check in full text view.

---

webservices/docs.py

updating docs to match the new amended filtering #1289

---

README.md
system-security-plan.yml

Includes badge for Quantified Code results in the README.

Document for authority to operate beta release

---

CHANGELOG.md

See https://github.com/18F/openFEC/blob/release/public-beta-20151026/CHANGELOG.md for full changelog.

Rebuild CHANGELOG.

---

CONTRIBUTING.md
LICENSE.md
README.md

[ci skip]
@leahbannon @LindsayYoung @jenniferthibault @noahmanger @jmcarp

Standardizes readme language

---

scripts/bootstrap/fec_bootstrap.sh

See [this blog entry][1] for why I didn't use `set -e`. Fixes #1246.
[1]: http://david.rothlis.net/shell-set-e/

Made fec_bootstrap.sh exit if a command fails.

---

webservices/docs.py

Should be "whether"
Resolves: 18F/FEC/issues/139
cc @LindsayYoung

Eliminates weather

---

README.md

Adds StoriesonBoard line
Per feedback from Content Critique group:
- Moves licensing to bottom
- Makes "Installation" fall under larger "Set up" heading
- Tweaks to language and repository information
cc @noahmanger

Content edits

---

webservices/docs.py

"Data is updated nightly."
fix #381

adding data updated nightly to API docs

---

.about.yml

This should resolve the validation errors seen on the staging dashboard

openFEC about.yml updates

---

.codeclimate.yml

Ignore test files on code climate.

---

requirements.txt
webservices/rest.py

Log errors using Sentry.

---

webservices/resources/dates.py

Use correct args on election dates resource.

Fix election date args

---

webservices/docs.py

We did not explain the IE aggregates in the documentation. 
h/t @corbyhobbs

adding schedule e aggregate information.

---

data/functions/acronyms.sql
data/sql_updates/create_omnibus_dates.sql
webservices/args.py
webservices/common/models/dates.py
webservices/resources/dates.py
webservices/schemas.py

Just a few miscellaneous changes from frontend work.
* Add missing acronym helper
* Add indexes on calendar dates
* Exclude text columns from schemas
* Fix typos

Miscellaneous date cleanup.

---

data/sql_updates/create_committee_history.sql
tests/test_committees.py
webservices/args.py
webservices/common/models/committees.py
webservices/resources/committees.py
webservices/schemas.py

Expose full-text filter on committee treasurer name.

---

data/sql_updates/create_omnibus_dates.sql
webservices/args.py

h/t @noahmanger @jenniferthibault

Condense reporting deadline categories.

---

data/sql_updates/create_committee_history.sql
webservices/common/models/committees.py

Per discussion with @PaulClark2 and @noahmanger, include dates of first
and last filings of any type, plus date of last F1.
[Resolves #1428]

Update committee filing dates.

---

tests/test_dates.py
webservices/calendar.py

Add high-level tests for calendar exports.

---

data/functions/purpose.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_purpose.sql
data/sql_setup/prepare_schedule_b.sql
webservices/args.py
webservices/common/models/itemized.py
webservices/resources/sched_b.py

After we talked about this today, I remembered that I had most of this patch written from a month or two ago.
Part of #1454.

Filter on disbursement purpose category.

---

data/sql_updates/create_omnibus_dates.sql

Fix type and aggregate.

---

data/functions/utils.sql
data/sql_updates/create_communication_cost_view.sql

Handle invalid dates in communication costs.

---

webservices/resources/costs.py

should be with other resources in electioneering and communication cost

Move to correct category

---

webservices/tasks/__init__.py

Restore nightly refresh to celery-beat.

Fix path to refresh task in scheduler.

---

requirements.txt
webservices/tasks/download.py

Fixes an error on downloading itemized independent expenditures such
that table headers were inconsistent with field names.

Handle related fields in data export.

---

data/sql_incremental_aggregates/update_schedule_e.sql
data/sql_setup/prepare_schedule_e.sql
webservices/args.py
webservices/resources/sched_e.py

Prerequisite for hiding non-F3X items on the webapp.

Filter itemized IEs on filing form.

---

manage.py
manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
webservices/config.py

Abort deploy if:
* Environment variables or credentials missing
* Cloud Foundry services missing
* Required tables missing
Part of https://github.com/18F/openFEC-web-app/issues/1020.
cc @LindsayYoung

Abort deploy on invalid configuration.

---

webservices/tasks/download.py

Whitelist cost views for export.

---

data/sql_updates/create_omnibus_dates.sql

reformats report code

---

README.md

Adding the following to the readme.
```
pip install -r requirements-dev.txt 
npm i 
```
per issue: #1519

adding requirements-dev and npm i to readme

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
webservices/config.py
webservices/tasks/utils.py

Use S3 service in Cloud Foundry.

---

data/sql_updates/create_omnibus_dates.sql

Just a little inline documentation. @ccostino since you haven't looked at it maybe you would be a good to just eyeball this file and judge if this is helpful or if there are additional things to document. We don't need to spend a lot of time on it, hopefully this script will be replaced with a better input method.

Adding some more inline docs closes #1533

---

.travis.yml
README.md
manifest_base.yml
tasks.py

* Replace homegrown blue-green deploy with autopilot
* Store deploy meta-data in .cfmeta
* Update deploy docs
[Resolves #1511]
Note: once this is reviewed and merged, we'll want to make parallel changes in openFEC-web-app and fec-cms. Since @ccostino is assigned to implement continuous delivery on fec-cms in https://github.com/18F/fec-cms/issues/188, I'm assigning you to review this.

Use autopilot for zero-downtime deploys.

---

manifest_base.yml

Adding 1G of memory

---

manage.py

Since the names of the management commands sound similar

Trying to be extra explicit

---

manifest_feature.yml

This adds the manifest for the new `feature` space. I have already deployed this on the space, so I know it works :).

adding feature space manifest

---

LICENSE.md
README.md

Makes updates to README content

---

data/sql_updates/omnibus_dates.sql

This was part of the next PR but there isn't a reason for it to wait. 
I ran this on staging if you want to take a look.
The other more complicates state filtering  PR is on dev (as of 05/24/2016).

Add title case to party

---

data/sql_updates/candidate_aggregates.sql
data/sql_updates/candidate_flags.sql
tests/factories.py
webservices/args.py
webservices/common/models/candidates.py
webservices/docs.py
webservices/resources/candidates.py
webservices/schemas.py

We are going to have to run more sql updates for this.

Changing the 5k flag to has_raised_funds

---

manifest_prod.yml
manifest_stage.yml

This adds the elasticsearch service to staging and prod.

adding elasticsearch service to stage and prod

---

requirements.txt

temporarily helps #1695 
Use git flow to merge into master and dev branches:
http://danielkummer.github.io/git-flow-cheatsheet/

The api is currently incompatible with Flask .11

---

webservices/docs.py

Incorrect definition was overwriting correct definition.

fix report year definition

---

bin/run.sh
tasks.py

Turning off slack notifications till intergration service is back

Turning off slack notifications till intergration service is back

---

bin/run.sh

[MERGE WITH GETFLOW] turn off slack for now

---

webservices/docs.py

This is a small text change we talked about in sprint planning I am using it to test our Travis deployment.

Remove reference to changelog

---

webservices/flow.py

cand_cmte_linkage needs to be built before candidate_aggregates

Add missing dependency for schema updates

---

requirements.txt

Flask version fix, the fix was to update Flask-RESTful

Flask Versioning fix

---

system-security-plan.yml

Adding link to updated system diagram

---

README.md
tasks.py

This changeset accounts for recent changes with our CloudFoundry setup and only logs you in if necessary now.
h/t @adborden for the same work in the web app.
/cc @LindsayYoung, @anthonygarvan, @adborden, @jontours, @noahmanger

Update CloudFoundry login setup

---

tasks.py

The login stays the same for Travis, we use the new format. Correct me if I am wrong, but the new way doesn't work on Travis and the old way does.

2nd try at new travis and local log in

---

tasks.py

This changeset ensures that we are properly specifying the API to use before authenticating if need be.
h/t to @adborden again for catching this.
/cc @LindsayYoung, @jontours, @adborden, @anthonygarvan, @noahmanger

Target cloud.gov api for deploy

---

.travis.yml

in the before deploy in Travis

Adding the build step for the documentation 

---

.travis.yml

Reverts 18F/openFEC#1767
It did not work

Revert "Adding the build step for the documentation "

---

.buildpacks
.cfignore
.gitignore
manifest_base.yml

that expires in January, but the documentaion works now

Reverting #1645 this puts us back on the old multi buildpack 

---

webservices/common/models/itemized.py
webservices/docs.py
webservices/schemas.py

Adding this early, people might want to start using that now since we are depreciating the other name.

Expose memo code

---

data/functions/calendar.sql
data/sql_updates/omnibus_dates.sql

This adds a link to the reporting page. 
We originally wanted more granular links, but the link generation used different coding so it is difficult to reproduce. 
close  #1697

Adding links to the main reporting page for the year.

---

data/sql_updates/totals_pac.sql
data/sql_updates/totals_party.sql
tests/test_integration.py
webservices/args.py
webservices/common/models/totals.py
webservices/docs.py
webservices/flow.py
webservices/resources/reports.py
webservices/resources/totals.py
webservices/schemas.py

Open to different ways of doing this, i.e. let me know if there is something glaringly wrong with this strategy.  
That strategy consists of adding materialized views to support pac/party information, and new models and filters to support them.  At first adding MV(s) for these seemed heavy handed, but maybe not if more and more super pacs come into existence.
Work left to be done is perhaps adding a new view class for this functionality, although it may not be needed.

Modify pac/party committee for filtering, sorting [WIP]

---

data/sql_updates/omnibus_dates.sql

We can add more specific links later.

Adding general reporting page link for reporting periods

---

webservices/args.py

This will fix the detail panel on web
fix #1782

Fixing args so that the datatype for image numbers are strings

---

data/sql_updates/totals_house_senate.sql
data/sql_updates/totals_pac_party.sql
data/sql_updates/totals_presidential.sql
webservices/common/util.py
webservices/sorting.py

This fix is by no means pretty, if anything don't merge it.  If worse comes to worse it can be merged to buy us more time, but it works.  Figuring out the real data issue should be the better fix.

Fix for candidate totals bug

---

webservices/resources/candidate_aggregates.py
webservices/rest.py

It would be really great if someone could help me out with the description wording.  I believe terse is always the best, but don't want to leave out any other important details.   @LindsayYoung @ccostino

Added candidate/totals to swagger docs

---

data/functions/individual.sql

Remove 18J as an individual line item
close #1832

Fix individual calculations

---

manage.py

This changes the code a little bit to deal with logging error messages in a cleaner way. I meant to commit it with previous PR but forgot to save the file (:doh:).

logging tweak

---

manage.py

Taking out redundant schedule e update

---

manage.py
webservices/resources/legal.py
webservices/rest.py

Note this branch is badly named now, it actually adds a new endpoint, not a new keyword to the existing search endpoint.

adding api for advisory opinion canonical page

---

webservices/resources/legal.py

This removes the heuristic to prioritize final opinions.

disabling prioritizing final opinion

---

requirements.txt

This changeset updates and pins the following packages in our project:
* psycopg2
* sqlalchemy
* pyelasticsearch
/cc @LindsayYoung, @jontours, @anthonygarvan, @adborden

Update and pin new package versions

---

tests/test_legal.py
webservices/resources/legal.py

@anthonygarvan I'd appreciate you taking a look at this. I'll set this up on `feature` so that folks can play around with it.

Legal phrase search

---

requirements-dev.txt
requirements.txt

Bug fix/update requirements

---

tests/factories.py
tests/test_itemized.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py
webservices/resources/sched_e.py

[USE GITFLOW]Hotfix/sorting error

---

manage.py

This fixes the issue fec-partners were seeing when trying to search for regulations numbers and not seeing them as the top hit.

[merge with git flow] Hotfix: import all subparts from regulations

---

manage.py
webservices/load_legal_docs.py

- Remove the duplicate legal loading code
- Move the hotfix from manage.py to load_legal_docs

Remove duplicate code

---

manage.py

This changeset fixes an issue recently introduced with duplicate imports in our `manage.py` script.
/cc @LindsayYoung, @jontours, @anthonygarvan, @adborden

Fixes duplicate imports

---

webservices/docs.py

I think I made the change in the right place. @LindsayYoung is this right?
Resolves https://github.com/18F/openFEC/issues/1926

Changing rate limit docs

---

.travis.yml

This changeset addresses an issue with our Travis CI config in which we were upgrading our pinned project dependencies.
/cc @LindsayYoung and @jontours

Fix Travis CI setup for pip

---

data/sql_updates/rad_analyst.sql

There are spelling errors in the underlying data. This function fixes them. 
closes #1974

fix pary to party

---

webservices/tasks/refresh.py

This fixes the refresh error on dev.

fixing refs, removing reg sync and adding mur sync

---

webservices/common/models/large_aggregates.py

The right variable names help!

showing cumulative 

---

webservices/schemas.py

@ccostino @LindsayYoung comments out csv urls.

Commenting out field from schema

---

data/sql_updates/large_aggregates.sql
webservices/rest.py

Better, party and other totals need work

Removes amended records

---

webservices/tasks/refresh.py

There is an error on import we can fix later

Stopping mur update for now

---

README.md

Anyone can review. So fast! This will be super fast for you! <3

Capitalizes president

---

manage.py
webservices/legal_docs/__init__.py
webservices/legal_docs/load_legal_docs.py

This enables stemming (eg. "presidents" returns results for "president") under the english analyzer in elasticsearch.

adding enable_stemming function

---

data/sql_updates/large_aggregates.sql
data/sql_updates/omnibus_dates.sql
requirements.txt
webservices/common/models/large_aggregates.py
webservices/rest.py

Trying to get the totals to line up with what we had before.
- made changes suggested by Jon and Paul

Working on making the charts better

---

data/functions/urls.sql
data/sql_updates/filings.sql
data/sql_updates/reports_house_senate.sql
data/sql_updates/reports_ie.sql
data/sql_updates/reports_pac_party.sql
data/sql_updates/reports_presidential.sql
webservices/args.py
webservices/common/models/filings.py
webservices/common/models/reports.py
webservices/docs.py
webservices/resources/filings.py
webservices/resources/reports.py

Also gonna add some logic to generate the fec urls via sql function.  We mentioned that before as a task and since it's so closely related knocking that out here as well.

Add means_filed to reports and filings endpoints

---

.travis.yml

This changeset fixes an earlier issue with the new credentials we created for Travis CI.
/cc @LindsayYoung

[MERGE WITH GIT FLOW]: Fix Travis CI credentials

---

webservices/common/models/filings.py

should fix efile file endpoint

[MERGE WITH GITFLOW] removed FEC url form model. I think it conflicted with the mixin

---

tests/factories.py
tests/test_filings.py
tests/test_reports.py
webservices/common/models/filings.py
webservices/common/models/reports.py
webservices/resources/reports.py

No idea why the sort test does not return reciept_date

Adding some efiling tests

---

opencontrol.yaml

Making progress on this for ATO renual

open control yaml 

---

tests/test_itemized.py
webservices/args.py
webservices/docs.py
webservices/sorting.py
webservices/utils.py

Still need to add logic for plugging in right min/max value depending on column data type (simple dict should do it)

Pagination with null sort columns

---

requirements-dev.txt

Pulls new dependency in to address fake-factory deprecation.

Faker library added

---

data/sql_updates/large_aggregates.sql
requirements-dev.txt
tests/test_large_aggregates.py
webservices/common/models/large_aggregates.py

cumulative_candidate_disbursements

misspelling causing chart error

---

newrelic.ini
requirements.txt

Related to https://github.com/18F/openFEC-web-app/issues/1701
This changeset updates the New Relic configuration and dependencies to the latest versions.  We recently ran into an issue with the web app failing to monitor correctly due to this, so we would like to ward off that problem here as well.
/cc @tadhg-ohiggins, @LindsayYoung, @jontours

Update New Relic config

---

manage.py

This closes #2112
also made the quote styling the same

Adding explanations to management commands

---

data/sql_updates/committee_history.sql
data/sql_updates/communication_cost.sql

Removes remaining data warehouse table references, fec_vsum_f76 and wv_filing_history
Closes #2102 
This was the last mile on a long journey

getting off data warehouse

---

webservices/resources/sched_e.py

Addresses filter bug(s) from: https://github.com/18F/openFEC/issues/2157.

Argument changed back to right key

---

data/sql_updates/filings.sql

Filter out records marked for deletion [MERGE W/ GITFLOW]

---

data/sql_updates/filings.sql
webservices/schemas.py

Resolves https://github.com/18F/openFEC/issues/2094.  `update_schemas` must be run for this.

Remove fec_url from rfai_filings

---

data/sql_updates/rad_analyst.sql
webservices/args.py
webservices/common/models/rad_analyst.py
webservices/resources/rad_analyst.py

**MERGE WITH GIT FLOW**
This changeset is a duplicate of pull request #2168 except that it is intended to be deployed as a hotfix.  The folks in RAD need this functionality to be in place before our next release.
h/t to @patphongs for all of the work in the original PR!

[MERGE WITH GIT FLOW] Hotfix/rad analyst email

---

tests/test_load_legal_docs.py
webservices/legal_docs/index_management.py
webservices/legal_docs/load_legal_docs.py

When reinitializing legal docs on prod I encountered some issues. Doesn't need to be a hotfix since this is an async operation.

updates to legal doc load

---

data/sql_updates/reports_house_senate.sql
data/sql_updates/reports_ie.sql
data/sql_updates/reports_pac_party.sql
data/sql_updates/reports_presidential.sql
webservices/args.py
webservices/common/models/reports.py
webservices/resources/reports.py

This is not working but it is close.

Implement amendment filter for reports

---

webservices/schemas.py

This just uncomments the code that we had in place for csv downloads of filings.
@jontours is there anything else we need to do here? I tested it out and it all seems to work well.

Uncommenting csv urls

---

data/sql_updates/filings.sql
webservices/args.py
webservices/resources/filings.py
webservices/sorting.py
webservices/utils.py

As it turned out grouping committee filings was fairly easy, just have to tie in multiple sort options.

Implement multiple sort for filings

---

data/sql_updates/rad_analyst.sql
webservices/args.py
webservices/common/models/rad_analyst.py
webservices/resources/rad_analyst.py

Analyst title needed to be added as a parameter for the ServiceNow application. Please review for merge into production.

Added analyst title

---

webservices/common/models/filings.py
webservices/common/models/reports.py
webservices/schemas.py

This is a string with the format of `FEC-{file_number}`.  Added to all efiling endpoints, reports, and filings.

Add fec_file_id

---

webservices/tasks/refresh.py

Strategy for replacement will be figured out in  18F/openFEC#2220.

Remove calls to defunct methods for loading AOs

---

webservices/resources/legal.py

Nested queries with empty strings seem to return nothing.

Use a nested query only when query param present

---

data/sql_updates/candidate_history.sql

Made a left join an inner join- resolves the cases mentioned in #2210
closes #2210

Don't exclude candidates without valid party codes.

---

.travis.yml

Add prod creds

---

bin/run.sh
requirements.txt

This changeset makes a few improvements to the web server tooling we have in place.  It adds gevent for async request support in gunicorn and bumps the number of gunicorn workers up to 2.  It also updates the newrelic agent to the latest version.

Update web server tooling

---

webservices/resources/filings.py

TODO: see why the validator is not working and then restore it

[MERGE WITH GITFLOW] Fix efile/filings

---

tests/data/archived_mur_bad_pdf_doc.json
tests/data/archived_mur_doc.json
tests/data/archived_mur_empty_doc.json
tests/test_current_murs.py
webservices/legal_docs/advisory_opinions.py
webservices/legal_docs/current_murs.py
webservices/legal_docs/load_legal_docs.py

With the switch from East-West to the FR certified cloud.gov,
we have to set the S3 region correctly.

Use the us-gov-west-1 S3 region

---

webservices/resources/filings.py
webservices/utils.py

FRQ filers are included with results any time RFAI is passed as a filter.

FRQ Feature

---

webservices/resources/filings.py

Other form types were being erased by the logic, this preserves them adds FRQ.

Appends FRQ so as not to wipe out other arguments if they exist

---

data/sql_updates/totals_candidate_committee_house_senate.sql
data/sql_updates/totals_candidate_committee_presidential.sql

Fixed for Presidential, going to try and find a good test case for senatorial candidates.

Fixes missing cycles for presidential candidates

---

data/sql_updates/rad_analyst.sql

Use RAD analyst view from disclosure schema.

---

webservices/docs.py

closes #2404 
final change in: 
https://github.com/18F/swagger-ui/pull/12

remove beta language

---

data/sql_updates/filings.sql

This addresses a pre-flip issue, which was the duplicate filings.

Filters out SL form type filings

---

manage.py
webservices/tasks/__init__.py

Adding a refresh command and task that runs every 15 minutes

---

tasks.py

**MERGE WITH GIT FLOW**
The third time is the charm! :-)

[MERGE WITH GIT FLOW] Fix deploy run statement

---

data/sql_updates/totals_combined.sql

Ready for review after update schemas is finished and totals verified.

Reference correct column for loans

---

data/sql_updates/totals_combined.sql
data/sql_updates/totals_presidential.sql
webservices/common/models/totals.py

For committee profiles.  Completes open issue for this.

Fixes net_contributions and net_operating_expenditures

---

webservices/tasks/refresh.py

[MERGE WITH GITFLOW]remake schedule e nightly so that it is up to date

---

data/functions/acronyms.sql
tests/test_itemized.py
webservices/args.py
webservices/common/models/itemized.py
webservices/partition/sched_a.py
webservices/partition/sched_b.py
webservices/partition/utils.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py

Ready for review.  Partitioning has to be done for this as it adds a column to the itemized endpoints.  Since we have to do that again here soon I didn't see that as a problem.

Line number filter

---

data/functions/urls.sql
data/sql_updates/filings.sql
data/sql_updates/reports_house_senate.sql
data/sql_updates/reports_ie.sql
data/sql_updates/reports_pac_party.sql
data/sql_updates/reports_presidential.sql
webservices/common/models/filings.py
webservices/common/models/reports.py

Add html links to \reports and \filings

---

data/sql_setup/prepare_schedule_e.sql

Argh, test is failing when it really shouldn't.  I'm thinking it's in the test data.   Will update soon.

Union simplification for Schedule E

---

data/sql_setup/prepare_schedule_e.sql

This changeset addresses a few issues we uncovered while testing and validating the schedule E data updates we recently made for this release.  The form 5 filings had been lost and it did not resolve the missing 24/48 hour notices either.
/cc @jontours and @LindsayYoung

Fix schedule E definition

---

manifests/manifest_celery_worker_dev.yml

increased the celery-worker instance from 1 to 2.

Incremented the celery-worker instance to 2

---

data/functions/itemized.sql
data/sql_partition/partition_schedule_a.sql
data/sql_partition/partition_schedule_b.sql
manage.py
tests/test_integration.py
webservices/partition/base.py

Move add_itemized_partition_cycle feature to SQL

---

webservices/tasks/legal_docs.py

Add refresh of current MURs to the periodic legal_docs download task

Refresh current MURs periodically

---

data/load_murs_schema.sql

Include pg_date in view

---

webservices/schemas.py

Welp, turns out it was the code.  Schemas.py was breaking the marshalling of the JSON.  I did originally see the field in the json, but changed the name to the right name for the front-end, and forgot to remove this reference.  Sorry!
Resolves issues mentioned here: https://github.com/18F/openFEC-web-app/pull/2230

Fix for missing column

---

tests/test_itemized.py
webservices/docs.py
webservices/utils.py

Opened this in lieu of other PR that was failing for reasons I'm too tired to figure out.

cast last_index to string; updated docs

---

data/sql_updates/candidate_history.sql
tests/test_aggregates.py
tests/test_elections.py
tests/test_utils.py
webservices/common/models/candidates.py
webservices/resources/candidate_aggregates.py
webservices/resources/elections.py
webservices/schemas.py

Alabama issue resolved (although I'm seeing 24 candidates @PaulClark2, this can also be reflected by doing a select on ofec_candidate_history_mv for this special election).  Now debugging Colorado 6th district issues.

API fixes for election view page

---

webservices/resources/elections.py

Some small adjustments to fix issues @PaulClark2 found.  It fixes the issues with Alabama.  Haven't checked for Utah yet.

Election search fixes

---

webservices/resources/elections.py

Making sure we don't have duplicates

---

webservices/common/models/itemized.py
webservices/schemas.py

removing extra data from models

hotfix/ fix sched b

---

README.md
manifests/manifest_base.yml
manifests/manifest_dev.yml
manifests/manifest_prod.yml
manifests/manifest_stage.yml
manifests/manifest_task_dev.yml.template
manifests/manifest_task_prod.yml.template
manifests/manifest_task_stage.yml.template
webservices/config.py
webservices/tasks/__init__.py

I already created the high availability redis32 instances in dev, stage and prod.
After successful deploy, we will what to delete the old redis instance in each environment.

updating code for HA redis

---

README.md

Hi! I believe this fixes #2650.

Fix README links #2650

---

data/functions/calendar.sql

Taking out today from calendar descriptions because it didn't make sense in website context.

[MERGE WITH GITFLOW] hotfix/no-Today

---

data/crosswalks/f3x_reports.sql
data/sql_updates/totals_pac_party.sql

Adding operating expenditures to F3x

---

data/load_murs_schema.sql

Check for updates to MURs only

---

data/sql_updates/candidate_history.sql

sql script was modified to correct value in candidate_inactive column.
#2706

modify sql script to correct value in column candidate_inactive

---

README.md

Howdy!
I updated some urls to either avoid an http-> https redirect or redirect to a newer page. This helps improve user experience by going directly to a page and by avoiding potential link rot.
Thank you for your time!

Updated urls to avoid redirects

---

bin/run.sh
webservices/rest.py

We are initializing new relic earlier. It was not picking up on the many things that were happening before it was initilized. 
We don't use slacker anymore so I just cleaned that up.

this should give us better logging

---

bin/run.sh
requirements.txt
webservices/rest.py

**MERGE WITH GIT FLOW**
This changeset modifies the API logging configuration to ensure that as much info is possible is coming through into our logs to help provide visibility into what is happening at any given moment.  This includes a change to the Flask application configuration as well as the gunicorn startup command.
Furthermore, it also updates the newrelic and requests packages to ensure that we are using the latest versions and accounting for recent bugfixes and enhancements.
Information around this change was pulled from a few sources:
* https://github.com/benoitc/gunicorn/issues/379
* http://docs.gunicorn.org/en/latest/settings.html#loglevel
* http://flask.pocoo.org/docs/0.12/errorhandling/
* https://docs.cloudfoundry.org/devguide/deploy-apps/streaming-logs.html#types
* …

[MERGE WITH GIT FLOW] Improve logging setup and update New Relic and requests

---

data/sql_updates/omnibus_dates.sql

[MERGE WITH GITFLOW] Hotfix/calandar filter

---

package-lock.json
webservices/templates/swagger-ui-libs.html

Updating swagger template

---

manifests/manifest_celery_beat_dev.yml
manifests/manifest_celery_beat_prod.yml
manifests/manifest_celery_beat_stage.yml

Update
`manifests/manifest_celery_beat_dev.yml`
`manifests/manifest_celery_beat_stage.yml`
`manifests/manifest_celery_beat_prod.yml`
Add `--loglevel INFO` to the `command:` section to add logging for celery-beat
Thanks so much @LindsayYoung for your help!

Add logging to celery-beat

---

README.md

Issue#4753: https://github.com/18F/FEC/issues/4753
Update readme API_URL env var and added warning about SQLA_CONN env var impact on DB updates

Update readme API_URL env var and added warning 

---

README.md

Make sure PR is approved, then `git pull` on each of the three branches

Add to README - PR approval and getting most recent branches

---

manifests/manifest_base.yml

Addresses https://github.com/18F/openFEC/issues/2765

Update build pack - needs load testing

---

data/migrations/V42__add_comid_index_to_real_efile_tables.sql

Index tables on `comid` column.

---

data/migrations/V0043.1__calendar_permissions.sql

fixes permissions error on ofec_dates_vw

fixing permissions error

---

locustfile.py

Add load tests for itemized Sch A, B for load testing using Locust. Related to PR https://github.com/18F/openFEC/pull/2786
Locust is now compatible with [Python 3](https://github.com/locustio/locust#supported-python-versions) - removed old docstring
Currently getting lots of 502's for the problematic queries (`poor_performance_a` and `poor_performance_b` lists) on `dev`. Reproduced a similar problem on `prod`: https://api.open.fec.gov/v1/schedules/schedule_b/?per_page=20&sort=-disbursement_date&api_key=DEMO_KEY&last_disbursement_date=2016-03-03&two_year_transaction_period=2018&sort_hide_null=true

Add load tests for itemized Sch A, B

---

data/fips_states.csv

American Samoa,60, AS
Guam,66, GU
Northern Mariana Islands,69, MP
Puerto Rico,72, PR
Virgin Islands,78, VI
https://www.census.gov/geo/reference/ansi_statetables.html

update fips codes

---

webservices/tasks/refresh.py

fixed the new relic app name to be a string, removed old buffer used for the mail function

Fixing nigtly slack notificaiton for updates

---

data/migrations/V0055__add_expression_based_index_for_sched_b_tables.sql

add_expression_based_index_for_sched_b_tables is part of the attempt to address issue #2791

add_expression_based_index_for_sched_b_tables

---

data/migrations/V0059__rename_ofec_candidate_flag.sql
manage.py
webservices/common/models/candidates.py

Renamed materialized view ofec_candidate_flag to ofec_candidate_flag_mv and made the changes to all the places that reference it.

Rename ofec_candidate_flag mv

---

README.md
webservices/config.py

Updated the readme and removed the check for email, since we don't have that anymore.

Remove check for old creds

---

data/migrations/V0062__change_audit_case_mv_na_cand_name.sql

Change "N/A" cand name to "No authorized candidate". add new V0061__ file.

Change N/A cand name to No authorized candidate.

---

webservices/tasks/__init__.py

Added some extra check or retries to connect to Redis service during app deployment.

Retry Redis connection on startup

---

webservices/tasks/__init__.py

This changeset addresses another issue with the Redis retries:  [`py-cfenv`](https://github.com/jmcarp/py-cfenv/) only pulls credentials from `VCAP_SERVICES`; the space name (and a few other things) come from `VCAP_APPLICATION` and are exposed differently.
Additional comments explaining what is happening in the method have also been added.

Fix retrieval of application space name in cloud.gov for Redis retries

---

CONTRIBUTING.md
README.md
webservices/docs.py

- Updates readme
- added a pr review section
- Addresses deploy for #2950
- Read the text
- readme  
- links to the repo should now got to fecgov
- mailto link in the docs

🎉 Updating ownership from 18F to FEC  🎉

---

README.md

Update README.md:
- deploy to dev first
- wait for build to pass
- deploy to master

Update hotfix instructions - deploy to dev first

---

webservices/docs.py

noticed this was broken, it is so small I thought I would just put in a PR
mailto link was broken
- mailto apiionfo@fec.gov link in docs, run npm run build first
-  docs

fix mailto link

---

manifests/manifest_api_dev.yml
manifests/manifest_celery_beat_dev.yml
manifests/manifest_celery_worker_dev.yml

Remove the  **CACHE_ALL_REQUESTS: True** from **Dev** space yml file
- Addresses # [_Issue number_]
Disable cache calls in Dev
Removed the **CACHE_ALL_REQUESTS: True** from
-  manifest_api_dev.yml
-  manifest_celery_beat_dev.yml
-  manifest_celery_worker_dev.yml
-
-  
NONE

Removed the cache calls env variable from DEV yml files

---

tests/test_downloads.py
webservices/resources/candidate_aggregates.py
webservices/schemas.py

- Addresses  https://github.com/fecgov/openFEC/issues/2710: Enable house/senate downloads along with fec-cms PR: https://github.com/fecgov/fec-cms/pull/1875. Testing the cms change will be much easier if we merge this first.
_Enable downloads from the prez/senate/house pages:_
- President: http://localhost:8000/data/candidates/president/?election_year=2016&cycle=2016&election_full=true&min_receipts=50000
- Senate: http://localhost:8000/data/candidates/senate/?election_year=2016&cycle=2016&election_full=false&min_receipts=50000
- House: http://localhost:8000/data/candidates/house/?election_year=2016&cycle=2016&election_full=false&min_receipts=50000
- Check out this branch (`feature/enable-candidate-downloads`) and run the API
- Get `redis` and `celery` running locally …

Enable candidate downloads

---

webservices/tasks/__init__.py
webservices/tasks/cache_request.py

Set redis configuration time outs and re-tries.  And also change the cached-calls delete time to 10pm EST.  Add a message before deletion of cached-calls.

Update celery redis configuration and added log message to cached-calls

---

data/migrations/V0077__add_cmte_type_audit_case.sql

add three committee type 'U', 'V', 'W' into MVs in order to filter by these committee type.
modify like this: 
AND dc.cmte_tp IN ('H', 'S', 'P', 'X', 'Y', 'Z', 'N', 'Q', 'I', 'O', 'U', 'V', 'W')
AND dc.cmte_tp = b.filed_cmte_tp_cd

[Migration 77 - wait for migration 76] Add three committee type 'U','V','W' into MVs.

---

data/migrations/V0078__add_trc_election_result.sql

- Part of work to address https://github.com/fecgov/openFEC/issues/3076
_Add `trc_election_result` table, then set up golden gate transfer._

Add trc_election_result table

---

webservices/legal_docs/current_murs.py

- Addresses an issue found while testing
_Add better error handling for loading an invalid or archived MUR number._
- get Elasticsearch v. 5.6 running locally and environment variables needed to load legal docs
- Test a current MUR number: `./manage.py load_current_murs -m 7260`
- Test an archived MUR number: `./manage.py load_current_murs -m 4767`
- Test reloading all current MURs: `./manage.py load_current_murs`

Add error handling for when `load_current_murs` is passed an invalid or archived MUR number

---

webservices/rest.py

The commit
github.com/fecgov/openFEC/commit/e7854ad018bf554c71222a28b760130d6c8280a6 switched logging from the Flask app logger to a custom logger which in turn was not properly configured. This commit restores the original Flask.app logger.
This can be tested by verifying that log messages relating to caching (e.g. "Attempting to cache request") will start showing up in the logs.

Restore Flask.app logger

---

data/migrations/V0081.1__add_column_to_ofec_report_pac_party_all_mv.sql
manage.py
webservices/common/models/reports.py
webservices/flow.py

- Addresses #3103  [_Issue number_]
- add form_tp column to change hard coded the value of form type in model file -
- If local database has enough sample data, the materialized view should have this row:
FILE_NUM | CMTE_ID | FORM_TP | RPT_TP | RPT_YR | BEGIN_IMAGE_NUM |
1206344 | C00156554 | Form 3 | YE | 2017 | 201801240300187403
- otherwise, run a select statement against the query part only

add form_tp to report mv

---

PULL_REQUEST_TEMPLATE.md

Using the keyword resolves to automatically close the referenced pull request upon merge
- Resolves #3191 
_Using the keyword "resolves" to automatically close the referenced issue upon PR merge._

Closing issue using keyword "resolves" in PR

---

README.md

Added snyk flyway vulnerability badge

flyway badge addition

---

webservices/tasks/__init__.py

Modify the task names to match what is in schedule for reload all AOs
Change the name of the task to match what is in the schedule 
Just the task name change
-
-  
branch | PR

Renamed weekly reload AO task to match what's in schedule

---

CONTRIBUTING.md

- Addresses https://github.com/fecgov/fec-transition/issues/189
_Includes information about boards pipelines and pre-release testing procedures._

Updating with pre-release testing

---

README.md

- Get fresh copies of `develop` and `master`
- Make a PR to `master`
- Update Travis references to Circle

Update hotfix instructions in README

---

requirements.txt

- Resolves #3344
-
-  
branch | PR

openFEC#3344: Flask upgrade from 0.12 to 0.12.3.

---

webservices/docs.py
webservices/legal_docs/responses.py
webservices/resources/legal.py
webservices/rest.py
webservices/spec.py

Add Swagger docs for legal API

---

.circleci/config.yml

Cherry picked cache fix from dev to stage.

Use cache key prefix for finer control of cache

---

requirements.txt

-
those 4 packages have been updated to the newest version.
Flask==1.02
Flask-Cors==3.0.6
Flask-Script==2.0.6
Flask-RESTful==0.3.6
branch | PR

Update Flask and Flask-related packages.

---

webservices/docs.py

Updating the sale or use link to point to the updated article.
Resolves https://github.com/fecgov/fec-cms/issues/2225

Update sale or use link in open api

---

webservices/schemas.py

- Resolves #3476
max(None, None) was throwing an error - this falls back to zero for null values
until we can take a closer look at refactoring the code and/or fixing the data
- this link should load when connected to the DEV database: http://localhost:5000/v1/efile/reports/house-senate/
-  https://www.fec.gov/data/reports/house-senate/?data_type=efiling

[MERGE WITH GIT FLOW] Add fallback zero values for Form 3 cash-on-hand

---

requirements.txt

fix the dev branch requirements.txt file
local testing issue
git+https://github.com/fecgov/apispec.git@dev#egg=apispec -->
git+https://github.com/fecgov/apispec.git@dev
-
-  
branch | PR

fix dev branch requirements.txt file.

---

webservices/legal_docs/current_cases.py

- Resolves #3515
Update disposition data to filter for case_id
This is manually deployed to `dev` - comparing `dev` to `prod` with EQS as the source of truth: https://docs.google.com/spreadsheets/d/1Pz0gT2xTE1W4ER3WQ0nWv2T8AER7pUrBfv_yM9aBoXo/edit#gid=0
- MUR disposition section

[MERGE WITH GIT FLOW] Update disposition data to filter for case_id

---

requirements.txt

update openFEC requests module
- Resolves #3478 
run all unittests
run at least one legal doc_indexing job: python manage.py index_statues
-  legal_doc indexing
- slack notification

ofec-3478 requests update to newest version 2.20.1

---

webservices/rest.py

- Resolves individual using unlimited API key to hit downloads directly. This has caused our site to go down in the past.

[MERGE WITH GIT FLOW] Temporarily block one IP address

---

locustfile.py

adding download api test to locust
derived from #3637. keep this test in locust file so we don't lose it.
download api testing added.
running locust on different tiers:
`locust --host=https://api-stage.open.fec.gov/v1/` (stage)
`locust --host=https://api.open.fec.gov/v1/` (prod)
`locust --host=https://fec-dev-api.app.cloud.gov/v1/` (dev)
-
-  
branch | PR

adding download tests to locust.

---

README.md

Add user-friendly detail for `flyway` configuration to README.md and update references to `flyway-5.1.3` to `flyway-5.2.4`
- Resolves #3675 
-  README.md
#3676

make flyway readme more user friendly #3675

---

PULL_REQUEST_TEMPLATE.md

Removed the extra space on `PULL_REQUEST_TEMPLATE.md`

[MERGE WITH GITFLOW] Remove extra space

---

webservices/rest.py

- Resolves #3689 : Block one IP
- Once this is deployed, check logs to make sure there are no successful hits (no 200's)

[MERGE WITH GIT FLOW] Hotfix: Temporarily block ip

---

data/migrations/V0132__ofec_cand_totals_mv_update.sql

- Resolves #[3700]
fix syntax error
Refers to PR #3726
-  
branch | PR

fix syntax error

---

data/migrations/V0133__fix_ofec_cand_cmte_linkage_mv.sql

- Resolves #[3747] Fix logic in calculation of election_yr_to_be_included column in ofec_cand_cmte_linkage_mv
Calculation of election_yr_to_be_included column in this mv does not address the odd year special election under some situation.  This migration file update the logic of election_yr_to_be_included calculation to be more complete.
Download the branch feature/3700-fix-BernieSanders-totals-incorrect, run migration file V0133 (or run invoke create_sample_db) to make sure migration files runs without error.
tmp materialized view public.ofec_cand_cmte_linkage_mv_tmp_jj had been created in DEV database that has the updated MVs logic.
--Connect to DEV database and run the following query.
'H0AL03101' is a good example that has an odd number …

fix election_yr_to_be_included logic

---

data/migrations/V0143__break_dependencies_on_committee_history.sql
data/migrations/V0144__add_affiliated_committee_to_committee_history.sql
tasks.py
webservices/common/models/committees.py

Resolves https://github.com/fecgov/openFEC/issues/3807
- Fix `invoke create_sample_db` task to output Flyway migration errors
- Add connected org/affiliated cmte to '/committee/<committee_id>/history/'
-  `invoke create_sample_db` to test migrations
- Point to `dev` database
- Change `class CommitteeHistory(BaseCommittee)` to point to `__tablename__ = 'ofec_committee_history_mv_lb_tmp'`
- Test with http://localhost:5000/v1/committee/C00053553/history/?per_page=1&api_key=DEMO_KEY and examples below
SSF examples:
org_tp | ~min~ max | ~max~ min
-- | -- | --
W | [C00012153](http://localhost:5000/v1/committee/C00012153/history/?per_page=1&api_key=DEMO_KEY) | [C00690149](http://localhost:5000/v1/committee/C00690149/history/?per_page=1&api_key=DEMO_KEY)
C | …

Add connected org to committee history and committee detail

---

data/MV_change_template
data/MV_change_template.txt

- Resolves #[3882](https://github.com/fecgov/openFEC/issues/3882)
Add a template migration file that describe the materialized view update process
This is a template file that provide explanation and example of the MV updating process.  There is no code to test.
Please review the template to check if 
- the explanation is clear enough 
- there is no step(s) missing and the example can be followed without confusion
-  None
branch | PR

Add a template migration file that describe the materialized view update process

---

data/migrations/V0165__ofec_sched_a_agg_state_mv.sql

- Resolves #3970
/schedules/schedule_a/by_state/by_candidate slowness problem
Originally, this endpoint use a view public.ofec_sched_a_agg_state_vw to sum up all the non-real state as 'OT'
Although views can not have indexes, they will take advantage from the indexes of its base tables. 
However, the original query use a subquery and a view composed of multiple base tables and database optimizer somehow decided not to use the view's base tables' indexes and cause the slowness.
We can choose to re-write the query or create a MV to replace the view.
There are more than one endpoints share the same function in resource file to generate final query, it would be less impact to create a MV to replace the view.
Also for better readability.
Since this is a new MV, flow.py and manage.py had been …

Add ofec_sched_a_agg_state_mv to solve the slowness of ScheduleAByStateCandidate

---

data/migrations/V0165__ofec_sched_a_agg_state_mv.sql
manage.py
webservices/flow.py

- Brings changes from issue #3970 into the release
Original develop PRs:
https://github.com/fecgov/openFEC/pull/3972
https://github.com/fecgov/openFEC/pull/3974

Bring "Schedule A by state" speed improvements into the release

---

data/migrations/V0170__ofec_sched_e_mv_add_filing_date.sql

- Resolves #[4054]
Add Filing_date to ofec_sched_e_mv
-Download branch to local machine.  
Execute flyway migrate or invoke create_sample_db.  Make sure it executed successfully.
Run pytest, make sure it executed successfully.
-  This is a new column, no impact to the API.  It is to support API work in issue #3817.
branch | PR

Add filing_date to ofec_sched_e_mv

---

data/migrations/V0171__drop_ofec_totals_candidate_committees.sql
manage.py
webservices/flow.py

Bring migration V0171 into release

Bring migration V0171 into release 

---

webservices/docs.py

- Resolves #4045 
-  `docs.py`

Update raw efile docs to reflect 4 months of data instead of 2 years

---

tasks.py

Update dev deploy rule to point to develop branch

---

data/migrations/V0182__add_ofec_presidential_by_candidate_vw.sql
tests/factories.py
tests/test_presidential.py
webservices/args.py
webservices/common/models/presidential.py
webservices/docs.py
webservices/resources/presidential.py
webservices/schemas.py
webservices/spec.py

- Resolves #4170 
Add `/presidential/contributions/by_candidate/`
Future work: Will check with @fecjjeng on indexes as part of #4186 performance testing
- `export FEC_FEATURE_PRESIDENTIAL=True`
- Change `PresidentialByCandidate` tablename to `'ofec_presidential_by_candidate_vw_lb'`
- http://localhost:5000/v1/presidential/contributions/by_candidate/?contributor_state=US&election_year=2020&per_page=100&page=1&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
- Test migration with 
```
flyway migrate
```
-  Future presidential map
**Query plan:**
```
explain(SELECT public.ofec_presidential_by_candidate_vw_lb.idx, …
```

[V0182] Add /presidential/contributions/by_candidate/

---

data/migrations/V0183__add_ofec_presidential_by_state_vw.sql
tests/factories.py
tests/test_presidential.py
webservices/common/models/presidential.py
webservices/resources/presidential.py
webservices/schemas.py

(national map circle per candidate):
(view on DISCLOSURE.PRES_CA_CM_SCHED_A_JOIN_20D / _16
Filter: candidate_id, election_year
- Resolves [#4177](https://github.com/fecgov/openFEC/issues/4177)
- run this cmd : `export FEC_FEATURE_PRESIDENTIAL=True`
- Change `PresidentialByState` tablename to `'ofec_presidential_by_state_vw_jl'`
(no filter)
http://127.0.0.1:5000/v1/presidential/contributions/by_state/?sort_hide_null=false&sort_null_only=false&page=1&per_page=20&sort_nulls_last=false
(filter: candidate_id)
http://127.0.0.1:5000/v1/presidential/contributions/by_state/?sort_hide_null=false&sort_null_only=false&page=1&candidate_id=P80001571&per_page=20&sort_nulls_last=false
(filter: election_year) …

[V0183]Feature/4178 add endpoint PresidentialByStateView

---

webservices/args.py
webservices/common/models/presidential.py
webservices/docs.py
webservices/resources/presidential.py

Add the following five bubble endpoints description. 
/presidential​/contributions​/by_candidate​/
​/presidential​/contributions​/by_size​/
​/presidential​/contributions​/by_state​/
​/presidential​/coverage_end_date​/
​/presidential​/financial_summary​/
- Resolves [#[_4191_]](https://github.com/fecgov/openFEC/issues/4191)
2) export FEC_FEATURE_PRESIDENTIAL=true
3)check endpoint description section.

Add bubble endpoints description.

---

.circleci/config.yml
data/migrations/V0182__add_ofec_presidential_by_candidate_vw.sql
data/migrations/V0183__add_ofec_presidential_by_state_vw.sql
data/migrations/V0184__add_ofec_presidential_summary_vw.sql
data/migrations/V0185__add_ofec_presidential_by_size_vw.sql
data/migrations/V0186__add_ofec_presidential_coverage_date_vw.sql
tests/factories.py
tests/test_itemized.py
tests/test_presidential.py
webservices/args.py
webservices/common/models/presidential.py
webservices/docs.py
webservices/resources/presidential.py
webservices/resources/sched_e.py
webservices/schemas.py
webservices/spec.py

This is for the sprint (11.4) release.
@jason-upchurch will do the release. make sure if need sync back to develop branch. Thanks

[MERGE WITH GITFLOW] Release/public 20200225

---

.circleci/config.yml
requirements.txt

1. Update the CircleCI configuration version from 2.0 to 2.1 to enable pipelines.
2. Update Git Python pkg to latest v3.1.0  to fix the build errors (see gitpython-developers/GitPython#983) 
- Resolves #4231 
- updated circleci configuration in circleci/config.yml
- upgrade GitPython pkg v3.1.0 in requirements.txt to fix the build issue 
- update the tasks.py with the `feature/4231-enable-circleci-pipeline` branch and deploy to `dev` space.
**CircleCI dashboard **_without_** pipeline:**
**CircleCI dashboard _**with**_ pipeline**

[openFEC] Enable circleci pipeline

---

requirements.txt

hotfix to address the build issue caused by the GitPython pkg

[MERGE WITH GIT FLOW] Update GitPython pkg v3.1.0

---

requirements.txt

- Resolves #4228 
- updates codecov to resolve vulnerability
- restores correct version of webtest@2.0.34 (accidentally reverted to older version when resolving merge conflicts) and places into requirements.txt since required for CI/CD
Any one of three reviews is sufficient.
- create new python 3.7.7 environment
- install requirementst.txt (don't need requirements-dev.txt)
- pytest
- snyk test --file=requirements.txt
-  requirements.txt

upgrade codecov@2.0.9 to 2.0.17

---

requirements-dev.txt

- Resolves issue found in testing 
Update locust to python 3.7 compatible version. See https://github.com/locustio/locust/releases/tag/0.10.0
>Fixes: “Immediate crash under python 3.7 #852”
As noted by @fec-jli if we update to the latest version (`0.14.5`), we get the error `locustio 0.14.5 has requirement gevent==1.5a3, but you'll have gevent 1.4.0 which is incompatible`. We don't want to go to an alpha `gevent` release, so finding the closest 3.7-compatible version.
**Before**: Locust fails with error:
```
(api-env) $ locust --host=<URL>
Traceback (most recent call last):
File "/Users/lbeaufort/.pyenv/versions/api-env/bin/locust", line 11, in <module>
load_entry_point('locustio==0.7.3', 'console_scripts', 'locust')()
File "/Users/lbeaufort/.pyenv/versions/3.7.7/envs/api-env/lib/python3.7 …
```

Update locust to python 3.7 compatible version (10.0)

---

data/migrations/V0198__add_index_sa7_sb4.sql

- Resolves #[4346](https://github.com/fecgov/openFEC/issues/4346),  #[4345](https://github.com/fecgov/openFEC/issues/4345)
_added index to real_efile.sa7 and real_efile.sb4 to improve performance_
-Download branch to local
- run `pytest`
- run `flyway migrate`

add index to real_efile.sa7 and real_efile.sb4

---

webservices/docs.py

- Resolves #[_4362_](https://github.com/fecgov/openFEC/issues/4362)
_Update URL in the description of presidential end point._
-Download branch to local
-run `pytest`
-run `manage.py runserver` to start api on local, and the description in presidential endpoint should be like this:
http://127.0.0.1:5000/developers/#/presidential

Update URL for presidential data on API page

---

README.md

- Resolves #[_4332_](https://github.com/fecgov/openFEC/issues/4332)
_Current production database is running on version 10.  The description in README needs to be updated_
Check paragraph under "Project prerequisites" on this page:
https://github.com/fecgov/openFEC/tree/feature/4332-update-readme

Update description of postgresql version in README

---

requirements.txt

- Resolves 
The codecov post-test check errors in circleci
- update codecov package to v2.1.7 in requirements.txt
- Rerun the latest circle build of this feature branch.  Verify the post-test checks task and codecov errors should not appear.
before:
After upgrading the codecov package to v2.1.7
-  circleci post-test checks

Update codecov pkg to v2.1.7

---

tasks.py

removes manual deploy line from tasks.py
- verify tasks.py has no extra lines of code in the deploy rules
-  tasks.py

remove manual deploy line

---

webservices/docs.py

- Resolves #4547 
- Replace "FEC Form" with "Form"
- update URLs for Form 1 and 2
- Just view the "files changed" tab to verify changes.

Replace 'FEC Form' with 'Form' and update URLs

---

runtime.txt

Unpins python version in runtime.txt

Unpin python in runtime.txt

---

webservices/docs.py

- Resolves #4507 
- @patphongs @lbeaufort @JonellaCulmer please review (all required)
- review wiki (https://github.com/fecgov/openFEC/wiki/Deprecation-policy/2f8b4b9146532cc16df73114d85517a9277fe028)
- review swagger doc language:
-  swagger docs
- openFEC wiki

Add deprecation policy link to swagger

---

endpoints_walk.py
webservices/rest.py

Resolves #4248
- Remove `/committee/{committee_id}/communication_costs/by_candidate/`, replaced by `/communication_costs/aggregates/?committee_id={committee_id}`
- Remove `/committee/{committee_id}/electioneering/by_candidate/`, replaced by `electioneering/aggregates/?committee_id={committee_id}`
- One developer please
**Endpoints don't filter by committee ID** (note the result committee ID's don't match the committee ID in the URL)
- https://api.open.fec.gov/v1/committee/C30001101/electioneering/by_candidate/?per_page=20&api_key=DEMO_KEY&sort_null_only=false&sort_nulls_last=false&election_full=true&sort_hide_null=false&page=1&office=senate&cycle=2020&state=ME
- https://api.open.fec.gov/v1/committee/C70002563/communication_costs/by_candidate/?per_page=20&api_key=DEMO_KEY&sort_null_only=fal …

Remove two broken endpoints

---

manifests/manifest_api_dev.yml

- Resolves #4623
Update dev api memory to match other spaces
-  API memory allocation in `dev` space
Issue #4578 and PR https://github.com/fecgov/openFEC/pull/4605

Update dev api memory to match other spaces

---

manifests/manifest_api_dev.yml

- Partial resolution for #4695 - removes unused service created for testing only.
Only one approval requested, thanks!

Remove unused service

---

webservices/env.py
webservices/tasks/utils.py

Fix public s3 bucket settings
List related PRs against other branches: https://github.com/fecgov/openFEC/pull/4722

 fix public s3 bucket

---

README.md

deploy to master failed due to missing tag

[MERGE WITH GITFLOW] Update elasticsearch-7.4 in README.md

---

README.md

After upgrading ES7, we need update the README file.
Ref ticket #4693 
Reviewer:
One developer is good.

Update README for ES7 upgrade

---

requirements.txt

- Resolves #4803
Update `requests` to latest version
- Run the API, make sure nothing breaks
- Deploy API, no dependency errors (unlike `develop`) upon deploy

Update requests to latest version

---

PULL_REQUEST_TEMPLATE.md

(Include who is required to review prior to merge. For example: One designer and two front end developer reviews are required prior to merge)
-  
branch | PR
(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point …

Changes per group discussion

---

README.md
webservices/common/models/base.py
webservices/rest.py

(Include who is required to review prior to merge. For example: One designer and two front end developer reviews are required prior to merge)
-  
branch | PR
(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point …

[MERGE WITH GIT FLOW] Hotfix/revert release/public 20210511

---

data/migrations/V0231__create_af_number_rad_civil_pnlty_updt.sql

- Resolves #4896 
SQL script for fec_mur.af_number_rad_civil_pnlty_updt.
One developer is required.
- Download feature branch, and run `pytest`
- run `flyway migrate` to test migration
- Delete latest row (version = '0231') from table: flyway_schema_history,  and run `flyway migrate` again to make sure no errors.

[Merge after V230]Add migration file for af_number_rad_civil_pnlty_updt

---

webservices/utils.py

- Resolves #4918 
- Resolves #4842
Do not add coalesce to pagination statement when sort_by_column is not null is in the where clause
In the where clause of schedule A query below, when there is 'disclosure.fec_fitem_sched_a.contb_receipt_dt IS NOT NULL', there is no need to have coalesce in this pagination statement:
```sql
AND (coalesce(disclosure.fec_fitem_sched_a.contb_receipt_dt, $3::date), disclosure.fec_fitem_sched_a.sub_id) < $4::date, $5)
```
2 approvals requested
-  All `ItemizedResource` endpoints (Schedule A, B, E)
http://localhost:5000/v1/schedules/schedule_b/?per_page=100&sort_hide_null=True&sort=-disbursement_date&recipient_name=gross&two_year_transaction_period=2020&recipient_state=NY&last_index=401122021208450 …

Don't add coalesce if sort index can't be null

---

package-lock.json
webservices/utils.py

This is the 15.3 mini release.

[MERGE WITH GITFLOW] Release/public 20210728

---

requirements.txt
webservices/utils.py

This is for sprint 15.4 release. @pkfec will deploy the release

[MERGE WITH GITFLOW] Release/public 20210810

---

README.md

- Resolves #5000 
Adds MV refresh process to ReadMe and corrects small typo. 
1 reviewer
-  OpenFEC ReadMe

5000-Add MV refresh process to ReadMe

---

data/migrations/V0240__modify_function_expand_document.sql
webservices/decoders.py

Currently, there is the inconsistency of labeling for some documents. Some are capitalized, sentence case, or random capitalization.
All documents should be consistently formatted and in title case after this PR.
- Resolves #4982 
- Add new migration V0240 to update function:public.expand_document
- Modify decoders.py, update form_types description.
One designer and one developer reviews
"document_description" column in endpoint: /filings/, 
-  
Before:
</br>
After:
- Checkout branch and point to aurora 13 dev db
- `flyway migrate`
- `pytest`
-  `./manage.py runserver`
-  Compare prod and local api url and check "document_description" column.
Prod: …

Update document formatting--4982

---

data/migrations/V0241__idx_ofec_sched_b_aggregate_recipient_mv.sql

To make sure the value of idx is unique, This PR will change this column to use row_number.
- Resolves #5016 
one developer
- Checkout branch and point to aurora 13 dev db
- `flyway migrate`
- `pytest`
-  `./manage.py runserver`

Change idx to row number in ofec_sched_b_aggregate_recipient_mv.

---

tests/test_aggregates.py
webservices/args.py
webservices/common/models/candidates.py
webservices/resources/candidate_aggregates.py
webservices/schemas.py

1)Add three new columns into /candidate/totals/by_office/ (AggreagteByOfficeView)
```
individual_itemized_contributions
transfers_from_other_authorized_committee 
other_political_committee_contributions
```
2)Add three new filters in AggreagteByOfficeView
```
'election_full': election_full,
'min_election_cycle': fields.Int(description=docs.CYCLE),
'max_election_cycle': fields.Int(description=docs.CYCLE),
```
3)Add one new filter in AggregateByOfficeByPartyView
` 'election_full': election_full,
`
- Resolves #5028 
- Reference PR #5050 , PR #5054 and [PR #3801](https://github.com/fecgov/openFEC/pull/3801)
4) Create two new follow-up tickets: 
[Add auto test case into AggregateByOfficeByPartyView](https://github.com/fecgov/openFEC/issues/5062)
[Create filter_boolean …

Add filters to AggregateByOfficeView and AggregateByOfficeByPartyView

---

package-lock.json
package.json
webservices/templates/swagger-ui.html

- Resolves #https://github.com/fecgov/openFEC/issues/5007
1. Upgrade swagger-ui-dist to v4.5.0 in package.json
2. Override the default width of` swagger-ui .response-col_description` that was causing the  Name, Descriptions columns overlap on Swagger UI in swagger-ui.html
3. On Swagger UI: 
- A filter of type array[string]:  filter button is renamed as `Add string item`
- A filter of type array[integer]: filter button is renamed as `Add integer item`
(See the screenshots below)
Two developers must
-  Swagger UI
**Production**:
**Endpoint**: https://api.open.fec.gov/developers/#/candidate/get_candidates_search_
**feature/upgrade-swagger-ui-dist branch**:
**Endpoint**: http://localhost:5000/developers/#/candidate/get_candidates_search_
-  git checkout feature/upgrade-swagger-ui-dist
- pyenv …

upgrade swagger-ui-dist to latest

---

data/migrations/V0244__modify_committee_type_function.sql
webservices/docs.py

- Resolves #5041 
Modifies expand_committee_type function and docs to update committee type I language
1-2 devs
-  API

5041-Update Committee type I language

---

data/migrations/V0245__add_state_district_ofec_candidate_totals_mv.sql

Add these three new columns into ofec_candidate_totals_mv:
1)state
2)district
3)district_number
1 database developer
ofec_candidate_totals_mv
2) 
```
dropdb cfdm_unit_test
createdb cfdm_unit_test
```
3)pytest
4)Check data on test mv: public.ofec_candidate_totals_mv_tmp_jl
SELECT * FROM public.ofec_candidate_totals_mv_tmp_jl

Add columns state district in candidate_totals_mv

---

requirements.txt

API deploy’s are failing due to Flask dependency package Jinja2. Flask pulls the latest Jinja2 v3.1.1, which was released on Mar 25th causing the pytests and deploys to fail which is also causing OUT OF MEMORY errors in API server.
Pytest error with latest Jinja2 v3.1.1:
```
ImportError while loading conftest '/Users/pkasireddy/Projects/api/openFEC/tests/conftest.py'.
tests/conftest.py:1: in <module>
import manage
manage.py:10: in <module>
from flask_script import Server
../../../.pyenv/versions/3.8.12/envs/dev-api/lib/python3.8/site-packages/flask_script/__init__.py:14: in <module>
from flask import Flask
../../../.pyenv/versions/3.8.12/envs/dev-api/lib/python3.8/site-packages/flask/__init__.py:14: in <module>
from jinja2 import escape
E   ImportError: cannot import name 'escape' from …
```

[MERGE WITH GIT FLOW] Hotfix/pin jinja2 to fix deploy errors

---

package-lock.json
package.json
requirements.txt

Reverts fecgov/openFEC#5137, need to remove gevent upgrade

Revert "5125-Snyk Prototype Pollution upgrade async"

---

data/migrations/V0251__ofec_filings_all_mv_add_filer_name_text.sql

In order to search keyword `filer_name`, we will add one more column: `filer_name_text` in ofec_filings_all_mv
ref: [Endpoints to add committee name keyword search](https://docs.google.com/spreadsheets/d/1AkQjXA2XMQfxlRyinSY0uynhf2ZRMh7l_BTWdJgHzXY/edit#gid=0)
- Resolves part of #5160
1 db dev
2)
```
pytest
```

Add filer_name_taxt in filings_all_mv

---

data/migrations/V0252__ofec_report_presidential_mv_add_filer_name_text.sql
data/migrations/V0253__ofec_report_house_senate_mv_add_filer_name_text.sql
data/migrations/V0254__ofec_report_pac_party_mv_add_filer_name_text.sql

In order to search keyword `filer_name`, we will add one more column: `filer_name_text` in
public.ofec_reports_presidential_mv
public.ofec_reports_house_senate_mv
public.ofec_reports_pac_party_mv
ref: [Endpoints to add committee name keyword search](https://docs.google.com/spreadsheets/d/1AkQjXA2XMQfxlRyinSY0uynhf2ZRMh7l_BTWdJgHzXY/edit#gid=0)
- Resolves part of #5160
1 db dev
2)
```
pytest
```

Add filer_name_text in 3 reports_mv

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml

Upgrade flyway to the latest version9.2.0
- **Resolves** #5218 
1 or 2 developers
-  DB migrations
**flyway v9.0.2**
**flyway v9.2.0**
- checkout feature/5218-upgrade-flyway
- run `snyk test --all-projects`. No vulnerability on this branch
- run `flyway migrate`. All 256 migrations should run OK against `cfdm_test` db 
- run `pytest`. All tests pass

upgrade flyway

---

data/migrations/V0262__ofec_sched_e_mv_add_coalesce.sql

- Resolves #5247 
This PR modifies ofec_sched_e_mv by adding coalesce to cmte_name, and pulling cmte_name from other tables.
1 developer
- Download feature branch 
- Run `pytest`
- Run `flyway migrate`

Fix null value in committee name

---

data/migrations/V0264__ofec_reports_ie_only_mv_add_committee_name.sql

Fix 500 error in reports/ie-only/ endpoint
- Resolves #5232 
- Ref PR #5255 
Add one column: committee_name
1 dev
- Download feature branch 
- Run `pytest`
- Run `flyway migrate`

add committee_name in reports_ie_only_mv

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml
manifests/manifest_api_dev.yml
manifests/manifest_api_prod.yml
manifests/manifest_api_stage.yml

This is for the sprint (19.6) release.
@pkfec will deploy this.

[MERGE WITH GITFLOW] Release/public 20221122

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml
manifests/manifest_api_dev.yml
manifests/manifest_api_prod.yml
manifests/manifest_api_stage.yml
tests/factories.py
tests/integration/test_committees.py
tests/test_aggregates.py
tests/test_committees.py
webservices/common/models/committees.py
webservices/resources/candidate_aggregates.py
webservices/resources/committees.py
webservices/resources/search.py
webservices/rest.py
webservices/schemas.py

This is a develop branch rebased off master to try and solve the current issues with merge conflicts between develop/release and master.

Test rebased develop

---

src/components/Footer.js

- Resolves #5327 
This PR adds an explicit type to the footer button. 
-  /footer.js
branch 
#5314 
1. Navigate to the home page - http://127.0.0.1:5000/developers/
2. Scroll down to the footer
3. Click the button that states "Email FEC API Info"
4. Ensure that the button works still

Add Type to footer button

---

requirements.txt
tests/test_committees.py
webservices/common/models/committees.py
webservices/common/models/itemized.py
webservices/common/views.py
webservices/docs.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py
webservices/resources/sched_e.py

This is for the sprint (20.3) release.
@cnlucas  will deploy this 1/24

[MERGE WITH GITFLOW] Release/public 20230124

---

locustfile.py
requirements-dev.txt

- Resolves #5322 
Upgrades locustio to locust (2 major versions)
1-2
-  locust testing 
- `pyenv virtualenv 3.9.15 locust`
- `pyenv activate locust`
- run locust test (look for instruction inside locustfile.py file)
- """Load testing for the API and web app. Run from the root directory using the
locust --host=https://api-stage.open.fec.gov/v1/ (stage)
locust --host=https://fec-dev-api.app.cloud.gov/v1/ (dev)
command, then open localhost:8089 to run tests"""
NOTE: Removed print statement that clutters the terminal and pulls the success/code which can be found in the browser. Thanks @pkfec for the feedback!

replace locustio with locust

---

webservices/args.py
webservices/docs.py
webservices/resources/legal.py

1. Add/Update `case_doc_category_id` field with the latest MUR/ADR document categories to API (`New Doc Order` column in the screenshot below)
Table with latest mur/adr categories:
2. Change `type` and `mur_type` fields types from text to dropdown list
- Resolves #https://github.com/fecgov/openFEC/issues/5339
- Related PR #https://github.com/fecgov/openFEC/pull/5179
2 or more developers
-  /legal/search/ API endpoint
**In Prod:**
**Current branch:**
- Choose Method#1 **OR** Method#2 to test this PR
**Method#1:**  local workspace
- Follow wiki instructions and setup [ElasticSearch7.4](https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-setup-and-test-locally) on local environment
- Checkout feature branch: `git checkout feature/5339-update-mur-adr-categories`
- run: `pytest`
- …

update mur adr categories

---

webservices/tasks/legal_docs.py

Fix Elasticsearch snapshot backup bug.
deploy on dev.

Fix es snapshot bug

---

data/migrations/V0271__h4_mv_create.sql

- Resolves #5361 
Adds the materialized view and view pair for the H4 endpoint work
1 dev
-Database
- Activate your current pyenv api env
- `createdb cfdm_test`
- `invoke create_sample_db`
You should see the MV/V and the indexes in Dbeaver

5361-Add H4 MV

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml
requirements.txt

- Resolves #5382 
This ticket upgrades flyway to the latest version to remove security vulnerabilities. 
- readme 
2. Uninstall flyway `brew uninstall flyway`
Method Two: Follow the [readme](https://github.com/fecgov/openFEC#installing-flyway) to install flyway [version 9.16.3](https://documentation.red-gate.com/fd/command-line-184127404.html?_ga=2.234928961.193109968.1681304355-253257385.1681304355) manually 
4. Confirm version 9.16.3 was downloaded `flyway -v` 
5. Find your flyway.conf file in your Cellar and add URL and locations  
6. `dropdb cfdm_test`
7. `createdb cfdm_test`
8. `invoke …

Upgrade flyway v9.16.3

---

webservices/tasks/legal_docs.py

Increase snapshot sleep time to 60s

Increase snapshot sleep time to 60s

---

webservices/docs.py

Update the description for endpoint  `/legal/search/`, explain how to do pagination.
- Resolves #5405 
1 dev
`/legal/search/`
check branch
pytest
review description: [http://127.0.0.1:5000/developers/#/legal/get_legal_search_](http://127.0.0.1:5000/developers/#/legal/get_legal_search_)

Update legal search description for pagination

---

webservices/docs.py

- Partially Resolves #5365 
This PR adds the deprecation notice to the by_office and by_party endpoints. We notified users 4/24 and will re-notify users on 5/24 before removing the endpoints on or after that date. 
1 reviewer
-  Just the docs section under these endpoints 
- activate your virtual env
- flask run
- http://127.0.0.1:5000/developers/#/candidate/get_candidates_totals_by_office_
- http://127.0.0.1:5000/developers/#/candidate/get_candidates_totals_by_office_by_party_

add deprecation notice for by_office and by_office/by_party endpoints

---

manifests/manifest_api_dev.yml
manifests/manifest_api_feature.yml
manifests/manifest_api_prod.yml
manifests/manifest_api_stage.yml
manifests/manifest_celery_beat_dev.yml
manifests/manifest_celery_beat_feature.yml
manifests/manifest_celery_beat_prod.yml
manifests/manifest_celery_beat_stage.yml
manifests/manifest_celery_worker_dev.yml
manifests/manifest_celery_worker_feature.yml
manifests/manifest_celery_worker_prod.yml
manifests/manifest_celery_worker_stage.yml
manifests/manifest_task_dev.yml.template
manifests/manifest_task_feature.yml.template
manifests/manifest_task_prod.yml.template
manifests/manifest_task_stage.yml.template

- Resolves #5443 
This ticket upgrades the stack to cflinuxfs4. A test of the stack change has been done in the dev space. 
-  manifests 
Test on dev
- Deploy this branch to dev (will do on Monday)

Upgrade stack to use cflinuxfs4

---

data/migrations/V279__add_pdfurl_to_h4.sql

- Resolves #5364 (partially)
This adds pdf_url to the h4 endpoint, so that we can add the images to the datatable
1 dev
-  H4 endpoint
- invoke create_sample_db

5364-add pdf_url to h4 mv

---

.prettierrc
src/App.js
src/components/Footer.js
src/components/Header.js
src/index.js
src/server.js

- Resolves #5474 
We should alter the prettier defaults from single quotes and semicolons
1 dev
-  pre-commit hooks
- `pre-commit install`
- try to commit a change with double quotes

5474 Change prettier settings- singlequote and semi

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml

- Resolves #https://github.com/fecgov/openFEC/issues/5465
Upgrade flyway to latest v9.19.4
One developer
-  Database migrations
-  checkout develop
- run `snyk test --file=data/flyway/build.gradle` (snyk flags org.xerial:sqlite-jdbc Arbitrary Code Execution vulnerability)
- checkout feature/5465-upgrade-flyway
- run `brew install flyway` (v9.19.4 will be downloaded)
- run `flyway -v` (verify the downloaded flyway v9.19.4)
- run `dropdb cfdm_test`
- run `createdb cfdm_test`
- run `flyway migrate`
- run `snyk test --file=data/flyway/build.gradle` (snyk no longer flags snyk flags org.xerial:sqlite-jdbc Arbitrary Code Execution vulnerability)
- run `pytest` (all tests PASS)

Upgrade flyway to v9.19.4

---

tests/test_downloads.py

- Resolves #5139 
Adds test to export all election totals --export functionality is already working
1 dev
-  test_downloads
- pip install -r requirements-dev.txt
- pytest tests/test_download.py

Test export all election totals

---

requirements.txt

- Resolves #5459 
Upgrades requests to the latest version to remediate the current security vulnerability
1-2 devs
-  requirements.txt
pip install -r requirements.txt
rm -rf node_modules/
npm i &&  npm run build
pytest
flask run

5459-update requests

---

src/components/Footer.js

- Resolves #5526 
Hotfix PR for the work over on PR #5527

[HOTFIX - MERGE WITH GITFLOW] 5526 address

---

tests/test_itemized.py
tests/test_sched_c.py
tests/test_sched_d.py
webservices/args.py
webservices/common/models/itemized.py
webservices/docs.py
webservices/exceptions.py
webservices/resources/sched_c.py
webservices/resources/sched_d.py
webservices/resources/sched_e.py
webservices/resources/sched_f.py
webservices/resources/sched_h4.py

Sprint 23.5 release branch. @tmpayton  will deploy on Jan 2nd, 2024

[MERGE WITH GITFLOW] Release/public 20240102

---

requirements.txt
webservices/resources/download.py
webservices/tasks/download.py

- Resolves #5742 and #5681 
This PR upgrades werkzeug to v3 to remove security vulnerabilities without impacting our export/download tasks. 
- Downloads.py
locally:
1. checkout this branch: `git checkout feature/5742-upgrade-werkzeug`
2.  `pyenv activate <your virtualenv>`
3. `pip install -r requirements.txt`
4. `snyk test --file=requirements.txt --package-manager=pip` ensure werkzeug is not listed
5. `pytest`
6. `flask run`
On Dev:
7. Deploy test branch to dev, you can use [this](https://app.circleci.com/pipelines/github/fecgov/openFEC/2688/workflows/d2ae5dfc-15e7-4cea-8d31-170cfc1c4c50) one
8. Test downloads and compare to prod 
Test URLs: 
https://dev.fec.gov/data/debts/?form_line_number=F3-10 …

upgrade werkzeug v3

---

README.md
webservices/docs.py

- Resolves #5871 
Switches broken link and removes typo
1 dev
- API readme and docs
- Go to the link
- pull this PR
- flask run

[MERGE WITH GITFLOW] 5871- Hotfix/5871 fix broken links

---

requirements.txt

- Resolves #5845 
upgrades requests to remove snyk vulnerability
1-2 reviewers
-endpoints walk, public key creation, post_to_slack
- pyenv activate yourvenv
- pip install -r requirements.txt
- pytest
- go to manage.py and find slack_message. Update from #bots to #test-bot
```
def slack_message(message):
""" Sends a message to the bots channel. you can add this command to ping you when a task is done, etc.
run ./manage.py slack_message 'The message you want to post'
"""
post_to_slack(message, "#bots")
```
- python cli.py slack_message test
- snyk test --file=requirements.txt --package-manager=pip

5845-upgrade requests

---

manifests/manifest_api_stage.yml
webservices/common/models/filings.py
webservices/docs.py
webservices/resources/filings.py
webservices/rest.py
webservices/schemas.py

- Resolves #5860 
Add feature flag-dependent test F1 endpoint
1-2 devs
- Test form 1 endpoint in staging environment
https://github.com/fecgov/openFEC/pull/5906
https://github.com/fecgov/openFEC/pull/5905
- Set `FEC_SHOW_TEST_F1` to `True` in rest.py
- http://localhost:5000/v1/efile/test-form1/

Add feature flag-dependent test F1 endpoint

---

webservices/resources/filings.py

- Resolves #5925 
switches to the new model to fix the filters
1 dev
- test efile endpoint
Push to stage and then test the filters:
- https://api-stage.open.fec.gov/v1/efile/test-form1/?&file_number=7788762&api_key=DEMO_KEY
- https://api-stage.open.fec.gov/v1/efile/test-form1/?&committee_id=C00101915&api_key=DEMO_KEY
- https://api-stage.open.fec.gov/v1/efile/test-form1/?&api_key=DEMO_KEY&election_state=DC
- https://api-stage.open.fec.gov/v1/efile/test-form1/?candidate_office=H&api_key=DEMO_KEY
- https://api-stage.open.fec.gov/v1/efile/test-form1/?api_key=DEMO_KEY&candidate_district=02
- https://api-stage.open.fec.gov/v1/efile/test-form1/?api_key=DEMO_KEY&image_number=202406279024715274
- …

[MERGE WITH GITFLOW] Hotfix/5925 fix test efile endpoint

---

cli.py
manage.py

- Resolves #5932 
This PR adds two tasks to update, add, or remove environment variables. [Here](https://github.com/fecgov/openFEC/wiki/Add,-Update,-or-Remove-Environment-Variables-using-Task) is the wiki page that gives the full instructions.
- cli.py 
Note: Make sure all commands are run in the same directory 
1. in mange.py line 445 change slack channel from bots to `test-bot`
2. login to cloud.gov cli `cf login -a api.fr.cloud.gov  --sso`
3. target dev `cf target -s dev`
4. get cloud.gov token and place it in a file name token.txt `cf oauth-token > token.txt`
5. Run commands to update environment variables in test service (test-modify-env-vars): 
Add or Update: 
python cli.py add_update_env_var   [space]  [service …

Modify environment variables using task

---

requirements.txt

- Resolves #5914 
Upgrade certifi to remove snyk vuln 
1 dev
-pyenv activate (your venv)
-pip install -r requirements.txt
-pytest
-flask run

5914 upgrade certifi

---

locustfile.py

- Resolves #5955
Adding the new tests created during load testing different number_of_fragments 
1 dev
-locust file
-Here's the number of fragments load test research doc:
https://docs.google.com/spreadsheets/d/1TbRGN6bnBXF7sLGA1BfhcxX8Nhr5qno1xfeaVYH07tA/edit?gid=128201280#gid=128201280
You can also test by load testing:
https://docs.google.com/document/d/1ru6Qg0ErTQLD7a86qxW7kbaKbzkayt_X9PmGjZdC_nY/edit

5955- add inner hits tests

---

webservices/resources/legal.py

- Resolves #5948 #5949 
This PR removes name and number from the keyword search and highlight. 
- AO legal search
- MUR, ADR and AF legal search
2. uncomment debug line in legal.py `logger.setLevel(logging.DEBUG)`
3. `pyenv virtualenv <your virtual environment>`
4. `flask run`
5. In another terminal, start elasticsearch: `./elasticsearch`
6. Test AO search and compare output
7. Test CASE search and compare output
example: 
http://127.0.0.1:5000/v1/legal/search/?q=%22PoliticalMeetings.com%22&type=advisory_opinions
Before: 
```
UniversalSearch() final query ={
"query": {
"bool": {
"must": [
{
"term": {
"type": "advisory_opinions"
}
},
{
"bool": {
"minimum_should_match": 1
}
}
],
"should": [
{
"nested": …
```

Remove number and name from AO keyword search

---

webservices/resources/legal.py

- Resolves #5948
This PR removes name, no from the should and comments out the debug line 
1 dev
- legal search q
2. uncomment debug line in legal.py `logger.setLevel(logging.DEBUG)`
3. `pyenv virtualenv <your virtual environment>`
4. `flask run`
5. In another terminal, start elasticsearch: `./elasticsearch`
6. Test AO search and compare output
7. Test CASE search and compare output
http://127.0.0.1:5000/v1/legal/search/?q=4250
DEBUG:webservices.resources.legal:UniversalSearch() final query ={
"query": {
"bool": {
"must": [
{
"term": {
"type": "statutes"
}
},
{
"simple_query_string": {
"query": "4250"
}
}
]
}
},
"sort": [
"sort1",
"sort2"
],
"size": 20,
"from": 0,
"_source": {
"exclude": [
"text", …

5948-remove name & number from should

---

requirements.txt

- Resolves #5935 
Upgrades flask-cors to remove snyk vuln 
1-2 devs
-pull this branch
-start your virtualenv
-pip install -r requirements.txt 
-pytest
-flask run
-snyk test --file=requirements.txt

5935 upgrade flask-cors

---

requirements.txt

- Resolves #5980 
Removing comment to fix snyk imports 
1 dev

remove comment

---

webservices/legal_docs/current_cases.py

Some of disposition category list key missing `.`, this PR will fix that.
1 dev
legal search
make sure, include `.` in the key 
[mur_disposition_category_list.csv](https://github.com/user-attachments/files/17117838/mur_disposition_category_list.csv)

Fix MUR disposition category list key

---

data/migrations/V0304__add_arch_curent_mur_sorting_vw.sql

- Resolves #6005 
This view includes case_serial form both current MURs and archived Murs which will facilitate the sorting.
Related ticket: #5982 
1 dev
- Run `pytest`
- Run `flyway migrate`

Add view for MUR sorting

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml

- Resolves #5994 
This ticket upgrades flyway to v10.19.0 to remove a security vulnerability
(Include who is required to review prior to merge. For example: One designer and two front end developer reviews are required prior to merge)
- flyway
2. Update flyway `brew upgrade flyway`
4. Confirm flyway version 10.19.0: `flyway -v` 
8. `pytest`
9. run `snyk test --file=data/flyway/build.gradle` and make sure no vulnerability.
Note: To run the snyk command you may need to upgrade gradle by running `brew upgrade gradle`

Upgrade flyway v10.19.0

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml
data/migrations/V0304__add_arch_curent_mur_sorting_vw.sql
requirements.txt
tests/integration/test_current_cases.py
webservices/args.py
webservices/docs.py
webservices/legal_docs/advisory_opinions.py
webservices/legal_docs/current_cases.py
webservices/legal_docs/es_management.py
webservices/resources/legal.py

Sprint 26.3 release branch. @cnlucas will deploy on 10/15/2024

[MERGE WITH GITFLOW] Release/public 20241015

---

tests/integration/test_current_cases.py
webservices/legal_docs/current_cases.py
webservices/utils.py

- Resolves #5996 
This ticket loads the mur citations into the `legal/citations` endpoint
- MUR load 
- Archived MUR load
- Checkout this branch
- Start elasticsearh
- Create case_index: `python cli.py create_index case_index`
- load current murs: `python cli.py load_current_murs` you can stop this early - citations are loaded first 
- `flask run`
Test citations endpoint and doc_type filter: 
http://127.0.0.1:5000/v1/legal/citation/statute/10
http://127.0.0.1:5000/v1/legal/citation/regulation/100.13
http://127.0.0.1:5000/v1/legal/citation/regulation/1/?doc_type=murs
http://127.0.0.1:5000/v1/legal/citation/statute/9/?doc_type=murs
http://127.0.0.1:5000/v1/legal/citation/statute/9/?doc_type=advisory_opinions (no murs show)
Check MUR disposition citations against prod: …

Feature/5996 add MUR citations

---

webservices/common/models/costs.py

This fixes the 500 errors we're getting when sorting electioneering by '-disbursement'
- electioneering mv 
- check out this branch 
- `flask run`
- Go to: http://127.0.0.1:5000/v1/electioneering/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&sort=-disbursement_date&per_page=30&page=1

[MERGE WITH GITFLOW] Hotfix/fix election type

---

webservices/resources/legal.py

- Resolves #6030 
This PR removes unused code from legal.py 
- legal.py
- start elasticsearch 
- `flask run `
- Test type filter 
Sample URLs: 
http://127.0.0.1:5000/v1/legal/search/?type=wrong_type
http://127.0.0.1:5000/v1/legal/search/?type=123
http://127.0.0.1:5000/v1/legal/search/?type=murs
http://127.0.0.1:5000/v1/legal/search/?type=advisory_opinions

Remove unused code from legal.py

---

requirements.txt

- Resolves #6037
Upgrades werkzeug to remove snyk vulnerability
1-2 devs
1. Checkout this branch
2. pip install -r requirements.txt
3. snyk test --file=requirements.txt --package-manager=pip
4. pytest
5. flask run

upgrade werkzeug

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml

- Resolves #6065
Upgrades flyway to version 11
1-2 devs
- db local migrations
2. Update flyway `brew upgrade flyway`
4. Confirm flyway version 11.0.0: `flyway -v` 
8. `pytest`
9. run `snyk test --file=data/flyway/build.gradle`

6065 upgrade flyway 11

---

tests/conftest.py
tests/integration/test_ao_elasticsearch.py
tests/integration/test_cases_elasticsearch.py
tests/test_dates.py
tests/test_legal_data.py
webservices/args.py
webservices/docs.py
webservices/exceptions.py
webservices/resources/legal.py

This is for the sprint (27.2) release.
@tmpayton  will deploy this.

[MERGE WITH GITFLOW] Release/public 20250114

---

data/migrations/V0307__add_fec_fitem_sched_ab_2025_2026.sql

- Resolves #6100 
add_fec_fitem_sched_a_2025_2026 and fec_fitem_sched_b_2025_2026 table
Require one database developer
-None
| branch           | PR       |
| ---------------- | -------- |
| fix/other_pr     | [link]() |
| feature/other_pr | [link]() |
- download the branch to local machine, either …

add_fec_fitem_sched_a_2025_2026 and fec_fitem_sched_b_2025_2026 table

---

webservices/resources/legal.py

This PR fixes a bug in prod to add kwargs to accept the api_key argument

[MERGE WITH GITFLOW] Add kwargs for api_key

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml
data/flyway/run.sh
tests/common.py
tests/conftest.py

- Resolves #6235 
This PR upgrades Flyway and fixes errors when running pytest. 
- flyway
- pytest
- start virtualenv 
- upgrade flyway using brew `brew upgrade flyway`
- check version and ensure it matches 11.8.2 `flyway -v`
- `pytest`

Upgrade flyway 11.8.2

---

requirements.txt

- Resolves #6256 
upgrades requests to remediate snyk vulnerability
1 dev
-  endpoints walk, public key creation, post_to_slack
- pyenv virutalenv 3.11.9 api
- pyenv activate api
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- npm i && npm run build
- pytest
- go to manage.py and find slack_message. Update from #bots to #test-bot
```
def slack_message(message):
""" Sends a message to the bots channel. you can add this command to ping you when a task is done, etc.
run ./manage.py slack_message 'The message you want to post'
"""
post_to_slack(message, "#bots")
```
- python cli.py slack_message test
- snyk test --file=requirements.txt --package-manager=pip

6256-upgrade requests

---

data/migrations/V0311__add_fosers_tables.sql

- Resolves #6223 
Add migration file for fosers tables
1-2 dev
1. Download feature
3. Run `flyway migrate`

Add migration file for fosers

---

webservices/legal_docs/advisory_opinions.py

- Resolves #6286 
This PR re-orders the nested AO documents starting with the final opinion, then the category id ascending
- AO legal search 
- activate virtual env 
- re-load AOs: `python cli.py initialize_legal_data ao_index`
- flask run 
- ensure that In AO nested documents, the final opinion is listed first, followed by the categories in ascending order: `http://127.0.0.1:5000/v1/legal/search/?type=advisory_opinions`

Re-order nested AO documents

---

data/migrations/V0314__create_form_56_mv.sql

- Resolves #6277
Adds mv for form 5 endpoint
2-4 devs
- Adds form 4 receipts endpoint
- remove the alter statement and run in dbeaver dev
- compare indexes to filters in [Form 5 endpoint ](https://github.com/fecgov/openFEC/pull/6330)
- pyenv activate env
- pytest
- invoke create-sample-db

[Wait to merge until endpoint it reviewed] 6277 add form 5 mv

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml

- Resolves #6356
This PR upgrades flyway to remove a snyk vulnerability. 
- flyway
- Update flyway run: `brew upgrade flyway`
- Confirm flyway version 11.13.1: `flyway -v`
- run `dropdb cfdm_test`
- run `createdb cfdm_test`
- run `invoke create-sample-db`
- run` pytest`

Upgrade flyway v11.13.1

---

webservices/resources/rulemaking.py

- Resolves #6358 
This PR fixes a bug when using more than one nested filter. I will add a comment below with a sample query.
- rulemaking search 
- start virtual env 
- start elasticsearch 
- load some rulemakings: `python cli.py load_rulemaking`
- load these specific rulemakings:  
`python cli.py load_rulemaking 2023-04`
`python cli.py load_rulemaking 2013-02`
`python cli.py load_rulemaking 2013-04`
`python cli.py load_rulemaking 2013-05`
`python cli.py load_rulemaking 2021-01`
- `flask run`
Sample URLs: 
Description: http://127.0.0.1:5000/v1/rulemaking/search/?q=%22REG%202023-04%22 (2023-04)
Lvl 1: http://127.0.0.1:5000/v1/rulemaking/search/?q=%22Inflation%20Adjustment%20Act%22 (2013-02)
Lvl2: …

Fix nested rulemaking filters
