fecgov/openFEC

run_api.py
webservices/db.py
webservices/resources.py
webservices/rest.py
webservices/setup/rest_server.conf

* Places a `run_api.py` file in the repo root. This allows `webservices` to be a package (as the top-level module is the repo root, rather than within `webservices`). This is actually needed for this PR, but will be with the next one (which separates candidate resources)
* Split out database connection info
* Split out SingleResource and Searchable
* Format is now determined by the resource (rather than `assign_formatting`)
* Flake8 for new files

Separate out base resources

---

data/ddl/processed_schema.in_rds.sql
data/ddl/processed_schema.to_rds.live.sql
data/ddl/processed_schema.to_rds.sql
data/ddl/psql_w_vars.sh
data/ddl/to_rds_ddl.live.sql
data/ddl/to_rds_ddl.sql
documentation/notebooks/processes.ipynb

either current live data or a copy in process
Many and kind of cryptic changes (sorry, reviewer!) but the point is that, from PostgreSQL on the bridge machine, it's now possible to push a full copy of the data from FEC to a separate schema on RDS, while the current data remains in place.  When that copy is done we can rapidly swap it to become the new production data.

Separate ``live`` and ``processed_live`` schemas to access

---

webservices/candidates/models.py
webservices/rest.py

We need to do more complex ordering in the future, but that will be much easier after we alter the import script and we are working off of pre-joined tables. For now, lets make it look pretty by making the default sorting by name.
This doesn't fully implement #176, but it makes it better.

Simple order to candidate and committee

---

webservices/manage.py

Just a little something I've found helpful while learning my way around this app. Might be helpful for others, too.
- Shows all routes in the app, with their Python methods and HTTP methods
- To invoke: `python manage.py list_routes`

Add 'list_routes' management command

---

webservices/candidates/resources.py
webservices/test_api.py
webservices/tests/candidate.py
webservices/tests/candidate_tests.py
webservices/tests/common.py

Adds a regression test for querying all fields on a single candidate + comments on where these fields are coming from. This will need to be rewritten for #360, but may help debug that, too.
Also fixed a bug with "other_names".

Candidate tests

---

data/sql_updates/create_candidates_vw.sql
webservices/resources/candidates.py
webservices/test_api.py

- `active_through` now shows most recent year
- `election_years` will show all election years candidate participated
regardless of filters
- ofec_candidates_vw will now only return one line per candidate
- all status details will be according to the most recent record

Changed candidate list view election years behavior

---

data/sql_updates/create_candidates_vw.sql
webservices/resources/candidates.py
webservices/test_api.py

This standardizes the names so that we are not using _short anymore. I hope this makes the refactor easier on the front end and the name in the calls will reflect the output. I also added sentence case for the full names, since that was what Noah said he preferred. 
I will use the same patterns in /committees to keep things consistent.

Name standardization to match the previous _full pattern.

---

requirements-scrapers.txt
scripts/scrapers/pubrec.py

This was a quick Open Data Day hack; nothing groundbreaking here
This will do a really simple translation from XLS data sources to records on disk. This is likely *not* the best way to import the data, but I figured I'd at least have the scraper do *something* before I left ODD.
Reamining issues:
:+1: 
```json
{"LAST NAME, FIRST": "Dornan, Robert K. \"Bob\"", "#": 503.0, "RUNOFF %": "", "GENERAL %": "", "Notes (See Endnotes Tab)": "", "DISTRICT": "46", "GE RUNOFF": "", "LAST NAME": "Dornan", "TOTAL VOTES": "", "PRIMARY": 13630.0, "GENERAL": "", "GE RUNOFF %": "", "FIRST NAME": "Robert K. \"Bob\"", "STATE": "California", "STATE ABBREVIATION": "CA", "PRIMARY %": 0.16468910852806845, "RUNOFF": "", "PARTY": "R", "FEC ID": "H6CA27124", "INCUMBENT INDICATOR": ""}
```

Add some simple scrapers for FEC election results

---

data/ddl/keys.sql
data/sql_updates/create_candidate_detail_vw.sql

- Added limits to DISTINCT ON subqueries to help Postgres figure out the
plan
- Added one index
- Removed unnecessary aggregate functions on GROUP BY columns
- Cast election_yr to int instead of numeric (as Postgres was doing
behind the scenes) when doing join

Sped up candidate detail view SQL

---

webservices/rest.py

It was referencing old classes so it was throwing a 500

fix base url so there is no 500

---

.travis.yml
data/sql_updates/README.md
data/sql_updates/alter_read_only_web_role.sql
data/sql_updates/create_candidate_detail_vw.sql
data/sql_updates/run_all.sql
manage.py
requirements.txt
webservices/common/util.py
webservices/manage.py
webservices/rest.py
webservices/totals/resources.py

This is a simpler system than "migrations", but we don't need real migrations when all of our tables are (materialized) views, and updating them simply means dropping and recreating them, no matter the change. We also don't have views that rely on one another, at least at this point, so ordering is not a problem.
What this provides is a one-step command that runs all the SQL scripts, and can be easily called by either a dev or another process, to keep the database up to date.
```
python webservices/manage.py refresh_db
```

Added a 'refresh_db' command to manage.py

---

runtime.txt

- CloudFoundry needs to run on Python 3

Update runtime.txt to use Python 3.4.3

---

README.md
scripts/bootstrap/Vagrantfile
scripts/bootstrap/fec_bootstrap.sh
scripts/bootstrap/provision.sh
scripts/bootstrap/tmux/fec-local.yml

Getting started with development on the two repos is non obvious. This PR adds the ability to quickly bootstrap the environment for working on openFEC and openFEC-web-app.
Next steps could be to add provisioning scripts to add all requirements for Linux or OSX automatically (python3, virutalenv, postgres, etc).

[WIP]Adds bootstrap script and vagrant setup

---

webservices/common/models.py
webservices/tests/committee_tests.py
webservices/tests/common.py

The `CommitteeList` resource may attempt to query on `candidate_ids`, but that field isn't mapped in the `Committee` model. This patch adds the missing column and tests on querying by candidate ID.

Query candidate ids

---

.travis.yml
cron.py
data/refresh/refresh.sql
manage.py
requirements.txt
run_api.py
scripts/bootstrap/fec_bootstrap.sh

Add cron-like task based on Celery Beat to refresh materialized views nightly. Subsumes #566.
This has been updated and should now actually work with the usual CF workflow. Note that the celery beat task isn't debounced at the moment, so invocations could stack up if it were scheduled too frequently--but this shouldn't be an issue for running nightly.
Also, postgres 9.4 added a `REFRESH MATERIALIZED VIEW CONCURRENTLY` function, which might make the refresh faster. @arowla: if we upgrade, we might want to give that a try (we're using 9.3, right?).
* Add cron-like task to run `refresh_materialized` every night at midnight
* Rename management command `refresh_db` to `update_schemas`
* Add management command `refresh_materialized`; refreshes all materialized views
* Add management commands …

Cron refresh

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml

... until the new one's Python buildpack is ready

Explicitly keep us on the old stack

---

webservices/rest.py

This is for security and use by api.data.gov. We could add more ips later, if we wanted to. 
issue #518

White listing the api.data.gov ip when PRODUCTION=true

---

run_api.py

Make environment configuration consistent with webapp, which uses
FEC_WEB_DEBUG flag for debug mode.
[resolves #582]
I noticed that openFEC-web-app handles this issue with a `FEC_WEB_DEBUG` flag, so figured it would be simplest to use that approach here for consistency. The `PRODUCTION` flag was only used to set debug mode on the app, so I think it's reasonable to use the more specific name.

Use FEC_API_DEBUG flag to control debug mode.

---

webservices/resources/totals.py

The default totals model was using the abstract `CommitteeTotals` model, not the concrete `CommitteeTotalsPacOrParty` model. My bad.

Fix default totals model.

---

Procfile
manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
newrelic.ini
requirements.txt
run_api.py

Removes some settings from `newrelic.ini` and moving them to env variables.
Removes double reporting by only using the `Procfile` command instead of the `run_api` instantiation. 
It requires a `NEW_RELIC_LICENSE_KEY` to be set.
Fixes #602
/cc @arowla 
Also, use Gunicorn for better performance and better reporting.

Change New Relic config

---

data/sql_updates/create_candidate_history_view.sql
data/sql_updates/create_committee_detail_view.sql
data/sql_updates/create_linkage_names_view.sql
webservices/common/models.py

Note: This patch will fail on Travis, since the data in the repo have
diverged from the data on golden gate. This patch should be updated with
new sample data before merge.
* Disambiguate `candidate_id` column
* Column now exists on multiple tables in join, leading to ambiguous reference
* Pull `filing_freq` from `dimcmtetpdsgn` rather than `dimcmteproperties`
* Remove `link_date` column

Update import scripts for golden gate.

---

data/sql_updates/create_candidates_view.sql
data/sql_updates/create_committee_detail_view.sql
data/sql_updates/create_committees_view.sql
data/sql_updates/create_linkage_names_view.sql

A handful of materialized view queries used per-row SELECT statements,
so that a separate SELECT was emitted for each row of the view. This
patch replaces per-row SELECTs with JOINs, which makes queries
noticeably faster on the production data.
Once this gets merged, we should see faster schema migrations and view refreshes. On the local data, these changes took migration time from ~7s to ~3s. On GoldenGate, queries that took an unacceptably long time (I got impatient and cancelled anything that ran for 10 minutes without finishing) actually finished.

Optimize queries to build materialized views.

---

webservices/resources/committees.py

Queries were being constructed with faulty where clause that tried to filter on ofec_committees_mv instead of ofec_committee_detail_mv. Fliters like 'designation' were not working at all.

Changed CommitteeDetail to filter with CommitteeDetail

---

data/sql_updates/create_committee_detail_view.sql
data/sql_updates/create_committees_view.sql

The `dimcmtetpdsgn` table sometimes contains multiple entries per
`cand_sk`, possibly a change since the switch to Golden Gate. This patch
uses only the most recent entry in `dimcmtetpdsgn` when constructing the
materialized views for committees.
This should fix the duplicate committees issue that @LindsayYoung noticed earlier today.
attn @LindsayYoung @arowla

Fix duplicates in committees views.

---

data/sql_updates/create_candidate_detail_view.sql
data/sql_updates/create_candidate_history_view.sql

Continuing in the same vein as #674, this patch sorts by
`candproperties_sk` instead of the now-uninformative `load_date` when
building views that pull from the `dimcandproperties` table.
@LindsayYoung I think this resolves the issue you brought up in conversation on #674 about getting the most recent candidate properties for the candidate history view.

Use most recent candidate properties in materialized views.

---

data/sql_updates/create_committee_detail_view.sql
data/sql_updates/create_committees_view.sql
webservices/common/models.py
webservices/resources/committees.py
webservices/tests/committee_tests.py
webservices/tests/common.py

Note: Based on the recommendation of FEC, this patch only considers
receipt dates from F1 filings. Since we're doing an `INNER JOIN` to combine
`dimcmte` and `dimcmteproperties`, committees that have never filed an F1
are excluded. We could switch to a `LEFT JOIN`, but then we'd have a bunch
of committees with `NULL` dates and values from `dimcmteproperties`.
Thoughts @lindsayyoung @arowla?
[Resolves #624]
[Resolves #649]

Update first and last filing dates for committees.

---

README.md

Add status badges to show new people that our builds are (normally) passing and which issues are up for grabs.

Add Travis CI and Waffle badges to docs.

---

deploy.sh
manifest_dev.yml
manifest_prod.yml
manifest_stage.yml

This is necessary for a parallel change to the webapp that builds assets
remotely. The webapp needs to use both the python buildpack (to run the
app) and the node buildpack (to compile the assets).

Use buildpack-multi for webapp.

---

manifest_prod.yml

Enable HTTPS redirect implemented in https://github.com/18F/openFEC-web-app/pull/117 in prod space. Related to #619.

Force HTTPS in production.

---

data/sql_updates/create_committee_detail_view.sql

Based on correspondence with FEC, we should only use F1 filings to
determine original filing dates, but we can use the most recent filings
regardless of form type for other committee properties. I got this
almost right in #678 but applied the F1 filter to the most recent
committee properties rather than the original properties. This patch
moves the filter to the right join.
Thanks @lindsayyoung and @arowla for identifying the issue.

Move form filter to correct join.

---

webservices/schemas.py

- Adds missing `coverage_start_date` to the reports API
- found missing federal funds total

Adding missing start date and federal funds

---

.cfignore
manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
webservices/rest.py

* Fetch swagger-ui source remotely
* Ignore local `node_modules` (was interfering with remote download)
* Fix hard-coded static asset path
This is the code that's currently deployed to dev.

Fix static files needed for swagger documentation.

---

tests/committee_tests.py
tests/factories.py
webservices/common/models.py
webservices/resources/candidates.py
webservices/resources/committees.py

* Fix typo in view name
* Add regression test
This patch fixes a three-character typo ("dimcmte_fulltext" becomes "dimcmte_fulltext_mv") and adds a regression test to make sure we're covering fulltext search on committees.

Fix name of committee fulltext view.

---

data/sql_updates/create_committee_detail_view.sql
data/sql_updates/create_committees_view.sql

The `org_tp` and `org_tp_desc` columns in the `dimcmte` table are
occasionally inconsistent: a small subset of rows have non-null values
for the format and nulls for the latter. This patch ignores `org_tp_desc`
and instead builds the organization description from `org_tp`.
[Resolves #754]

Build organization type description from organization type.

---

tests/candidate_tests.py
webservices/common/models.py
webservices/resources/candidates.py
webservices/rest.py
webservices/schemas.py

* Add `principal_committees` relationship to `Candidate`.
* Add `/candidates/search` endpoint; includes nested principal committees.
* Use `subqueryload` to avoid n+1 database queries.
* Update unit tests.
Pinging @arowla for review and @msecret to let me know if this will be adequate for candidate search. If you'd like the reverse nesting, I'll add that as well. By the way, we could also encode the output variables in the query parameter (e.g. `/candidates?nest=true`), but then it's hard to decide how to describe the output format (not sure how/whether Swagger handles optional output fields OTOH).

Add candidate search endpoint with nested principal committee.

---

data/sql_updates/create_candidates_view.sql

- This fixes a bug (#762) where the `max()` on party and party_full were pulling
from different rows, resulting in a party code/party description
mismatch

Changed dimcandoffice to pull just most recent

---

README.md

Give example usage of test data for local development.
Related to this, the integration tests will automatically load the test subset and attempt to run the SQL import scripts, so tests will fail if there are any syntax errors in the SQL scripts. This may be relevant to discussion on #767 @LindsayYoung.

Clarify test subset usage.

---

data/sql_updates/create_candidate_detail_view.sql
data/sql_updates/create_candidates_view.sql

When we fixed candidate party descriptions by altering the join between
`dimcand` and `dimcandoffice`, we also introduced a regression, such
that each candidate had at most one year in `election_years`. To select
both the correct row in `dimcandoffice` to determine party affiliation
and the correct rows to determine election years, we need two joins.
This patch adds a second join, and harmonizes the candidate views to use
the same logic.

Restore correct `election_years` and `active_through` columns.

---

data/sql_updates/create_reports_house_senate_view.sql
data/sql_updates/create_reports_pacs_parties_view.sql
data/sql_updates/create_reports_presidential_view.sql

Previously, we were joining `dimcmte` on `dimcmtetpdsgn` to generate
views for committee reports. Because committees may have multiple
designations, this was in some cases creating duplicate reports. Since
we only used the join on `dimcmtetpdsgn` to fetch the committee type,
and since this value was neither imported into SQLAlchemy nor serialized
to the API, the simplest way to handle the duplication was to remove the
join.

Remove duplicated reports.

---

tests/candidate_tests.py
webservices/common/models.py

Fix a syntax error on secondary join between Candidate and Committee
tables. Also fix insufficiently strict unit test.
Resolves an issue reported by @noahmanger in https://github.com/18F/openFEC-web-app/pull/165#issuecomment-103174202. Good catch!

Fix principal committee join.

---

data/sql_updates/create_committee_detail_view.sql
data/sql_updates/create_committee_history.sql
data/sql_updates/create_committees_view.sql

We currently calculate committee cycles from committee statements of
organization (F1 filings), but committees may file financial reports
(e.g. F3s) in cycles during which they have not filed F1s. This patch
uses F3s instead of F1s to calculate active cycles per committee. Among
other issues, this resolves the missing data for the 2015-2016 cycle
reported by FEC.

Calculate committee cycles from fact tables.

---

tests/candidate_tests.py
webservices/exceptions.py
webservices/resources/candidates.py
webservices/rest.py
webservices/sorting.py
webservices/utils.py

When using `subqueryload` for eager loading with the `CandidateSearch`
resource, we have to specify which model we're sorting on, e.g.
`Candidate.candidate_id` instead of "candidate_id". This patch adds an
optional `model` argument to the `fetch_page` helper, which retrieves
the column property from the model if provided. We also now throw a 400
if a user tries to sort on a column that doesn't belong to the relevant
model.
h/t @msecret

Fix sorting on candidate search view.

---

tests/report_tests.py
webservices/common/models.py

@LindsayYoung: This was kind of a subtle problem. In the tests, we're using `Integer` fields to store `beginning_image_number`, but the realistic number we provided here was too big. Switching to `BigInteger` fixes the issue. For some reason, Flask swallowed the `integer out of range` error we *should* have been getting and threw an interpretable error instead. And the issue would never come up outside of testing because the SQL scripts will intelligently detect the correct data type for us when we're importing real data.
`¯\_(ツ)_/¯`

Use BigInteger to avoid overflow on image numbers.

---

data/sql_updates/create_reports_house_senate_view.sql
data/sql_updates/create_reports_pacs_parties_view.sql
data/sql_updates/create_reports_presidential_view.sql
tests/report_tests.py
webservices/args.py
webservices/resources/reports.py

Allow API consumers to specify report types in reports endpoints. This can be used to either include or exclude reports by type:
* `/committee/<committee_id>/reports?type=Q1&type=Q2`
* `/committee/<committee_id>/reports?type=-TER`
Partial fix for #881 based on feedback from @dcpcc1967 and @jwchumley.

Allow specification of included and excluded report types.

---

tests/committee_tests.py
webservices/resources/candidates.py
webservices/resources/committees.py

Search wildcards were partly added in #882, but I missed one on the committees endpoint. This patch adds the missing wildcard and a regression test to go along with it.
h/t @LindsayYoung

Add more wildcards to search terms.

---

requirements.txt
tests/candidate_tests.py
tests/committee_tests.py
tests/common.py
tests/report_tests.py
tests/test_api.py
webservices/schemas.py

Smore ignores the `fields` and `additional` meta options of `Schema`
classes, but my fork respects the `exclude` option. This patch switches
to my fork of smore and relies on `exclude` instead of `fields` to
ensure that internal fields such as `idx` are excluded from Swagger
output.

Hide internal fields from Swagger output.

---

webservices/docs.py
webservices/rest.py

When running in production mode, include an `api_key` param in the
Swagger spec for all endpoints.
[Resolves #863]

Add API key to Swagger in production.

---

requirements.txt

This is a quick follow-on to the JSON encoding fix--better to install dependencies from the PyPI unless we're using a custom fork, so that unreleased breaking changes don't gum up the works.

Install flask extensions from PyPI; use recent versions.

---

webservices/resources/candidates.py
webservices/resources/committees.py
webservices/rest.py

For the webapp (and potentially other consumers of the API), we need to
be able to look up information about nested resources at a particular
time: e.g., information about all of a candidate's associated committees
in the 2011-2012 election cycle. We currently support these nested
history lookups for committee history, but not for candidate history,
exposing an edge case on the webapp where we can occasionally show the
wrong information for a candidate on her/his committee page. This patch
adds consistent endpoints for nested history resources.

Use consistent endpoints for candidate and committee history resources.

---

tasks.py

Realized that git flow uses a branch called 'release' to prepare releases before it gets merged into master AND tagged... so we should probably host the release branch on staging.

Changed staging branch from 'master' to 'release'

---

README.md

Note: Everything in these instructions can be automated using Boto. But since we shouldn't need to create new snapshots often, and may pick a different approach for copying data to dev and stage, I don't think automating is worth the time just now. The next person to update the snapshots may want to revisit this and write scripts as they go along.
[Resolves #835]

Document database snapshots.

---

manifest_prod.yml
webservices/rest.py

Necessary to get caching through api.data.gov. Prerequisite to #889.
See http://apiumbrella.io/docs/caching/ for more information.

Add caching headers from environment.

---

tasks.py

Not strictly necessary for the API at this point, but we may need this
later on, and it's more consistent with the webapp.

Handle spaces that should be mapped to multiple routes.

---

webservices/args.py

Since all of our request parsing assumes that list parameters are repeated (e.g. `foo=bar&foo=baz`), set `collectionFormat='multi'` as the default on the `Arg` constructor.
This is at least a partial fix to #980; not sure if anything else needs to happen here.

Direct swagger-ui to combine query arguments correctly.

---

data/sql_updates/create_candidate_history_view.sql

Using report key as a proxy for when the report was received. Would like to use receipt date in the future. Fixes #987

order candidate records to get the most recent

---

.travis.yml

Attempt to run Travis builds without sudo privileges. This lets us use Travis's much faster containerized builds--if it works!

Use containerized builds.

---

manifest_base.yml

Necessary to prevent buildpack compilation failures. Based on https://github.com/18F/foia-hub/pull/830.

Upgrade to current CF stack.

---

data/functions/acronyms.sql

now the label will say 'Super PAC (Independent Expenditure-Only)' which is better for smaller screens,

updating label

---

webservices/docs.py

Explain how keyset pagination works, because it's not what API consumers may expect. h/t @LindsayYoung.

Document keyset pagination.

---

webservices/rest.py

The `/` and `/v1/` URLs are currently empty and incorrect, respectively. This patch redirects both URLs to the developer documentation.

Redirect from empty URLs to developer documentation.

---

webservices/args.py

h/t @LindsayYoung 
Bad dates used to throw errors like this: `Expected type "parse" for max_date, got "string"`
Now they will throw better errors like this: `Expected date for max_date; got "11932151128"`

Improve error messages on invalid date args.

---

webservices/docs.py

Self-explanatory. Note: tests will fail on Travis because requirement versions aren't yet pinned on master. Merging hotfix #1042 will resolve this.

Link to data restrictions in API docs.

---

tests/test_utils.py
webservices/args.py

Handle currency arguments like "$50". Useful for users who accidentally
use currency symbols, and for the webapp, which also prepends "$" to
currency values.

Parse currency strings from query.

---

data/sql_updates/post_committees_create_filings_view.sql

We only permit sorting on indexed columns, since sorting on non-indexed
columns can be painfully slow. This patch adds indexes on columns on
which the webapp tries to sort filings data.

Add indexes on filings columns.

---

data/sql_incremental_aggregates/prepare_schedule_a_aggregate_size.sql

To match FEC reporting rules.
@LindsayYoung: Think we should keep the rest of the buckets as they are, or also change to `<=` for consistency?

Use <= 200 for first contribution size bucket.

---

webservices/templates/swagger-ui.html

Turns out we need to add Ethnio here to get it to show up in the API docs.
@noahmanger can you confirm that this is the right link? I went to the ethn.io url and got and empty response.

Add Ethnio link.

---

webservices/rest.py

Adding a default key when none is supplied- should make the documentation more approachable. 
close #1066

adding demo key by default to make it easier to try out.

---

tests/test_api.py
webservices/args.py

Don't let users request unlimited records per page, which can lead to out of memory errors. h/t @LindsayYoung.

[dontmerge] Hotfix/cap per page

---

webservices/args.py
webservices/docs.py
webservices/resources/elections.py

- moved elections to the financial tag 
- added an enum to create drop-down options in documentation
- added some explanation of how to use the endpoint
- added a warning that you shouldn't use this to see who
is running since there could be a significant lag.

Small doc improvements for this awesome endpoint!

---

manage.py

Prevent cron script from rebuilding aggregates from scratch.

Separate aggregate tasks into rebuild and update.

---

data/sql_incremental_aggregates/prepare_schedule_a_aggregate_employer.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_occupation.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_size.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_state.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_zip.sql
tests/test_integration.py

See discussion in https://github.com/18F/openFEC-web-app/issues/339 for
motivation.
This restricts aggregates to contributions from individuals for the following:
* Schedule A by state
* Schedule A by zip
* Schedule A by employer
* Schedule A by occupation
* Schedule A by contribution size
Schedule A aggregates by contributor type are unchanged; ditto for Schedule B aggregates.
This also incorporates a few fixes from #1067.
Ping @LindsayYoung

Restrict most aggregates to individual contributions.

---

data/sql_updates/create_committee_history.sql

Previously, the committee history view was built by joining
`dimcmteproperties` on `dimcmtetpdsgn` using date columns. Recently, the
`receipt_date` column on `dimcmtetpdsgn` appears to have been changed
such that nearly all values are `NULL`. This patch uses `form_sk` to
join the tables and preserve designation information.

Join designation by form ID.

---

requirements.txt
webservices/rest.py

The API currently uses the `Access-Control-Allow-Origin` header, but not
the `Access-Control-Allow-Headers` header. This leads to CORS errors
when using Safari, which sends the `Accept-Encoding` header with its
`OPTIONS` requests. Rather than allowing the `Accept-Encoding` header,
this patch switches to Flask-CORS for CORS configuration, which has
better defaults and is easier to configure than settings CORS headers
manually.
Thanks @onezerojeremy and @noahmanger for help with debugging.
[Resolves https://github.com/18F/openFEC-web-app/issues/462]

Use Flask-CORS for more robust CORS configuration.

---

tests/test_elections.py
webservices/paging.py

* Catch zero division error on empty query sets with no per-page cap
* Add regression test
h/t @noahmanger for finding the error

Fix error on empty elections.

---

tests/test_utils.py
webservices/args.py
webservices/resources/elections.py
webservices/sorting.py
webservices/utils.py

Allow API consumers to specify whether null values are treated as small
or large when sorting using the `sort_nulls_large` parameter. Useful for
keeping candidates with small fundraising totals out of the top of the
election view endpoint.

Expose control over null order.

---

tests/test_elections.py
webservices/args.py

We currently require congressional district search parameters to be two
characters wide, such that searching for "02" returns results, but
searching for "2" does not. This patch zero-pads district queries so
that API users don't have to remember to do it themselves.
Written for use with the election lookup widget.

Handle numeric congressional districts.

---

tests/test_itemized.py
webservices/paging.py

Seek pagination currently serializes `datetime` values correctly but
doesn't handle `date` values. This patch handles `date` values and adds
a regression test.

Fix sort by date on seek pagination.

---

tests/test_filings.py
webservices/args.py
webservices/resources/filings.py
webservices/rest.py

Currently, the filings view mounted as a sub-resource of a candidate or
committee does no filtering, which breaks the filter widget on the
committee and candidate filings pages. This patch adds filtering on
filings sub-resources and merges the two filings resources into a single
class.
Note: To make this play nicely with Swagger, the path parameters for
committee and candidate IDs are prefixed with "path_". This is a hack
but has no effect on the behavior of the API, so I think it's
acceptable.

Fix filtering on filings view.

---

webservices/paging.py

Seek pagination with multiple sort columns requires the use of SQL row
value comparisons (e.g. `(foo, bar) < (1, 2)`). This patch uses the
SQLAlchemy `tuple_` expression to use row values; plain Python `tuple`
objects don't translate to the correct query.
Fixes a sorting issue raised in fec-partners.

Use `tuple_` expression for row value filters.

---

data/functions/individual.sql
data/functions/utils.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_employer.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_occupation.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_size.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_state.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_zip.sql
data/sql_setup/prepare_schedule_a.sql
data/sql_updates/post_committees_create_filings_view.sql
tests/test_itemized.py
webservices/resources/sched_a.py

The filings view is currently filtered on `report_year`, but this column
is always set to 0 for F1 filings. This patch checks both the
`report_year` and `receipt_date` columns, such that F1 filings have
dates and can be included.
Partial workaround for #1147.

Include F1 filings in filings endpoint.

---

webservices/paging.py
webservices/resources/sched_a.py
webservices/utils.py

When filtering on multiple committees, the query planner can't take
advantage of the compound indexes on `sched_a_sk` and other receipts
columns, resulting in very slow queries. This patch creates a separate
subquery for each committee and combines the results with `UNION ALL`.
Note that both the subqueries and the combined query must apply the same
filters and `ORDER BY` rules.
h/t @arowla for suggesting subqueries

Allow filtering receipts on multiple committees.

---

data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql

By default, the histograms used by the query planner are too coarse to
capture rarely-occurring values in large tables. This means that queries
by state on rare states (AS, PR) can be extremely slow. This patch
insructs the database to use finer histogram bins for state columns on
the itemized tables and explicitly re-analyzes the tables after creating
indexes for better performance on these queries.

Use detailed query statistics.

---

data/functions/aggregates.sql
webservices/common/views.py
webservices/resources/aggregates.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py
webservices/resources/sched_e.py

The codebase currently has a few different approaches at base resource
classes that handle query generation and filtering. To avoid
duplication, this patch unifies them into a single `ApiResource` class.

Unify base resource classes.

---

webservices/resources/filings.py

Clean up some duplicated code. One base resource class to rule them all.

Use base resource class to avoid duplicated code.

---

data/sql_updates/create_totals_house_senate_view.sql
data/sql_updates/create_totals_pacs_parties_view.sql
data/sql_updates/create_totals_presidential_view.sql

Fix a typo mixing up starting and ending cash on hand. After this
change, fundraising totals on the election page are identical to the
corresponding totals on each candidate's detail page.
[Resolves #1110]

Fix last cash on hand.

---

tests/test_elections.py
webservices/resources/elections.py
webservices/rest.py
webservices/schemas.py

Add an election summary endpoint returning the number of candidates and total receipts and disbursements across all associated committees for a given election:
```
$ http http://localhost:5000/v1/elections/summary/?office=president&cycle=2012
HTTP/1.0 200 OK
Content-Length: 89
Content-Type: application/json
Date: Wed, 09 Sep 2015 18:31:41 GMT
Server: Werkzeug/0.10.4 Python/3.4.3
{
"api_version": "1.0",
"count": 105,
"disbursements": 1346584691.25,
"receipts": 1347810482.25
}
```

Add election summary endpoint.

---

data/sql_updates/create_election_outcome_view.sql
data/sql_updates/create_sched_e_aggregate_candidate.sql
tests/test_integration.py

Using `REFRESH MATERIALIZED VIEW CONCURRENTLY` requires that the table
has at least one unique index. This patch adds unique indexes to tables
that were missing them before, and adds a regression test to prevent
errors of this type in the future.
h/t @LindsayYoung

Fix concurrent refresh; add regression test.

---

webservices/common/views.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py

Apply the `UNION ALL` optimization for performant queries on itemized
resources by multiple committees to the base `ItemizedResource` class.
This patch improves performance for these queries against Schedule B
transactions.

Generalize and document itemized committee queries.

---

webservices/resources/elections.py

This patch uses the `cand_inactive_flg` to exclude candidates from election views: candidates with non-`NULL` values for this column are no longer included in the election summary or detail views.
h/t @PaulClark2 @LindsayYoung
[Resolves #1193]

Exclude inactive candidates from election views.

---

requirements.txt
webservices/args.py
webservices/common/views.py
webservices/resources/aggregates.py
webservices/resources/candidate_aggregates.py
webservices/resources/candidates.py
webservices/resources/committees.py
webservices/resources/dates.py
webservices/resources/elections.py
webservices/resources/filings.py
webservices/resources/reports.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py
webservices/resources/sched_e.py
webservices/resources/totals.py
webservices/rest.py
webservices/schemas.py
webservices/spec.py
webservices/utils.py

Glue code for parsing request parameters with webargs and marshalling responses with marshmallow, plus generating swagger documentation, has moved over to https://github.com/jmcarp/flask-smore, which is more flexible and better tested than the code in this repo. This patch removes code that lives in flask-smore and takes advantage of improved APIs to reduce duplication.
h/t @sloria for help with flask-smore design

Move generic helpers and Swagger tools to flask-smore.

---

tests/test_aggregates.py
webservices/resources/candidate_aggregates.py

Prevents double-counting some candidate aggregates on the elections
page.

Use more restrictive join between candidates and committees.

---

data/sql_updates/create_committee_history.sql
webservices/args.py

This should be more accurate for groups that do not file F1. It is looking only after the start date because the old ids got reused in some cases.
fixes #1209

Made committee first file date with the filings table. 

---

tests/test_committees.py
webservices/resources/candidates.py
webservices/resources/committees.py

Candidate and committee counts can be inflated when queries involve
joins on the candidate-committee join table. This patch applies
`DISTINCT` to these queries to avoid double-counting.
h/t @dannguyen for reporting!
[Resolves #1112]

Use distinct queries for candidate and committee resources.

---

data/sql_updates/create_sched_e_aggregate_candidate.sql

This is a temporary fix for #1226. As described in the issue, Schedule E
transactions from 24- and 48-hour reports aren't currently grouped by
unique transaction, such that multiple amended versions of the same
transaction can exist in the database. In the long term, @paulclark2 and
@jwchumley will work on aggregating Schedule E transactions across
amendments, but as a short-term fix, this patch simply restricts
Schedule E aggregates to transactions filed on form F3X.

Restrict Schedule E aggregates to form F3X.

---

data/sql_updates/create_committee_history.sql

Self-explanatory. Deals with missing data as described in #1235.

Exclude filings with missing report years from cycle aggregation.

---

data/sql_updates/create_candidate_history_view.sql

Checking for an F2 for cycle selection, so that we don't have dropdown options on candidate pages for periods that the candidates didn't file to run for office. 
(I tried to add the same logic to the elections, but it was too aggressive and took out real elections. So, that can be a different PR.) 
This should help with #964

Improve the cycle selection for candidates

---

data/sql_updates/create_committee_history.sql
data/sql_updates/post_committees_create_filings_view.sql

Thanks to @PaulClark2, all records in `vw_filing_history` now have
non-zero values for `report_year`, so we can revert a few temporary
patches for handling missing years.
This doesn't add a feature or fix a bug--we're just deleting crufty code that no longer serves a purpose.

Remove temporary workarounds around filings report years.

---

bin/run.sh

Previously, different dependencies pinned to conflicting versions of
upstream dependencies, requiring an manual install of pinned versions on
deploy. The conflict has been resolved, and the pinned versions are now
out of date, so this patch reverts the workaround.

Revert temporary fix for dependency conflicts.

---

data/sql_updates/post_committees_create_filings_view.sql

I was looking over my patch yesterday and realized it should be even simpler. We don't need to extract the year from the receipt date at all now that we have reliable report years in the filings view.

Further simplify report year logic.

---

data/sql_updates/create_candidate_history_view.sql
webservices/args.py

This will decrease the chances of offensive names popping up in typeahead.
This is not perfect because there are some issues with dimcandproperties. there are candidates that should show up that don't.
fix 18F/openFEC-web-app#804

limiting typeahead

---

webservices/resources/elections.py

As discussed in #1252, candidate status values are sometimes out of
date or missing; filtering by candidate status inappropriately excludes
some relevant elections. This also makes the election search logic more
consistent with the election detail logic.
Related to https://github.com/18F/openFEC-web-app/issues/766.

Remove election search filter on candidate status.

---

webservices/resources/elections.py

Hide elections with district "99" from election search results.
Note: this is a workaround; a better solution would be to fix the
underlying data, as described in #1271.
Related to https://github.com/18F/openFEC-web-app/issues/766

Hide district 99 from election search.

---

data/functions/acronyms.sql
data/sql_updates/create_candidate_history_view.sql
manifest_stage.yml

Some candidate office districts assembled from `dimcandproperties`,
`dimcandoffice`, and `candoffice` have values of "99" instead of their
true values. Based on a suggestion from @PaulClark2, this patch uses
`cand_valid_fec_yr` instead of `dimcandoffice` and `candoffice` to fetch
candidate state and district values.
This patch only touches a few parts of our materialized view, but this will need a careful review. @LindsayYoung take a look when you have time, and if it makes sense, we can deploy to dev and make sure this doesn't cause any collateral problems.
[Resolves #1271]

Get candidate office from `cand_valid_fec_yr`.

---

requirements.txt
webservices/resources/aggregates.py
webservices/resources/candidate_aggregates.py
webservices/resources/candidates.py
webservices/resources/committees.py
webservices/resources/dates.py
webservices/resources/elections.py
webservices/resources/filings.py
webservices/resources/reports.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py
webservices/resources/sched_e.py
webservices/resources/totals.py
webservices/rest.py
webservices/utils.py

Upgrade to latest flask-smore, which has been renamed to flask-apispec. This fixes the issue reported by @LindsayYoung and @leahbannon where the demo key isn't added in production.
Note: this is a hotfix, so once it's reviewed, we'll merge into both develop and master.

[hotfix] Rename flask-smore to flask-apispec.

---

data/sql_updates/create_committee_history.sql
data/sql_updates/create_linkage_names_view.sql
webservices/common/models/links.py

This patch fixes double-counting in election summary totals. Some totals
were multiply counted because of repeated candidate-committee linkage
rows; this patch ignores these expired duplicate rows. Thanks
@LindsayYoung and @PaulClark2 for guidance.
* Exclude all linkage rows where `expire_date is not null`.
* Add missing index on linkage view.
* Use helpers to expand acronyms.
Replaces #1284.

Exclude expired linkage rows from views.

---

.about.yml

The Team API should probably be case-insensitive, but this fixes a breakage for now.
cc: @jmcarp @LindsayYoung

Update LindsayYoung's case

---

data/sql_updates/create_reports_house_senate_view.sql
data/sql_updates/create_reports_pacs_parties_view.sql
data/sql_updates/create_reports_presidential_view.sql
tests/test_integration.py
tests/test_reports.py
webservices/args.py
webservices/resources/reports.py

* Include F3* records with non-null `expire_date`
* Add "amended" filter to committee reports views
* Index `expire_date`
Note: this requires a quick patch to the frontend so that only current
reports are requested for the committee detail view. This will be
submitted shortly.
[Resolves https://github.com/18F/openFEC-web-app/issues/874]

Included amended F3* records.

---

webservices/schemas.py

To avoid truncation of large numbers by some JSON parsers, serialize
`sub_id` and `original_sub_id` values on filings and itemized
transactions as strings.
Related to #1247.

Serialize sub_id values as strings.

---

webservices/resources/elections.py

Following changes in the construction of the candidate history view,
representations of missing states and districts changed such that
missing districts may be encoded as "00" or `None`. Until this
inconsistency is resolved, handle both missing values in the election
search view.
h/t @noahmanger

Handle multiple representations of null districts.

---

webservices/resources/reports.py
webservices/resources/totals.py

Due to a mismatch in active cycles between `dimcmteproperties` and
`vw_filing_history`, some committee reports and totals return 404s on
attempting to resolve the committee type when a cycle is specified. This
patch temporarily falls back to resolving committee type from the detail
table when no matching results can be found for the specified cycle.
Note: this should be reverted after the underlying issue described in
https://github.com/18F/openFEC-web-app/issues/875 is resolved.

Temporarily fetch committee type from detail table.

---

data/sql_incremental_aggregates/prepare_schedule_a_aggregate_contributor.sql
tests/test_filters.py
webservices/filters.py

When aggregating receipts by contributing committee, we filter out items
with entity type equal to "IND". As implemented, this filter
unintentionally remove items with entity type `null` as well. To fix,
this patch coalesces `entity_tp` with the empty string.
[Resolves #1294]

Check for null entity type on filter.

---

data/sql_updates/create_reports_ie_only.sql
tests/test_reports.py
webservices/common/models/reports.py

Expose expiration date on IE reports.
Fixes an uncaught exception on fetching IE reports with
`is_amended=false`. Thanks @PaulClark2 for reporting.
To verify, check a URL like localhost:5000/v1/committee/C00590398/reports/?is_amended=false (or likewise for any IE filer) and check that the response code is 200, not 500.
Attention @LindsayYoung

Expose expiration date on IE reports.

---

requirements.txt
webservices/rest.py

The latest version of flask-apispec includes a minor breaking change. This patch upgrades to the latest version, installed from the PyPI rather than GitHub, and fixes the import that changed since the last version.
cc @LindsayYoung

Upgrade to latest version of flask-apispec.

---

data/functions/clean.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_contributor.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_recipient_committee.sql
data/sql_incremental_aggregates/update_schedule_a_fulltext.sql
data/sql_incremental_aggregates/update_schedule_b_fulltext.sql
data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql
webservices/common/models/itemized.py

As described in #1306 and #1330, committees sometimes enter the same values for
`contbr_id` and `cmte_id` (for receipts) and for `recipient_cmte_id` and
`cmte_id` (for disbursements). In these cases, values of `contbr_id` and
`recipient_cmte_id` should be ignored for receipts and disbursements,
respectively. This patch creates `clean_contbr_id` and
`clean_recipient_cmte_id` columns, which are displayed in the API
instead of the original `contbr_id` and `recipient_cmte_id` columns.
[Resolves #1306]
[Resolves #1330]
To verify, we'll rebuild the itemized tables on the dev server and verify that the incorrect contributor and recipient committee IDs described in #1306 aren't displayed in the API (or on the data site).

Censor duplicate committee IDs in itemized tables.

---

.travis.yml

See https://github.com/nickstenning/travis-pip-cache.
To verify that this works, run the build more then once; expect faster install times after the first run.

Cache compiled dependencies for faster builds.

---

tests/test_candidates.py
webservices/common/models/candidates.py

Join candidates to their principal committees using committee
designation values from the linkage table. This ensures that we're
fetching the most recent principal committee, not the most recent
committee that was ever a principal committee. This also fixes a few
candidates for whom principal committee designations are correct in the
linkage table but missing in the committee designation table.
Related to #1299.

Use committee designation on linkage table.

---

.buildpacks
package.json

The Cloud Foundry team recently updated the node buildpack and the
default version of node installed. This causes deployments to fail on
buildpack compilation. This patch pins our node and buildpack versions
to the last known working releases.

Pin node and buildpack versions.

---

data/sql_updates/create_committee_history.sql

I noticed one last reference to `dimlinkages` in our materialized views. This tiny patch switches it over to `cand_cmte_linkage`. The check on `expire_date` is removed because the column doesn't exist in the FECP table.

Remove all uses of dimlinkages from materialized views.

---

tests/test_elections.py
webservices/resources/elections.py

Searching elections by zip code or congressional district is expected to
return relevant Senate and Presidental elections, as well as House
elections. This behavior was broken with the switch to
`cand_valid_fec_yr`. This patch restores the expected search behavior
for congressional districts.

Show Senate and Presidential elections on district election search.

---

data/sql_updates/create_candidate_history_view.sql
data/sql_updates/create_committee_history.sql
data/sql_updates/create_totals_house_senate_view.sql
data/sql_updates/create_totals_ie_only_view.sql
data/sql_updates/create_totals_pacs_parties_view.sql
data/sql_updates/create_totals_presidential_view.sql
data/sql_updates/post_totals_create_fulltext_views.sql
tests/test_api.py
webservices/common/models/candidates.py
webservices/common/models/committees.py
webservices/common/views.py
webservices/resources/search.py
webservices/rest.py
webservices/utils.py

Weight committee and candidate typeahead results by total receipts.
* Include total committee receipts in committee typeahead view
* Include total receipts summed over authorized and principals in candidate typeahead view
* Order typeahead results by descending receipts
Note: this patch uses total receipts as a very simple heuristic for search relevance. We can implement more elaborate rules if needed, such as including disbursements or weighting results by time, but I propose that we try this out first.
Pinging @LindsayYoung for review as time permits. @noahmanger: let me know if you want to take this for a test drive or demo to FEC, and we can deploy to dev.

Weight typeahead search by committee receipts.

---

data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql
data/sql_setup/prepare_schedule_e.sql

Create temporary itemized tables, then drop existing tables and rename
when ready. Avoids downtime on itemized resources during schema updates.

Create temporary itemized tables to avoid downtime.

---

data/sql_updates/create_candidate_history_view.sql

Fix a regression from #1386 that allowed duplicate election years in
candidate views. Thanks @noahmanger for spotting.
IMO this fix has to go in before the next release, so I'm hoping @LindsayYoung can take a look in the morning. I'm going to deploy this change to the dev database for testing now.

Ensure unique candidate election years.

---

webservices/resources/candidates.py
webservices/resources/committees.py
webservices/sorting.py
webservices/utils.py

Allow sorting candidates and committees by total receipts when the "q"
parameter is set; otherwise, full-text search tables aren't joined, and
sorting by receipts is undefined.
[Resolves #1396]

Allow sorting candidates and committees by receipts.

---

data/sql_updates/create_cand_cmte_linkage_view.sql
data/sql_updates/post_totals_create_fulltext_views.sql
webservices/resources/committees.py

Ignore linkages with mismatched committee types.
[Resolves #1406]
To verify:
* House candidate Tammy Baldwin should not be linked to Baldwin for Senate
* Senate candidate Tammy Baldwin should appear before House candidate Tammy Baldwin in typeahead search results
cc @PaulClark2 @LindsayYoung

Ignore linkages with mismatched committee types.

---

data/sql_incremental_aggregates/update_schedule_a.sql
data/sql_incremental_aggregates/update_schedule_a_fulltext.sql
data/sql_incremental_aggregates/update_schedule_b.sql
data/sql_incremental_aggregates/update_schedule_b_fulltext.sql
data/sql_incremental_aggregates/update_schedule_e.sql
data/sql_incremental_aggregates/update_schedule_e_fulltext.sql
data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql
data/sql_setup/prepare_schedule_e.sql
tests/test_integration.py

Nightly updates on itemized tables fail when the same item has been
added or modified more than once within a single update cycle. To fix,
this patch adds primary key constraints on the queue tables and deletes
any existing records in the queues by primary key on insert.
Note: We'll be able to express this more concisely as an upsert once
postgres 9.5 is available on RDS.
[Resolves #1392]
@arowla: Have time to take a look? This is a very small patch--I just want to verify that the approach makes sense here, and that there isn't a smarter way to solve this problem.

Ensure itemized queues are unique on corresponding primary key.

---

requirements.txt
webservices/calendar.py
webservices/resources/dates.py
webservices/rest.py

Export calendar dates in ical format for use with Google Calendar, iCalendar, etc.
Note: All exports are automatically filtered to +/- 1 year around the time of the request. Pagination isn't an option here--calendar applications generally expect to get *all* events in a single request. Because there aren't many rows in the calendar table, performance is adequate without pagination--about 0.6s to get all events, with no filters.
@LindsayYoung @noahmanger

Add icalendar exports.

---

tests/factories.py
tests/test_aggregates.py
tests/test_candidates.py
tests/test_utils.py
webservices/args.py
webservices/common/models/aggregates.py
webservices/common/views.py
webservices/resources/aggregates.py
webservices/resources/candidates.py
webservices/resources/committees.py
webservices/resources/dates.py
webservices/resources/elections.py
webservices/resources/filings.py
webservices/resources/reports.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py
webservices/resources/sched_e.py
webservices/resources/totals.py
webservices/sorting.py
webservices/utils.py

* Disable multi-column sort
* Always sort on unique keys on aggregate tables
By sorting aggregate tables on a unique key as well as the
user-specified sort key, results are returned in a stable order even in
the presence of duplicates on the selected sort column. Note: this
requires that tables have composite indexes on each possible sort column
and the unique column.
[Resolves #1361]
Ping @LindsayYoung for code review. This doesn't change a huge amount of code, but it might be helpful to talk through the proposed changes synchronously at some point.

Ensure stable sort on aggregate tables.

---

webservices/resources/aggregates.py

Prevent candidate aggregate views from sorting on the index column of
their base models, which may not have a `FROM` clause in the aggregate
query. This fixes sorting on candidate aggregates for "other spending".
h/t @LindsayYoung

Nullify index column on candidate aggregates.

---

tests/test_candidates.py
tests/test_elections.py
webservices/resources/candidates.py

The `CandidateHistoryView` resource is meant to take an `election_full`
flag, but previously hadn't included the flag in its `args`. This patch
adds the missing request parser and a regression test.
[Resolves #1031]

Use election full flag in candidate history view.

---

webservices/tasks/download.py

Necessary for downloads on https://github.com/18F/openFEC-web-app/pull/987.
cc @LindsayYoung

Whitelist independent expenditure downloads.

---

webservices/tasks/__init__.py

Starting our refresh at 4 am will get us all the main tables except for calendar data. That isn't done until 7am and I think if we waited that long to do our update, that would impact performance. 
@jmcarp do you agree that starting our data refresh at 4 will give us enough time so we don't run into morning performance issues?
Closes #1448

Looking to update data 4 am eastern, 9 GMT to get fresher data

---

webservices/rest.py

Since we're running the API behind a proxy, we need to use the `ProxyFix`
middleware to pull the forwarded URL, scheme, etc. off the request. This
fixes redirects from https to http. I'm guessing this issue emerged when
we dropped the unnecessary nginx proxy.

Use ProxyFix middleware.

---

data/sql_updates/create_omnibus_dates.sql
webservices/docs.py

As written, this patch excluded all odd-year reports and all reports
with the 12C or 12P types. This update only excludes 12C and 12P reports
in even years.

Update exclusion rule.

---

tests/test_utils.py
webservices/args.py
webservices/common/views.py
webservices/resources/elections.py
webservices/sorting.py
webservices/tasks/download.py
webservices/utils.py

Allowing users to control where nulls appear in sort order has the
undesirable consequence of permitting queries that sort without relying
on an index. This patch removes the `sort_nulls_large` option to prevent
users from sending potentially slow queries of this type.

Revert null position option.

---

data/sql_updates/create_candidate_history_view.sql

As implemented, the statutory candidate flag includes a number of false
negatives due to a `group by` on `cand_status`, combined with a
`distinct` on `cand_id`. The `group by` yields potentially many rows per
candididate, with some `true` and some `false`; the `distinct` selects
just one of these rows, which could be a `false` when other rows are
`true`. This patch drops these two expressions. And now that the
grouping logic is the same as in a previous select, it also combines
selects to make the view slightly faster to build.
* Drop group by on `cand_status`
* Drop unnecesary distinct on `cand_id`
* Move status aggregate into existing select
* Simplify case to plain &&
BTW: any `case` statement that only yields `t` or `f` should be possible to simplify to a boolean operation.

Fix and clean up statutory candidate flag.

---

data/functions/utils.sql
data/sql_updates/create_candidate_history_view.sql
data/sql_updates/post_totals_create_candidate_aggregates.sql
tests/test_aggregates.py
tests/test_candidates.py
tests/test_committees.py
webservices/common/models/candidates.py
webservices/resources/candidate_aggregates.py
webservices/resources/candidates.py
webservices/resources/committees.py

* Use pre-computed election ranges for `election_full` flag
* Limit election ranges to maximum office duration
[Resolves https://github.com/18F/openFEC-web-app/issues/1107]

Use pre-computed election ranges to round up to next election.

---

tests/test_dates.py
webservices/calendar.py

[Resolves https://github.com/18F/FEC/issues/262]
[Resolves https://github.com/18F/openFEC/issues/1549]
Note: the issues above only seem to affect google calendar subscriptions. To verify manually, deploy to dev and verify that times are correct on google calendar subscriptions. Google seems to cache subscribed events, so changes may not show up immediately--changing calendar filters should help.

Add timezones to ics exports.

---

README.md

This quick pull request fixes two typos:
* `create up your environment` --> `create your environment`
* `make sure you environment` --> `make sure your environment`

Fix two typos in 'Quick(ish) start' section

---

requirements.txt
tests/test_downloads.py
webservices/tasks/download.py

The PostgreSQL `COPY TO` helpers have been externalized and generalized
at https://pypi.python.org/pypi/sqlalchemy-postgres-copy. This patch
switches to the external library for `COPY TO` logic.

Use external library for COPY TO.

---

webservices/docs.py

Quick typos I found while working with the API and reading docs.

Fixes docs.py typos

---

CONTRIBUTING.md

This changeset updates our CONTRIBUTING.md documentation with up-to-date information around our team practices based on recent conversations we have had internally.
There are now two formal teams at 18F working with the FEC on related projects and we are largely working within the same repositories for project-related work. Based on recent conversations between the two teams, we are committed to supporting one another to achieve success and produce the highest quality work we can.
These changes reflect the agreements and commitments we have made to one another. As our needs and/or the needs of the project change, we are also committed to updating these team practices as necessary to keep them current.
cc: @emileighoutlaw, @anthonygarvan, @jenniferthibault, @adborden, @jenniferthibault, …

Updates to our contributing guidelines

---

tests/common.py
webservices/resources/candidates.py
webservices/schemas.py

We introduced a handful of lazy-loaded relationships in #1548. For
example, loading N records via `CandidateView` currently runs one query
(to fetch candidate detail rows) followed by N additional queries (one
to fetch the flags row for each candidate row). This patch uses eager
loading for all candidate views that expose related attributes via
flags, and restores `nplusone` to prevent future performance
regressions.

Eager-load flags on candidate views and restore nplusone.

---

README.md

This changeset adds more details to the test data subset instructions found in the README.
The existing instructions were not completely clear in what information you needed to provide in order for the commands to work, or that you needed to create a new database for yourself that was completely empty.
/cc @emileighoutlaw and @LindsayYoung

Updated test data subset instructions

---

data/sql_updates/omnibus_dates.sql

Cleaner party names, but uppercased. Also switches one instance off of a warehouse table.
@emileighoutlaw can you confirm uppercased parties are better that title cased parties that have junk in them sometimes.

Use better party discription on calendar

---

.travis.yml
tests/common.py

Although this is a very minor fix.  I'm wondering how people are getting tests to pass locally? (guessing that the sql string is set via environment variable)  And finally, are the tests being actively used and maintained?  Sorry for all the questions.  This pull request was more for me to get comfortable with the git flow workflow.

Fixed database string, changes dashes to underscores

---

README.md

This changeset accounts for a missing installation step in the README that we accidentally removed during our cleanup.
h/t to @jontours for finding the missing step!

Small fix to npm install instructions in README

---

webservices/docs.py

I wanted to emphasize that it was a two-year period, so we don't assume they already know our two year cycle construct. Also I think it is more helpful to mention the field names by what they see in the API rather than the underlying SQL tables that users don't see. 
I ran it by @emileighoutlaw too get her opinion too. 
Thanks!

small definition tweak

---

webservices/rest.py

Fixed this problem using the "import x as z" statement, so as not to break all the references to restful and cors.  Warnings can be verified as gone by starting up the api server.

Fix for flask import warning statements

---

.buildpacks
.cfignore
.gitignore
.travis.yml
manifest_base.yml

* Switch to vetted python buildpack
* Install swagger-ui on travis and include in deploy
* Remove `node_modules` from `.cfignore`
Part of https://github.com/18F/openFEC/issues/1643.
Note--we could simplify this further and `git clone` swagger-ui instead of `npm install`-ing it, since I'm guessing this repo isn't going to accumulate more npm requirements. I don't have a preference about this--just thought I'd mention the possibility.

Build assets on CI.

---

tests/factories.py
tests/test_itemized.py
webservices/args.py
webservices/common/models/itemized.py
webservices/docs.py
webservices/partition/base.py
webservices/partition/sched_a.py
webservices/partition/sched_b.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py

Part of #1735
This changeset renames the field we originally went with for partitioning the itemized schedule A and B tables. We had received feedback that `transaction_year` was a bit confusing and have decided to go with `two_year_transaction_period` instead to be more descriptive of what this value represents.
/cc @LindsayYoung, @jontours

Rename transaction_year field

---

tasks.py

Addresses https://github.com/18F/openFEC/issues/1738
This changeset ensures that we only authenticate with cloud.gov if the login environment variables are set (which should only be in the case of a bot, e.g., Travis CI), but that we always change our target organization and space to match what was detected and/or passed in.
h/t to @adborden on accounting for the targeting step!
/cc @LindsayYoung, @jontours, @noahmanger, @adborden, @anthonygarvan

Account for CF target in deploy task

---

webservices/schemas.py
webservices/tasks/download.py

This changeset addresses a few things that were flagged as needing to be changed based on the recent feedback we received.  These changes include the following:
* Enabling the display of the Memo Code field (memo_cd in the database) in the CSV output (this has the side effect of displaying it in the API as well)
* Displaying the time zone label with the timestamp given in the manifest (the timestamp is processed as UTC).
These modifications are a part of the full list in https://github.com/18F/openFEC/issues/1748
/cc @LindsayYoung, @jontours, @noahmanger

Address itemized downloads feedback

---

tasks.py

This changeset ensures that we are properly specifying the API to use before authenticating if need be.
h/t to @adborden again for catching this.
/cc @LindsayYoung, @jontours, @anthonygarvan, @noahmanger

Target cloud.gov api for deploy

---

data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql
webservices/partition/base.py

Addresses #1760 
This changeset addresses an issue with failing updates for the Schedule A and B tables.  The update process did not take into account the table partitioning and was still basing the checks off of the report year (`rpt_yr`) instead of the new calculated value (`two_year_transaction_period`).  In order to fix this, I had to do the following:
* Add the `two_year_transaction_period` column to both sets of queue tables for Schedule A and B.
* Remove the `two_year_transaction_period` column from the column factory in the select statement generation for processing updates.
* Add full support for the `timestamp` column in the Schedule B queue tables.
I do not believe this is entirely straightforward so there is a comment in the code that refreshes the child tables during an …

Fix Schedule A and B updates

---

requirements.txt
tasks.py

Low priority, but I noticed that invoke deprecated its old task definition api and now requires tasks to take a context argument. This patch pins to the latest invoke and uses the new task api. It's also fine to stick with an older invoke, but IMO it's worth upgrading, if only so that our tasks look like the tasks in the invoke docs. Plus miscellaneous bug fixes invoke has made between 0.10 and 0.13.

Upgrade to latest invoke.

---

tests/test_aggregates.py
webservices/resources/candidate_aggregates.py
webservices/schemas.py

Related to this PR: https://github.com/18F/openFEC-web-app/pull/1295.  The flags are now present on the totals/candidate endpoint.  At the end of the day it was a fairly easy fix, it helps to dig into SqlAlchemy and see what query is actually being ran against the database.  Ready for review and merge.

Add flags to JSON returned by candidate/totals endpoint.

---

webservices/partition/base.py

@LindsayYoung @ccostino This is a pretty simple change.  If anything else needs to be changed with this let me know, but I've verified with my test database that this does indeed add the primary keys after running update_all.

Primary Key fix for partitioned tables

---

data/sql_incremental_aggregates/prepare_schedule_a_aggregate_employer.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_occupation.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_size.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_state.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_zip.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_purpose.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_recipient.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_recipient_committee.sql
data/sql_updates/sched_a_by_size_merged.sql

Fixes #1775
This changeset adjusts the processing for the aggregate tables to make use of temporary tables first. Prior to this, any updates to the aggregates in the database would cause the site to not yield the data that we expect to see.  We would like to achieve as little downtime as possible and the rest of our database processing makes use of creating temporary tables and views to accomplish this, so we are making use of them here as well.
For the initial approach I opted to do the renaming inline with the table processing.  Most of our materialized views are renamed separately at the end of processing, but if we want to follow those steps we'll need to move the creation of all of the triggers for each of these tables.
There is one instance of a table that has dependent objects, the …

Adjust aggregate table processing to make use of temporary tables

---

webservices/tasks/__init__.py

So they don't collide with dev on the same RDS everynight
fix #1626

Getting rid of daily updates on feature 

---

webservices/sorting.py

This is a fix for the election sorting endpoint.  I thought that maybe the logic I wrote caused this problem, but after doing some inspection of the code, in this case the logic I wrote in sorting.py was returning the same sorting column it did in the past.  So this gets back to something that broke the logic.  
Did we update sql alchemy at some point?  I know when we updated to flask 11 some of the import statements changed, but the library at the core of those imports _should_ have stayed the same.  However, it does seem to be that just using the raw sort string itself no longer works on queries that aren't simple entity model mappings.
Anyway, this fix accounts for columns that are aliased by SqlAlchemy.  I think that should be all the edge cases for the different queries that are …

Fix for election sorting

---

manage.py

I think that grouping the updates with the respective queue deletion
might prevent an issue where the updates run half way and the things
that are successfully updated are not cleared from the queue.

Reorder updates

---

manage.py
requirements.txt
webservices/common/models/base.py
webservices/common/models/candidates.py
webservices/common/models/committees.py
webservices/rest.py
webservices/utils.py

Turns out there were some of the`flask.ext` import statements hanging around.  All of our imports are now current with Flask 0.11.  However there is still one deprecation warning, and I think that's originating from NPlusOne.  @jmcarp would it be all right if we open a issue with that and potentially submit a pull request?

Removed flask.ext imports

---

tests/factories.py
tests/test_utils.py

Currently added a new tests in test_utils to test hiding nulls for candidate totals.  This is to ensure that any changes to this endpoint doesn't not cause any regressions.
Still need to add a test for Elections, unfortunately I don't know of any easier ways of doing this, but it does work.

New tests for sorting

---

webservices/resources/legal.py

This commit prioritizes Final Opinions in the search results for advisory opinions. It does not exclude other document types.

prioritizing final opinion document category

---

data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql

Part of #1820 
This changeset replaces the delete statements that went missing from the schedule A queue processing we have.  This has caused an issue where multiple records with the same `sub_id` might exist in these tables and therefore might result in insert errors in the main `ofec_sched_a_*` tables due to existing primary keys from records already processed.
This changeset also addresses an issue where an index being created on the `fec_vsum_sched_b` table was being duplicated due to not being dropped first.
/cc @LindsayYoung, @jontours

Replace missing delete statements

---

manage.py
webservices/partition/base.py

Part of #1838 
Fixes #1840
When partitioning the itemized Schedule A and B tables, the indexes of the existing tables were being dropped and recreated, but this impacted the existing tables before they were replaced. As partitioning these tables takes a long time with the full FEC data set, this can cause problems if the partitioning is taking place during normal usage times.  Without indexes on these tables for the columns that we expose for searching and filtering, the database performance grinds to an absolute halt and queries back up.
This changeset alleviates this issue by renaming the indexes once the tables themselves are renamed so that they are not removed too early.  The `create_index` method still attempts to drop the indexes like before, but it will only do so if they still …

Add support for renaming indexes

---

runtime.txt

With the recent cloud.gov update, the python buildpack no longer supports python 3.4.3, so let's upgrade.
https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.5.8

Bump python version for cloud foundry

---

.cfignore
.gitignore
requirements.txt

This changeset updates Celery to the latest patch level version and addresses a small problem we ran into during recent deploys.  If you have a local copy of the `celerybeat-schedule` file, it will go up with the deploy to cloud.gov and cause the `celery-beat` app to error out upon starting.  Adding this file to the `.gitignore` and `.cfignore` files will prevent this from happening.
/cc @LindsayYoung, @jontours 
h/t to @jmcarp for helping troubleshoot, thank you!

Address issue with celerybeat-schedule

---

webservices/resources/legal.py

This fixes a bug when >10 docs are present in an AO.

returning all docs in ao

---

tests/factories.py
tests/test_itemized.py
webservices/common/models/itemized.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py
webservices/resources/sched_e.py

The sort errors are fixed by adding a default sort order
For the transaction id, we had it going twice and the transaction_id was always null. Now we just have the string version going.

Fix transaction id in schedules and sort bug fixes

---

webservices/common/models/reports.py
webservices/schemas.py

@noahmanger @ccostino @LindsayYoung, this PR adds the missing fields needed to the efiling summaries: document_description and pdf_url.  Verified that the urls exist, also fixed an ambiguous column name: qual -> qualified_muliticandidate_committee.  Gleaned that from the linked form!!  Yay information!

Added document_description and pdf_url to all efile reports summaries

---

README.md
requirements-dev.txt
setup.cfg

With py.test >= 3.0, the section name should be [tool:pytest]
Pin to latest versions of pytest and pytest-cov

Fix py.test warning

---

data/sql_updates/committee_history.sql
webservices/common/models/itemized.py
webservices/schemas.py
webservices/tasks/download.py

Closes #1940 
This changeset addresses #1940 by adding support for related fields back into our exports on the itemized tables.  It does this by defining an extra attribute in our schema Meta objects that is ignored by everything but our export code.  This extra attribute allows you to set additional columns that are found in nested models related to the parent model you are trying to export.  If any are defined, the export functionality will follow the relationship to pull the information out and display it in the output with the specified label.  Documentation in the schema provides more information on how to do this.
This changeset also modifies our Schedule E model by removing the `committee_name` field set directly to the `cmte_nm` field in the table.  This field can sometimes be …

Adds committee names back into itemized schedule downloads

---

tests/test_dates.py

@ccostino @LindsayYoung hotfix for test fix.  Mostly identical to original PR.  Moved initialization of year variable to `setUp` method for convention's sake.

[MERGE W/ GITFLOW] Added year to test model

---

webservices/tasks/download.py

Closes #1947
This changeset enables support to export most of our remaining itemized schedule endpoints.
I'm keeping this open for now in case we want to add more, right now I've only enabled all of what we have for schedule A and B as well as the main schedule D and F endpoints.
/cc @LindsayYoung and @jontours

Adds support for exporting more itemized schedule endpoints

---

webservices/common/models/aggregates.py
webservices/schemas.py

This changeset adds support for displaying committee names in the CSV exports of the itemized aggregate tables.  There is a small amount of technical debt taken on here as I had to incorporate the relationships across multiple models and the existing schema creation convenience methods do not account for this easily.  There might be a way to simplify this in the future, but I also did not want to impact the existing schema building that we have.
This may also expose some additional committee information in the API endpoints, but we can exclude those if need be.
/cc @LindsayYoung and @jontours

Add committee names to itemized aggregate exports

---

data/sql_updates/candidate_aggregates.sql
webservices/common/models/candidates.py

This is ready for review.  Adding `coverage_start_date` and `coverage_end_date` wasn't all that difficult as it turned out.  Have to run update_schemas to fully test this on dev, as it is backed by a materialized view.
/cc @noahmanger @LindsayYoung @ccostino 
Addresses https://github.com/18F/openFEC-web-app/issues/1584.

Added coverage start and end date to candidate totals materialized view

---

webservices/common/models/dates.py

After talking to @LindsayYoung it was discovered that one of the tables is staying in the `public` schema for now.

Removing reference to disclosure schema

---

.cfignore
.gitignore

Since we need to make files to change the creds, I don't want those accidentally checked into source control. This will catch files that have the naming convention we outline in the wiki:
https://github.com/18F/openFEC/wiki/switch-out-cf-service-environment-variables

prevent accidents 

---

webservices/utils.py

Addresses https://github.com/18F/openFEC/issues/2022.  The sort column is needed to ensure pagination can sort through pages and guarantee already seen records don't appear again, aka duplicates.
However, may employ a similar strategy to actually page through nulls, once they appear in the data set.  But strategy to employ will most likely be a little different.
cc @LindsayYoung @ccostino

Keyset pagination fix

---

data/sql_updates/candidate_history.sql

I think this is a nice way to expose more candidates while keeping options to restrict them.  Some of the candidates will be `U` type candidates, however the `principal_committees` will still only be `P` type committees, so we can decorate any of the resources (how candidate search is done now) with more restrictions on a case-by-case basis.
@LindsayYoung @ccostino

Relax candidate table construction

---

webservices/args.py
webservices/resources/totals.py

This changeset adds support for sorting on the `total` column with the new itemized resource by state recipient totals endpoint.
h/t to @xtine for noting the missing sort parameter!
/cc @LindsayYoung and @jontours

Added support to sort by the total column

---

tests/test_load_current_murs.py
webservices/legal_docs/current_murs.py
webservices/legal_docs/reclassify_statutory_citation.py

Display one link per distinct target citation. As we cannot link directly to
52 U.S.C. 30118(b)(3)(B) and can only link to 52 U.S.C. 30118, we will
concatenate the text of all citations that have this link target and
have a single link for them. This has the following benefits:
- Considerable reduction in the use of vertical space.
- Less user frustration as we avoid having multiple links to the same
target.
- It should be easier for humans to comprehend the elided citations at a
glance as we do not bother to expand them. E.g., we would display
"434(b)(2),(3), 434(b)(4),(6)(B)(v)" (from the original text) instead of
"434(b)(2),434(b)(3), 434(b)(4),434(b)(6)(B)(v) ".
Closes 18F/openFEC#2069

Simplify citation text and links

---

manage.py
webservices/legal_docs/__init__.py
webservices/legal_docs/load_legal_docs.py

Enable stemming when creating an empty index through remove_legal_docs.
Remove enable_stemming management command as it is no longer needed.

Enable stemming when creating index

---

data/sql_updates/committee_history.sql

Closes issue: https://github.com/18F/openFEC/issues/2088.  Why this wasn't exposed as a bug originally is hard to say, suffice to say a `select distinct *` requires more column integrity than just `select *`.  Because during the distinct selection postgres couldn't determine the column type.

Casting null to date so distinct can work right [merge w/ git flow]

---

webservices/legal_docs/load_legal_docs.py

When initializing for the 1st time, the index may not be present

Protect against missing index

---

manage.py
webservices/legal_docs/__init__.py
webservices/legal_docs/index_management.py
webservices/legal_docs/load_legal_docs.py

The commands are rather opinionated:
create_staging_index creates a new index `docs_staging` and moves `docs_index`
to point to it.
restore_from_staging_index moves documents from `docs_staging` back to `docs`
and restores the aliases `docs_index` and `docs_search`.

Add commands to support index alias management

---

tests/test_itemized.py

Defined map for arguments as a member of the test class and passed into all the url endpoints that need it.  Only one test need the year to be manually bumped, and that test explicitly tests without the two year contribution period.
/cc @ccostino @LindsayYoung

added kwargs for contribution period

---

manage.py
tests/test_partitioning.py
webservices/partition/base.py

**MERGE WITH GIT FLOW**
Closes #2136
This changeset adds a management command to support creating new child tables to an existing partition of Schedule A and Schedule B data. It will check first before just creating the new table(s) so existing data is not wiped out.
This also includes the beginning of a test suite for the partitioning code.
I modified the existing partitioning code a bit to break out some of the underlying child table processing code and ended up having to add a new flag to a couple of those methods to account for when we're doing a full partition vs. operating against already partitioned tables.
The new command is this:
```sh
./manage.py add_itemized_partition_cycle
```
Given the current year at the time of this PR (2017), this will attempt to create the 2017 - 2018 …

[MERGE WITH GIT FLOW] Adds support for generating new itemized child tables

---

data/functions/calendar.sql
data/sql_updates/large_aggregates.sql
tests/test_large_aggregates.py
webservices/common/models/large_aggregates.py
webservices/resources/large_aggregates.py
webservices/schemas.py

Closes #2122 
This changeset adds support for sorting by date in our entity charts.  It accomplishes this by deriving a date from the `month` and `year` columns that are created in the `ofec_entity_chart_mv` materialized view (and always assuming the first of the month as the day).  Note that we already have a `date` property on the Python side in the `EntityReceiptDisbursementTotals` model, so I did not want to disrupt anything currently using that.  Hence the name for this new column and field being `chart_date`.
h/t to @LindsayYoung for the implementation idea!

Adds support to sort by date for entity charts

---

manifest_base.yml

Health check process instead of port: https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#health-check-type. Necessary for no-route apps on govcloud.

Use process health check

---

data/sql_updates/communication_cost.sql

has multiple entries in the committee history table.
I used the most up to date name, that is what we do elsewhere.
Removed idx because we were not using it since we have the unique
key sub_id.

This is a fix so records do not get duplicated if the committee

---

tests/test_load_current_murs.py
webservices/legal_docs/current_murs.py

This reverts commit 01ff18300f369f893b6b1f70c2d6043504aad965.
18 MURs have non-integral case numbers.

Revert "Sort MURs by descending case number"

---

README.md
webservices/tasks/__init__.py

I saw an issue with redis in our support channel and noticed that the govcloud branch still refers to the `redis28-swarm` service, which is replaced with `redis28` in govcloud.

Update redis service name.

---

README.md
bin/cf_env_setup.sh

This changeset adds support and instructions for running `cf ssh` in the GovCloud environment.  While it is easy and straightforward to SSH into a running application, there is a little bit of environment setup to do once you are in.  This script makes it easy to take care of these things with one command.

Add support and instructions for cf ssh

---

.travis.yml
CONTRIBUTING.md
README.md
manifest_feature.yml
requirements-dev.txt
requirements.txt
runtime.txt
webservices/tasks/__init__.py
webservices/tasks/download.py

This changeset updates some of the tooling and infrastructure in the API to bring things up to date. It includes the following:
* Cleanup of .travis.yml
* Updates several Python dependencies
* Removal of all references to Sentry/Raven
* Updates cloud.gov Python runtime to 3.5.3
* Updates New Relic environment name in the manifest_feature.yml config
* A handful of documentation updates
The Travis cleanup includes updating nvm to make use of the latest stable release of Node.js, which I have been running locally for a while now with no issues.
I originally tried to get things running with Python 3.6 with these changes, but there are a couple of dependencies that are not playing nice with it (namely `slate` and the `distribute` dependency it has).  Things are working fine with Python 3.5 …

Update some of the backend tooling for the API

---

requirements.txt

Turns out that including these two dependencies is something pip warns against - removing them to ensure things work as expected (or break as expected for that matter).

Removing setuptools and wheel due to pip warning output

---

tests/test_current_murs.py
webservices/legal_docs/current_murs.py

The 2nd part, which is usually 'R' or 'r', cannot be used as it
conflicts with other 2nd sort fields which are ints.

Use only case number for sorting MURs

---

tests/test_reports.py
webservices/resources/filings.py
webservices/resources/reports.py

This helps address the issue of amendments appearing lower in the list than the report they amended.
The params to pass into the url for proper sorting would be `sort=-receipt_date&sort=-beginning_image_number`.  It is best to do it this way I think as the time in the time stamp is all zeros for any equal dates.

Multi-sort fully enabled for reports

---

manage.py

Fixes #2286 
This changeset addresses a couple of other issues that have cropped up with the processing in our `update_all` script.  There are two known issues thus far:
* An error while processing the new database connection strings, likely caused by unescaped/unquoted strings
* An error while processing one of the materialized views in which a column being referenced is not found
More items will be added as they are found until the script runs successfully again.  In addition to fixing these issues, this changeset also adds a few more logging statements to provide visibility into the state of things while running the command.

Fix update_all processing

---

tests/test_legal.py
webservices/resources/legal.py

Highlight fields regardless of whether the query matched on them
specifically. Also, remove the highlight_query option as we are not
doing anything special in highlighting.

Restore highlights

---

data/sql_incremental_aggregates/prepare_schedule_a_aggregate_employer.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_occupation.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_size.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_state.sql
data/sql_incremental_aggregates/prepare_schedule_a_aggregate_zip.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_purpose.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_recipient.sql
data/sql_incremental_aggregates/prepare_schedule_b_aggregate_recipient_committee.sql
manage.py
webservices/partition/base.py

**WIP:  PLEASE DO NOT MERGE**
Fixes #2286 
This changeset addresses a few remaining issues with the SQL that references the queue tables and not accounting for the `unknown` type of the `schedule_type` column.  It also addresses the `refresh_child()` method in the partitioning for the same problem.  The previous work done to fix this issue did not take into account the nightly refresh component of the partition code, only the creation of the partitions.
Additional notes have been added to some of the comments as well to explain the purpose and usage of some methods as well.

[WIP] Fix queue processing to account for column type mis-match

---

manage.py
tests/test_integration.py
webservices/partition/base.py
webservices/tasks/refresh.py

This changeset adds a bit of extra support for logging when the nightly updates are run for the itemized schedule data.  It also splits the methods out a bit more from the one management command into one for each, just like the we did for the partitioning code.  This should provide us with more flexibility as well as more visibility into any problems that are currently being swallowed by the success messages.

Improve logging and split out calls for nightly updates

---

tests/test_elections.py
tests/test_utils.py
webservices/resources/elections.py

Turns out to be a relatively simple solution here.  The `outerjoin` in the sql_alchmey code was causing nulled entries for Presidents and Senators, because all the code was doing was querying CandidateHistory, finding entries with a two-year period that matched the cycle passed in, and did an outerjoin on ElectionResults.  Since there are entries for numerous candidates in CandidateHistory for any given cycle there were nulled out entries in the join (null district and candidate_name).  The same problem for Senators.
The outer join was maybe necessary to address data inconsistencies as was discussed at https://github.com/18F/openFEC/issues/1271.  Because the endpoint was also allowing candidates with null districts.
This code is ready for review.  I checked the endpoint with a couple of …

Election search results fix

---

webservices/common/models/itemized.py

This re-orders the schedule A model so that the contributor aggregate amount shows up after the individual receipt amount for greater clarity when downloading and viewing as a CSV.
cc @PaulClark2 @ChristianHilland

Move contributor aggregate after single receipt amount

---

webservices/rest.py
webservices/tasks/__init__.py
webservices/utils.py

This changeset updates most env var references to use `env.get_credential` to ensure that an environment variable is always found.

Update env var references

---

manifest_base.yml
manifest_dev.yml
manifest_feature.yml
manifest_prod.yml
manifest_stage.yml

As we found out, celery can not scale horizontally without creating errors, this pr uses vertical scaling to create the same ratio of workers and memory  in production that we started out with and increases the resources to be be in balance with the other production increases. We know that we can get slow response times if celery is under resourced.

[MERGE WITH GITFLOW] hotfix/celery-vertical

---

data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql

This changeset removes the `RAISE` statements in the itemized schedule triggers as they appear to be causing GoldenGate to malfunction when they are called.  They are only supposed to write statements to the PostgreSQL log, not throw exceptions, but it seems that GoldenGate is treating them as exceptions anyway and halting processing.

Remove RAISE statements from triggers

---

README.md

replaces with `FEC.gov`, `the FEC`, or `the new FEC.gov` as appropriate

swaps out beta references from README

---

tests/test_legal.py
webservices/resources/legal.py

The name of the AO number field is `no`, not `ao_no`.

Use the right field name for AO number

---

data/load_advisory_opinions_schema.sql
webservices/tasks/__init__.py
webservices/tasks/legal_docs.py

Check every 15 minutes for AOs modified in the last day. Use the
first AO in this set as the starting AO for loading advisory opinions.
This may be run multiple times with no harm as the loading process is
idempotent.

Refresh AOs every 15m

---

data/sql_updates/totals_combined.sql

Places nulls last for `cvg_end_dt`.  Then when we find distinct entries, we aren't left with null coverage end dates.  Addresses https://github.com/18F/FEC/issues/4201.

Reduces chance of null coverage end dates in committee totals

---

data/sql_updates/totals_candidate_committee.sql

By adding `cand_election_yr` to group by, this disambiguates the totals; the distinct statement then removes duplicates.

Fixes double counting issue for special election candidates

---

tests/test_itemized.py
webservices/args.py
webservices/partition/sched_a.py
webservices/resources/sched_a.py

Might add some tests for this.  Gonna say it needs repartitioning, even though I'd say it shouldn't since this only adds indexes for zip, but last time we tried that the partitions got jacked up.

Zip code search enabled on contributions

---

README.md

The QuantifiedCode service is shutting down on July 22, 2017, so this changeset removes the badge from our README.  We will be researching an alternative in the near future.

Remove QuanitifiedCode badge

---

data/crosswalks/f3x_reports.sql
data/sql_updates/totals_pac_party.sql

This was the variable replacement that Jeff found. No changes needed in combined because it adds other and candidate loans.

Amending the f3x total loan field because it is called other loans

---

webservices/tasks/__init__.py

To minimize the delay between legal documents published in Postgres and
getting indexed in Elasticsearch, use a cron based schedule. As the
Postgres refresh runs 0, 15, 30 and 45 minutes after the hour, and is
very quick, we should schedule the legal docs refresh to run 5, 20, 35
and 50 minutes after the hour.

[MERGE with git flow] Hotfix/schedule legal refresh with cron

---

data/sql_updates/filings.sql
webservices/common/models/filings.py
webservices/schemas.py

Fixes #2533 
This change set fixes the html_url property in the filings end point and adds the property to the efile/filings end point.
**NOTE**
This requires running `update_schemas` in the database.

Fixes html_url property in filing end points

---

webservices/tasks/download.py

This is to prevent deletion of bulk-downloads directory within s3 bucket.

Deletion exception for bulk-downloads

---

requirements.txt
tests/test_downloads.py
webservices/resources/download.py
webservices/tasks/__init__.py
webservices/tasks/download.py

This changeset updates Celery to the latest current 4.0.x release.  We are doing this to keep our dependencies up to date and to help address some issues we have been having with our downloads recently.
We are following Celery's [4.0 upgrade documentation](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#upgrading-from-celery-3-1) and making adjustments as necessary to get the new version working.
**TODO**
/cc @jmcarp - I won't ask for a formal review, but you're more than welcome to chime in if you'd like! :-)

Upgrade Celery to latest 4.0.x release

---

.travis.yml
requirements-dev.txt

We are running into some issues with our tests failing in Travis and currently all signs point to something breaking down in the Travis build.  This changeset forces the build environment to use Trusty (which Travis is in the process of rolling out to all builds regardless), which in turn also supports using PostgreSQL 9.6 (which this project is running on).  We will continue making adjustments as necessary to see what is causing the tests to fail and what might be needed to get them to work.
This PR also pins all of our development dependencies to specific versions.  Please see issue #2573 for more information.

Force using Trusty and PostgreSQL 9.6 in Travis CI

---

tests/test_advisory_opinions.py
tests/test_current_murs.py
tests/test_downloads.py
tests/test_legal.py
tests/test_load_legal_docs.py
tests/test_mail.py
tests/test_map_citations_murs.py

This changeset addresses an issue that was uncovered shortly after the updates to the development requirements.  I had not cleaned out my virtual environment entirely and therefore still had the existing backport `mock` library in it, which prevented me from seeing the import errors with the change to using the internal `mock` library.  The library needs to now reference `unittest.mock` instead.
h/t to @vrajmohan for catching this, thank you!  It is also still unclear why the Travis builds have not caught this issue either.

Fix tests with references to the unittest.mock module

---

requirements.txt

Part of #2585
This changeset updates Celery to the latest release, 4.1.0, to help address oddities we have been noticing with the recent update to 4.0.2.

Update Celery to 4.1.0

---

data/functions/itemized.sql
data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql
manage.py
tests/test_integration.py
webservices/tasks/refresh.py

Part of #2585
This changeset removes the nightly retry processing we had initially setup for the itemized schedule A and B data.  We have found this to be more cumbersome to get working and maintain than it is worth and it has resulted in several nightly updates failing due to deadlocked processes and record conflicts.
We will attempt to improve our processing and updating of itemized schedule A and B data through our continued refactoring that we had started previously to make the partitioning code more efficient and easier to maintain.

Remove nightly retry processing of itemized schedule A and B data

---

.travis.yml
data/functions/extensions.sql
data/functions/itemized.sql
tests/common.py

Part of #2423
This changeset modifies our GIN indexes in the itemized schedule A and B data to be multi-column, similar to the other multi-column indexes we have setup.  The intent is to provide a boost in performance when searching/filtering on text/ts_vector fields across multiple cycles.
This requires the support of the `btree_gin` PostgreSQL extension, which is installed in Amazon RDS but not enabled by default.  It can be enabled by running the following:
```sql
CREATE EXTENSION btree_gin;
```
This will also require repartitioning to rebuild the indexes.
For more information about this, see the following bits of documentation:
* [PostgreSQL 9.6 extensions supported in Amazon RDS](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.Fea …

Add support for multi-column GIN indexes

---

webservices/tasks/__init__.py

This changeset flips the [`ack_late`](http://docs.celeryproject.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.acks_late) (`task_acks_late` in the config code) setting to be `False` again due to some strange behavior we are seeing in the dev environment.  Tasks occasionally get run twice and at the moment this appears to be the only culprit.  The documentation in Celery clearly states that if a worker crashes while processing the task will be run again, but we are not seeing a crash when a task has run more than once.
While this may help the issue, we should continue investigating to see if tasks are being redelivered to the workers as that can also cause this to happen.  It seems that the [`celery flower`](http://docs.celeryproject.org/en/latest/userguide/monitoring.htm …

Tweak Celery config to flip ack_late setting

---

.travis.yml
data/functions/itemized.sql
data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql
manage.py
requirements-dev.txt
tests/test_advisory_opinions.py
tests/test_current_murs.py
tests/test_downloads.py
tests/test_integration.py
tests/test_legal.py
tests/test_load_legal_docs.py
tests/test_mail.py
tests/test_map_citations_murs.py
webservices/tasks/refresh.py

This changeset is intended to alleviate an immediate problem we are facing in prod with record inserts.  This work was already completed in the development branch with #2589 and tested in that environment and has had the desired and positive impact we were looking for.  The situation in prod is becoming worse and we cannot wait for the next release for this to be fixed, hence this hotfix.
This hotfix also addresses the broken tests and dependency adjustments we had made and tested in `develop`.  In addition to ensuring this hotfix has passing tests and can be deployed successfully to production, this will also fix the automatic deploys that we have setup to refresh the application.

Remove nightly refresh of schedule A and B in prod

---

data/functions/itemized.sql
data/sql_partition/index_schedule_a.sql
data/sql_partition/index_schedule_b.sql
data/sql_partition/partition_schedule_a.sql
data/sql_partition/partition_schedule_b.sql
manage.py

This changeset adds support to manage the indexes separately in the itemized schedule A and B partitions.  It does this by leveraging the existing code to setup the tables and creates the indexes only if they do not already exist.  After that is finished, any old indexes are then dropped so performance on the tables is not impacted.  This index management is exposed as a new management command, `index_itemized`.

Add support for separate partition index management

---

webservices/tasks/refresh.py

This changeset adds a call to `update_functions` to the nightly process to ensure that the function definitions get updated properly and are not missed.  We have run into a couple of issues in the past with these being out of sync and this is a good way to prevent that from happening again.

Add update_functions to nightly refresh

---

webservices/tasks/refresh.py

This changeset removes the refreshed_itemized method from the nightly update script.  We had removed this method when wrapping up the last itemized schedule updates but this change did not make it through to the release branch at the time the release branch was made.

Remove old function from nightly update tasks

---

webservices/resources/legal.py

Restricting the search to only the `documents.text` field is too
restrictive, and moreover, does not work without a `nested` query.

Restore default search by `_all` field

---

.circleci/config.yml
README.md
package-lock.json
package.json
runtime.txt

This changeset updates the Python runtime to be `3.5.4` and makes some small adjustments to the README file to account for the recent switch from Travis CI to CircleCI.
This also makes adjustments for running with the latest version of Node.js, `8.6.0`.

Update Python and Node.js runtimes and README

---

data/sql_setup/prepare_schedule_a.sql
data/sql_setup/prepare_schedule_b.sql
tests/test_integration.py

Ideally the functions that do the actual aggregate updates should also
be removed. As this is an emergency fix, I am only dropping the calls to
those functions, and not the functions themselves.

[Merge with git flow] Hotfix/remove aggregate update from trigger

---

tests/test_advisory_opinions.py
webservices/legal_docs/advisory_opinions.py
webservices/resources/legal.py

Added REGEX handling for statutes formatted "52 U.S.C. § 30101" and "2 USC §437f" and regulations formatted "11 C.F.R. § 100.15"
Statute: `(?P<title>\d+)\s+U\.?S\.?C\.?\s+§*\s*(?P<section>\d+).*\.?`
Regulation: `(?P<title>\d+)\s+C\.?F\.?R\.?\s+§*\s*(?P<part>\d+)\.(?P<section>\d+)`
Added tests to confirm this worked

Add handling for "C.F.R." in regulation citations and extra space in statute citations

---

.circleci/config.yml
package.json

This changeset updates the nvm and Node.js setup to use the latest versions of each. Node.js has a new LTS version that we are now leveraging, so we want to make sure CircleCI is using it as well in our builds. At the time of this PR, that is version 8.9.1 (Carbon).

Update nvm and Node.js setup in CircleCI

---

README.md

Updates to README:
- Remove references to deprecated repos: `openFEC-web-app` and `fec-style`
- Remove old storiesonboard link
- Fix link to `fec-cms` README

Remove deprecated references in README

---

README.md

Fixes #2795
This changeset adds the line to install `swagger-tools` back into the README.md file after we had inadvertently taken it out.  These tools are required in order to run one of the automated tests we have that tests to ensure the API documention is generated correctly.  I have included an extra note in the README about this requirement so folks know why it is there and what purpose it serves.

Add swagger-tools installation back to README.md

---

tests/test_advisory_opinions.py
webservices/legal_docs/__init__.py
webservices/legal_docs/advisory_opinions.py

Addresses https://github.com/18F/openFEC/issues/2762
For AO statute citations, prior citations and additional text were being added to the matches set [here](https://github.com/18F/openFEC/pull/2781/files#diff-324d3f17f824202b1e914e4bedbc79b5R271). These fields weren't being used and were creating duplicate statute citations for AO's.
AO 2012-36 [local link](http://127.0.0.1:8000/data/legal/advisory-opinions/2012-36/) now only showing the 2 citations. 
Discovered bug with 2 USC mapping with letters, got most the way done with it, then it proved to be complicated, so rolled back and split up the work into a two issues - see https://github.com/18F/openFEC/issues/2803

Remove duplicate AO statute citations

---

data/sql_updates/omnibus_dates.sql

Makes sure we only show published events. 
We will need to run update_schemas or the script for the change to take effect

only show published events

---

webservices/legal_docs/advisory_opinions.py
webservices/legal_docs/current_murs.py

Add logging to AO, MUR loading for better understanding of https://github.com/18F/openFEC/issues/2816
`./manage.py load_advisory_opinions -f '2015-11'`
`./manage.py load_current_murs -f '6000'`

Add logging to AO, MUR loading process

---

data/refresh/rebuild_schedule_e.sql
manage.py

Fixes #2813
This changeset adds support for schedule E nightly refreshes back into place.  The recent migration work accidentally removed the nightly refresh support for schedule E.
A huge h/t to @vrajmohan and @LindsayYoung for helping test and uncover this issue!

Reinstate nightly refreshes for schedule E data

---

manage.py
webservices/common/models/base.py

**PLEASE MERGE WITH GIT FLOW**
Fixes #2829
This changeset fixes an issue that we uncovered with the latest production deployment, where the nightly updates had partially failed due to materialized views not being refreshed properly.  The cause was because the `db.session` object was being used instead of the `db.engine` object, which in turn made the queries go through the custom router we have setup instead of connecting directly to the master database.

[MERGE WITH GIT FLOW] Fixed refresh materialized management method

---

requirements.txt

Part of #2773
This changeset updates the `redis-py` dependency to the latest version.  We are hoping that by doing this we will see some improvement in our Celery worker stability when it comes to dealing with dropped connections to Redis.

Updated redis-py to latest version

---

manifests/manifest_api_dev.yml
manifests/manifest_api_stage.yml
manifests/manifest_base.yml

-  We saw a performance hit in PROD today after the cache calls was deployed in RSB-2 release.
-  Need more time to test this functionality in DEV before pushing to PROD.
- Added the "CACHE_ALL_REQUESTS: True" variable only on Dev and Stage env's.

remove request caching 

---

data/migrations/V0051__alter_ofec_elections_list_mv.sql

**Merge with git flow: Hotfix**
Fixes bad join in materialized view causing some districts to repeat: https://www.fec.gov/data/elections/?cycle=2018&state=KS&district=4
Add new SQL migration file to remove the DISTINCT on cand_id for incumbents - some races have more than one incumbent where there was a special. 
Districts that probably have this issue are: CA-34, GA-06, KS-04, MT-00, SC-05 and UT-03. All these districts had members that resigned  and now have a new incumbent.

[MERGE WITH GIT FLOW] Modify ofec_elections_list_mv to handle multiple incumbents

---

webservices/legal_docs/index_management.py
webservices/utils.py

Elasticsearch was timing out on [restore_from_staging_index](https://github.com/18F/openFEC/blob/develop/webservices/legal_docs/index_management.py#L461) and [move_archived_murs](https://github.com/18F/openFEC/blob/develop/webservices/legal_docs/index_management.py#L474) on `reindex` commands, which was messing with our ability to restore from a staging index. (Needed for management command `refresh_current_legal_docs_zero_downtime`)
This PR reverts the global elasticsearch connection settings, and passes the proper parameter to the elasticsearch `reindex` command to allow the resource-heavy task to finish.
[Elasticsearch 2.4 API docs on timeout](http://elasticsearch-py.readthedocs.io/en/2.4.0/api.html#timeout)
"Global timeout can be set when constructing the client (see Connection‘s …

Fix elasticsearch reindex timeouts, revert global connection setting

---

webservices/resources/elections.py
webservices/schemas.py

In order to show coverage end date on pages like https://www.fec.gov/data/elections/house/CO/04/2018/, we need to return `coverage_end_date` on `/elections/` endpoint
**This PR unblocks:** https://github.com/18F/fec-cms/issues/1470 - Add Coverage end date to Source reports column on election pages which has a WIP PR: https://github.com/18F/fec-cms/pull/1701
Local test URL: http://127.0.0.1:5000/v1/elections/?page=1&office=house&sort=-total_receipts&state=VA&district=01&per_page=20&cycle=2018

Add coverage end date to /elections/endpoint

---

tests/test_downloads.py
tests/test_reports.py
webservices/resources/reports.py
webservices/rest.py

So that the processed/raw toggle button maintains filters, fix the committee_id filter for the `/efile/reports/` endpoint
[Example of not filtering URL](https://api.open.fec.gov/v1/efile/reports/house-senate/?api_key=DEMO_KEY&sort_hide_null=true&committee_id=C00558627&sort=-receipt_date&per_page=30&page=1)
The dynamically changing models/schemas based off committee types was proving problematic for debugging and writing tests. I split the efile/reports into 3 different views: house-senate, presidentials, and pac-party, which made for a much simpler implementation at the expense of a bit of redundancy. 
Remaining items
cc: @PaulClark2

[MERGE WITH GIT FLOW] (Hotfix) Fix the committe_id filter for /efile/reports/ endpoint

---

tests/test_itemized.py
webservices/common/models/itemized.py
webservices/resources/sched_b.py
webservices/schemas.py
webservices/sorting.py
webservices/utils.py

Addresses #2791
This changeset adds support for expression-based sorts in API queries, meaning that instead of sorting on a specific column we can choose to sort on an expression.  This is useful if an expression needs to be used to provide the desired value as opposed to what is stored in the column itself, especially if that expression is also used in the `WHERE` clause of the query.  Furthermore, this allows us to leverage expression-based indexes properly to ensure that the API queries are performant.
To create expression-based sorting options, you can follow the pattern developed for the `sort_expressions` hybrid property on the model in this PR, or followed a more [detailed set of instructions](https://github.com/18F/openFEC/wiki/Enabling-an-expression-based-sort) in the wiki.

Add support for expression-based sorts in API

---

data/migrations/V0059.1__public_audit_case_mv.sql

create V0059.1__public_audit_case_mv to modify mv to support 'allow users to get results by selecting only a primary category'.
issue: https://github.com/18F/openFEC/issues/2920

Fixed show sub_category results when select only primary_category_id.

---

data/migrations/V0060__add_remaining_schedule_b_coalesce_indexes.sql

Addresses #2923 
This changeset adds a set of `COALESCE`-based indexes in the Schedule B partition to augment the other ones we already have to cover the other permutations of queries that would have a `COALESCE` statement in them.
We are finding that the queries are still not as performant as they could be so we want to be sure these use cases are fully covered before moving on to other performance tuning opportunities.

Add remaining Schedule B COALESCE-based indexes

---

tests/factories.py
tests/test_filters.py
tests/test_itemized.py
webservices/filters.py

Add capability to search for results not matching a certain value
Update `filters.py` : `filter_match`, `filter_multi`, `filter_fulltext` to use `not_in` functionality to exclude results with a certain value when passed `parameter=-value`. I also check for when API is passed "key=A and key!=B" and handled that behavior by splitting out the arguments
___
Filters that didn't get updated with exclude capabilities:
`filter_range` exclude - possibly for the future, this hasn't been requested.
`filter_contributor_type`? `filter_election` - not needed

Add "exclude" capabilities to filters.py 

---

tests/test_elections.py
webservices/resources/elections.py

The `elections/search` endpoint should default to sort first by `sort_order` (P, S, H) and then `district` ascending.  This PR adds multi-sort capability to the endpoint and changes the default sort order to `sort_order`, `district`. In addition, I added tests for default and specified sort order for this endpoint.
Local test URL: http://localhost:5000/v1/elections/search/?per_page=100&cycle=2016&state=AZ
Expected behavior: P, S, H01, H02, etc sort order

Add multi-column sort to /elections/search/ endpoint, fix default sort order

---

webservices/common/views.py
webservices/resources/reports.py

Addresses https://github.com/18F/openFEC/issues/2953
Followup work from issue https://github.com/18F/openFEC/issues/2897
- Removes unused `filter_fulltext` function in `ApiResource` 
- Refactors `reports.py` to use "exclude" functionality added to `filter_multi` in`filters.py`

Remove unused ApiResource function, refactor /reports/ "exclude" report_type 

---

data/migrations/V0063__filings_add_request_type_idx.sql
tests/test_filters.py
webservices/args.py
webservices/docs.py
webservices/filters.py
webservices/resources/filings.py

**Update exclude logic**
- Change "exclude" filter logic in API to return null values. When searching for "not value A" it should return all values not matching A **as well as** null values for that parameter.
- Update automated tests for new logic. Separate tests into different classes to preserve scope. (`ReportsHouseSenateFactory` creates committees too)
**Add request type**
- Add `request_type` filter to /filings/ endpoint (Thanks @patphongs!)
- Add index to the `request_type` column to `public.ofec_filings_all_mv` 
https://github.com/18F/fec-cms/issues/1760

Handle nulls in "exclude" filters, add request_type to filings

---

webservices/tasks/__init__.py

This changeset attempts to fix an issue we are running into with our Redis connection retry adjustment.  At the very least it provides more logging to give insight into where the breakdown might be (or could be in the future), but a couple of the checks have been adjusted to be more explicit and might help alleviate the issue as well.  If not, we will continue to monitor and adjust, but we will need to get this running in the cloud.gov environment to see.

Attempt to fix Redis connection retries

---

webservices/docs.py

Fix misspelling in   /schedules/schedule_b/{sub_id}/ two_year_transaction_period description.
It looks like in [this PR](small definition tweak #1723) some changes were made and a word was misspelled, so this PR fixes that.

changed transation to transaction in docs.py

---

data/migrations/V0059.2__temp_ofec_candidate_flag.sql

Originally we have renamed it to have _mv at the end. But for backword
compatibility we will add the original name again until the next release.
This temporary view will be deleted during next release.

Originally we have renamed it to have _mv at the end. But for back word

---

data/migrations/V0065__add_missing_permission.sql

- Addresses # 2927
Currently, we have the following schema in database fec
'public','fecmur','aouser','auditsearch','disclosure','fecapp','staging','rad_pri_user','real_efile','real_pfile'
The current migration file add/correct the mission permission and the following rules should be followed in granting permission in the future.
1. fec role should be the owner of all tables, views, and MVs in these schemas and has full privilege of these objects.
2. fec_read role should have SELECT and only SELECT privilege of all these fec owned tables, views, and MVs
3. aomur_usr has SELECT, INSERT, UPDATE, DELETE to all tables and SELECT to views and MVs in schemas fecmur and aouser
4. real_file has SELECT, INSERT, UPDATE, DELETE to all tables and SELECT to views and MVs in schemas real_efile and …

add missing permission

---

webservices/resources/legal.py

For our API design, we can follow the “gracious" way to handle request parameters.
Scenario1) if miss mandatory parameter:
a) if have default. set to default.
b) if don’t have default, abort right away, don’t need execute query
Scenario2) if miss need parameter:
set to default or None
Scenario3)For extra parameters or bad value parameters:
ignore those parameters quietly
this ticket only fix /legal/search/ endpoint with nonsense parameters: type.
we will set default type=all
- Addresses # [_Issue number_]
[https://github.com/18F/openFEC/issues/2934](https://github.com/18F/openFEC/issues/2934)
in legal.py:
if doc_types is not in one of these 4 doc types :'statutes', 'regulations', 'advisory_opinions', 'murs'
then reset type = all (= four default …

Fix Legal search endpoint 500 error for unexpected parameters

---

webservices/rest.py

Check if the request.url has /v1/ then cache the endpoints.
- Addresses # [_Issue number_]
https://github.com/fecgov/openFEC/issues/2913
This link should be UP and running when you start the server on openfec repo.
- http://localhost:5000/developers/
Swagger API
-  
branch | PR

Fixed the broken api link.

---

webservices/rest.py

Fixes fecgov/openFEC#2962
Thanks to @lbeaufort for discovering flask-restful/flask-restful#578.
It was difficult to investigate this in local environments as they run
in debug mode where all exceptions are propagated. 
- Addresses #2962 
- Turn off debug mode by running
```
python manage.py runserver --no-debug
```
- Access the API endpoint with an invalid query, e.g., `curl -v http://localhost:5000/v1/elections/`
You should get a clean 422 response with a proper JSON message:
```
{
"message": "Required parameter \"office\" not found.",
"status": 422
}
```
-  This would primarily benefit public API users by providing better error responses

Prevent flask-restful from taking over all errors

---

webservices/resources/legal.py

This PR is partially related with PR#3018: [https://github.com/fecgov/openFEC/pull/3018](https://github.com/fecgov/openFEC/pull/3018)
and related this issue: [https://github.com/fecgov/openFEC/issues/2934](https://github.com/fecgov/openFEC/issues/2934)
and this issue: [https://github.com/fecgov/openFEC/issues/2962](https://github.com/fecgov/openFEC/issues/2962)
There are two problems need to be fixed in this PR:
##Problem 1) how to handle exception?
on dev server: return 500 (Internal Server Error)
[https://fec-dev-api.app.cloud.gov/v1/legal/search/?type=regulations&q=+public+%26%26+type+%25SystemRoot%25%5C%5Cwin.ini+%26%26+&hits_returned=20&from_hit=0&api_key=DEMO_KEY](https://fec-dev-api.app.cloud.gov/v1/legal/search/?type=regulations&q=+public+%26%26+type+%25SystemRoot%25%5C%5Cwin.ini+% …

exception handling for legal search endpoint, debug single test_legal.py

---

data/refresh/rebuild_schedule_e.sql

- Addresses # 2927
Some database objects have incorrect permissions, PR #3001 had a migration file had already address these permission issues.  However, after the PR had been merged in DEV database and all permission are good, we noticed the permission to ofec_sched_e had been flipped back to the incorrect permission repeatedly while all the other fixed permission stays correct.  After research, I discovered that the cronjob to refresh this table everyday is actually recreate this table. And the script that recreate this table does not specify the owner; and the cronjob is run by fec_api, so every night this table recreated, the ownership flip back to fec_api.   Therefore, in addition to the migration file, data/refresh/rebuild_schedule_e.sql need …

fix ofec_sched_e reoccurring permission problem

---

webservices/env.py
webservices/tasks/utils.py

`smart_open` uses `boto` and not `boto3`. The explicit connection
parameters seem to not work anymore and the current code requires that `~/.aws` is configured correctly. A workaround is to have them as
environment variables, which appears to work for both `boto` and `boto3`
connections.
This can be tested by renaming `~/.aws` or not configuring it correctly.

Use envvars instead of explicit connection params

---

.circleci/config.yml
README.md
runtime.txt

Upgrade the API to Python 3.6, update circle ci to use python 3.6, and cloud.gov deployment to use Python 3.6

Upgrade Python to 3.6

---

data/migrations/V0071__update_ofec_totals_candidate_committees_mv.sql

- Addresses https://github.com/fecgov/openFEC/issues/3041
_Changes materialized view `ofec_totals_candidate_committees_mv` to display the proper contribution refunds total._
[Original calculation:](https://github.com/fecgov/openFEC/blob/develop/data/migrations/V0026__more_public_schema_objects.sql#L5307) `sum((p.pol_pty_cmte_contb + p.oth_cmte_ref)) AS contribution_refunds`
[New calculation: ](https://github.com/fecgov/openFEC/pull/3042/files#diff-f16707a1e2de3aafc7a39eee794c2e97R149) ` sum(p.ttl_contb_ref) AS contribution_refunds`
- Test the migration on your local db using Flyway (`flyway migrate`)
- Check out this branch and change the model (`webservices/common/models/totals.py`) to point to `ofec_totals_candidate_committees_mv_tmp` on line 136 and 162 (I created this temp view on the …

Fix contribution_refunds total

---

tests/test_advisory_opinions.py
tests/test_map_citations_murs.py
webservices/legal_docs/advisory_opinions.py
webservices/legal_docs/current_murs.py
webservices/legal_docs/index_management.py
webservices/legal_docs/load_legal_docs.py
webservices/legal_docs/reclassify_statutory_citation.py

- Addresses https://github.com/fecgov/openFEC/issues/2803
_Fix bug where REGEX isn't accounting for characters (IE "2 USC 441b" is being parsed as "2 USC 441") which is causing lookup mistakes. 1980-01 is an example. Add tests for handling these characters properly_
~2 U.S.C. §437f == 52 U.S.C. §30105~
~2 U.S.C. §441b == 2 U.S.C. §441~
2 U.S.C. §437f == 52 U.S.C. §30108
2 U.S.C. §441b == 52 U.S.C. §30118
2 U.S.C. §441a-1 == 52 U.S.C. §30117
- Get Elasticsearch up and running
- get the latest S3 credentials from `dev`
- run `./manage.py initialize_current_legal_docs` which recreates the docs index and loads current AO's. Quit the process when it gets to MURs - not needed.
- Check http://localhost:5000/v1/legal/search/?type=advisory_opinions&ao_no=1980-01&ao_category=F and the statutory …

Fix AO statute mapping where section contains a letter

---

webservices/docs.py

Fix missing space before [APIinfo@fec.gov] in swagger docs

Fix missing space before [APIinfo@fec.gov]

---

data/migrations/V0073__update_ofec_committee_fulltext_and_candidate_fulltext_mvs.sql
tests/test_api.py
webservices/common/models/candidates.py
webservices/common/models/committees.py
webservices/resources/search.py

- Addresses #3057 
_Change the sort order for typeahead results. Previously, these results were being sorted by receipts, but that was making it very hard to find C7, C9 etc committees that tend to show more IE's. Update the `/names/committee` and `names/candidate` sort order to sort on receipts+disburs+IE's for committees and receipts+diburs for candidates. I used `EXPLAIN` and `EXPLAIN ANALYZE` to make sure there was no performance hit - oddly, these changes seemed to improve performance slightly._
- test the migration: `flyway migrate`
- Check out this branch and point to temporary MV's on `dev`:
- Change the `CandidateSearch` model to point to `'ofec_candidate_fulltext_mv_tmp'`
- Change the `CommitteeSearch` model to point to `'ofec_committee_fulltext_mv_tmp'`
- Run `develop` branch …

Change typeahead search on home page to sort by total activity

---

README.md

Add vulnerability tracker badge to show Snyk: https://snyk.io/docs/badges
We'll remove Gemnasium once we're no longer using both

Add Snyk vulnerability tracker badge

---

data/migrations/V0076__add_ofec_candidate_totals_with_0s_mv.sql
manage.py
tests/test_aggregates.py
webservices/common/models/candidates.py
webservices/resources/candidate_aggregates.py

- Addresses #3023
_Refactor /candidates/totals to show candidates with $0 activity and simplify endpoint query logic_
- Use new MV/Model: change model `CandidateTotal(db.Model)` to use `ofec_candidate_totals_with_0s_mv`
- Move some filters into `filter_match` utility
- Simplify the SQLAlchemy join
- Add test  for candidates without filings and $0 activity
- Test the migration - `flyway migrate`
- Set `SQLA_CONN=postgresql://:@/cfdm_test` and test refreshing the MV's. You'll need to manually change this because we don't have data for all MV's - `refresh_materialized(concurrent=False)` - `./manage.py refresh_materialized`
- Set `SQLA_CONN` to the `dev` database and use the temporary view on `dev` - change model `CandidateTotal(db.Model)` to use `ofec_candidate_totals_with_0s_mv_tmp`
- Look …

[Migration 76] Refactor /candidates/totals to show candidates with $0 activity

---

webservices/rest.py

_Addresses issues found in testing_
- Add specific exception message
- refactor `is_url_path_cacheable` function to use `def` instead of `lambda` for readability
- make formatting PEP8 compliant, remove duplicate import
- test the error handling by setting `SQLA_CONN=""` and test http://localhost:5000/v1/rad-analyst/?per_page=20&page=1&title=senior
- test the cached calls by adding print statements and testing different URLs
- Cached calls 
- Local API development

Add specific exception message, refactor `is_url_path_cacheable` function

---

data/migrations/V0078__add_trc_election_result.sql

Due to Golden Gate transfer issues, change the `trc_election_id` and `trc_election_result_id` columns to `bigint`. From @fecjjeng "I usually put bigint when original Oracle table does not specify the precision of the number field". @fecjjeng will trigger the migration manually
Branch | PR
feature/refactor-elections-endpoint | [link](https://github.com/fecgov/openFEC/pull/3091)

Change the trc_election_id and trc_election_result_id columns to bigint

---

manifests/manifest_task_dev.yml.template
manifests/manifest_task_prod.yml.template
manifests/manifest_task_stage.yml.template

Addresses an issue found in testing - add redis to manifest task files
Test with a headless app: https://cloud.gov/docs/getting-started/one-off-tasks/#deploy-an-app-that-performs-a-task

Add redis to manifest task files

---

manifests/manifest_api_dev.yml
manifests/manifest_api_prod.yml
manifests/manifest_api_stage.yml
manifests/manifest_celery_beat_dev.yml
manifests/manifest_celery_beat_prod.yml
manifests/manifest_celery_beat_stage.yml
manifests/manifest_celery_worker_dev.yml
manifests/manifest_celery_worker_prod.yml
manifests/manifest_celery_worker_stage.yml
manifests/manifest_task_dev.yml.template
manifests/manifest_task_prod.yml.template
manifests/manifest_task_stage.yml.template
requirements.txt
webservices/utils.py

Elastic Search Service was upgraded from 24 to 56 in this PR https://github.com/fecgov/openFEC/pull/3084
While testing this new ES56 service on **dev**, we encountered Gateway and ReadTime outs.
We are still following up with cloud.gov team to resolve the timeout issues.
Until then we are rolling back the ES56 services and will be using the existing ES24 service on cloud.

Revert ES56 Services 

---

webservices/resources/elections.py
webservices/schemas.py

Addresses https://github.com/fecgov/fec-cms/issues/1910
This modifies the /elections/ endpoint to show `candidate_pcc` where a candidate has a linked committee has designation 'P' (Primary Campaign Committee.) Where two committees are marked 'P' in an election cycle (this really shouldn't happen) it takes the highest (aka most recent) committee ID. 
The plan is to refactor the /elections/ endpoint this sprint, but this *unblocks* the election profile redesign (cc: @patphongs @JonellaCulmer) 
**Note**: not all candidates have committees yet. Where there is no linked committee, the elections endpoint returns `null`.
This works across time where the data is there. Example, Graham:
http://127.0.0.1:5000/v1/elections/?office=senate&cycle=2014&state=sc&per_page=100
PCC is C00458828 in 2014 …

Add candidate_pcc to /elections/ endpoint

---

data/migrations/V0080__audit_committee_fulltext.sql
webservices/args.py
webservices/resources/audit.py

Partial name and keyword committee/candidate searches in audit search should return comprehensive results
- Addresses # [_fec-cms#1965 and #1966_]
[https://github.com/fecgov/fec-cms/issues/1965](https://github.com/fecgov/fec-cms/issues/1965)
[https://github.com/fecgov/fec-cms/issues/1966](https://github.com/fecgov/fec-cms/issues/1966)
This needs both openFEC and fec-cms repos changes
add 'q'--committee name/id search
'qq'--candidate name/id search
`    filter_fulltext_fields = [
('q', models.AuditCommitteeSearch.fulltxt),
('qq', models.AuditCandidateSearch.fulltxt),
]
`
test api locally
1)setup branch feature/fix_cand_cmte_name on local
2)test filters on auditcase endpoint:
a)candidate_id= P20002671 (should return 1 record)
b)committee_id= …

Fixed audit committee and candidate name sub-string search.

---

README.md
manifests/manifest_api_dev.yml
manifests/manifest_api_prod.yml
manifests/manifest_api_stage.yml
manifests/manifest_celery_beat_dev.yml
manifests/manifest_celery_beat_prod.yml
manifests/manifest_celery_beat_stage.yml
manifests/manifest_celery_worker_dev.yml
manifests/manifest_celery_worker_prod.yml
manifests/manifest_celery_worker_stage.yml
manifests/manifest_task_dev.yml.template
manifests/manifest_task_prod.yml.template
manifests/manifest_task_stage.yml.template
requirements.txt
webservices/utils.py

- Addresses #2921 
_Upgrade Elasticsearch to v. 5.6. (Adding [asynchronous reindexing](https://github.com/fecgov/openFEC/issues/3118#issuecomment-389915229) later due to some wonkiness with the implementation.)_
- Install Elasticsearch 5.6 locally
- Update your requirements: `pip install -r requirements.txt`
- Try loading and reloading docs with the management commands
-  legal resources (AOs/MURs)
- Original upgrade: #3084 
- PR to back that out due to some cloud.gov issues: #3106

Upgrade Elasticsearch to v. 5.6

---

requirements.txt

According to
https://stackoverflow.com/questions/50444988/celery-attributeerror-async-error,
Celery does not pin its requirements for kombu and billiard to specific
versions. kombu 4.2.0 was released with a breaking change and previous
versions of celery automatically install it.

Upgrade Celery to fix kombu issues

---

tests/test_downloads.py

##Summary:
when run py.test on local based on develop branch, got the function **test_download_forbidden** in test_downloads.py failed
- Resolves
endpoint: **elections** has two required  parameters : cycle and office.
should add these two parameters in url.
checkout branch:feature/fix_test_download_miss_parameter locally, and run **py.test**, make sure pass all tests

Fix test_download function test_download_forbidden

---

webservices/tasks/__init__.py

- Addresses #3174 
As a corrective action to the outage on 5/29/18 (post-mortem [here](https://docs.google.com/document/d/1GLFkkWetHiCOz2LCiAHpQm0SA8AHrZ028wZjbzHTC7g/edit#heading=h.dmpjekprmy7z)) this PR changes how we connect to Redis.
We relied on [cfenv](https://github.com/fecgov/openFEC/blob/develop/webservices/tasks/__init__.py#L61) to grab our username, password, and port. `cfenv` [used FURL](https://github.com/jmcarp/py-cfenv/blob/master/cfenv/__init__.py#L85-L86) to assemble the URL, which had a backwards incompatible change. Instead, we can just use the URI parameter to connect to redis:
`url = redis.credentials.get('uri')`
Here, `redis` is a `Service` object. Here are the available properties and methods for a `Service` object in `cfenv`: …

Connect to Redis using URI parameter

---

data/migrations/V0083__fix_ofec_sched_a_aggregate_state_recipient_totals_mv.sql

- Resolves #3142 
`ofec_sched_a_aggregate_state_recipient_totals_mv` is joining on "state = fips code", resulting in the /schedule_a/by_state/totals/ endpoint returning incorrect results: https://api.open.fec.gov/v1/schedules/schedule_a/by_state/totals/?sort=cycle&per_page=20&api_key=DEMO_KEY&page=1
```
WHERE (agg_st.state::text IN (SELECT fips_state_code
FROM staging.ref_zip_to_district))
``` 
should be (typo is in the table)
```
WHERE (agg_st.state::text IN (SELECT **state_abbrevation**
FROM staging.ref_zip_to_district))
``` 
- test the view by dropping/creating `cfdm_test` and running `invoke create_sample_db` I also ran the script on the `dev` DB and it worked.
- …

Fix join on state for ofec_sched_a_aggregate_state_recipient_totals_mv

---

webservices/common/models/reports.py
webservices/resources/reports.py

- Resolves [#3103](https://github.com/fecgov/openFEC/issues/3103)
ofec_report_pac_party_all_mv was created to include F3 forms that were filed by pac/party. This was implemented in PR [#3164](https://github.com/fecgov/openFEC/pull/3164)
logic for **year** was added to function that checks for committee_type
- setup openFEC locally and pull branch: **feature/fix-missing-reports**
- test endpoint:  /reports/{committee_type}/. 
> committee_id = C00156554;
> year = 2017;
> committee_type = pac-party
The endpoint will return 2 : FEC-1206344 (form 3) and  FEC-1175151 ( form 3x) 
current production api only returns 1:  FEC-1175151 ( form 3x) .  
https://api.open.fec.gov/v1/reports/pac-party/?sort=-coverage_end_date&page=1&per_page=20&year=2017&api_key=DEMO_KEY&committee_id=C00156554
- test …

Fix missing reports from API's /reports/ endpoint

---

data/migrations/V0084__add_table_entity_chart.sql

- Resolves # 3204
Add new table disclosure.Entity_Chart to cloud databases
After migration is done, a new table disclosure.entity_chart should be created in disclosure schema.
Currently no API is pointing to this new table 
branch | PR

add table entity_chart

---

requirements.txt

Fixes #3087.
The minimum version required to fix the issue is 1.5.31. Upgrading to
1.7.21, which is the latest release at this time.
- Downloads
- Caching of requests in S3

Upgrade boto3 to 1.7.21

---

data/migrations/V0085__fix_ofec_candidate_totals_mv.sql
manage.py
tests/factories.py
tests/test_aggregates.py
tests/test_committees.py
webservices/common/models/candidates.py
webservices/flow.py
webservices/resources/candidate_aggregates.py

- Resolves #3196 and Resolves #3200. The /candidates/totals endpoint was doubling totals for odd-year special election candidates, and missing at least one odd-year special election candidate
Change to `ofec_candidate_totals_mv`:
Add a `SELECT DISTINCT`:
```
), link AS ( --Off-year special election candidates have > 1 row/cycle
SELECT DISTINCT cand_id,
cand_election_yr + cand_election_yr % 2 as rounded_election_yr,
fec_election_yr,
cmte_id,
cmte_dsgn
FROM ofec_cand_cmte_linkage_mv
WHERE cmte_dsgn IN ('P', 'A')
```
| cand_id   | cand_election_yr   | fec_election_yr   | cmte_id   | cmte_tp   | cmte_dsgn   
|-------|--------------|-----------|--------------------|-------------------|-----------|
| S0AL00156 | 2018               | 2018              | C00640623 | S         | P           | P  | …

Fix totals for off-year special candidates on /candidates/totals endpoint

---

.circleci/config.yml
README.md
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml

- Resolves #3222 
_Update Flyway to v. 5.1.3._
- Test with a temporary deploy ([done](https://circleci.com/gh/fecgov/openFEC/408))
- Test with headless app (see instructions in [README](https://github.com/fecgov/openFEC/blob/develop/data/flyway/README.md)) (done)
- Locally: install new Flyway version (instructions [here](https://docs.google.com/document/d/1pMi59CQOj0dO9WyRS-tCGxHqd9CRTOU_4GaBD4VNbGk/edit)), drop/create `cfdm_test` and run `flyway migrate`
- Database Migrations upon merge 
- Database migrations using a headless app

Update Flyway to v. 5.1.3

---

webservices/args.py

Add committee_designation filter into /audit-case/ endpoint.
to enable JFC search
- Resolves # Issue: [https://github.com/fecgov/fec-cms/issues/2093](https://github.com/fecgov/fec-cms/issues/2093)
will return 1023 rows

Add committee_designation filter into audit-case endpoint

---

tests/test_elections.py
webservices/resources/elections.py

remove joint fundraiser inflated figures from totals
- Resolves  The first Item of Issue [3221] 
[https://github.com/fecgov/openFEC/issues/3221](https://github.com/fecgov/openFEC/issues/3221)
1)checkout openFEC feature branch:  feature/joint_fundraisers_inflating_mone
2)run py.test and run server,
3)compare Total receipts, Total disbursements, Cash on hand 
from prod and local. will see difference as screenshot below.
[http://127.0.0.1:8000/data/elections/senate/VA/2018/](http://127.0.0.1:8000/data/elections/senate/VA/2018/)
[https://www.fec.gov/data/elections/senate/VA/2018/](https://www.fec.gov/data/elections/senate/VA/2018/)
on production:
on local:

Remove the joint fundraisers inflating money from totals

---

data/migrations/V0092__drop_ofec_election_result_mv.sql
manage.py
tests/factories.py
tests/test_elections.py
tests/test_utils.py
webservices/common/models/elections.py
webservices/resources/elections.py
webservices/schemas.py

- Resolves #3076 
_Remove 'won' from /elections/ until we find a better data source for won/lost results._
- Run this branch locally and test an elections query and make sure `won` is showing up http://localhost:5000/v1/elections/?api_key=DEMO_KEY&cycle=2018&office=house&state=CO&stateFull=Colorado&district=07&per_page=0&sort_hide_null=true
-  https://api.open.fec.gov/v1/elections - The `won` field doesn't show up on the front end - this is an API-only change

Remove 'won' from /elections/

---

tests/test_advisory_opinions.py
webservices/legal_docs/advisory_opinions.py

Testing:
- Resolves #2276 
Allow more complex parsing of AO citations: capture multiple statutes and regulations. Examples: 52 USC 30101 and 30106, 11 CFR 101, 102, 103, and 104.
**Statutes (ex. 52 USC 30101, 30133):**
Keep the first pass looking for citations REGEX and logic the same. When looking for multiples, grab all the text until a . or a ; Then loop through that group of text with the original citation REGEX to find matches.
**Regulations (ex. 11 CFR 110.1 and 112.4):**
Keep the first pass looking for citations REGEX and logic the same. When looking for multiples, grab the next 70 characters. Then loop through that group of text with the original citation REGEX to find matches.
Because the "multiples" logic is more forgiving, add functions that confirms the matches are within the …

Allow more complex parsing of AO citations

---

data/migrations/V0096__drop_ofec_sched_a_objects.sql

- Resolves #3099 
ofec_sched_a_master and its children tables are dropped. The queue table, database procedures/triggers and the scheduled tasksused to handle their updates are dropped too. SQL statements in the Sample_db.sql that populated these tables are removed too.
After Flyway migration completed, the ofec_sched_a related objects listed in the migration file V0096 should not exist in the local database anymore.
After successfully switching to use the fec_fitem_sched_a tables, these ofec_sched_a table are not in use anymore and will not have impact on API.
branch | PR

update migration file for permission problem

---

tests/test_downloads.py
tests/test_elections.py
tests/test_utils.py
webservices/resources/elections.py
webservices/schemas.py

1)In order to enable 'export' button on these two sections in election summery page, we need refactor elections endpoint to extend ApiResouce and handle download function.
These two sections use same endpoint: `resource.ElectionView`
a)Candidate financial totals section:
[https://www.fec.gov/data/elections/senate/VA/2018/?tab=election-data](https://www.fec.gov/data/elections/senate/VA/2018/?tab=election-data)
b)Candidate information section:
[https://www.fec.gov/data/elections/senate/VA/2018/?tab=about-election](https://www.fec.gov/data/elections/senate/VA/2018/?tab=about-election)
- Resolves Issue# [https://github.com/fecgov/openFEC/issues/3254](https://github.com/fecgov/openFEC/issues/3254)
fec-cms need to be changed to enable the button and make event trigger work.
1)setup openFEC …

[WIP]Refactor elections endpoint to handle candidate finance totals export function

---

webservices/resources/elections.py

Summary:
when fec-cms pass per_page=0 (means: get all results, don't do pagination),  
the elections endpoint not handle this case, 
so set cap=0 to avoid doing pagination.
related PR: [https://github.com/fecgov/openFEC/pull/3292](https://github.com/fecgov/openFEC/pull/3292)
How to test locally:
1) checkout branch : feature/fix_elections_per_page
2)DB--dev
3)loach cms point to local api
4)test elections summary pages to make sure all data sets result correctly.

Fix elections endpoint to handle per_page=0

---

tests/test_itemized.py
webservices/docs.py
webservices/resources/sched_a.py

- Resolves [#3054](https://github.com/fecgov/openFEC/issues/3054)
1) Enable zipcode search for zipcodes greater than 5 digits.
2) Enable search for foreign zipcode that has letters, space, and -,  and to exclude certain special character.  
3) The results still match on the first 5 characters.
4) refactor test case accordingly.
1) run this branch locally, using DEV database
2) test this endpoint locally :  /schedules/schedule_a/
two_year_transaction_period=2016
contributor_zip: using the value in **zip code** column
zip code | counts before change | counts after change |  
---- | -- | -- | --
10050 | 26 | 26 |  
100502814 | error code = 400 | 26 |  
10050-2814|error_code = 400 | 26
L2A2W4 | error code = 400 | 3 |  L2A2W4 ( 3 )
L5K 2B3 | error code = 400 | 3 | L5K 2G1;   L5K 2G1;    L5K …

[WIP]Enable zipcode search for foreign zipcodes, and remove input of 5-digits restricition

---

webservices/utils.py

- Resolves #3270 
Now that cloud.gov has implemented an elasticsearch configuration fix on their end, I've tested and confirmed that we have [vastly improved performance](https://docs.google.com/spreadsheets/d/176GslTcBtvxMUBM6PK3XaH1ZRdDJ3RQOwtOTOzICji8/edit#gid=0) with our default settings. We should revert our elasticsearch connection settings to the defaults (`timeout=10, retry_on_timeout=False, max_retries=3`)  so that MUR 253 will load: https://fec-dev-api.app.cloud.gov/v1/legal/search/?mur_no=253
- I tested with a manual deploy to `dev` and ran locust tests `get_mur` and `get_ao`. This wasn't an issue locally - only on cloud.gov. 
- This bug archived MUR only loads with the default connection settings: https://fec-dev-api.app.cloud.gov/v1/legal/search/?mur_no=253. You can see the …

[MERGE WITH GIT FLOW] Hotfix: Revert elasticsearch connection settings to the defaults

---

README.md
manage.py
tests/test_load_legal_docs.py
webservices/legal_docs/__init__.py
webservices/legal_docs/load_legal_docs.py

- Resolves #3234 
_Update instructions on loading archived MURs._
- See if you understand how to load archived MURs
-  Index management/legal docs
Modify `load_archived_murs` to properly handle MURs with multiple PDFs https://github.com/fecgov/openFEC/pull/3278

Update instructions on loading archived MURs

---

data/migrations/V0099__modify_candidate_committee_totals.sql
tests/factories.py
tests/test_totals.py
webservices/common/models/operations_log.py
webservices/common/models/totals.py
webservices/resources/totals.py
webservices/schemas.py

- Resolves #3217 
_Add transaction_coverage_date to candidate and committee totals._
- **Candidates**: I changed the candidate totals on the **MV/SQL** side because it's a `1-many` relationship between candidates and committees (`ofec_totals_candidate_committees_mv`) and we’re already aggregating all the committees together in the MV.
(Look for `transaction_coverage_date` in the migration - it's the only thing I changed.)
- **Committees**: On the committee side, I modified on the **SQLAlchemy/Python** side because it's a `1-1` relationship and there are 5 possible models:
```
'H': models.CommitteeTotalsHouseSenate = ofec_totals_house_senate_mv
'S': models.CommitteeTotalsHouseSenate = ofec_totals_house_senate_mv
'I': models.CommitteeTotalsIEOnly = ofec_totals_ie_only_mv
'O': …
```

Add transaction_coverage_date to candidate and committee totals

---

data/migrations/V0098__add_ofec_sched_a_agg_state_vw.sql
data/migrations/V0100__add_ofec_sched_a_agg_state_vw.sql
tests/test_aggregates.py
webservices/common/models/aggregates.py
webservices/resources/aggregates.py

Example link:
[https://www.fec.gov/data/committee/C00370007/?tab=raising](https://www.fec.gov/data/committee/C00370007/?tab=raising)
on Individual contributions section in committee profile page, click Group by State, we will group by all non-US state values into one new row called: `Other`
- Resolves # [https://github.com/fecgov/openFEC/issues/3246](https://github.com/fecgov/openFEC/issues/3246)
related fec-cms Issue: [https://github.com/fecgov/fec-cms/issues/2237](https://github.com/fecgov/fec-cms/issues/2237)
tag: receipts
Path:/committee/{committee_id}/schedules/schedule_a/by_state/
endpoint: resources---aggregates.ScheduleAByStateView
model. aggregates.py—ScheduleAByState
new view: public.ofec_sched_a_agg_state_vw
table: …

Show non-US states(Other) in Committee Schedule A by state aggregates

---

README.md
tasks.py

- Resolves #3324 
Add ability to deploy without running migrations. `Invoke` task can only take a `True` flag or a value flag (per the [docs](http://docs.pyinvoke.org/en/0.11.1/api/tasks.html#invoke.tasks.task)):
>"arguments may be given as value-taking options (e.g. `--my-arg=myvalue`, wherein the task is given `"myvalue"`) or as Boolean flags (`--my-arg`, resulting in `True`)."
so I made the flag `skip-migrations`, defaulted to `False`
This is a follow-up item from our post-mortem [here](https://docs.google.com/document/d/1t_up-38Kvofg8ILzVJq_RYgFXUxSF-xsxgSocjXT8vs/edit)
- With migrations: `invoke deploy --space dev`
- Without migrations `invoke deploy --space dev --skip-migrations`
-  Circle deploys and manual …

Add ability to deploy without running migrations

---

webservices/rest.py

- Resolves #3237 
_Add endpoint-specific caching: Default is 1 hour, legal and calendar are 5 minutes, efiling is none._
Run this branch locally and look at the response headers using `CURL`:
- default: `curl -I http://localhost:5000/` 1 hour = 3600s
- legal: `curl -I "http://localhost:5000/v1/legal/search/?description=excessive&ao_is_pending=True&type=advisory_opinions&api_key=DEMO_KEY"` 5 min = 300s
- calendar: `curl -I http://localhost:5000/v1/calendar-dates/` 5 min = 300s
- efile: `curl -I http://localhost:5000/v1/schedules/schedule_a/efile/?api_key=DEMO_KEY` = 0
-  API caching
Remove S3 caching #3235

Add endpoint-specific caching

---

tasks.py

- Resolves an issue that came up in testing `invoke deploy --space [SPACE: dev/stage/prod]`
Check for FEC_MIGRATOR_SQLA_CONN_[SPACE] before trying to run migrations
>Traceback (most recent call last):
File "/Users/lbeaufort/.pyenv/versions/api-env/bin/invoke", line 11, in <module>
sys.exit(program.run())
File "/Users/lbeaufort/.pyenv/versions/3.6.5/envs/api-env/lib/python3.6/site-packages/invoke/program.py", line 293, in run
self.execute()
File "/Users/lbeaufort/.pyenv/versions/3.6.5/envs/api-env/lib/python3.6/site-packages/invoke/program.py", line 408, in execute
executor.execute(*self.tasks)
File "/Users/lbeaufort/.pyenv/versions/3.6.5/envs/api-env/lib/python3.6/site-packages/invoke/executor.py", line 114, in execute
result = call.task(*args, **call.kwargs)
File …

Add better error message for missing migrator environmental variable

---

webservices/docs.py

- Resolves #3296
_There were 2 dead links to sql functions in the API documentation. Fixed link for individual contributions sql function and purpose by disbursement sql function._
- Look at webservices/docs.py to make sure dead links from individual contributions sql function and purpose by disbursement sql now go to correct URL.

Fixed dead SQL links in API docs

---

data/migrations/V0101__add_column_orig_amndt_dt_to_form_9.sql

- Resolved issue #3330 Add column orig_amndt_dt to form_9 tables
Format Update V8.3 add column orig_amndt_dt to form_9 tables:
disclosure.nml_form_9
real_efile.f9
real_pfile.f9
After running the migration file to your local database, the new column orig_amndt_dt should exist in the 3 following tables:
disclosure.nml_form_9
real_efile.f9
real_pfile.f9
-
The new column is currently not needed for any of the view/materialized views that relying on form_9.  So there is no impact to the application.
-  
branch | PR

add column orig_amndt_dt to form_9

---

webservices/tasks/download.py

This call is no longer needed as we no longer store anything under the
name cached-calls.

Remove stale code

---

data/migrations/V0102__drop_ofec_rad_mv.sql
manage.py
tests/test_committees.py
tests/test_filing_resources.py
webservices/args.py
webservices/common/models/rad_analyst.py
webservices/flow.py
webservices/resources/aggregates.py
webservices/resources/committees.py
webservices/resources/dates.py
webservices/resources/filings.py
webservices/resources/rad_analyst.py
webservices/resources/reports.py

Resolves #3333 "Making "updated" fields available & searchable in API endpoints"
**`/committees/`:**
- make `last_filed_f1` filterable
**`/rad-analyst/`:**
- add `assignment_update` to output, make it filterable
- replace `ofec_rad_mv` with `ofec_rad_analyst_vw`
**technical debt**
- Modify `args.IndexValidator` to look up the model's schema
- Test migrations by `drop/create cfdm_test` and `invoke create_sample_db`
- point `SQLA_CONN` to `cfdm_test` (or just `unset SQLA_CONN`)
- http://localhost:5000/v1/committees/?sort=name&max_last_f1_date=7%2F31%2F18&min_last_f1_date=7%2F25%2F18&per_page=20&page=1
- http://localhost:5000/v1/rad-analyst/?per_page=20&page=1&max_assignment_update_date=2018-09-10
- Test endpoints with modified `IndexValidator`: …

Add filters to help ServiceNow query more efficiently

---

.circleci/config.yml
README.md
requirements-dev.txt

This makes it consistent with `fec-cms`.
Also, change the invocation command to `pytest` instead of `py.test`
as per https://github.com/pytest-dev/pytest/issues/1629 and to be
consistent with `fec-cms`.

Bump pytest to 3.7.4

---

data/migrations/V0103__fix_ofec_rad_analyst_vw.sql

Resolves issue found in testing. Rename `ofec_rad_analyst_vw.assignment_update` to `assignment_update_date`
I ran this on `dev` with a manual deploy so our migrations will stay in order.
Test with http://localhost:5000/v1/rad-analyst/?per_page=20 or https://fec-dev-api.app.cloud.gov/v1/rad-analyst/

Rename 'ofec_rad_analyst_vw.assignment_update' to 'assignment_update_date'

---

requirements.txt

This reverts fecgov/openFEC#3372, because the version targeted in that PR  (0.12.3 )failed certain tests. 
It was agreed to go to Flask==0.12.4, a stable version for our tests. Meaning it pasts all our tests. This  PR includes that change

Flask upgrade from 0.12 to 0.12.4

---

webservices/legal_docs/current_cases.py
webservices/tasks/__init__.py
webservices/tasks/legal_docs.py

Follow-up issue for #3359 
- Add test data for sample db for ADR/AF
- Modify `reload_mur` celery task to reload all modified cases (MUR/ADR/AF)
- Add better error handling for when no AF-specific fields are found (may only apply to test data but we should account for the possibility)
- Recreate sample db (drop/create/ `invoke create_sample_db`)
- unset  SQLA_CONN to point to local
- run redis/celery beat/celery worker (https://github.com/fecgov/openFEC/wiki/Set-up-Redis,--Celery-on-local-and-test-the-downloads)
- run elasticsearch locally, make sure you have the required parameters
- fake a modified ADR/AF on local cfdm_test db: `update fecmur."case" set name=concat(name,' test'), pg_date=now()`
- see if it reloads properly

Add ADR and AF to celery reload task

---

requirements.txt
tests/test_swagger.py
webservices/spec.py

Resolves #3356 and Resolves #3280 
`apispec` accepted my PR to [fix the `PyYAML` vulnerability](https://github.com/marshmallow-code/apispec/issues/278) but we haven't heard back on another change that's [preventing us from being able to run the latest `validate_spec`](https://github.com/marshmallow-code/apispec/issues/282) so I [made the change on our end](https://github.com/fecgov/apispec/pull/1). 
This PR uses our forked version until we can (hopefully) get `apispec` to make a change.

Update apispec package to use fecgov's forked repo

---

data/migrations/V0108__drop_ofec_entity_chart.sql
manage.py
webservices/flow.py

- Resolves # [3399](https://github.com/fecgov/openFEC/issues/3399)
_Materialized view public.ofec_entity_chart_mv is not used by by line chart anymore,  and should be 
deleted_
- set up cfdm_test database locally
- run migration against cfdm_test and check to see this object has been dropped.

drop ofec_entity_chart and its nightly refreshing

---

webservices/rest.py

- Related #3403 
_The latest upgrade of flask was causing requests from the CMS to 500 in the API due to lack of a trailing slash from the CMS request call. To fix this, this PR disables `strict_slashes` so that both types of requests will work._
Solution from: https://stackoverflow.com/questions/33241050/trailing-slash-triggers-404-in-flask-path-rule
- Run local API and make sure that both of these endpoint sill render (notice one has a trailing slash after history and the other does not):
http://localhost:5000/v1/candidate/H8GA06195/history?api_key=DEMO_KEY
http://localhost:5000/v1/candidate/H8GA06195/history/?api_key=DEMO_KEY
- Run local CMS environment and try to render a candidate or committee page based on these changes:
http://localhost:8000/data/candidate/H8GA06195/ …

Disables strict slashes in API, add 404 error handler

---

data/migrations/V0109__add_more_form_type_to_rpt_mv.sql
data/migrations/V0110__Include_F13_F4_in_ofec_totals_pacs_parties_mv.sql

- Resolves  [# 3400 ](https://github.com/fecgov/openFEC/issues/3400)
- The work in this PR will fix the data problem identified in ticket [#3382](https://github.com/fecgov/openFEC/issues/3382). Because inaugural committees file F13,  and convention and host committees file F4 sometimes, we need to add those forms to materialized views 
- pull the feature branch
Make sure to set this variable SQLA_SAMPLE_DB_CONN to cfdm_test
- check these two mvs in CFDM_TEST for F13 and F4, and there should return two F13 and two F4.
ofec_report_pac_party_all_mv
ofec_totals_pacs_parties_vw
C00540005 |	F13 |2013
-------------|--------|--------
C00458166|	F13|	2009
C00493254|	F4|	2016	
C00493254|	F4|	2017

Refactor mv and add testing data to sample db

---

webservices/common/counts.py
webservices/common/views.py
webservices/resources/aggregates.py
webservices/resources/elections.py
webservices/resources/filings.py
webservices/tasks/download.py

- Resolves #3104: **Count estimate for receipts search approximately doubles the amount returned**
Set 500k default threshold estimate for all endpoints
Tested performance and results aren't wildly different, but we'll want to keep testing. Locust test results: https://docs.google.com/spreadsheets/d/11y9OcjiK5ZHYkyPXeN-Toerrtvh-J0mJNAEccRQDHTE/edit#gid=1816955716
- run this branch of the api, go to http://127.0.0.1:5000/v1/schedules/schedule_a/?api_key=XE9ZYUzWKKe8SRLfEftx9vUndkWYnIXIQw3cOQOS&sort_hide_null=true&data_type=processed&committee_id=C00000935&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=05%2F01%2F2018&contributor_state=IL&sort=-contribution_receipt_date&per_page=30 - counts are no longer doubled
- you can also test `feature/add-datatable-counts` branch of …

Set 500k threshold estimate for all endpoints

---

tests/factories.py
tests/test_aggregates.py
webservices/resources/aggregates.py
webservices/schemas.py

Use fulltext filter for:
Schedule A: employer, occupation
Schedule B: purpose, and recipient name
- Resolves #3429 : "Disbursements missing from /schedule_b/by_recipient/"
Use full text filter for aggregate resources
Use fulltext filter for:
**Schedule A:** employer, occupation
**Schedule B:** purpose, and recipient name
This allows partial matches on these text fields.
- http://localhost:5000/v1/schedules/schedule_b/by_recipient/?api_key=DEMO_KEY&cycle=2016&per_page=20&recipient_name=Starboard%20strategic&page=1 should return results for "STARBOARD STRATEGIC, INC."
-  /schedule_a/by_employer/ -> Can use partial text search for employer
- /schedule_a/by_occupation/ -> "" occupation
- /schedule_b/by_purpose/ -> "" purpose …

Use full text filter for aggregate resources

---

.circleci/config.yml
tests/test_elections.py
webservices/resources/elections.py

Resolves #3442 and resolves https://github.com/fecgov/fec-cms/issues/1656
- Show only authorized (P, A) `committee_ids` in /elections/ endpoint
- Update Circle cache to v2 due to failing builds
- Point to `dev` db
- (optional) run local CMS and point to local API
- http://localhost:5000/v1/elections/?api_key=DEMO_KEY&cycle=2018&election_full=true&office=senate&state=MO&stateFull=Missouri&per_page=0&sort_hide_null=true - McCaskill should only have two authorized committees.
- Run CMS locally and test election profile page totals. Also, clicking through to "View all" under "Source Reports" should now only go to authorized campaign committees.
- Other candidates with multiple committees (Click "Compare to opposing candidates" button to see election profile pages): 
Feinstein (Senate) …

Show only authorized (P, A) committee_ids

---

data/migrations/V0112__add_amndt_ind_prev_file_num_to_ofec_sched_e_mv.sql
webservices/common/models/itemized.py

Add columns `prev_file_num` and `amndt_ind` to schedule_e endpoint 
- Resolves https://github.com/fecgov/openFEC/issues/3448
1. Add DB mappings in the itemized.py model file.
2. Add new DB migration file to include the two columns in the `ofec_sched_e_mv`
- on API :  query the /schedules/schedule_e/ endpoint. in the JSON output, the two columns should appear with data
- on CMS : IE screen, the columns should appear when the data is downloaded(EXPORT) 
- IE : /schedules/schedule_e/ endpoint 
- IE Export

[MERGE TO DEVELOP]feature/fix-3448-IE-bug

---

data/migrations/V0112__add_amndt_ind_prev_file_num_to_ofec_sched_e_mv.sql
webservices/common/models/itemized.py

Add columns `prev_file_num` and `amndt_ind` to schedule_e endpoint 
- Resolves https://github.com/fecgov/openFEC/issues/3448
1. Add DB mappings in the itemized.py model file.
2. Add new DB migration file to include the two columns in the `ofec_sched_e_mv`
- on API :  query the /schedules/schedule_e/ endpoint. in the JSON output, the two columns should appear with data
- on CMS : IE screen, the columns should appear when the data is downloaded(EXPORT) 
- IE : /schedules/schedule_e/ endpoint 
- IE Export

[MERGE TO RELEASE]feature/fix-3448-IE-bug

---

tests/test_itemized.py
webservices/args.py
webservices/common/models/itemized.py
webservices/resources/sched_b.py

Thanks for this PR: [https://github.com/fecgov/openFEC/issues/3357](https://github.com/fecgov/openFEC/issues/3357)
added the spender committee type column (cmte_tp) into discloure.fec_fitem_sched_b tables.
unblock this ticket, we can add 'spender_committee_type' filter into ScheduleBView endpoint easily.
- Resolves # [https://github.com/fecgov/openFEC/issues/3274]
also clean some codes to fit flake8 format.
1)checkout branch locally :feature/sched_b_add_spender_committee_type_filter
2)set SQLA_CONN to dev-replica-1
3)test url:
[http://127.0.0.1:5000/v1/schedules/schedule_b/?spender_committee_type=E&two_year_transaction_period=2018&sort=-disbursement_date&sort_hide_null=false&per_page=20&sort_null_only=false&api_key=DEMO_KEY](http://127.0.0.1:5000/v1/schedules/schedule_b/?spender_committee_ …

Add spender committee type filter into ScheduleBView

---

data/migrations/V0117__update_ofec_filings_all_mv_rm_redundent_RFAI_data.sql

- Resolves #3440 
ofec_filings_all_mv was originally composed data from
disclosure.f_rpt_or_form_sub
disclosure.nml_form_rfai
However, disclosure.f_rpt_or_form_sub already has all the RFAI filing information, under FORM_TP = 'FRQ'.   So the union all from disclosure.nml_form_rfai is redundant.
After download the branch and execute create sample DB.  
select form_type, count(*) 
from ofec_filings_all_mv 
group by form_type;
Should not result in 'RFAI' rows, only 'FRQ' rows.
-
The original API code already handled the case when user searches for form_type RFAI, search for RFAI and FRQ. Therefore no need to update the API after ofec_filings_all_mv refactoring.  
branch | PR
------ | …

refactor ofec_filings_all_mv to remove redundent RFAI rows

---

tests/test_itemized.py
webservices/args.py
webservices/common/models/itemized.py
webservices/resources/sched_a.py

Contributor committee type add in this PR: [https://github.com/fecgov/openFEC/issues/3357](https://github.com/fecgov/openFEC/issues/3357)
added the contributor committee type column (cmte_tp) into discloure.fec_fitem_sched_a tables.
- Resolves # [https://github.com/fecgov/openFEC/issues/3248]
1)checkout branch locally feature/sched_a_add_contributor_committee_type_filter 
2)set SQLA_CONN to dev-replica-1
3)test url:
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&sort=contribution_receipt_date&per_page=20&contributor_committee_type=d&contributor_committee_type=e&sort_null_only=false&two_year_transaction_period=2018&api_key=DEMO_KEY
http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&sort=contribution_receipt_date&per_page=20&contributor_committee_type=q& …

Add contributor committee type filter to sched_a end point.

---

tests/test_aggregates.py
webservices/common/models/aggregates.py
webservices/docs.py
webservices/resources/candidate_aggregates.py
webservices/schemas.py

- Resolves https://github.com/fecgov/openFEC/issues/3456
Add 'count' column into two endpoints:
ScheduleABySizeCandidateView 
ScheduleAByStateCandidateView
1)checkout branch feature/fix_no_count_sched_a
2)run api to check `count` column in result set.
3)test url:
**a) test /schedule_a/by_size/by_candidate**
[http://127.0.0.1:5000/v1/schedules/schedule_a/by_size/by_candidate/?per_page=20&page=1&api_key=DEMO_KEY&election_full=false&sort_null_only=false&cycle=2018&sort_hide_null=false&candidate_id=S8FL00166](http://127.0.0.1:5000/v1/schedules/schedule_a/by_size/by_candidate/?per_page=20&page=1&api_key=DEMO_KEY&election_full=false&sort_null_only=false&cycle=2018&sort_hide_null=false&candidate_id=S8FL00166)
**b) test /schedule_a/by_state/by_candidate** …

Add ‘count’ col to ScheduleABySizeCandidateView and  ScheduleAByStateCandidateView

---

tests/test_ao_citations.py
webservices/legal_docs/advisory_opinions.py

- Resolves #3461
Add handling for manually including/excluding AO citations (AO, statute, regulation)
- Uncomment `logger.setLevel(logging.DEBUG)` in `advisory_opinions.py`, get local elasticsearch set up, and `./manage.py load_advisory_opinions -f '1999-40'` and `2017-03` (you can cancel after each one loads). 
- AO '2017-03' shouldn't cite: ['2010-11', '2011-12', '2015-16']
- AO '1999-40' should cite (11, 110, 3)
-  Advisory opinion AO, statute, regulatory citations

Add handling for include/exclude AO citations

---

tests/test_candidates.py
tests/test_itemized.py
webservices/args.py
webservices/sorting.py
webservices/utils.py

- Resolves #3470: Add optional "NULLS LAST" (`sa.nullslast`) sort
Currently, nulls will sort last by default when sorting *ascending* - this feature adds an optional `sort_nulls_last` parameter which forces nulls to the bottom for *descending* sort. The default behavior of the API is unchanged. This is needed for proper display of front-end data tables.
- Test this link with the default behavior. Nulls should show first: http://127.0.0.1:5000/v1/candidates/?api_key=DEMO_KEY&sort_hide_null=false&has_raised_funds=true&sort=-first_file_date&per_page=30&page=1
- Add the `sort_nulls_last=true` parameter and nulls should appear on the last page instead of the first page: http://127.0.0.1:5000/v1/candidates/?api_key=DEMO_KEY&sort_hide_null=false&has_raised_funds=true&sort=-first_file_date&per_pag …

Add optional parameter to sort nulls last

---

tests/test_candidates.py
webservices/resources/candidates.py

- Resolves https://github.com/fecgov/fec-cms/issues/2463
For new house candidates that file for a future election,
the 2-year period will equal `prev_election_yr`
until we reach the 2-year period for that future election.
This `>=` (rather than `>`) guarantees results for candidate pages.
~`models.CandidateHistory.two_year_period > models.CandidateElection.prev_election_year`~
`models.CandidateHistory.two_year_period >= models.CandidateElection.prev_election_year`
A `SELECT DISTINCT` on `candidate_id` prevents duplicate rows.
- Connect to `dev` replica
- This link should return results: http://127.0.0.1:5000/v1/candidate/H0FL18173/history/2020?per_page=1&election_full=true
whereas on production, there are no results: https://api.open.fec.gov/v1/candidate/H0FL18173/history/2020/?api_key=DEM …

Show history for first-time, future-cycle house candidates

---

requirements.txt

This reverts commit 2e5686467745c7dc90dbedb874ea954084f77f38. Commits shouldn't be made directly to `develop`, `release`, or `master` branches.
I can't figure out what happened with commit 55349bb3d723f3b30104ff97c19b00cf39b1402a ("Merge branch 'develop' of https://github.com/fecgov/openFEC into develop") so I think I have to leave it there.

Revert "fixing requirements.txt on develop branch."

---

tests/test_candidates.py
webservices/resources/candidates.py

- Expedited hotfix release of https://github.com/fecgov/fec-cms/issues/2463
Show history for first-time, future-cycle house candidates. This has already been merged to `develop` but @jwchumley requested a hotfix
See original PR: https://github.com/fecgov/openFEC/pull/3483

[MERGE WITH GIT FLOW] Show 2020 house candidate history

---

tests/factories.py
tests/test_aggregates.py
webservices/common/models/aggregates.py
webservices/docs.py
webservices/resources/aggregates.py
webservices/schemas.py

- Resolves # [_3390_](https://github.com/fecgov/openFEC/issues/3390)
_Currently some disbursements are missing from schedule B aggregate endpoints.  Most of those disbursements are memoed items.  To fix this, totals and counts of memoed items are added to three aggregate tables_
-Test this link and API will return 1 result ( using DEV database ): 
http://127.0.0.1:5000/v1/schedules/schedule_b/by_recipient/?cycle=2016&per_page=20&sort_null_only=false&sort_hide_null=false&page=1&recipient_name=DRL%20Publications
current API returns 0:
https://api.open.fec.gov/v1/schedules/schedule_b/by_recipient/?api_key=DEMO_KEY&per_page=20&page=1&sort_null_only=false&cycle=2016&recipient_name=DRL%20Publications&sort_hide_null=false
Current disbursement aggregate pages only display non-memo total.  With …

Switch to new schedule B aggrgeate tables with memo totals

---

.circleci/config.yml
tasks.py

Related Issue: Add Circle Ci IP address to AWS DEV PG Security Group,
[https://github.com/18F/fec-accounts/issues/151](https://github.com/18F/fec-accounts/issues/151)
- Enable IP whitelist for database connections
- Create Bastion Host 
- Establish Bastion Host tunnel through port mapping
- Modify FEC_MIGRATOR_SQLA_CONN_DEV to point to Bastion Host tunnel through port mapping.
**Notes for cut branch and release**
1)before cut release branch, update FEC_MIGRATOR_SQLA_CONN_STAGE
2)before release, update FEC_MIGRATOR_SQLA_CONN_PROD

Create Bastion Host Tunnel in CircleCI configuration

---

manage.py
webservices/legal_docs/__init__.py
webservices/legal_docs/index_management.py
webservices/tasks/__init__.py
webservices/tasks/download.py
webservices/tasks/legal_docs.py

Resolves #3143: **Automate elasticsearch backups**
- Add a management task to configure elasticsearch backup repository
- Add a management command to create an elasticsearch backup (optional name parameter)
- Add a management command to restore from backup (optional name parameter)
- Add celery task for weekly backups
- I needed to do a test deploy to `dev` to test this one - `invoke deploy --space dev --skip-migrations`
- `cf target --space dev`
- This should only have to be run once, but it's nice to automate this too. I've had to do this before if I can't authenticate - I think sometimes it gets wonky.
- `cf run-task api "python manage.py create_backup_repository -r test_repo_setup" -m 4G --name es-backup-1`
- Set up port forwarding (see elasticsearch [backup instructions]( …

Automate elasticsearch backups

---

tests/test_itemized.py
webservices/args.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py

- Resolves #3495
- http://localhost:5000/v1/schedules/schedule_b/?sort=-disbursement_date&sort_nulls_last=true should still return nulls first
- http://localhost:5000 should not show `sort_nulls_last` parameter for schedules A and B
-  Receipts, individual contributions, disbursements data tables
https://github.com/fecgov/openFEC/pull/3474 **Add optional parameter to sort nulls last**

Disable sort_nulls_last for Sch A and B

---

data/migrations/V0118__drop_original_sb_agg_tables.sql

- #3459 Drop old set of dsc_sched_b_aggregate tables after complete switch to new tables with update business logic
After run the migration file in local database, make sure the following 3 tables not exist anymore:
disclosure.dsc_sched_b_aggregate_purpose
disclosure.dsc_sched_b_aggregate_recipient
disclosure.dsc_sched_b_aggregate_recipient_id
These three tables are not being used anymore after issue #3390 had been deployed.
branch | PR

drop original dsc_sched_b_aggregate tables

---

tests/test_itemized.py
webservices/args.py
webservices/common/models/itemized.py
webservices/resources/sched_a.py

- Resolves #3511: Rename `contributor_committee_type` to `recipient_committee_type`
- http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&sort=contribution_receipt_date&per_page=20&recipient_committee_type=d&contributor_committee_type=e&sort_null_only=false&two_year_transaction_period=2018&api_key=DEMO_KEY
- http://127.0.0.1:5000/v1/schedules/schedule_a/?sort_hide_null=false&sort=contribution_receipt_date&per_page=20&recipient_committee_type=q&sort_null_only=false&two_year_transaction_period=2018&api_key=DEMO_KEY)
-  /schedules/schedule_a/
Original PR: https://github.com/fecgov/openFEC/pull/3472/files

Rename 'contributor_committee_type' to 'recipient_committee_type'

---

tests/test_itemized.py
webservices/args.py
webservices/docs.py
webservices/resources/sched_e.py

From API, make support_oppose_indicator sortable on ScheE endpoint.
API endpoint that is modified under **Independent Expenditures**:
/**schedules/schedule_e/**
- Resolves https://github.com/fecgov/openFEC/issues/3518
1. Make support_oppose_indicator sortable
2. Add tests to sort(asc,desc order) by support_oppose_indicator column
1. checkout feature/make-support-oppose-indicator-column-sortable-scheduleE
2. Sort by support_oppose_indicator in descending order :::
- http://localhost:5000/v1/schedules/schedule_e/?sort=support_oppose_indicator&sort_hide_null=false&sort_nulls_last=false&committee_id=C90010661&per_page=100&sort_null_only=false
3. ascending order:::
-  http://localhost:5000/v1/schedules/schedule_e/?sort=- …

Make ScheE endpoint sortable by support_oppose_indicator

---

webservices/args.py
webservices/docs.py

- Resolves # [3507](https://github.com/fecgov/openFEC/issues/3507)
_The list of report types in report endpoints has more than what it has in materialized views. A new list was created based on the data in materialized views._
-http://127.0.0.1:5000/developers/#/financial/get_committee__committee_id__reports_
-http://127.0.0.1:5000/developers/#/financial/get_reports__committee_type__
New list of base report type:
10D Pre-Election
10G Pre-General
10P Pre-Primary
10R Pre-Run-Off
10S Pre-Special
12C Pre-Convention
12G Pre-General
12P Pre-Primary
12R Pre-Run-Off
12S Pre-Special
30D Post-Election
30G Post-General
30P Post-Primary
30R Post-Run-Off
30S Post-Special
60D Post-Convention
M1 January Monthly
M10 October Monthly
M11 November Monthly
M12 December Monthly
M2 February Monthly
M3 March …

Modify the list of report types in report endpoints

---

data/migrations/V0120__update_ofec_sched_e_mv_s_o_ind_handling.sql

#3532 Update sched_e MV to support sort on non-standard s_o_ind value
update ofec_sched_e_mv definition to handle non-standard s_o_ind value
After migration file run, check the ofec_sched_e_mv definition, 
The s_o_ind should be as followed:
CASE when se.s_o_ind in ('O', 'S') then se.s_o_ind else NULL::character varying END AS s_o_ind,
That is, the output should only has the standard 'S' and 'O' value, all other values (including null) should be treated as null.
This issue is to support a CMS issue:
fecgov/fec-cms#2494
The functionality of fecgov/fec-cms#2494 does not depending on this issue.  However, completion of this update will make the display make more sense to the users. …

update ofec_sched_e_mv to handle non-standard s_o_ind value

---

requirements.txt
webservices/tasks/utils.py

- Resolves # [https://github.com/fecgov/openFEC/issues/3398](https://github.com/fecgov/openFEC/issues/3398)
- Resolve # [https://github.com/fecgov/openFEC/issues/3527](https://github.com/fecgov/openFEC/issues/3527)
Upgrade smart-open to version 1.7.1
Remove request module from webservices/tasks/utils.py
1. Pull branch to local environment
2. Remove following packages from your local python environment using pip uninstall:
pip uninstall boto
pip uninstall boto3
pip uninstall botocore
pip uninstall smart-open
3. Run the following commands to install new packages:
pip install -r requirements.txt
pip install -r requirements-dev.txt
4. Run `pip freeze` to check the newer version of packages
smart-open==1.7.1
boto==2.49.0
boto3==1.9.62
botocore==1.12.62 …

Upgrade smart-open==1.7.1 and remove request module from task/utils.py 

---

webservices/common/models/costs.py
webservices/docs.py

- Resolves [https://github.com/fecgov/openFEC/issues/3535](https://github.com/fecgov/openFEC/issues/3535)
_Include a summary of proposed changes
1. Map the two DB columns  payee_nm and payee_st in EC model file.
2. Moved the column descriptions that are long to the docs.py.
- checkout the feature/add-payee-columns-to-ec-endpoint
- export SQLA_CONN to point to DEV DB
- test the /electioneering/ endpoint. the results section should display these two additional columns.
- test URL :
http://127.0.0.1:5000/v1/electioneering/?page=1&sort_nulls_last=false&sort_null_only=false&per_page=20&sort_hide_null=false
Screenshot : 
Prod URL without the additional columns:
https://api.open.fec.gov/v1/electioneering/?sort_nulls_last=false&page=1&per_page=20&sort_null_only=false&sort_hide_null=false&api_key=D …

add-payee-columns-to-ec-endpoint

---

tests/test_legal.py
webservices/resources/legal.py

- Resolves #3504 
- Remove mur-specific query fields - use `case_`
- Fix admin fine filter typo
- Run ES locally, do a mur query: http://localhost:5000/v1/legal/search/?case_no=7400
-  MUR search

Remove mur-specific query fields - use 'case'

---

tests/test_elections.py
webservices/resources/elections.py

Cash-on-hand(COH) for 2020 candidates is now displaying the amount on election profile pages. 
- Resolves # https://github.com/fecgov/openFEC/issues/3562
- checkout the branch `feature/fix-coh-on-election-profile-pages`
- export the `SQLA_CONN` to point to DEV DB
- The `/elections/` endpoint should now display amount against `cash_on_hand_end_period` column.
http://127.0.0.1:5000/v1/elections/?page=1&sort_nulls_last=false&per_page=20&election_full=true&cycle=2020&office=president&sort_null_only=false&sort=-total_receipts&sort_hide_null=false
- Website:  https://www.fec.gov/data/elections/president/2020/
- API : https://api.open.fec.gov/v1/elections/?api_key=DEMO_KEY&cycle=2020&election_full=true&office=president&per_page= …

Fix COH on election profile pages

---

data/migrations/V0123__ofec_totals_combined_mv_update_op_exp.sql

- Resolves # 3582 Operating expenditures wrong on committee profile page
The value for operating_expenditures and fed_operating_expenditures is incorrect for F3X filing committees. 
The unerline ofec_totals_combined_mv, which feeds the ofec_totals_pacs_parties_mv/vw 
only use op_exp_per as the source for operating_expenditures column.
That is correct for F3/F3P but for F3X needs to use the ttl_op_exp_per column. 
The following change is made to the base ofec_totals_combined_mv:
(case when vsd.form_tp_cd = 'F3X' then vsd.ttl_op_exp_per else vsd.op_exp_per end)
In DEV database, a tmp MV and a tmp VW had been created with the updated definition
(ofec_totals_combined_mv_tmp/ofec_totals_pacs_parties_vw_tmp):
compared result from the original and the …

update op_exp calculation in ofec_totals_combined_mv

---

tests/test_filings.py
webservices/common/models/filings.py
webservices/docs.py
webservices/resources/filings.py

Modified eFiling date range filter to use filed_date (Date type), which enable the user to query data by a single day.
- Resolves [https://github.com/fecgov/openFEC/issues/3563](https://github.com/fecgov/openFEC/issues/3563)
Added filed_date to the model and filter by it
- modified:   webservices/common/models/filings.py
- modified:   webservices/resources/filings.py
- pull feature/filter-raw-filing-single-day branch to your local environment
- Point SQLA_CONN to dev database
- run local server
- Open a browser window to http://localhost:5000/developers/#/efiling/get_efile_filings_
- Filter records by min_receipt_date and/or max_receipt_date
- …

Modified eFiling date range filter to use filed_date

---

data/migrations/V0124__ofec_candidate_history_mv_update_cand_inactive.sql

- Resolves #3564 Exclude inactive candidates from election pages
The main driver for the endpoint shown in the above example (ElectionView) is ofec_candidate_history_mv, which already has the candidate_inactive column. The dynamic query built in ElectionView already has the condition candidate_inactive = false built in. However, the sql statement that create ofec_candidate_history_mv need to be updated to produce correct data to exclude inactive candidate.
* download this branch to your local machine.  Run create_sample_db to make sure migration script executed successfully without error.
* A tmp version of the ofec_candidate_history_mv_tmp had been created in the DEV environment using the update sql statement.
* To test the DB change:
select …

update ofec_candidate_history_mv to fix cand_inactive value

---

bin/run.sh

- Resolves #https://github.com/fecgov/fec-proxy/issues/117
_Increasing API timeout from default gunicorn 30 seconds to 300 seconds (5 mins) to account for slower queries._
- This is currently deployed to https://stage.fec.gov, you can test slower queries there.

Increase API timeout to 300

---

requirements.txt

upgrade redis to version3.2.0 to resolve celery worker and beat connectivity issues caused in `dev` and `stage` environments after kombu was updated to a version 4.4.0.
bump the **`redis version to 3.2.0`** in **`requirement.txt`**
all scheduled tasks (celery worker/beat tasks), cron jobs

Upgrade redis to version 3.2.0 

---

tests/test_aggregates.py
webservices/args.py
webservices/docs.py
webservices/resources/candidate_aggregates.py

'is_active_candidate' filter added to 'candidates/totals' api
#3572
'is_active_candidate' filter added to current api:
- is_active_candidates=True: load active candidates only
- active_candidates=False: load inactive candidates only
- default(argument missing): load both
files changed/added:
M webservices/args.py
M webservices/docs.py
M webservices/resources/candidate_aggregates.py
M tests/test_aggregates.py
pull feature/add-cand-active-filter branch to your local environment
Point SQLA_CONN to dev database
run local server
Open a browser window to http://localhost:5000 for testing:
e.g.
- load both active/inactive candidates
>>http://127.0.0.1:5000/v1/candidates/totals?api_key=NICAR16&candidate_id=H2MA05120
result: 5 …

adding active_candidates filter to totalCandidateView with unit tests.

---

manifests/manifest_api_dev.yml
manifests/manifest_api_prod.yml
manifests/manifest_api_stage.yml
manifests/manifest_celery_beat_dev.yml
manifests/manifest_celery_beat_prod.yml
manifests/manifest_celery_beat_stage.yml
manifests/manifest_celery_worker_dev.yml
manifests/manifest_celery_worker_prod.yml
manifests/manifest_celery_worker_stage.yml
manifests/manifest_task_dev.yml.template
manifests/manifest_task_prod.yml.template
manifests/manifest_task_stage.yml.template
requirements.txt

1.  In  manifest files for **`dev/stage/prod`**, updated the stack to cflinuxfs3.
2.  In requirements.txt  : 
-  Upgrade redis to 3.2.0 to resolve connectivity issues caused in celery worker/beat apps due to the 
recent kombu upgrade.
-  Upgrade psycopg2 to 2.7.3.2 : This upgrade is required to build and deploy the `api` app 
successfully on `dev`, `stage` and `prod` spaces with the new OS-cflinuxfs3 
- Resolves #3566
1. manifest_api_dev.yml
2. manifest_api_prod.yml
3. manifest_api_stage.yml
4. manifest_celery_beat_dev.yml
5. manifest_celery_beat_prod.yml
6. manifest_celery_beat_stage.yml
7. manifest_celery_worker_dev.yml
8. manifest_celery_worker_prod.yml
9. manifest_celery_worker_stage.yml
10. requirements.txt
- checkout the branch …

Update OS stack to cflinuxfs3 

---

requirements.txt
tests/test_swagger.py

- Workaround for #3612 until we can find a better solution. #3612 is blocking the release as well as testing some urgent security issues.
- Temporarily remove `prance[osv]` which is bringing in `pathlib`, which conflicts with `pytest`. As a result, remove swagger validation
- Create a fresh virtual env
- `pip install -r requirements.txt -r requirements-dev.txt -r requirements-ci.txt`
- Run `pytest` and local API
-  Swagger validation will be missing until we can resolve conflicts - ideally `openapi-spec-validator` will release a new version (0.2.7) where they use `pathlib2` https://pypi.org/project/openapi-spec-validator/#history
branch | PR …

Temporarily remove prance[osv] and swagger validation

---

requirements.txt
tests/test_swagger.py

- Workaround for #3612 until we can find a better solution. #3612 is blocking the release as well as testing some urgent security issues.
- Temporarily remove `prance[osv]` which is bringing in `pathlib`, which conflicts with `pytest`. As a result, remove swagger validation
- Create a fresh virtual env
- `pip install -r requirements.txt -r requirements-dev.txt -r requirements-ci.txt`
- Run `pytest` and local API
-  Swagger validation will be missing until we can resolve conflicts - ideally `openapi-spec-validator` will release a new version (0.2.7) where they use `pathlib2` https://pypi.org/project/openapi-spec-validator/#history
branch | PR …

(Release PR) Temporarily remove prance[osv] and swagger validation

---

requirements.txt

Upgrade SQLAlchemy to the latest version 1.3.1
- Resolves #3589
Update the SQLAlchemy library in `requirements.txt` 
- checkout `feature/upgrade-sqlalchemy`
- run `pip freeze`. Local virtual env should have SQLAlchemy1.2.8
- run  `pip install -r requirements.txt`
- run `pip freeze`. Local virtual env should have new version SQLAlchemy1.3.1
- run `pytest`. Make sure all the tests PASS
- start the local server : `./manage.py runserver` and test few API endpoints. 
For example: 
- http://127.0.0.1:5000/v1/candidates/totals/by_office/?sort_hide_null=false&active_candidates=true&per_page=20&sort_nulls_last=false&page=1&sort_null_only=false
- http://127.0.0.1:5000/v1/elections/search/?sort_hide_null=false&per_page=20&page=1&sort=sort_order&sort=district&s …

Upgrade SQLAlchemy to latest version 1.3.1.

---

data/migrations/V0125__ofec_totals_combined_mv_ttl_fed_disb_null.sql

- Resolves #3581
PAC "Total Federal Disbursements" returning "null"
In the parent MV ofec_totals_combined_mv, currently the source for fed_disbursements is fed_funds_per column in disclosure.v_sum_and_det_sum_report.
sum(vsd.fed_funds_per) AS fed_disbursements
Column "TTL_FED_DISB_PER" should be used as the source for fed_disbursements
In DEV database, a tmp MV and a tmp VW had been created with the updated definition
(ofec_totals_combined_mv_tmp/ofec_totals_pacs_parties_vw_tmp):
compared result from the original and the view with the updated definition. 
For example:
(you can try other PAC/Party committee such as C00000935 or C00003418)
select committee_id, cycle
, fed_disbursements
from ofec_totals_pacs_parties_vw
where committee_id = 'C00344234' …

update ofec_totals_combined_mv to fix ttl_fed_disb null problem

---

webservices/rest.py

- Resolves #3545: Add caching between 9am and 7:30pm ET
This is easiest to test with a manual deploy, because cloud.gov apps are in UTC and our local environments are on local time.
Only `stage` and `prod` have the API umbrella, so on `dev` all we can check is that the `cache-control` headers are returning the proper `max-age` value. I tested this with a manual deploy to `stage`.
- Between 9am and 7:30pm ET, `curl -I -X GET "https://api-stage.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY"` and other queries below  should return `Expires: <today's date, ie. Mon, 18 Mar 2019> 23:00:00 GMT` (7:30pm ET)
- Outside of those times (after 7:30pm until 9am the next day), `curl -I -X GET "https://api-stage.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY"` and other queries below …

Add all-day cache between 9am and 7:30pm ET

---

webservices/common/models/itemized.py

- Resolves # [3634]
Query against processed sched tables should use two_year_transaction_period instead of re-calculated in the query.
The fec_fitem_sched_tables already have two_year_transaction_period column, which is the partition key of the huge fec_fitem_sched_a and fec_fitem_sched_b tables. It is calculated based on rpt_yr + rpt_yr % 2. The current code re-calculate the it again in the query, which slowed down the query. The model file for itemized need to updated to change the join condition for fec_fteim_sched_a/b to ofec_committee_history_mv.
Download the branch to the local machine. In order to verify the query generated by the SQLAlcheny correctly use the disclosure.fec_fitem_sched_a/b.two_year_transaction_period = ofec_committee_history_mv_1.cycle join condition, you can do …

use two_year_transaction_period in join for fec_fitem_sched_a/b

---

webservices/flow.py

- Resolves #3632 
ofec_candidate_history_with_future_election_mv need to be refreshed before ofec_candidate_totals_mv
ofec_candidate_totals_mv depends on ofec_candidate_history_with_future_election_mv. Therefore ofec_candidate_history_with_future_election_mv needs to be refreshed first in order for ofec_candidate_totals_mv to get the most updated data from ofec_candidate_history_with_future_election_mv
Download the branch to your local machine.  
The last step of create_sample_db is refreshing all the MVs.  
Review the output of MV refresh, make sure 
INFO:manager:Refreshing ofec_candidate_history_with_future_election_mv
appears **_BEFORE_** 
INFO:manager:Refreshing ofec_candidate_totals_mv
No API …

fix-mv-refresh-sequence

---

webservices/rest.py

- Resolves #3545 
Limit extra caching to /schedules/
- I tested this with a deploy to `stage`. 
- During peak hours (9am-7:30pm ET), `/schedules/` endpoints should return an `Expires: <today's date, ie. Mon, 18 Mar 2019> 23:00:00 GMT` (7:30pm ET) header:
`curl -X GET -I "https://api-stage.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY"`
-  During peak hours (9am-7:30pm ET),  endopoints that aren't `/schedules/` `/efile/`, `/legal/`, or `/calendar-dates/` endpoints (ie. /filings/) should return the default header:  `Cache-Control: public, max-age=3600`:
`curl -X GET -I "https://api-stage.open.fec.gov/v1/committees/?api_key=DEMO_KEY"`
-  Caching /schedules/ data during peak hours
List related PRs against other …

Limit extra caching to /schedules/

---

tests/factories.py
tests/test_elections.py
webservices/common/models/totals.py
webservices/resources/elections.py

- Resolves [#3611](https://github.com/fecgov/openFEC/issues/3611) 
- Refactor Financial:/elections/ to use ofec_totals_combined_vw when calculating totals for presidential election profile page. By doing so will take care of the scenario when committee files wrong forms to FEC ( F3 or F3X).  Originally the endpoint uses ofec_totals_presidential_mv which is a subset of ofec_totals_combined_mv by setting form_type=F3P
- Pull feature/fix-election-profile-total to local
- Set SQLA_CONN to DEV ( page loading in DEV will be a little bit slower ( it takes about 3s ) comparing to STAGE because the latter RDS has been upgraded )
- Run endpoint:
http://127.0.0.1:5000/v1/elections/?election_full=true&sort=-total_receipts&page=1&sort_nulls_last=false&cycle=2020&office=president&sort_null_only=false&so …

Fix Financial:/elections/ to include F3 for presidential election_profile totals

---

.circleci/config.yml

update circleci config.yml to switch base docker image to python:3.6.4-stretch
circleci build failure issue with openFEC - failed at the flyway installation step for jessie update：
https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository
switch docker base image from 3.6.4-jessie to 3.6.4-stretch
push this branch to remote to invoke circleCI build and the build should be successful.
-
-  
branch | PR

updateing circleci docker base image to 3.6.4-stretch.

---

data/migrations/V0126__ofec_candidate_totals_mv_coh.sql

- Resolves # 3635
COH for John Delaney incorrect on /candidates/totals
- Fix /candidates/totals/ cash on hand and debts owed by committee for F3&F3P combo committees. Some candidates file on F3 and F3P - this adjusts the COH calculation for ofec_candidate_totals_vw where there is more than one totals row for the same cycle for the same committee
- Addition layers of aggregation are added to address the issue of candidates with multiple
P/A cmtes.  The COH of these rows need to be summed up.
- The grouping of cycle_totals should include election_year instead of taking max(election_year), otherwise cycle data after election_year for the same election_year will be folded into different election_year and resulted in error.
- The join condition of ofec_candidate_history_with_future_election_vw …

update ofec_candidate_totals_mv to handle coh aggregation for candida…te with multiple form type and/or multiple committees

---

README.md

- Resolves #https://github.com/fecgov/openfec/issues/3547
In README.md file, added two new sync vulnerability links. These links will display the count of vulnerabilites found in `package.json` and `requirements.txt file` and in flyway/build.gradle file off the `develop` branch
Verify vulnerabilities count in the Snyk app link(Snyk app link: https://snyk.io/org/fecgov/projects) against new links added on fec-eregs README.md file. Make sure the count matches and the links are not broken.

OPENFEC - Add snyk links

---

README.md

Resolves ##3547
Updated sync vulnerability links In README.md file. These links will display the count of vulnerabilities found in package.json and requirements.txt file and in flyway/build.gradle files
- on github/openfec repo, edit the README.md file, copy and paste the above links. Click on the preview tab and see if the counts are displaying properly and make sure the links are not broken. DO NOT SAVE THE CHANGES.

fix the synk links to show the vulnerabilities counts 

---

tests/test_itemized.py
webservices/args.py
webservices/config.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py

remove two-year restriction from sched_a and sched_b endpoints but don't update the api docs
- Resolves #3595
1. two_year_transaction_period: required --> not required
2. update two_year_transaction_period to allow for multiple value
3. one pytest disabled - checking for default two_year_transaction_period missing value
- pytest should pasd
- test on local server:
1. manage.py runserver
2. test the following api for multiple two_year_transaction_period values:
>>http://127.0.0.1:5000/v1/schedules/schedule_b/?sort_hide_null=false&per_page=20&max_date=12%2F31%2F2018&api_key=DEMO_KEY&min_date=1%2F1%2F2014&is_individual=true&two_year_transaction_period=2018&sort_null_only=false&min_amount=500&two_year_transaction_period=2016&two_year_transaction_period= …

update sched_a.py and sched_b.py and remove two year restriction.

---

README.md

Update `SQLA_SAMPLE_DB_CONN` instructions
https://stackoverflow.com/questions/5598517/find-the-host-name-and-port-using-psql-commands
```
export SQLA_SAMPLE_DB_CONN="postgresql://<username>:<password>@localhost:<port - default is 5432>/cfdm_test"
```
@jason-upchurch please let me know if you think this adds clarity.

Update SQLA_SAMPLE_DB_CONN instructions

---

requirements.txt

- Resolves #3608 
* update requirements.txt with kombu version and note on celery
* `pip install -r requirements.txt`
For local API setup, impacts dependent packages installed by requirements.txt
branch | PR
feature/3608-pin-requirements-kombu-4.3.0| [3608](https://github.com/fecgov/openFEC/issues/3608)
edited to include how to test locally

pin requirements for kombu 4.5.0

---

.circleci/config.yml
data/flyway/build.gradle
data/flyway/manifest_headless_flyway.yml

- Resolves #3654: Update Flyway to version 5.2.4
- Download new version, set up: [Install version 5.2.4](https://github.com/fecgov/openFEC#project-prerequisites)
- Run`invoke create_sample_db`
- I tested this with a manual deploy to `dev`.
- Database migrations  
branch | PR
feature/upgrade-flyway | https://github.com/fecgov/openFEC/pull/3223

Update Flyway to version 5.2.4

---

package-lock.json
package.json

- Resolves #3639 
_This upgrades our node to v10.15.1 and npm to v6.8.0._
- `nvm ls` will list which versions of Node are installed locally. `node -v` will show the current version. This PR is using the 10.15.1 version. To install it, use `nvm install v10.15.1`. Switch to it with `nvm use 10.15.1`
- `npm install -g npm` will update npm to (currently 6.8.0)
- It would be a good idea to remove the node_modules directory, either delete it through Finder or use `rm -rf node_modules/`
- `npm i` will go get versions of everything in package.json
- `npm run build`
- Run the server and/or watch as usual
- Test the site's page that utilizes swagger: http://localhost:5000/developers/
-  May effect swagger-ui documentation part of …

Upgraded node and npm versions

---

webservices/rest.py

Resolves #3651 
- Limit access to /downloads/ to one API key, only when `RESTRICT_DOWNLOADS` is turned on
- Turn `BLOCKED_IPS` into an `env var`
- This is hard to test locally because it needs the API umbrella in place. There's currently a manual deploy on `stage` (`invoke deploy --space stage --skip-migrations`)
-  Downloads

Limit access to /downloads/ to one API key

---

data/migrations/V0129__add_fec_fitem_sched_ab_2019_2020.sql

- Resolves #[3657](https://github.com/fecgov/openFEC/issues/3657)
create fec_fitem_sched_a_2019_2020 and fec_fitem_sched_b_2019_2020 partition tables and related objects.
update finalize_itemized_schedule_a_tables and finalize_itemized_schedule_b_tables functions to  to simplify and streamline the index creation process when new child partition tables are created.
- download the branch to local machine, invoke create_sample_db process.  Make sure migration executed successfully.
- Connect to local_db, verify fec_fitem_sched_a_2019_2020 and fec_fitem_sched_b_2019_2020 tables and the indexes created successfully.  
select tablename
from pg_tables 
where tablename like 'fec_fitem_sched_%_2019_2020'
order by tablename;
-- there should be 2 rows returned
select tablename, indexname
from …

add fec_fitem_sched_a_2019_2020 and fec_fitem_sched_b_2019_2020 tables

---

tests/factories.py
tests/test_sched_d.py
webservices/common/models/itemized.py
webservices/resources/sched_d.py

Add sort args to `/schedules/schedule_d/{sub_id}/` endpoint.
- Resolves #3681 
There is no default sort argument set on this endpoint. Added sort by `load_date` in  resources/sched_d.py 
- Checkout feature/fix-scheduled_subid_endpoint
- export SQLA_CONN to `dev` DB
- start the  server
- copy this URL in the browser : http://127.0.0.1:5000/v1/schedules/schedule_d/4022220171371899074/?per_page=20&page=1
- This URL should bring the results back
**Production API URL (Broken)**:
https://api.open.fec.gov/v1/schedules/schedule_d/4022220171371899074/?api_key=DEMO_KEY&per_page=20&page=1
api endpoint : /schedules/schedule_d/{sub_id}/

add sort args to /schedule/schedule_d/{sub_id}/ endpoint

---

tests/factories.py
tests/test_sched_c.py
webservices/args.py
webservices/common/models/itemized.py
webservices/docs.py
webservices/resources/sched_c.py

This one PR will resolve two issues(two endpoints used for loans page) in sched_c.py:
- Resolves  [https://github.com/fecgov/openFEC/issues/3712](https://github.com/fecgov/openFEC/issues/3712)
ScheduleCView endpoint: Fix 'incurred date filter' not working issue
- Resolves  [https://github.com/fecgov/openFEC/issues/3696](https://github.com/fecgov/openFEC/issues/3696)
ScheduleCViewBySubId endpoint: Fix broken endpoint
- Add validators for 'incurred_date', 'payment_to_date', 'original_loan_amount'
- Create a new separated test_sched_c.py(easy to maintain in the future) to do automated test for above two endpoints.
1)setup openFEC repo locally, checkout branch
2)pytest
3)./manager runserver
4)Test endpoint: under Loans:/schedules/schedule_c/{sub_id}
ex: …

Fix schedule_c endpoints incurred date filter not work

---

tests/test_filing_resources.py
webservices/common/models/rad_analyst.py
webservices/resources/rad_analyst.py

- Resolves #3699 
* swagger ui
branch | PR
feature/3699-rad_analyst-filter-bug| [https://github.com/fecgov/openFEC/issues/3699](https://github.com/fecgov/openFEC/issues/3699)

Fix search by analyst title and email

---

tests/test_itemized.py
webservices/resources/sched_a.py

- Resolves #3717 
Require secondary filter for Schedule A when searching more than one 2-year period
- Connect to `stage` DB with `SQLA_CONN`
- Check out and run this branch
-  Queries with secondary criteria should work: http://localhost:5000/v1/schedules/schedule_a/?sort_null_only=false&committee_id=C00213512&sort_hide_null=false&sort=contribution_receipt_date&per_page=20
- Queries without secondary criteria should throw 400 error: http://localhost:5000/v1/schedules/schedule_a/?sort_null_only=false&sort_hide_null=false&sort=contribution_receipt_date&per_page=20
- Queries with multiple 2-year transaction periods and no secondary criteria should error: http://localhost:5000/v1/schedules/schedule_a/?sort_null_only=false&sort_hide_null=false&sort=contribution_receipt_date&per_page=20&two_yea …

[MERGE WITH GIT FLOW] Hotfix: Limit large Schedule A queries

---

webservices/resources/sched_a.py

remove line_number from sched_a secondary index list
- Resolves #[_3733_]
remove line_number from sched_a secondary index list. affected file is:
webservices/resources/sched_a.py
- run pytest, all unit tests should pass
- run './manage.py runserver', then fire those two endpoints request:
request1:
http://127.0.0.1:5000/v1/schedules/schedule_a?per_page=30&two_year_transaction_period=2018&sort=-contribution_receipt_date&api_key=DEMO_KEY&line_number=12&
sort_hide_null=false&is_individual=true&two_year_transaction_period=2016&sort_nulls_last=false
request2:
http://127.0.0.1:5000/v1/schedules/schedule_a?per_page=30&two_year_transaction_period=2018&sort=-contribution_receipt_date&api_key=DEMO_KEY&sort_hide_null=false&is_individual=true&two_year_transacti …

remove line_number from sched_a secondary index list.

---

data/load_base_mur_data.sql
data/migrations/V0130__add_published_flg_to_fecmur_case.sql
tasks.py
tests/integration/test_current_cases.py
tests/test_itemized.py
webservices/legal_docs/current_cases.py
webservices/resources/sched_a.py
webservices/tasks/legal_docs.py

A case (ADR, AF or MUR) is purged on  DB, by setting the `published_flg=false` and updating `pg_date` column in case table. This will initiate a celery task which deletes the case from elasticsearch service.
- Resolves #3573 
1. Modify the case queries to fetch the new boolean column published_flg
2. Update the `load_cases` script to check if `published_flg=false` set  on a case and delete it from ES service.
3. Update `test_current_cases.py` test to return the published_flg for a given case 
1.Follow the instructions and set up your workspace with the following services:
(https://github.com/fecgov/openFEC/wiki/Set-up-Redis,--Celery-on-local-and-test-the-downloads#testing-queued-tasks-locally)
2.start your local elasticsearch service
3.get the API …

Test published/unpublished cases

---

data/migrations/V0131__ofec_cand_cmte_linkage_mv_add_column.sql
data/migrations/V0132__ofec_cand_totals_mv_update.sql
tests/test_elections.py
tests/test_utils.py
webservices/common/models/links.py
webservices/resources/elections.py

- Resolves #3700
Bernie Sanders totals incorrect
-Download the branch feature/3700-fix-BernieSanders-totals-incorrect, run migration files V0131 and V0132 (or run invoke create_sample_db) to make sure migration files runs without error.
Two tmp materialized views had been created in DEV database that has the updated MVs logic.
(Note: ofec_candidate_totals_mv_tmp references ofec_cand_cmte_linkage_mv_tmp)
public.ofec_cand_cmte_linkage_mv_tmp
public.ofec_candidate_totals_mv_tmp
- To test database:
(Cand_id: 
'P60007168':  Bernie Sandersn (runs 2016, 2020)
make sure 2018 cycle financial data is calculated as part of election_cycle 2020, not 2016)
'P00003392': Hillary Clinton (runs 2008, 2016)
make sure 2014 cycle financial data  is calculated as part of election_cycle 2016, not 2008; 2010, …

[Do not merge before PR#3688 due to migration number]Fix bernie sanders totals incorrect

---

requirements.txt

Upgrade python requests package to latest version 2.21.0
- Resolves #https://github.com/fecgov/openFEC/issues/3722
In requirements.txt file, pin requests package to the latest v2.21.0
- export SQLA_CONN to point to DEV db
- test few api endpoints and make sure the data is returned
branch | PR
https://github.com/kennethreitz/requests/issues/5065

Upgrade requests package to latest version 2.21.0

---

data/migrations/V0134__ofec_totals_combined_mv_exclude_sl.sql

- Resolves #[_3740_](https://github.com/fecgov/openFEC/issues/3740)
SLs are sort of a sub-schedule for form 3x and should not be includes in cycle totals. Currently there are 500+ SLs in ofec_totals_combined_mv.  This fix will exclude SLs from this mv.
1. Download the feature branch to local
2. Run migration file V0134 (or run invoke create_sample_db) to make sure migration files runs without error.
3. ofec_totals_combined_mv_tmp_hc was created on DEV for testing purpose.  Run these queries to compare two materialized views.
select *
from ofec_totals_combined_mv_tmp_hc
where committee_id = 'C00044842'
and cycle = 2014
union all 
select *
from ofec_totals_combined_mv
where committee_id = 'C00044842'
and cycle = 2014
select *
from ofec_totals_combined_mv_tmp_hc
where form_type = 'SL'; …

Exclude SLs from ofec_totals_combined_mv

---

tests/test_itemized.py
webservices/filters.py
webservices/utils.py

Added 
```python                
for value in include_list:
filters.append(column.match(value))
```
as well as similar code for `exclude_list` in `filters.py` to make sure literal field inputs were considered by `fulltext_filter`. Testing is ongoing.
- Resolves #3716 
Modify `parse_fulltext` definition to return search string with terms at most numbering what the user entered and includes only non-special characters.
- Anywhere fulltext filter fields are used
- See issue #3716 for full listing of application areas using fulltext fields for filtering
branch | PR
feature/3716-parse_fulltext-bug | [link](https://github.com/fecgov/openFEC/issues/3716)

fix parse_fulltext match

---

data/flyway/build.gradle

Snyk identified vulnerability:
> Medium severity vulnerability found in mysql:mysql-connector-java
> Description: Privilege Escalation
> Info: https://snyk.io/vuln/SNYK-JAVA-MYSQL-174574
> Introduced through: org.flywaydb:flyway-commandline@5.2.4
> From: org.flywaydb:flyway-commandline@5.2.4 > mysql:mysql-connector-java@8.0.12
- Resolves #3752 
add `exclude group: 'mysql', module: 'mysql-connector-java'` to `build.gradle`
(this also resolves the `High severity vulnerability found in com.google.protobuf:protobuf-java` addressed in #3743 
-  `flyway`
branch | PR
feature/3752-mysql-gradle-vulnerability-privilege-escalation | …

fix privilege escalation add exclude group mysql to build.gradle

---

webservices/common/models/itemized.py

in `/common/models/itemized.py`, there are places where `transaction_id` and 'back_reference_transaction_id` are incorrectly specified as `Integer`. To make the code consistent with other occurrences of these identifiers, as well as consistent with the db datatype, change to `String`.
- Resolves #3750
Change datatype for `transaction_id` and `back_reference_transaction_id` to `String`
-  `/schedule_e/`
- `/schedule_f/`
branch | PR
feature/3750-fix-transaction_id | [feature/3750-fix-transaction_id](feature/3750-fix-transaction_id)

fix tran_id and back_ref_tran_id type to String

---

endpoints_walk.py
requirements.txt
webservices/common/models/audit.py
webservices/common/models/base.py

Resolves #3404 
- Update Flask-SQLAlchemy to 2.4.0
- [This commit](https://github.com/pallets/flask-sqlalchemy/commit/3fec7535922e687e0518bdbfcd24b6389ab5c3af) changed the default behavior of `create_session` from returning a `SignallingSession` class to returning a session maker factory that takes a `class` argument. This PR changes our custom `RoutingSQLAlchemy` `create_session` logic to return a session maker factory that creates `RoutingSession`-type sessions.
- SQLAlchemy 2.3 no longer supports putting `table_args` in an inherited class and throws the error `sqlalchemy.exc.ArgumentError: Can't place __table_args__ on an inherited class with no table.`. The best solution is putting the `table_args` in the subclasses explicitly. (see …

Update Flask-SQLAlchemy to 2.4.0

---

requirements-dev.txt
requirements.txt
webservices/args.py
webservices/rest.py

fix race condition due to `webargs@0.18.0`. Upgrade to `webargs@5.3.1` (`requirements.txt`)
- Resolves #3642 
-  `requirements.txt`
- `args.py`

update webargs to 5.3.1 fix race condition

---

.circleci/config.yml
README.md
tasks.py

Resolves https://github.com/fecgov/openFEC/issues/3754. Prevents accidentally running migrations in environments that aren't ready for them during manual deploys
To run migrations with a manual deploy, run:
```	
invoke deploy --space dev --migrate-database
```
- By default, deploy task skips migrations
- Change Circle command to always run migrations
- Update docs
- Manually: I tested this with `invoke deploy --space dev` and `invoke deploy --space dev --migrate-database` 
- Circle: I tested a Circle build with a temporary change to the deploy rules
- Manual deploy
- Circle deploys  
https://github.com/fecgov/openFEC/pull/3325 Originally implemented `--skip-migrations` flag

Update deploy task to skip migrations by default

---

data/migrations/V0135__ofec_candidate_history_mv_update_cand_election_yr.sql

- Resolves #3736
Fix cand_election_yr in ofec_candidate_history_mv
the calculation here for the election_year is similar to the election_yr_to_be_included column in ofec_cand_cmte_linkage table, but not exactly the same.  
The purpose of election_yr_to_be_included is to calculated the election_cycle the cycle financial data belongs to and an odd year will be rounded up and folded into its even year cycle.  
Here the election_year is for the election year, an odd election year need to be preserved, separated from its even year cycle.
The calculation is based on the fec_election_yr, the cand_election_yr, the cycle length (6, 4, 2), the next_election 
Simple and straight foward rules first, followed by more complicated rules.  
cycles, election_years, election_districts, active_through
are …

fix cand election yr ofec candidate history mv

---

tests/test_itemized.py
webservices/exceptions.py
webservices/resources/sched_a.py
webservices/resources/sched_b.py

adding line_number validation code and add line_number back to sched_a secondary index list
- Resolves #3741
1. line_number validation code added to both sched_a and sched_b
2. unit tests updated
1. start local server and connect to stage db
./manage.py runserver
2. the local requests should give you error messages:
request:
http://127.0.0.1:5000/v1/schedules/schedule_b/?per_page=50&sort_null_only=false&sort_hide_null=false&api_key=DEMO_KEY&two_year_transaction_period=2018&two_year_transaction_period=2016&two_year_transaction_period=2014&line_number=F3X23
response:
{
"message": "Invalid line_number detected.",
"status": 400
}
request:
http://127.0.0.1:5000/v1/schedules/schedule_a/?per_page=50&sort_null_only=false&sort_hide_null=false&api_key=DEMO_KE …

adding line_number validation code

---

tests/test_candidates.py
webservices/args.py
webservices/common/models/candidates.py
webservices/docs.py
webservices/resources/candidates.py

- Resolves #3796 
Add `is_active_candidate` to /candidates/
- Filter by candidates not actively seeking office: http://localhost:5000/v1/candidates/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&election_year=2020&state=MN&office=S&sort=-first_file_date&per_page=30&page=1&is_active_candidate=false
- Allows us to add an active candidates filter to "All candidates" datatable   (https://www.fec.gov/data/candidates/)

Add 'is_active_candidate' to /candidates/

---

tests/test_utils.py
webservices/rest.py
webservices/utils.py

For security reasons, we do not want to show or hard code the api umbrella ip addresses in our code. 
- Add `trusted_proxy_ips` as an API environment variable in `stage` and `prod` spaces. 
- Assign the API umbrella ips to this new environment variable.
- Put splitting `env vars` into a function, add tests
- Split trusted proxies into a list
- Add handling for 403 forbidden errors when bypassing the api umbrella
Note# there is no api umbrella in `dev` space. requests directly hit the DB.
- Resolves #3757 
In rest.py, add a new constant `trusted_proxie_ips`. assign the  api umbrella proxie ips to this new variable.
- i did a manual deploy to `stage` space and test the `stage api` and `stage website` and make sure the endpoints return the data.
- Try …

Set trusted proxies as an API environment variable.

---

tests/integration/test_candidates.py

add integrated test(s) to aid in debugging `/candidates/` where number of candidates is not consistent across various access methods (related issue #3673)
- Resolves #3791
add integrated tests to `openFEC/tests/integration/test_integrated.py`
- `git checkout feature/3791-write-candidates-totals-test-case`
- `cd openFEC/`
- `pytest` (connect to `pg` if not already)--all tests should pass.
-  mainly tests, but work done in `test_integration.py` enables additional programmatic testing of other endpoints by importing similar functionality as `test_amendment_chain.py`
branch | PR
feature/other_pr | [[WIP] Update house candidate …

add test_candidate.py

---

webservices/resources/filings.py
webservices/tasks/download.py

This will fix Exported excel file was blank when form_type=RFAI
- Resolves https://github.com/fecgov/openFEC/issues/3799
modify tasks/download.py:
when form_type=RFAI, we need append form_type=FRQ for download url. same as api endpoint url.
1. get `cf env api` from dev space
export access_key_id="xxxxxxx"
export secret_access_key="xxxxxxx"
export bucket="xxxxxxx"
export region="xxxxxxx"
2. setup 4 terminals on local:
1)first terminal: Redis
`redis-server `
2)second terminal: Celery Worker
active virtual env
setup 4 env variables (see above)
`celery worker --app webservices.tasks --loglevel INFO `
3)Third terminal: openFEC (point dev DB)
active virtual env
setup 4 env variables (see above)
export SQLA_CONN=dev database
./manage.py runserver
4)Forth …

Fix download blank page bug for form_type=RFAI
