- tests/integration/test_candidates.py
- Resolves #3806 
Given base table candidate data, the list of candidates should be the same for `/candidates/`, `/candidates/totals/`, and `/elections/`
- Test coverage only
-  Test coverage for `/candidates/`, `/candidates/totals/`, and `/elections/`
> Add more candidate integrated tests

- data/migrations/V0140__fix_cand_election.sql
- tests/test_elections.py
- webservices/resources/elections.py
- webservices/resources/sched_a.py
Resolves https://github.com/fecgov/openFEC/issues/3709
Resolves https://github.com/fecgov/openFEC/issues/3823
Puerto Rico's house candidates (called "resident commissioners") have 4-year election cycles, unlike other house candidates that have 2-year cycles.
- Fix `candidate/id/totals` by using the new `candidate_election_duration` function that takes PR into consideration
- Drop unused `election_duration` database function
- Fix `/elections/` by adding handling for PR 4-year cycles
- Refactoring `/elections/`
- Drop/create `cfdm_test` and run `invoke create_sample_db` task to check migrations
-  point `class CandidateCommitteeTotalsHouseSenate` to ` __tablename__ = 'ofec_totals_candidate_committees_mv_lb_tmp'` 
- check totals for …
> Fix PR candidate totals on candidate and election profile pages

- webservices/resources/sched_a.py
- Resolves https://github.com/fecgov/fec-cms/issues/2983
Add contributor zip back to secondary index list
- http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&contributor_zip=20009&two_year_transaction_period=2020&two_year_transaction_period=2018&sort=-contribution_receipt_date&per_page=30 should **not** throw an error, while https://fec-dev-api.app.cloud.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&contributor_zip=20009&two_year_transaction_period=2020&two_year_transaction_period=2018&sort=-contribution_receipt_date&per_page=30 **does** throw an error
-  Receipts datatables
> Add contributor zip back to secondary index list

- jdbc_utils.py
- tasks.py
- tests/common.py
- tests/conftest.py
Resolves https://github.com/fecgov/fec-accounts/issues/182
- Remove username/password from migration url, pass as username/password parameters to prevent displaying password in URL
- Strip out username from postgres error messages, preserve Flyway-specific error messages because they don't print username and we need them for debugging
- Fail build when deploy task fails (it was failing silently with `return` and that made it look like the build passed when it really didn't. See http://docs.pyinvoke.org/en/1.2/api/exceptions.html#invoke.exceptions.Exit for info on the built-in "clean" exit without stack trace)
**Successful migration**
-  Set `FEC_MIGRATOR_SQLA_CONN_DEV`
- Target `dev` space
- Make sure you don't have any new migration files (you can check out this branch)
- Run `invoke …
> Remove credentials from migration url

- requirements.txt
- Possible resolution for #3840 
_Update celery and related packages._
- Install requirements with `pip install -r requirements.txt`
- Deploy to `dev`: `invoke deploy --space dev`
- Point your local CMS to `dev`, test a download
- Check for nightly refreshes
- Install requirements with `pip install -r requirements.txt`
- Set up celery/redis using the wiki instructions: https://github.com/fecgov/openFEC/wiki/Set-up-Redis,--Celery-on-local-and-test-the-downloads
- (optional) Set up elasticsearch locally 
- Test celery with a download from the front-end or schedule a refresh 
-  Downloads, reloading legal tasks, nightly refresh
> Update celery and related packages

- requirements.txt
- tests/test_swagger.py
OSV is a third party package we rely on for swagger validation. There was a breaking change few months ago  on OSV  package whose dependency package pathlib got updated/replaced with pathlib2 package that impacted swagger tests in openFEC repo.
- Resolves #3612
add the swagger tests back in `tests/test_swagger.py`.
add forked OSV package back in requirements.txt
- run `pytest` make sure all the python tests run OK.
> Add swagger tests back.

- tests/test_aggregates.py
- tests/test_candidates.py
- tests/test_committees.py
- tests/test_elections.py
- webservices/args.py
- Resolves https://github.com/fecgov/openFEC/issues/3686
Change default value of `election_full` to `True`
Counts should match for /candidates/ and /candidates/totals/: 
http://localhost:5000/v1/candidates/?election_year=2019&election_year=2020&office=P
should match or be very close to 
http://localhost:5000/v1/candidates/totals/?election_year=2020&office=P
(/candidates/totals/ rounds election years and /candidates/ doesn't, which is why I've included 2019)
http://localhost:5000/v1/candidates/?election_year=2019&election_year=2020&office=H
should match or be very close to 
http://localhost:5000/v1/candidates/totals/?election_year=2020&office=H
Following endpoints default to `election_full=True` if not specified:
`args.candidate_history`
- `/candidate/<candidate_id>/history/`
- …
> Change default value of election_full to True

- data/migrations/V0146__ofec_report_presidential_mv.sql
- data/migrations/V0147__ofec_report_house_senate_mv.sql
- data/migrations/V0148__ofec_report_pac_party_mv.sql
- webservices/common/models/reports.py
- webservices/docs.py
- webservices/schemas.py
House and Senate committee reports, presidential committee reports and PAC and party committee reports downloads do not include names, just IDs
so we need add committee_name column into csv download file.
- Resolves #[[3844]](https://github.com/fecgov/openFEC/issues/3844)
modify/create three report committee MV to add `committee_name` column:
a)ofec_reports_presidential_mv
b)ofec_reports_house_senate_mv
c)ofec_reports_pac_party_mv
1)api test locally
checkout branch, point to dev. 
modify models/reports.py:
ofec_reports_presidential_mv ==> ofec_reports_presidential_mv_jl
ofec_reports_house_senate_mv ==>ofec_reports_house_senate_mv_jl
ofec_reports_pac_party_mv ==>ofec_reports_pac_party_mv_jl
go to swagger under tag: **financial**
path: …
> Add committee_name into 3 committee reports MV and export files

- data/migrations/V0149__add_extension_unaccent.sql
- Resolves #3862
Install postgres extension "unaccent" for related tsvector work
- After download the branch and run migration file on your local machine, open the pgAdmin and connect to your local database.  Check the Exension unaccent is installed.
-  There is no impact to the API
branch | PR
> Add extension unaccent

- webservices/args.py
- webservices/resources/reports.py
Resolves #3785 
- Use API error instead of marshmallow error - marshmallow's built-in `ValidationError` was getting picked up by our generic `handle_exception` function that always throws a 500 error
- Clean up `/reports/<committee_type>/` code
**API**
- http://localhost:5000/v1/reports/pac-party/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&data_type=processed&two_year_transaction_period=2018&min_receipt_date=01%2F01%2F2017&max_receipt_date=12%2F31%2F2018&sort=-name&per_page=30&page=1 should now throw a 422 error
-  Sort still works: http://localhost:5000/v1/reports/pac-party/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&data_type=processed&two_year_transaction_period=2018&min_receipt_date=01%2F01%2F2017&max_receipt_date=12%2F31%2F2018&sort=-receipt_date&per_pa …
> Use API error instead of marshmallow error, mild refactor for /reports/

- tests/test_itemized.py
- webservices/args.py
- webservices/common/models/itemized.py
- webservices/resources/sched_a.py
- webservices/resources/sched_b.py
- Resolves #3841
Add org_type and designation to schedules A and B: filters are:
**Schedule A**
`recipient_committee_org_type`
`recipient_committee_designation `
**Schedule B**
`spender_committee_org_type`
`spender_committee_designation `
- point to `dev` database
**Leadership PACs**
- Schedule A: http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&two_year_transaction_period=2020&recipient_committee_designation=D&per_page=30
- Schedule B: http://localhost:5000/v1/schedules/schedule_b/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&two_year_transaction_period=2020&spender_committee_designation=D&per_page=30
**Lobbyist registrant PACs**
- Schedule A: …
> Add org_type and designation to schedules a and b

- jdbc_utils.py
- Resolves #3869
add more `postgresql@9.6` error codes, change default return message.
- set `FEC_MIGRATOR_SQLA_CONN_DEV`
- Change the `FEC_MIGRATOR_SQLA_CONN_DEV` to something that doesn't exist (you can test bad DB name, bad username, bad password)
- no username should be passed in any error messages
- for cases where the error message is not one explicitly listed in `jdbc_utils.py`, the full non-stripped error message should be displayed.
-  `flyway` migration, `dev`, `stg`, `prd` spaces
branch | PR
feature/other_pr | [https://github.com/fecgov/openFEC/pull/3827](https://github.com/fecgov/openFEC/pull/3827)
> Add postgres@9.6 login errors and change default return

- tests/test_aggregates.py
- webservices/resources/candidate_aggregates.py
- Resolves #[_3816_](https://github.com/fecgov/openFEC/issues/3816) ,  #[_3874_](https://github.com/fecgov/openFEC/issues/3874)
- API:  /schedules/schedule_a/by_state/by_candidate/ ,    ​/schedules​/schedule_a​/by_size​/by_candidate​/
- This PR mainly fixes two issues: 
1) When candidates have two elections within the same fec_election_year, current endpoints return with doubles totals.  Subquery is ran against cand_cmte_linkage_mv to produce a distinct set of (candidate_id, committee_id, fec_election_year, election_yr_to_be_included).  This will prevent the totals being counted twice when joining happens between aggregate tables and linkage_mv
2) When passing election_full=true, cycle=cand_election_year, current endpoints return with two entries per state, and two entries per size …
> Fix doubled SA aggregate totals: by_size_by_candidate/by_state_by_candidate

- package-lock.json
- package.json
- Resolves #3887 
- add `"lodash": "^4.17.13"` to `"devDependencies"` in `package.json`
- rebuild `package-lock.json` with `npm install`
- note  reported`lodash` vulnerability
-  note `lodash` vulnerability no longer appears
> upgrade lodash in package.json, rebuild package-lock.json

- data/migrations/V0155__ofec_candidate_history_mv_add_filter_columns.sql
- webservices/flow.py
- Resolves #[3912]
Add two columns fec_cycles_in_election and rounded_election_years to ofec_candidate_history_mv
Download the feature branch to the local machine, run create sample db script to 
1) Verify migration file execute successfully
2) Verify the two new columns fec_cycles_in_election and rounded_election_years had been added to the materialized view ofec_candidate_history_mv.
3) Review the materialized view refresh statement at the end of the create sample db process, make sure ofec_cand_cmte_linkage_mv is refreshed before ofec_candidate_history_mv.
-  
branch | PR …
> Add columns to ofec_candidate_history_mv to help filtering "valid" fec_election_year

- data/migrations/V0156__ofec_agg_coverage_date.sql
- Resolves #[3915]
Fix ofec_agg_coverage_date_mv to remove double entries from committee_id/fec_election_yr at the turn of 2002/2003
Download branch feature/3915-fix-double-rows-in-ofec_agg_coverage_date_mv to local machine, run migration file V0156, make sure migration file executed successfully.
Run pytest on local machine, make sure no code break.
A tmp MV public.ofec_agg_coverage_date_mv_tmp had been created in DEV database.  Run the following query to make sure no double rows exist anymore.
select committee_id, fec_election_yr, count(*)
from ofec_agg_coverage_date_mv_tmp
-- from ofec_agg_coverage_date_mv -- compare to the original MV
group by committee_id, fec_election_yr
having count(*) > 1;
None
List related PRs …
> fix double rows in ofec_agg_coverage_date_mv

- data/migrations/V0158__ofec_cand_cmte_linkage_mv_exclude_leadership_PAC.sql
- Resolves #[3907](https://github.com/fecgov/openFEC/issues/3907)
The definition of ofec_cand_cmte_linkage_mv had been updated to exclude cmte_dsgn = 'D' committees in the calculation of election_yr_to_be_included column, which is the base for calculating candidate totals. 
To partially solve issue #3925, this PR also exclude committees that are not candidate committees
but have cmte_dsgn in P/A (in the calculation of totals in children MVs) in the calculation of election_yr_to_be_included.
SQLAlchemy code had been reviewed, all code that used to calculate candidate totals had include the restriction of only use committees that have cmte_dsgn of P/A.
- Download the branch to local machine and make sure migration file executed successfully.  
- A temporary MV named …
> Exclude leadership PAC from calculation of election_yr_to_be_included

- webservices/common/util.py
- webservices/rest.py
Resolves #3876 
- Add security-related headers to all responses (keep `Access-Control-Allow-Origin: *` header unchanged because this is a public API). See original issue for background information.
- Add endpoint for Content Security Policy (CSP) violation reporting
- Currently deployed to stage: https://api-stage.open.fec.gov/developers/
- run the API locally, check swagger UI browser errors
- `curl -I "http://localhost:5000/v1/committees"` to check headers
- I pushed a deploy to `stage` with Circle (as of 8/28)
- Test API for console errors
- Curl API to check headers
- Run scan like https://securityheaders.com/ and https://csp-evaluator.withgoogle.com/ results
- Make sure CMS can still access what it needs
- For developers, open up your inspector console and look for errors like this: …
> Add security-related headers

- data/migrations/V0159__ofec_candidate_totals_mv_include_all_F3_F3P_F3X_exclude_non_candidate_cmtes.sql
- data/migrations/V0160__ofec_totals_house_senate_mv_include_all_F3_F3P_F3X_exclude_non_H_S_candidate_cmtes.sql
- Resolves #[3925](https://github.com/fecgov/openFEC/issues/3925): update ofec_candidate_totals_mv and ofec_totals_house_senate_mv to include all F3/F3P/F3X and exclude non_candidate P/A committees
Download the branch to local machine.  
Run migration to make sure both migration files executed successfully.
A _tmp version of these two MV had been created in DEV database:
ofec_candidate_totals_mv_tmp
ofec_totals_house_senate_mv_tmp
To test API locally, on local machine, update the following two model files:
**webservices/common/models/candidates.py**
**webservices/common/models/totals.py**
**To point to the _tmp MVs**
Here are two examples of Candidate committees files incorrect F3/F3P/F3X forms so their totals are inconsistent in the 3 end-points stated in the ticket:
**H8CA35115, 2018, …
> Fix inconsistent totals derived from misfiled F3* data

- tests/test_candidates.py
- webservices/resources/candidates.py
- Resolves https://github.com/fecgov/fec-cms/issues/3163
**Fix future candidate history query**
```
-- Before
SELECT * 
FROM ofec_candidate_history_mv 
LEFT OUTER JOIN ofec_candidate_flag_mv AS ofec_candidate_flag_mv_1 
ON ofec_candidate_flag_mv_1.candidate_id = ofec_candidate_history_mv.candidate_id 
WHERE ofec_candidate_history_mv.candidate_id = 'S2MA00170' 
--
--Extra filter on future two-year-period:
--
AND ofec_candidate_history_mv.two_year_period = 2024 
--
AND ofec_candidate_history_mv.candidate_election_year % 2 + ofec_candidate_history_mv.candidate_election_year = 2024
-- After
SELECT * 
FROM ofec_candidate_history_mv 
LEFT OUTER JOIN ofec_candidate_flag_mv AS ofec_candidate_flag_mv_1 
ON ofec_candidate_flag_mv_1.candidate_id = ofec_candidate_history_mv.candidate_id 
WHERE …
```
> [MERGE WITH GIT FLOW] Fix candidate 404

- .circleci/config.yml
- README.md
- requirements-dev.txt
- requirements.txt
- runtime.txt
- Resolves #3951 
Updates `openFEC` to use `python@3.7.4` throughout the repo instead of `python@3.6.4` (`config.yml`) and `python@3.6.9` (`runtime.txt`)
- `api`, `api.app`
> update python version to 3.7.4

- data/migrations/V0165__ofec_sched_a_agg_state_mv.sql
- manage.py
- webservices/flow.py
- Resolves https://github.com/fecgov/openFEC/issues/3970
/schedules/schedule_a/by_state/by_candidate slowness problem
Originally, this endpoint use a view public.ofec_sched_a_agg_state_vw to sum up all the non-real state as 'OT'
Although views can not have indexes, they will take advantage from the indexes of its base tables. 
However, the original query use a subquery and a view composed of multiple base tables and database optimizer somehow decided not to use the view's base tables' indexes and cause the slowness.
We can choose to re-write the query or create a MV to replace the view.
There are more than one endpoints share the same function in resource file to generate final query, it would be less impact to create a MV to replace the view.
Also for better readability.
Since this is a …
> Add ofec_sched_a_agg_state_mv to solve the slowness of ScheduleAByStateCandidate

- package.json
- Resolves #3921 
_We do not appear to be using this package in our development. It is not imported into our eslint plugins, so we are not enabling it. See eslint-plugin-no-unsanitized [docs](https://github.com/mozilla/eslint-plugin-no-unsanitized#usage)._
Once the patch for this vulnerability is pushed into a new release, we can think about re-adding and enabling this plugin.
-  Should not effect anything as we were not enabling it for eslint
> Remove eslint-plugin-no-unsanitized from package due to vulnerability

- requirements.txt
- Resolves #3776 
replace forked version of `apispec` with `apispec@0.39.0`. 
- checkout `feature/3776-update-apispec`
- in a clean `python@3.7.4` environment:
- start postgres
- `pytest`
- from `openFEC`: `snyk test --file=requirements.txt`
- run local api, check that ui looks "normal"
> update apispec to nonforked version

- webservices/resources/sched_e.py
- Resolves #3948: Use actual counts for Schedule E efile endpoint. 
The API will use an estimated count if the estimate is greater than the threshold (defaults to 500K.) Because the estimate in this case is way off (in our example, 341,452,204 when it should be 13,227) and the Schedule E efile table isn't very big (currently 13,227 rows), we're telling the API using the **exact** count of the query. 
- Check out this branch, query http://localhost:5000/v1/schedules/schedule_e/efile/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&data_type=efiling&is_notice=true&sort=-expenditure_date&per_page=30&page=1
- Counts are correct 
-  Schedule E raw datatable …
> Use actual counts for Schedule E efile endpoint

- webservices/legal_docs/current_cases.py
- webservices/utils.py
Resolves #3985 
- Add retries to elasticsearch connection for one MUR that fails to load with some queries
- Fix unpublish logic for "all murs"
I couldn't figure out how to replicate this issue locally. The query to elasticsearch was timing out, so I increased the timeout to 30 seconds and manually deployed to `dev`. I entered a follow-up issue to research elasticsearch performance: https://github.com/fecgov/openFEC/issues/3999
These won't load on production, but now load with a manual deploy to `dev`:
- https://api.open.fec.gov/v1/legal/search?hits_returned=12&type=murs&from_hit=20&q=%22foreign+national%22+AND+%22ssf%22&sort=case_no&api_key=DEMO_KEY
- https://api.open.fec.gov/v1/legal/search?hits_returned=20&type=murs&from_hit=10&q=%22foreign+national%22+AND+%22ssf%22&sort=case_no&api_key …
> Add retries to elasticsearch connection, fix unpublish logic for "all murs" reload

- tests/test_committees.py
- webservices/args.py
- webservices/resources/committees.py
Resolves #4007: Add designation filters to committee history endpoints
- Add `designation` filter to resource `committees.CommitteeHistoryView`
- Add automated tests
- Clean up awkward test syntax
- Test designation filters for the following endpoints: 
example: http://localhost:5000/v1/candidate/S2MA00170/committees/history/?designation=P&designation=A
example: http://localhost:5000/v1/candidate/S2MA00170/committees/history/2018/?designation=P&designation=A
- Run local CMS, point to local API, test the candidate/committee profile pages:
example: http://localhost:8000/data/candidate/S2MA00170/?cycle=2018&election_full=true
example: http://localhost:8000/data/candidate/S2MA00170/?cycle=2018&election_full=true&tab=about-candidate
List general components of the application that this PR will …
> Add designation filters to committee history endpoints

- webservices/common/views.py
- Resolves #3996
Increase maximum number of committeeIDs for itemized resource tables
-  Make sure transaction endpoints return results for up to 10 committee IDs
http://127.0.0.1:5000/v1/schedules/schedule_a/?api_key=&sort_hide_null=false&sort_nulls_last=false&data_type=processed&committee_id=C00031781&committee_id=C00107391&committee_id=C00139998&committee_id=C00171538&committee_id=C00187435&committee_id=C00188888&committee_id=C00250191&committee_id=C00329706&committee_id=C00364091&committee_id=C00401224&committee_id=C00412304&committee_id=C00547679&sort=-contribution_receipt_date&per_page=30
- Make sure transaction endpoints return validation error message for **over** 10 committee IDs
http://localhost:5000/v1/schedules/schedule_a/?api_key=28Y8q8XFocq8yhKfBzzhUJXjFj2JHCZzIv4P2KIK&sort_h …
> Increase maximum number of committeeIDs to 10

- tests/test_aggregates_by_committee_id.py
- webservices/args.py
- webservices/docs.py
- webservices/resources/aggregates.py
- webservices/resources/aggregates_by_committeeID.py
- webservices/rest.py
1. This ticket will add filter by one or more committee ID (the filer ID) on these 9 endpoints:
/schedules/schedule_a/by_size/
/schedules/schedule_a/by_state/
/schedules/schedule_a/by_zip/
/schedules/schedule_a/by_employer/
/schedules/schedule_a/by_occupation/
/schedules/schedule_b/by_recipient/
/schedules/schedule_b/by_recipient_id/
/schedules/schedule_b/by_purpose/
/schedules/schedule_e/by_candidate/
2. These 9 endpoints are deprecated: 
/committee/<committee_ID>/schedules/schedule_a/by_employer/
/committee/<committee_ID>/schedules/schedule_a/by_occupation/
/committee/<committee_ID>/schedules/schedule_a/by_size/
/committee/<committee_ID>/schedules/schedule_a/by_state/
/committee/<committee_ID>/schedules/schedule_a/by_zip/
/committee/<committee_ID>/schedules/schedule_b/by_purpose/ …
> Add filter by committee_id on aggregate schedule A, B, E and Deprecate 9 endpoints 

- requirements.txt
- Resolves #4026 
- bumps version of Flask from 1.0.2 to 1.1.1 in requirements.txt
- check out this branch
- pip install -r requirements.txt
- pytest
- run local api and test endpoints
Updates Flask with non-breaking changes.
> bump flask 1.0.2-->1.1.1

- data/migrations/V0168__add_filing_type_to_filings_all_mv.sql
- data/migrations/V0169__add_cycles_has_reports_to_ofec_committee_history_mv.sql
- Resolves #4034 
Add cycles_has_financial and cycles_has_activity columns in ofec_committee_history_mv
Add form_category in ofec_filings_all_mv and updated most_recent for F13.
There changes will simplify API/front-end calculation.
Download the branch to local machine, execute invoke create_sample_db to make sure migration files executed successfully.
There are no changes in MV dependencies therefore no need to update manage.py and flow.py
-  These are new columns, the APIs that would utilize these new columns are implemented in issue #4016 
A tmp version of these two updated MVs are created in DEV for viewing.
ofec_committee_history_mv_tmp_jj  and ofec_filings_all_mv_tmp_jj 
two example committees are:
C00570978 (a …
> Add columns to committee_history_mv and filings_all_mv to help filtering to display cycles with either financial reports or with activity.

- tests/integration/test_totals.py
- Resolves #[_4027_](https://github.com/fecgov/openFEC/issues/4027)
- Integration tests are added for committee and candidate financial summary. 
- For committee financial summary,  testing scenario when presidential committee files F3x besides F3P
- For candidate financial summary,  testing scenario when candidate's other authorized committee files on F3
-Download feature branch, 
-Run pytest
> Add test coverage for committee financial summary

- webservices/resources/legal.py
Resolves https://github.com/fecgov/openFEC/issues/4028
- 8a46606b2941140e1dd9b18c7438bad72c46b407: Modify the `generic_query_builder` to use the logic in the other searches - only add the query string if it's provided. 
- a0bd35d49717b5b6ebae038c45b65089c1409418: Refactor the other query builders to use the shared  `generic_query_builder` as the base for queries
- Either manually deploy this branch to `dev` or:
- Load statutes and/or regulations into your local elasticsearch https://github.com/fecgov/openfec#create-index-for-current-legal-documents-excludes-archived-murs
- Do a default query with no parameters: https://fec-dev-api.app.cloud.gov/v1/legal/search or localhost:5000/v1/legal/search
- All statutes and regulations should be returned, like other legal docs
List general components …
> Default statutes and regulations search to return all results

- tests/test_itemized.py
- webservices/args.py
- webservices/resources/sched_e.py
- Resolves #4005 
- adds `candidate_id` in `args.py` and `sched_e.py`
- fixes PEP8 style complaints for whitespaces
- pytest
- run local api/swagger-ui and check that /schedules/schedule_e/efile/ has candidate_id filter and that using the filter returns expected results
-  /schedules/schedule_e/efile/ endpoint
> add candidate_id filter to /schedules/schedule_e/efile/

- tests/test_itemized.py
- webservices/args.py
- webservices/common/models/itemized.py
- webservices/docs.py
- webservices/resources/sched_e.py
Make `/schedules/schedule_e/` api endpoint filter on`filing_date` and `dissemination_date`.
- Resolves https://github.com/fecgov/openFEC/issues/3817
- In models/itemized.py :  map the new`filing_date`column  
- In resources/sched_e.py, ScheudleE class : add `filing_date` and `dissemination_date` as range filters (min/max) 
-  In test_itemized.py : add python tests to the date range filters
- run `pytest` make sure all tests PASS
- export `SQLA_CONN` to  point `dev` DB
- start server
- test`filing_date` and `dissemenation_date` filters in `schedules/schedule_e` endpoint
- example:
Dissemination Date: 
http://localhost:5000/v1/schedules/schedule_e/?max_dissemination_date=2019-10-29&sort_null_only=false&sort=-expenditure_date&sort_hid …
> add sche_e processed filters

- requirements-dev.txt
- requirements.txt
- Resolves #4044
- change `elasticsearch==5.5.1` to `elasticsearch==5.5.3` in `requirements.txt`
- add `pip-tools==4.2.0` to `requirements-dev.txt` (for `pip-compile`)
- check out this branch
- `pytest`
- @jason-upchurch to deploy to `dev` for testing (e.g., https://dev.fec.gov/data/legal/advisory-opinions/)
-  just dependency files, but work is needed to incorporate `pip-compile` into workflow
> update elasticsearch and add pip-tools

- data/migrations/V0173__add_most_recent_to_ofec_sched_e_mv.sql
- Resolves #[4056]
Add most_recent column to ofec_sched_e_mv to support added filters on most_recent in /schedules/schedule_e
- download the branch to local machine and run flyway migration and/or createSampleDB.  Make sure the migration file executed successfully.  
- A tmp version of the updated MV (ofec_sched_e_mv_tmp_jj) had been created in DEV database
Query some 24/48 hour notice with high number of amendment to see if the most_recent flag are set right.
Some examples as followed:
-- --------------
-- F24
-- --------------
select * from ofec_processed_financial_amendment_chain_vw where cand_cmte_id = 'C00662312' and rpt_yr = 2018 and form = 'F24'
/*
"C00662312";2018;"48";"N";"2018-09-07";1260479;1260479;"F24";1335535;"{1260479}" …
> Add_most_recent_to_ofec_sched_e_mv

- tests/test_counts.py
- tests/test_itemized.py
- tests/test_utils.py
- webservices/common/counts.py
- webservices/common/views.py
- webservices/resources/aggregates_by_committeeID.py
- webservices/resources/elections.py
- webservices/resources/filings.py
- webservices/resources/sched_e.py
- webservices/tasks/download.py
Resolves #4071
- Update downloads to check for exact counts
- Clean up tests
- Modify count logic to handle exact or estimated counts. Indicate whether counts are estimates for better testing and for future work: https://github.com/fecgov/openFEC/issues/4003
- Add test coverage for count logic
- Get downloads working locally: https://github.com/fecgov/openFEC/wiki/Set-up-Redis,--Celery-on-local-and-test-the-downloads
- Run your local CMS and point to your local API
- Test downloading all raw IEs: http://localhost:8000/data/independent-expenditures/?data_type=efiling&is_notice=true . You shouldn't get an error message like you do on production.
- Test other downloads
- Test estimated and exact counts (under and over 500K)
List general components of the application …
> Update downloads to check for exact counts, refactor count logic

- tests/test_itemized.py
- webservices/args.py
- webservices/common/models/itemized.py
- webservices/docs.py
- webservices/resources/sched_e.py
- webservices/utils.py
Add `most_recent` filter to the `schedules/schedule_e/` endpoint 
- Resolves #4058 
1. Map `most_recent` DB column in SE model, resource, args files
2. Add python test case to the `most_recent` filter 
- checkout branch feature/4058-sched_e_most-recent-filter
- export SQLA to dev db
- start server
-  test the `schedules/schedule_e` endpoint with most_recent filter
- examples:
http://127.0.0.1:5000/v1/schedules/schedule_e/?sort_null_only=false&sort=-expenditure_date&committee_id=C00483693&sort_nulls_last=false&per_page=20&most_recent=false&sort_hide_null=false
http://127.0.0.1:5000/v1/schedules/schedule_e/?sort_null_only=false&sort=-expenditure_date&committee_id=C00483693&sort_nulls_last=false&per_page=20&most_recent=true&sort_hide_null=false
List …
> Add most_recent filter to sched_e endpoint

- tests/test_spending_by_others.py
- webservices/args.py
- webservices/common/models/aggregates.py
- webservices/docs.py
- webservices/resources/aggregates.py
- webservices/rest.py
- webservices/schemas.py
The current endpoint:  /committee/{committee_id}/electioneering/by_candidate/ filter by committee_id not work.
- Resolves [#[_4066_]](https://github.com/fecgov/openFEC/issues/4066)
1. we create a new endpoint: **/electioneering/aggregates/**
based on same **ofec_electioneering_aggregate_candidate_mv**
and make all filters work as expected.
2. to do list: create a separated issue to remove (or deprecated ? don’t think any api user is using current one, because filter not work properly)current endpoint.
/committee/{committee_id}/electioneering/by_candidate/
3. change cms code to use /electioneering/aggregates/?committee_id={committee_id}
2) dev db
3) pytest
4) ./manage.py runserver
Test 1: compare current and new endpoint filter by …
> Add new EC endpoint /electioneering/aggregates/.

- README.md
`swagger-tools` removed from global install per #4109 and #4110. This PR cleans up the `openFEC` documentation.
> Remove reference to swagger-tools

- requirements.txt
- tasks.py
Update the pkg in requirements.txt file.
- Resolves #4076 
Update python-datautil to v2.8.1
Update icalendar to v4.0.2
Update smart_open to v1.8.0
- create a new python virtual env
- run `pip install -r requirements.txt` and `pip install -r requirememnts-dev.txt`
- run `pytest`
- test /dates/calendar-dates/export/  api endpoint:
Example 1 with `min_start_date`:
http://127.0.0.1:5000/v1/calendar-dates/export/?per_page=20&sort=-start_date&sort_null_only=false&renderer=csv&page=1&sort_nulls_last=false&sort_hide_null=false&min_start_date=12%2F26%2F2019
Example 2 with `min_end_date`:
http://127.0.0.1:5000/v1/calendar-dates/export/?per_page=20&sort=-start_date&sort_null_only=false&renderer=csv&page=1&sort_nulls_last=false&min_end_date=12%2F26%2F2019&sort_ …
> upgrade smart open related pkgs

- data/migrations/V0176__remove_null_from_ofec_committee_history_mv.sql
- tests/integration/test_committees.py
- Resolves #[_4126_](https://github.com/fecgov/openFEC/issues/4126)
_cycles_has_activity is an array column in ofec_committee_history_mv to meet  front-end's need.  The value is from f_rpt_or_form_sub.rpt_yr which may contain nulls, so filter is added to remove the nulls_
1. download feature branch.
2. run flyway migration on local cfdm_test database (run create_sample_db if you prefer to start 
from the version 0001 of migration files).  After migration is finished, run this query to compare:
select cycles_has_activity from ofec_committee_history_mv where committee_id='C00140590'
Before:
[1982, 1984, 1986, 1988, 1990, 1992, 1994, 1996, 1998, 2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020, NULL]
After:
[1982, 1984, 1986, 1988, 1990, 1992, 1994, 1996, 1998, 2000, 2002, …
> Remove nulls from cycles_has_activity in ofec_committee_history_mv

- data/migrations/V0178__add_candid_to_ofec_filings_all_mv.sql
- Resolves #[_4157_](https://github.com/fecgov/openFEC/issues/4157)
- This PR refactor ofec_filings_all_mv to display filings from unverified candidates on Filings webpage
- Because unverified candidates are not included ofec_candidate_history_mv,  so ofec_filings_all_mv.candidate_id is switched to get value from disclosure.f_rpt_or_form_sub.
`CASE WHEN upper(substr(filing_history.cand_cmte_id,1,1)) IN ('H','S','P') THEN filing_history.cand_cmte_id
ELSE NULL
END AS candidate_id`
https://github.com/fecgov/openFEC/blob/feature/4157-filling-from-unverified-cand/data/migrations/V0178__add_candid_to_ofec_filingsd_all_mv.sql#L13
original code: 
```
select 
cand.candidate_id,
.....
LEFT JOIN ofec_candidate_history_vw cand
```
1.  Download feature branch and run `pytest`
2. …
> Make filings from unverified candidates available on filings webpage

- README.md
- runtime.txt
- Resolves #4160
Fix python runtime version. Only specify major python version in runtime.txt  - python buildpacks available only seem to include the most recent two minor versions.
Example error message upon build:
```
-----> Supplying Python
**ERROR** Could not install python: no match found for 3.7.4 in [2.7.16 2.7.17 3.5.7 3.5.9 3.6.9 3.6.10 3.7.5 3.7.6 3.8.0 3.8.1]
Failed to compile droplet: Failed to run all supply scripts: exit status 14
Exit status 223
```
- Can only test with a manual deploy - only test with a deploy to `develop` space please :) Just check out this branch, target the dev space, and do a manual deploy.
```
cf target -s dev
invoke deploy --space dev
```
-  Deployments to cloud.gov
List related PRs …
> [HOTFIX - MERGE WITH GIT FLOW] Fix python runtime version

- data/migrations/V0179__update_ofec_candidate_history_mv.sql
- Resolves #4156
Missing candidate_election_yr 2018 in ofec_candidate_history_mv for H6MD08549
The main driver for materialized view ofec_candidate_history_mv is disclosure.cand_valid_fec_yr, which has the correlation of fec_election_yr and cand_election_yr.  
The original problem we discovered was that the fec_election_yr and cand_election_yr correlation are incorrect in a quite a few data
-- 
The first major change of ofec_candidate_history_mv was documented in migration file V0135/V0137 (to solve issue #3736 with PR #3763 )
In previous version described above, we assume the overall cand_election_yr in disclosure.cand_valid_fec_yr for a candidate is correct,  just the correlation on fec_election_yr and cand_election_yr are often mismatched due to the way this table is populated. …
> fix Missing candidate_election_yr 2018 in ofec_candidate_history_mv for H6MD08549

- data/migrations/V0180__add_PRES_2016_2020_tables.sql
- Resolves #4168
Create the 18 base tables contains data for supporting presidential map 2016 and 2020
- download this branch to local server.  Run flyway migrate (or create_sample_db).  Make sure migration finish successfully.  
log into cfdm_test, make sure the following tables created:
pres_ca_cm_sched_a_join_16
pres_ca_cm_sched_a_join_20d
pres_ca_cm_sched_link_sum_16
pres_ca_cm_sched_link_sum_20d
pres_ca_cm_sched_state_16
pres_ca_cm_sched_state_20d
pres_f3p_totals_ca_cm_link_16
pres_f3p_totals_ca_cm_link_20d
pres_nml_ca_cm_link_16
pres_nml_ca_cm_link_20d
pres_nml_f3p_totals_16
pres_nml_f3p_totals_20d
pres_nml_form_3p_16
pres_nml_form_3p_20d
pres_nml_sched_a_16
pres_nml_sched_a_20d
pres_nml_sched_b_16
pres_nml_sched_b_20d
- The tables were already created in all databases so we can …
> Create base tables to support data for presidential map 2016 and 2020

- .circleci/config.yml
- Resolves issue found in testing
Circle needs the `pytest`-related packages in `requirements-dev.txt` to run tests. It was relying on cached packages previously.
- Easiest to test in CircleCI. Rebuilding `develop` (or any branch) in Circle without cache will fail  because it can't find files for `pytest`:
https://circleci.com/gh/fecgov/openFEC/2212
```
Traceback (most recent call last):
File "/home/circleci/repo/venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 377, in _getconftestmodules
return self._path2confmods[path]
KeyError: local('/home/circleci/repo/tests')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/circleci/repo/venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 408, in …
```
> Install packages for pytest in Circle

- data/migrations/V0184__add_ofec_presidential_summary_vw.sql
- tests/factories.py
- tests/test_presidential.py
- webservices/common/models/presidential.py
- webservices/resources/presidential.py
- webservices/schemas.py
- Partial resolution for #4178 
Make endpoint `/presidential/financial_summary/`
- `export FEC_FEATURE_PRESIDENTIAL=True`
- Change `PresidentialSummary` tablename to `'ofec_presidential_financial_summary_vw_lb'`
**All:** 
- http://localhost:5000/v1/presidential/financial_summary
**Candidate ID:** 
- http://localhost:5000/v1/presidential/financial_summary/?candidate_id=P00000001
- http://localhost:5000/v1/presidential/financial_summary/?candidate_id=P00009621
**Election_year:**
- http://localhost:5000/v1/presidential/financial_summary/?election_year=2020
- Test migration with 
```
flyway migrate
```
- Presidential map data, right-hand …
> [V0184] Make endpoint /presidential/financial_summary/

- requirements.txt
- Resolves #4193 
Pin werkzeug version
We’re bringing in `Werkzeug>=0.15` from Flask==1.1.1, but `Werkzeug==1.0.0` went live today with breaking changes
- Manual deploy to `dev` or fresh `pip install -r requirements.txt` and run the app
-  `werkzeug` is part of Flask's internals - see more info about `ProxyFix` here: https://github.com/pallets/werkzeug/blob/1a02200528b19bbca5d2597f77d50933bdb60294/src/werkzeug/middleware/proxy_fix.py#L27
https://github.com/fecgov/openFEC/pull/1481
> [HOTFIX][MERGE WITH GIT FLOW] Pin werkzeug version

- data/migrations/V0185__add_ofec_presidential_by_size_vw.sql
- tests/factories.py
- tests/test_presidential.py
- webservices/args.py
- webservices/common/models/presidential.py
- webservices/docs.py
- webservices/resources/presidential.py
(national map circle per candidate):
(view on DISCLOSURE.PRES_CA_CM_SCHED_A_JOIN_20D / _16
Filter: candidate_id, election_year
- Resolves part of [#4177](https://github.com/fecgov/openFEC/issues/4177)
- run this cmd : `export FEC_FEATURE_PRESIDENTIAL=True`
- Change `PresidentialBySize` tablename to `'ofec_presidential_by_size_vw_jl'`
(no filter)
http://127.0.0.1:5000/v1/presidential/contributions/by_size/?per_page=100&sort_hide_null=false&sort_nulls_last=false&sort=size&sort_null_only=false&page=1
(filter: candidate_id)
http://127.0.0.1:5000/v1/presidential/contributions/by_size/?per_page=20&sort_hide_null=false&sort_nulls_last=false&sort=size&candidate_id=P80001571&sort_null_only=false&page=1
(filter: candidate_id, election_year) …
> [V0185]Feature/4170 add endpoint presidential by size

- data/migrations/V0186__add_ofec_presidential_coverage_date_vw.sql
- tests/factories.py
- tests/test_presidential.py
- webservices/common/models/presidential.py
- webservices/resources/presidential.py
- webservices/schemas.py
- Resolves #4178
Add `/presidential/coverage_end_date/`
- `export FEC_FEATURE_PRESIDENTIAL=True`
- Change `PresidentialCoverage` tablename to `'ofec_presidential_coverage_date_vw_lb'`
**All:** 
- http://localhost:5000/v1/presidential/coverage_end_date
**Candidate ID:** 
- http://localhost:5000/v1/presidential/coverage_end_date/?candidate_id=P00009621
**Election_year:**
- http://localhost:5000/v1/presidential/coverage_end_date/?election_year=2020
- Test migration with 
```
flyway migrate
```
-  Presidential map data
#4185
#4181
#4189
#4190
> [V0186] Add /presidential/coverage_end_date/

- webservices/common/models/presidential.py
- Resolves #4204
Add missing fields to financial summary: `cash_on_hand_end` and `federal_funds`
- Run this branch
- run: `export FEC_FEATURE_PRESIDENTIAL=true`
- Go to  http://localhost:5000/v1/presidential/financial_summary
- Check for `cash_on_hand_end` and `federal_funds`
-  Presidential map financial summary
> Add missing fields to financial summary

- tests/test_itemized.py
- webservices/args.py
- webservices/docs.py
- webservices/resources/sched_e.py
- Resolves #4208
Update `most_recent` filters to always include null values
- Checkout this branch, point to any database
- Schedule E and Schedule E efile should behave this way:
- When `most_recent` isn't specified, show all (matches current behavior)
http://localhost:5000/v1/schedules/schedule_e/
http://localhost:5000/v1/schedules/schedule_e/efile
- When `most_recent=true`, show `true` and `null` values:
http://localhost:5000/v1/schedules/schedule_e/?most_recent=true
http://localhost:5000/v1/schedules/schedule_e/efile/?most_recent=true
- When `most_recent=false`, show `false` and `null` values:
http://localhost:5000/v1/schedules/schedule_e/?most_recent=false
http://localhost:5000/v1/schedules/schedule_e/efile/?most_recent=false
List general components of the application that this PR …
> Update 'most_recent' filters to always include null values

- webservices/common/models/presidential.py
- Partial resolution for #4219
Add `transfers_from_affiliated_committees` to output for `/presidential/financial_summary/` endpoint 
- Make sure you have `FEC_FEATURE_PRESIDENTIAL` set to `True`
- Run this branch
- Confirm that http://localhost:5000/v1/presidential/financial_summary/?page=1&sort=-net_receipts&sort_nulls_last=false&sort_hide_null=false&sort_null_only=false&per_page=20 has `transfers_from_affiliated_committees`
-  Presidential map, transfers in
> Add 'transfers_from_affiliated_committees' field to output

- requirements.txt
- Resolves #4149
Update gunicorn to `19.10.0`. See https://snyk.io/vuln/SNYK-PYTHON-GUNICORN-541164
- Gunicorn is only used in production, so you need to deploy to `dev` to test
-  More info about gunicorn: https://gunicorn.org/
- See https://github.com/fecgov/openFEC/blob/develop/bin/run.sh
> Update gunicorn to 19.10.0

- data/migrations/V0187__add_F24_version.sql
- Resolves #4200
- Refactor ofec_filings_all_mv to include logic to calculate most_recent for F24, by left join to  
ofec_filings_amendments_all_vw. 
- Modified parts in migration file:
https://github.com/fecgov/openFEC/pull/4217/files#diff-9be1212e70aaeb43f6f7e935f2223a2aR72
https://github.com/fecgov/openFEC/pull/4217/files#diff-9be1212e70aaeb43f6f7e935f2223a2aR80
- download feature branch to local
- run pytest to make sure all tests passed, and migration runs well
- To test data, make a change to this model file:  models/filings.py, then run api locally
class Filings(FecFileNumberMixin, CsvMixin, db.Model):
__tablename__ = 'ofec_filings_all_mv_tmp_hc'
Local: most_recent=true
http://127.0.0.1:5000/v1/filings/?sort_nulls_last=false&sort_hide_null=false&per_page=20&committee_id=C00709691&so …
> correct the value of most_recent for F24 

- webservices/spec.py
Resolves issue found in testing. We should hide the presidential section of the docs until the feature is turned on.
Empty "presidential" section of docs
"Presidential" is hidden
- `unset FEC_FEATURE_PRESIDENTIAL` env var
- Check out this branch and run the app
- Go to swagger docs
- Make sure "Presidential" section doesn't show in API docs
-  Swagger docs
> Conditionally hide presidential section from docs

- tests/test_spending_by_others.py
- webservices/args.py
- webservices/resources/aggregates.py
- webservices/rest.py
- webservices/schemas.py
The current endpoint: /committee/{committee_id}/communication_costs/by_candidate/ filter by committee_id not work.
- Resolves [https://github.com/fecgov/openFEC/issues/4243](https://github.com/fecgov/openFEC/issues/4243)
Create a new endpoint: **/communication_costs/aggregates/**
based on same **ofec_communication_costs_aggregate_candidate_mv**
and make all filters work as expected.
2) dev db
3) pytest
4) ./manage.py runserver
Test 1: check filter by committee_id
on prod: **/committee/{committee_id}/communication_costs/by_candidate/**
return CC spending for all committee : 1265 rows (filter by committee_id not work)
https://api.open.fec.gov/v1/committee/C70000112/communication_costs/by_candidate/?cycle=2014&election_full=false&api …
> Add endpoint communication_costs/aggregates/

- data/migrations/V0189__ofec_candidate_totals_detail_mv.sql
- Resolves #[4214]
Candidate totals for H6MD08549 is inconsistent in /candidates/totals/ and /candidate/{candidate_id}/totals/ 
-to test database:
Download branch feature/4214-fix-inconsistencty-for-H6MD08549, run flyway migration (or create_sample_db), make sure migration finished successfully.
A tmp version of this MV had been created in DEV database (ofec_candidate_totals_detail_mv_tmp). 
- to test in API
In model file totals.py,
modify the following line to point to the tmp mv:
class CandidateCommitteeTotalsHouseSenate(CandidateCommitteeTotals):
`   __tablename__ = 'ofec_candidate_totals_detail_mv_tmp'`
class CandidateCommitteeTotalsPresidential(CandidateCommitteeTotals):
`   __tablename__ = 'ofec_candidate_totals_detail_mv_tmp'`
Point to the DEV database, start local server, run the …
> modify ofec_candidate_totals_detail_mv to correct candidate totals for H6MD08549

- webservices/config.py
- Resolves #4162
Update elasticsearch version in required services. I don't think this was causing outages, but it increases the chances of issues if we don't fix it.
You can see the error when you try to manually deploy the `develop` branch to `dev`:
- Checkout `develop`
- `invoke deploy --space dev`
- See error message `Missing services redis32, s3, elasticsearch24`... `RuntimeError: Invalid configuration: [[], ['elasticsearch24'], []]`
You can see the error goes away when you do the same steps after checking out this branch.
-  Deploys
> Update elasticsearch version in required services

- package-lock.json
- package.json
- webpack.production.config.js
- Resolves #4198
`uglifyjs-webpack-plugin` is archived. (This package was investigated because a transitive dependency, `serialize-javascript`, contains a vulnerability). `terser-webpack-plugin` seems to be a possible replacement. This PR replaces the archived plugin with the new plugin.
- `rm -rf node_modules`
- `rm package-lock.json`
- `npm i`
- `npm run build`
- `pytest`
- run localapi and verify functionality is preserved through spot-checking.
- if above tests are successful, I will do a manual deploy to `dev` for testing.
> replace uglifyjs-webpack-plugin with tersor-webpack-plugin

- data/migrations/V0192__add_pg_date_column_to_presidential_tables.sql
- Resolves #[4265] 
Add pg_date column to presidential tables
The presidential tables were originally created without the pg_date column. It is not needed for the website presentation. However, it is decided later that this column will be useful for later internal maintenance.  The column had already been added to the tables.  This migration file serves to keep the version control of the database objects.
- download the branch and run flyway migration on the local machine.  Make sure the migration file executed successfully and the pg_date column created for these presidential tables.
(optional, to mimic the effect on AWS database, after the migration file run the first time, connect to the local repository, delete version = '0192' from flyway_schema_historty and executing the migration …
> add_pg_date_column_to_presidential_tables

- webservices/common/models/base.py
- Resolves #4273: Fix downloads while using Schedule A routing setting 
The purpose of this change is to allow us to re-enable the setting to protect the rest of the website from Schedule A queries. If we’re getting hit hard on schedule A, we can serve up candidate profile pages, presidential map data, etc
**Technical implementation**
Only do request-based routing when there's request context. In other words, only do request-based routing for API calls, not celery-worker tasks. Sending flask request context to celery-worker is really complex (I spent a while trying to get this to work and it could introduce more bugs), so instead if we don't have request context, fall back to non-request based routing and just choose a random replica.
Some commonly cited resources on passing application …
> [MERGE WITH GIT FLOW] Hotfix: Fix downloads while using Schedule A routing setting

- .circleci/config.yml
- requirements-dev.txt
- requirements.txt
- Resolves #4278 
- move following packages to requirements.txt from requirements-dev.txt since they are required for build.
nplusone==0.8.0
webtest==2.0.27
factory_boy==2.8.1
- remove requirements-dev.txt from build as it includes packages not required for build/testing of build in production.
- pytest
- I further tested by manually deploying through circle while commenting out the cache portion in config.yaml
-  python dependencies
- circle ci build
issue | PR
#4047 | #4069, #4188
> move nplus one

- data/migrations/V0193__add_is_active_ofec_committee_history_mv.sql
- requirements-dev.txt
- requirements.txt
- Resolves https://github.com/fecgov/openFEC/issues/4283
add function is_committee_active based on this logic:
Label | cmte_filing_freq | filing frequency description
-- | -- | --
Active | Q | Quarterly flier
Active | M | Monthly filer
Terminated | T | Terminated
Terminated | A | Administratively terminated
Add is_active column to ofec_committee_hostory_mv
- download branch to local
`pytest`
- test migration on cfdm_test.   
`dropdb cfdm_test`
`createdb cfdm_test`
`invoke create_sample_db`
Note: 
1)also update webtest version from 2.0.27 to 2.0.34
Ref:
https://github.com/fecgov/openFEC/pull/4259/files#diff-f4c265073ea4274a80eca85440875e56R8
2) Fix incompatible version.
gevent
locustio
> Add is_active to ofec_committee_history_mv.

- data/migrations/V0193__add_is_active_ofec_committee_history_mv.sql
- requirements-dev.txt
- Resolves https://github.com/fecgov/openFEC/issues/4283
add function is_committee_active based on this logic:
Label | cmte_filing_freq | filing frequency description
-- | -- | --
Active | Q | Quarterly flier
Active | M | Monthly filer
Terminated | T | Terminated
Terminated | A | Administratively terminated
Add is_active column to ofec_committee_hostory_mv
- download branch to local
`pytest`
- test migration on cfdm_test.   
`dropdb cfdm_test`
`createdb cfdm_test`
`invoke create_sample_db`
Note: 
Fix locustio version.
> Add is_active to committee_history_mv

- tests/test_committees.py
- webservices/common/models/committees.py
- webservices/docs.py
To make it more clear to our users what the status of a committee is, we want to add an indicator at the top of the committee profile page.
- Resolves #[_4284_](https://github.com/fecgov/openFEC/issues/4284)
model: CommitteeHistory
test_committees.py
2)pytest
3)test url to see new field: is_avtive
on local:
a) is_active=true
http://127.0.0.1:5000/v1/committee/C00693234/history
b) is_active=false:
http://127.0.0.1:5000/v1/committee/C00000141/history/
> Add is_active to committee history endpoint

- webservices/rest.py
- Resolves #4301
Add feature flag to restrict traffic to allowed keys
To turn on, env var `RESTRICT_API_TRAFFIC` needs to be `True`
To turn off, remove env var `RESTRICT_API_TRAFFIC`
To add allowed keys, update `TRAFFIC_WHITELIST_API_KEY_IDS`
Key ID's can be found in the API umbrella and at minimum should include:
- Private key ID
- Public key ID
- Pingdom key ID
- Demo key ID
- Manual deploy to `stage` (need API umbrella in place)
- Test server-side (candidate profile page) and client-side (data table) calls
- Test a download
- Test `DEMO_KEY` on https://api-stage.open.fec.gov/developers/
- Test another key (your own, or let me know if you want one) that isn't whitelisted
> [MERGE WITH GIT FLOW] Add feature flag to restrict API traffic

- manifests/manifest_api_prod.yml
- Resolves #4315
Set prod api instances to 10
- Manifest file change equal to `cf scale api -i 10`
-  API app instances
> Set prod api instances to 10

- data/migrations/V0195__include_new_transaction_code_to_individual.sql
- Resolves #4322 
Request from EFO to add new transaction code 30E, 31E, 32E.  
These 3 transaction codes are considered individual contributions and need be added to is_coded_individual
- download this feature branch to local server.  
Run flyway migration.  Make sure migration executed successfully.
Open the local database, 
- Verify the function public.is_coded_individual(text) to ensure it includes the transaction code 30E, 31E, 32E.
- The following queries will return true.
select public.is_coded_individual('30E');
select public.is_coded_individual('31E');
select public.is_coded_individual('32E');
-  
branch | PR
feature/other_pr | …
> add new transaction codes to the list to be included as individual

- data/migrations/V0196__add_is_active_ofec_committee_detail_mv.sql
- data/migrations/V0197__add_is_active_ofec_committee_fulltext_mv.sql
- Resolves #[_4296_](https://github.com/fecgov/openFEC/issues/4296)
- Add is_active column to ofec_committee_detail_mv, ofec_committee_fulltext_mv
- run `py.test`
- Test flyway migration
- Spot checking by running these queries in DEV
```
select filing_frequency, is_active, count(*) 
from public.ofec_committee_detail_mv_tmp_hc
group by filing_frequency, is_active;
select  is_active, count(*) 
from public.ofec_committee_fulltext_mv_tmp_hc
group by is_active;
```
> Add is_active column 

- tests/test_committees.py
- webservices/common/models/committees.py
- webservices/schemas.py
To make it more clear to our users what the status of a committee is, we want to add an indicator at the dropdown list of committee global search. 
- Resolves #[_4270_](https://github.com/fecgov/openFEC/issues/4270)
model: CommitteeSearch
test_committees.py
2)pytest
3)test url to see new field: is_avtive
on local:
http://127.0.0.1:5000/v1/names/committees/?q=tru
compare with production api:
https://api.open.fec.gov/v1/names/committees/?q=tru&api_key=DEMO_KEY
> Add is_active column in names/committees/

- webservices/legal_docs/advisory_opinions.py
- update the AO python code to include and excludes the AO cites.
- Resolves https://github.com/fecgov/openFEC/issues/4333
- checkout branch `git checkout feature/4333-fix-missing-ao-cites`
- run local elastic search service instruction: https://github.com/fecgov/openFEC#run-locally
- set up local cms-->local api
- set local api --> to point to dev db
- get the dev s3 bucket creds from cf and export them in api terminal
- load AO : `python manage.py load_advisory_opinions -f 2018-15`
- on local cms  : http://localhost:8000/, verify that cites appear on AO's mentioned in issue #4333
- I have already deployed this feature branch to `dev` space and ran the api task that loads AO 
from 2018-15(`cf run-task api  "python manage.py load_advisory_opinions -f 2018-15"`)
- Look up for AO's …
> Update the AO task to include missing cites

- tests/test_aggregates.py
- tests/test_candidates.py
- tests/test_committees.py
- tests/test_reports.py
- tests/test_totals.py
- webservices/resources/candidates.py
- webservices/resources/committees.py
- webservices/resources/reports.py
- webservices/resources/totals.py
- Resolves #4355 
Handle case sensitivity for /example/<string:>/urls. Another issue found in testing: two endpoints aren't filtering for committee ID at all, but this PR is big enough (and solves a big front-end problem), so I split it off into another issue (https://github.com/fecgov/openFEC/issues/4357). 
Make sure candidate ID's and committee ID's return results when lower-cased.
candidates.CandidateView:
- http://localhost:5000/v1/candidate/p00009621/
- http://localhost:5000/v1/committee/c00693234/candidates/
candidates.CandidateHistoryView:
- http://localhost:5000/v1/candidate/p00009621/history/
- http://localhost:5000/v1/candidate/p00009621/history/2020/
- http://localhost:5000/v1/committee/c00693234/candidates/history/
- http://localhost:5000/v1/committee/c00693234/candidates/histo …
> Handle case sensitivity for /example/<string:>/urls

- tests/test_itemized.py
- webservices/common/views.py
- webservices/resources/sched_a.py
- webservices/resources/sched_b.py
- webservices/resources/sched_e.py
- webservices/resources/sched_h4.py
Resolves #4343
- **Add pagination validation:** For Schedules A, B, and E, if only `last_index` and not any of the sort options or `sort_hide_null=True` is chosen, throw a 422 error. Add test coverage.
- **Fix some Schedule A and Schedule B tests**: Make sure they pass both index values. For some tests, passing only `last_index` was hiding null values, which doesn't really make sense. Passing just `last_index` won't be valid behavior anymore, so for those tests, I explicitly added the `sort_hide_null=True` filter.
**Pagination basics** 
(from https://api.open.fec.gov/developers/#/receipts/get_schedules_schedule_a_):
> The `/schedules​/schedule_a​/` endpoint is not paginated by page number. This endpoint uses keyset pagination to improve query performance and these indices are required to …
> Add validation for offset pagination (Schedule A, B, E)

- requirements.txt
update pytest-flake8 to v1.0.6
- Resolves https://github.com/fecgov/openFEC/issues/4373
- update the pytest-flake8 in requirements.txt
- checkout branch  `git checkout feature/upgrade-pytest-flake8`
- run `pytest`
> Update pytest-flake8 to v1.0.6.

- requirements.txt
Update requests package version to2.22.0 to resolve the ERROR that shows up in deploy script.
```ERROR: prance 0.18.2 has requirement requests~=2.22, but you'll have requests 2.21.0 which is incompatible```.
- Resolves https://github.com/fecgov/openFEC/issues/4295
- update requests to v2.22.0 in `requirements.txt` file
- checkout branch `git checkout feature/upgrade-requests-pkg`
- install requirements`pip install -r requirements.txt`
- remove node modules: `rm -rf node_modules/`
- install node pkgs : `npm i`
- install python pkgs: `npm run build`
- run `pytest`
- run server : `python manage.py runserver`
- test endpoints here - `http://localhost:5000/`
- deploy this feature branch  to `dev` space and verify that the error (`ERROR: prance 0.18.2 …
> Update requests to v2.22.0

- webservices/docs.py
- webservices/rest.py
- webservices/spec.py
- webservices/templates/swagger-ui.html
- Resolves #4323
- add plain vanilla API Key Signup page to our swagger-ui in advance of heavier lift https://github.com/fecgov/openFEC/issues/3947
Reviewers can either do a manual deploy to dev if desired, or run locally. The following are the steps for running locally:
- locally `export` the `API_UMBRELLA_SIGNUP_KEY` envar value located in `cf env api` (`cf target -s dev`)
- locally `export API_UMBRELLA_SIGNUP_KEY_FEATURE_FLAG="True"`
- run local api
- (please test functionality/correctness)
-  swagger-ui, rest.py, docs.py, spec.py
> API key signup page

- tests/test_itemized.py
- webservices/common/views.py
- webservices/resources/sched_a.py
- webservices/resources/sched_b.py
- webservices/resources/sched_e.py
Resolves #3902
- Add max limits for additional fields (below)
- Add test coverage
**Schedule A endpoint (schedules/schedule_a/):** 
Limit 10 for:
- Name - `contributor_name`
- Zip - `contributor_zip`
- City - `contributor_city`
- Occupation - `contributor_employer`
- Employer - `contributor_occupation`
**Schedule B endpoint (schedules/schedule_b/):** 
Limit 10 for:
- Recipient name or ID - `recipient_name` (takes ID or name)
- City  - `recipient_city`
**Schedule E endpoint (schedules/schedule_e/):** 
Limit 10 for:
- Candidate name or ID (`candidate_id`)
```
filters_with_max_count = [
'committee_id',
'contributor_name',
'contributor_zip',
'contributor_city',
'contributor_employer',
'contributor_occupation',
]
```
'committee_id',
http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KE …
> Add max ten (10) limits for additional fields

- data/migrations/V0200__add_index_on_pg_date.sql
- Resolves #4379
This is to support users' request to filter on pg_date so they can download our new data for their usage.
The indexes had been created in DEV/STG/PRD on all partition tables during non-peak hour.
Download the branch to the local server.  Then run either 
or 
flyway migrate
Make sure the migration file executed successfully.
Login the local database, 
select tablename, indexname from pg_indexes where indexname like 'idx%pg_dt%' order by 1, 2;
You should see 46 indexes total, 2 per partition table.
-  
branch | PR
> add pg_date indexes to fec_fitem_sched_a tables

- tests/test_itemized.py
- webservices/args.py
- webservices/docs.py
- webservices/resources/sched_a.py
Adds the ability to filter by `load_date` in `sched_a` views so users can search for contributions loaded in a specific day.
- `pytest tests/test_itemized.py::TestScheduleA::test_schedule_a_load_date_filter`
-  `ScheduleAView`
> Add filter by load_date in sched_a

- webservices/args.py
- webservices/resources/sched_a.py
- Partial resolution for #4381 
Add deprecation notice to Schedule A for `contributor_aggregate_ytd`
- http://localhost:5000/developers/#/receipts/get_schedules_schedule_a_
-  Swagger docs
> Add deprecation notice to Schedule A for 'contributor_aggregate_ytd'

- webservices/resources/sched_a.py
Remind API user we will change contribution_receipt_date default sort order from ASC to DESC.
- Resolves #4402
sche-a.py
2) pytest
3) ./manage.py runserver
4) http://127.0.0.1:5000/developers/#/receipts/get_schedules_schedule_a_
> Add message to change sched-a sort to DESC

- webservices/docs.py
Tell API user how to paginate the /schedules/schedule_a/ endpoint properly, especially when reaching the last page.
- Resolves #4411
Ref : [Research on pagination beyond last page #4405](https://github.com/fecgov/openFEC/issues/4405)
docs.py
1) checkout branch (sorry for wrong number of branch name, should be 4411)
2) pytest
3) ./manage.py runserver
4) check /schedules/schedule_a/ endpoint
-
> Modify Schedule A endpoint description about last index.

- tests/test_api.py
- tests/test_counts.py
- webservices/common/counts.py
- webservices/common/models/itemized.py
- webservices/common/views.py
- webservices/resources/elections.py
- webservices/resources/filings.py
- webservices/resources/sched_a.py
- webservices/tasks/download.py
Resolves #4368
- Add option to only pass primary key column to count query
- Refactor `get_count` to have fewer parameters
[Locust tests](https://docs.google.com/spreadsheets/d/1VKjqaPdnf8GAU6znXHTwbMVQKBzIbbjFk2MKVXSUWy4/edit#gid=0)
Note: SQLAlchemy [requires a primary key](https://docs.sqlalchemy.org/en/13/faq/ormconfiguration.html), and should throw an error like this without one:
```
E   sqlalchemy.exc.ArgumentError: Mapper mapped class ScheduleA->fec_fitem_sched_a could not assemble any primary key columns for mapped table 'fec_fitem_sched_a'
```
So, this test `assert len(view.model.__mapper__.primary_key) > 0` would be a superfluous. However, it's possible we'd have a resource without a `model` attribute so I added both tests for more clarity on expected behavior.
```
<class …
```
> Add flag ('use_pk_for_count') to only select primary key column for count query

- PULL_REQUEST_TEMPLATE.md
See https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references
Remove confusing brackets in PR template
`Resolves #[Issue]` ends up looking like this (issue not undelined):
and will **not** close the linked issue
`Resolves #Issue` ends up looking like this (issue underlined): 
and **will** close the linked issue
> Remove confusing brackets in PR template

- data/flyway/build.gradle
- Resolves #4408 
```groovy
exclude group: 'com.google.guava', module: 'guava' //resolves new vulnerability due to fix
constraints {
implementation('org.postgresql:postgresql:42.2.14.jre6') //resolves reported vulnerability
}
```
- >The compile configuration is now deprecated and should be replaced by implementation or api
-  discussion at https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle. 
- pytest
- flyway migrate / invoke create_sample_db
- cd to `data/flyway` from project level directory and run `snyk test`
-  `build.gradle`
- migrations
> resolve postgresql security vulnerability

- requirements.txt
See https://github.com/jfinkhaeuser/prance/commit/e251bb201c17a9440de1bf8521f484b9646ab1d6
- Resolves issue found in testing
```
=============================== warnings summary ===============================
tests/test_swagger.py::TestSwagger::test_swagger_valid
/Users/lbeaufort/.pyenv/versions/3.7.7/envs/api-env/lib/python3.7/site-packages/prance/__init__.py:180: DeprecationWarning: Function 'semver.format_version' is deprecated. Deprecated since version 2.10.0.  This function will be removed in semver 3. Use 'str(versionobject)' instead.
self.semver = semver.format_version(*version)
```
- Also see https://app.circleci.com/pipelines/github/fecgov/openFEC/259/workflows/cc6c738b-02aa-4ed3-9cb1-8a893148661c/jobs/2635
**Before:** 
- `pytest tests/test_swagger.py` throws warnings
**After:** …
> Update prance to address deprecation warning

- webservices/docs.py
- webservices/templates/swagger-ui.html
- Resolves #4363
- hard coding "required fields" addressed under #4447
refine API key signup elements per completion criteria in #4363 
for non developers: 
- https://fec-dev-api.app.cloud.gov/developers/
for developers:
- pytest
- run local api
- verify that api signup looks correct per #4363 completion criteria.
-  swagger-ui.html
- docs.py
> refine api key signup page

- data/migrations/V0203__ofec_filings_all_mv.sql
- data/migrations/V0204__ofec_totals_combined_mv.sql
- data/migrations/V0205__tres_nm_ofec_filings_all_mv.sql
- Resolves #4463 
As part of deploying the Informatica mappings to populate the tres_nm field 
in f_rpt_or_form_sub table from tres_sign_nm field in nml form tables, 
the size of tres_nm field in f_rpt_or_form_sub table 
from varchar2(38) to varchar2(90) in FECP database. 
The size of tres_nm column in f_rpt_or_form_sub table in Postgress databases 
also need to be increased to accommodate this change.
Currently there are MVs/VWs referencing f_rpt_or_form_sub table. 
Two of them referencing this particular column 
so these MVs/VWs need to be updated as well.
- Download the branch to local server, run flyway migration or run invoke create_sample_db, make sure migration files executed successfully
- Run pytest.
- log into local cfdm_test database, check the size of tres_nm column in …
> Increase size of tres_nm column in f_rpt_or_form_sub table

- tests/factories.py
- tests/test_sched_e.py
- tests/test_spending_by_others.py
- webservices/resources/aggregates.py
Fix the broken sort by candidate_name, committee_name on the following endpoints:
1.  Independent Expenditures  - ` /schedules/schedule_e/by_candidate/` 
2. Communication Cost  -  `/communication_costs/by_candidate/`
3. Electioneering - `/electioneering/by_candidate/`
- Resolves #4360
- In resources/aggregates.py : Modify the sort_args in the `CandidateAggregateResource` to include `candidate_name` and `committee_name`
- Also added candidate_id and committee_id to sort_args function. While writing additional tests that sorts by those two parameters, pytests are failing with a 422 error. Reason being, these two columns are not found in the views(SE, CC and EC) and they are inherited from the parent class(BaseAggregates). pytests are unable to …
> Fix the broken sort by candidate_name, committee_name on IE, CC and EC by_candidate endpoint

- webservices/resources/aggregates.py
- Resolves issue found in testing
Remove unused/extra return
There’s a return on line 402 and another on line 421 that will never run, but it could cause problems if we change the code and don’t realize the behavior.
https://github.com/fecgov/openFEC/blob/85fb11a78246e51745f82a57896b5a602ea83cac/webservices/resources/aggregates.py#L400-L421
> Remove unused/extra return statement for 'join_cand_cmte_names' function

- README.md
- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
- manifests/manifest_celery_beat_prod.yml
- manifests/manifest_celery_beat_stage.yml
- manifests/manifest_celery_worker_prod.yml
- manifests/manifest_celery_worker_stage.yml
- manifests/manifest_task_dev.yml.template
- manifests/manifest_task_prod.yml.template
- manifests/manifest_task_stage.yml.template
- tests/common.py
- tests/test_downloads.py
- webservices/rest.py
- Partial resolution for #4417
Replace whitelist/blacklist with more descriptive language
|old|new|
|-|-|
|`TRUSTED_PROXY_IPS`| `FEC_API_TRUSTED_PROXY_IPS`|
|`BLOCKED_IPS`| `FEC_API_BLOCKED_IPS `|
|`DOWNLOAD_WHITELIST_API_KEY_ID `| `FEC_API_DOWNLOAD_KEY_ID`|
|`TRAFFIC_WHITELIST_API_KEY_IDS `| `FEC_API_BYPASS_RESTRICTION_API_KEY_IDS`|
|`RESTRICT_DOWNLOADS `| `FEC_API_RESTRICT_DOWNLOADS `|
|`RESTRICT_TRAFFIC`|`FEC_API_RESTRICT_TRAFFIC`|
Note: these are taken care of in the manifest files
|~`FEC_API_WHITELIST_IPS `~|~`FEC_API_USE_PROXY`~|
**Template** 
```
...,
"FEC_API_TRUSTED_PROXY_IPS":"",
"FEC_API_BLOCKED_IPS":"",
"FEC_API_DOWNLOAD_KEY_ID":"",
"FEC_API_BYPASS_RESTRICTION_API_KEY_IDS":"",
"FEC_API_RESTRICT_DOWNLOADS":"",
"FEC_API_RESTRICT_TRAFFIC":""
```
- Run `pytest`
- Need to test in …
> Modernize repository language

- tests/test_candidates.py
- webservices/args.py
Resolves #4486
- Add validation for `page=0` (should throw 422 instead of 500)
- Make error message friendlier 
- Add test coverage
- On production: https://api.open.fec.gov/v1/committees/?api_key=DEMO_KEY&committee_id=C00431445&page=0 throws 500 error
- Local: http://localhost:5000/v1/committees/?api_key=DEMO_KEY&committee_id=C00431445&page=0
```
{
message: "Must be greater than zero",
status: 422
}
```
-  No known front-end symptoms - saw this in logs from API users
> Add validation for page=0

- tests/test_itemized.py
- webservices/resources/sched_a.py
Currently for /schedules​/schedule_a​/ endpoint, the default sorting "contribution_receipt_date ASC". But SB and SE are sorted DESC by default. 
- Resolves #4402 
Ref : [https://github.com/fecgov/openFEC/pull/4427](https://github.com/fecgov/openFEC/pull/4427)
sched_a.py
2)pytest
3)./manage.py runsever
Test URL:
http://127.0.0.1:5000/v1/schedules/schedule_a/?two_year_transaction_period=2008&sort_null_only=false&sort=-contribution_receipt_date&per_page=20&sort_hide_null=true
/schedules​/schedule_a​/  api user
> Change sched-a default sort by DESC

- bin/run.sh
- manifests/manifest_api_dev.yml
- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
- manifests/manifest_celery_beat_dev.yml
- manifests/manifest_celery_beat_prod.yml
- manifests/manifest_celery_beat_stage.yml
- manifests/manifest_celery_worker_dev.yml
- manifests/manifest_celery_worker_prod.yml
- manifests/manifest_celery_worker_stage.yml
- manifests/manifest_task_dev.yml.template
- manifests/manifest_task_prod.yml.template
- manifests/manifest_task_stage.yml.template
Resolves #4489
- Update number of `gunicorn` workers to `9` (2*CPU+1) per https://docs.gunicorn.org/en/stable/design.html#how-many-workers
- Remove unused env var `WEB_CONCURRENCY` (gunicorn ignores this - can't figure out why we can't use this env var but it's not being used, so removed it)
Load testing results show improved speed: https://docs.google.com/spreadsheets/d/1DNs0O1YiL7AgHptYd9de-iuUv1c6tZ8ZtFA4Soym9cQ/edit#gid=0
- Manually deploy this branch with `invoke deploy --space dev` (please don't commit to this branch)
- ssh into instance 0 of the api app with `cf ssh api -0` 
- Check number of CPU cores with `cat /proc/cpuinfo`
- Check number of workers with `ps aux | grep gunicorn | grep -v grep | wc -l` (subtract one) per https://stackoverflow.com/a/33107962
List general …
> Increase number of gunicorn workers

- data/migrations/V0206__add_mur_arch_tables.sql
- This is first step of  #4465
_migration file for creating mur_arch schema and 11 tables_
- download feature branch
- run `pytest`
- run migration, then check local database: cfdm_test, there should be schema mur_arch and 11 tables under this schema
- to test re-run: delete 206 from flyway history table, run it again to make sure it can be re-run without any error.
> Create mur_arch schema and tables

- data/migrations/V0207__drop_ofec_filings_mv.sql
- manage.py
- Resolves #4478 
ofec_filings_mv is an older version of ofec_filings_all_mv. PR for issue #4463 had removed the last usage of this MV. It will be dropped to avoid confusion and dual maintenance.
- Download the branch to local machine.  Run `invoke create_sample_db`
Make sure it runs successfully.  
Log in local cfdm_test database, make sure ofec_filings_mv does not exist.
Review the output from invoke create_sample_db, make sure ofec_filings_mv is not in the refreshing materialized view list.
-  None
branch | PR
> drop MATERIALIZED VIEW ofec_filings_mv

- tasks.py
- webservices/docs.py
- Resolves #4511
adds terms of service and acceptable use policy to the api key signup page (swagger-ui)
note to reviewers: 
required: @JonellaCulmer 
optional: @PaulClark2 @lbeaufort @johnnyporkchops 
- I'll [deploy to dev](https://fec-dev-api.app.cloud.gov/developers/) so @JonellaCulmer can review (as of 8/1/2020 1:30 p.m. it's available on dev)
- otherwise, run locally, review `localhost:5000`
Things to test:
- click links
- verify it looks as expected
- text was copy/paste other than formatting, but another read through may be good.
> add terms of service and acceptable use policy

- webservices/common/models/itemized.py
- webservices/schemas.py
- Resolves #4491
Remove sort expression for Schedule B
- Check out develop branch
- Run any Schedule B query, or choose one from this list https://docs.google.com/spreadsheets/d/1J5QK4mw7HXbMnaDV_ClCGWEgbbI3VZZhXDqmjIFwBqI/edit#gid=0
- Print out query here: https://github.com/fecgov/openFEC/blob/b849152b2dd1f1bc6836fc57a464b029c62f3974/webservices/utils.py#L155
- Note that the `ORDER BY` has `COALESCE` in it
- Run any Schedule B query
- Note that the `ORDER BY` no longer has `COALESCE` in it
- Schedule B query internals
> Remove sort expression for Schedule B

- tasks.py
removes manual deploy line in tasks.py
- verify manual  deploy  line no longer in deploy rules
-  tasks.py
> remove manual deploy in tasks.py

- tests/test_downloads.py
- webservices/tasks/download.py
- Resolves #4502 
_Adds the `user_downloads` prefix to the API's user generated downloads path. The name is unaffected.
- Deploy to the dev or stage environment to test that downloads are writing into the stage downloads bucket under the `user_downloads` prefix.
-  /downloads/ endpoint
> Add user_downloads prefix to downloads bucket

- webservices/rest.py
- Resolves bug introduced in https://github.com/fecgov/openFEC/pull/4455
- changes instance of `RESTRICT_API_MESSAGE` to `RESTRICT_MESSAGE` to align with change introduced in that PR
- required reviewers = 1 (pick from @pkfec or @fec-jli )
- courtesy copy = @lbeaufort 
-visual inspection should be sufficient for this case.
#4455
> Resolve bug in rest.py

- webservices/docs.py
- Resolves #4508
_ adds deprecation notice to swagger-ui
- I would like both @fec-jli and  @lbeaufort to  review before merging
- check out branch and run locally. Check the `/communication-costs/` endpoint notice
- check  inbox for email announcing deprecation--went to  a total of 3 api users, only 1 external api user
-  `/communication-costs/` endpoint
branch | PR
#4203 |#4232
> Add deprecation notice to /communication-cost/ endpoint

- webservices/docs.py
- webservices/templates/swagger-ui.html
- Resolves #4554 
- returns language to indicate 120 calls per minute and removes conversion to other units
- fixes syntax for swagger-ui.html (Thanks @johnnyporkchops )
- run local api
- verify upgraded api key is 120 calls per minute and no longer has the incorrect "7,600 calls per hour"
- I signed up for an api key to test the swagger-ui.html change--you can as well, or check linting (@johnnyporkchops )
-  /webservices/templates/swagger-ui.html
- /webservices/docs.py
> [MERGE WITH GIT FLOW] Hotfix/4554 fix swagger math error

- webservices/docs.py
- webservices/rest.py
- webservices/templates/swagger-ui.html
- Resolves #4538 
- remove feature flag
- additional js changes (@johnnyporkchops, @rfultz )
This bug is sometimes hard to reproduce. But @johnnyporkchops and @jason-upchurch confirmed we were able to reproduce on local. So:
- clear browser history
- check out master branch
- run local api, see if form loads, try refreshing until form does not load
- clear browser history (again)
- check out this hotfix branch
- run local api
- test that api key signup form loads with page, refresh, etc.
- rest.py
- swagger-ui.html
- docs.py
> [MERGE WITH GIT FLOW] Hotfix/4538 fix api key signup load

- tests/test_spending_by_others.py
- webservices/resources/aggregates.py
- Issue: https://github.com/fecgov/fec-cms/issues/3921
- Fixes API for candidate name and committee name sort
- Run this branch
- Make sure you can filter by `candidate_name`. Example: http://localhost:5000/v1/communication_costs/aggregates/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&sort=candidate_name&per_page=30&page=1&election_full=false&cycle=2018&committee_id=C70001318
- Make sure you can filter by  `committee_name`. Example: http://localhost:5000/v1/communication_costs/aggregates/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&sort=committee_name&per_page=30&page=1&election_full=false&candidate_id=P80001571
-  /communication_costs/aggregates/ endpoint
> Fix sort on candidate and committee name

- webservices/docs.py
When looking at the [Schedule A API documentation](https://api.open.fec.gov/developers/#/receipts/get_schedules_schedule_a_), I noticed that the links appear to be in Markdown syntax but have spaces between the square brackets and parentheses.
Note: I didn't bother getting the API running locally, so I'm not 100% sure this fixes the issue.
- Run the API and make sure the links are present in Swagger UI
- API docs, hopefully? Maybe others?
None that I'm aware of.
> fix broken link syntax in documentation

- package-lock.json
- package.json
- Resolves #4570 
Bumping the version of Lodash to 4.17.20 to address a [Snyk vulnerability ](https://app.snyk.io/vuln/SNYK-JS-LODASH-590103)
- pull the branch
- `npm i`
- `npm run build`
- check for errors
- check that Swagger works as expected
We only upgraded Lodash so changes should be minimal. Lodash is a devDependency so errors should happen on build. If build runs fine and front-end functionality is the same, yay!
None
> Snyk High - Bump Lodash from 4.17.17 to 4.17.20

- data/migrations/V0210__add_mur_name.sql
- Resolves #4563 
_Five more tables are added to mur_arch._
mur_name_csv
mur_name
mur_arch_xml
archived_murs
documents
- download the branch
- run pytest
- run flyway migrate
- To test the migration file can be rerun without error:
- delete V0210 from table: flyway_schema_history
- run flyway migrate again
> Add more archived mur tables (V0210)

- manifests/manifest_api_dev.yml
- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
- manifests/manifest_celery_beat_dev.yml
- manifests/manifest_celery_beat_prod.yml
- manifests/manifest_celery_beat_stage.yml
- manifests/manifest_celery_worker_dev.yml
- manifests/manifest_celery_worker_prod.yml
- manifests/manifest_celery_worker_stage.yml
- Resolves #4579 
Decrease celery worker disk quota, specify quota for other apps. Disk is only used for the storage of the app itself and won't impact performance - therefore we can reduce the disk for `celery-worker` to 1G to match other applications.
- Only one backend dev approval required to merge
- Celery-worker disk isn't really test-able since it's only changed for `prod` but to test the other `disk_quota` settings you can do a manual deploy with `invoke deploy --space dev` and make sure it successfully deploys
-  Disk size allocation for `celery-worker` -  Disk is only used for the storage of the app itself and won't impact performance - therefore we can reduce the disk to 1G to match other applications.
> Decrease celery worker disk quota, specify quota for other apps

- webservices/docs.py
- Resolves #4591 
Removes "Please note /communication_costs/ is not yet in place, and this notice will be updated once it is in service." from deprecation notice since new endpoint will be in service with the 13.3 release.
- any tagged reviewer who has the time may review and merge (this is easy)
- verify that sentence is removed
> Update deprecation notice

- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
- manifests/manifest_celery_worker_dev.yml
- Resolves #4578
Increase API memory in production and stage to 1.5G, remove extra celery-worker instance in `dev`.
Note: Memory is in MB (1500M instead of 1.5G) because the `cf cli` didn't take decimals until version 6.33.0 and we're on 6.32.0. When I tested 6.52.0 there were still issues - might be with the `zero-downtime-push` but it didn't seem worth it to muck around with things in there when a comment can address any confusion.
- One developer (required) additional developers optional
- Test in stage with a manual deploy `invoke deploy --space stage`. Please don't commit to this branch, thanks!
-  API available memory
> Increase API memory in production and stage, remove extra celery-worker instance (targets release)

- tasks.py
- Resolves issue found in local setup
When running `invoke create_sample_db` tell the user if `SQLA_SAMPLE_DB_CONN` is unset instead of throwing a cryptic exception.
- One approval required to merge, thanks!
- Check out `develop`
- `echo SQLA_SAMPLE_DB_CONN` so you can reset it later
- `unset SQLA_SAMPLE_DB_CONN`
- Run `invoke create_sample_db`
- ➡️ get cryptic exception 😞 
```
Traceback (most recent call last):
File "/Users/lbeaufort/.pyenv/versions/api-env/bin/invoke", line 10, in <module>
sys.exit(program.run())
File "/Users/lbeaufort/.pyenv/versions/3.7.7/envs/api-env/lib/python3.7/site-packages/invoke/program.py", line 293, in run
self.execute()
File "/Users/lbeaufort/.pyenv/versions/3.7.7/envs/api-env/lib/python3.7/site-packages/invoke/program.py", line 408, in execute …
```
> Tell user why 'create_sample_db' task fails without 'SQLA_SAMPLE_DB_CONN'

- requirements.txt
- Resolves https://github.com/fecgov/openFEC/issues/4608
We ran into a vine.five error below:
```
2020-09-09T09:00:23.12-0400 [APP/PROC/WEB/0] ERR ModuleNotFoundError: No module named 'vine.five'
```
Dependency changed and we needed to pin vine to 1.3.0. See vine release history: https://pypi.org/project/vine/#history
```
- kombu [required: >=4.4.0,<5.0, installed: 4.6.3]
- amqp [required: >=2.5.0,<3.0, installed: 2.6.1]
- vine [required: >=1.1.3,<5.0.0a1, installed: 5.0.0]
```
branch | PR
release/public 20200908 | [link](https://github.com/fecgov/openFEC/pull/4598)
> pinned vine 1.3.0

- data/migrations/V0211__ofec_totals_house_senate_mv.sql
- tests/test_totals.py
- Resolves #4551 
_Remove the restriction of Joint fundraising committee in ofec_totals_house_senate_mv_
- run `pytest`
- Test migration: `flyway migrate`
- API check:   
In common/models/totals.py, change model to a temp materialized view and launch API on local
`class CommitteeTotalsHouseSenate(CommitteeTotals):`
`__tablename__ = 'ofec_totals_house_senate_mv_tmp_hc'`
Before change: 
https://api.open.fec.gov/v1/committee/C00701243/totals/?sort_hide_null=false&api_key=DEMO_KEY&sort=-cycle&sort_null_only=false&per_page=20&sort_nulls_last=false&page=1
After change:
http://127.0.0.1:5000/v1/committee/C00701243/totals/?sort_null_only=false&page=1&sort_hide_null=false&per_page=20&sort_nulls_last=false&sort=-cycle
List general components of the application that this PR …
> Add financial summary of Joint fundraising committee ( migration V0211 )

- locustfile.py
- Resolves issue found in testing
Fix failing locust tests by using separate download key
- One developer approval required, others optional
Locust instructions in locustfile.py docstring and also https://docs.google.com/document/d/1ru6Qg0ErTQLD7a86qxW7kbaKbzkayt_X9PmGjZdC_nY/edit
- Check out develop, run locust, see locust download tests fail every time
- Check out this branch, set `FEC_DOWNLOAD_API_KEY` to match `stage`, run locust, see locust download tests pass
- Alternately, just review the code 👍 
-  Locust download testing
> Fix locust tests by using separate download key

- webservices/resources/sched_b.py
- webservices/resources/sched_e.py
- Resolves #4429 
Use primary-key only count for Schedules B and E 
- Two developers please
- Print out the query under `get_query_plan` in `webservices.common.counts.py` (Shortcut: `subl webservices/common/counts.py:38`)
- Do a Schedule B query, make sure it only selects `sub_id` column instead of many columns.
- Do a Schedule E query, make sure it only selects `sub_id` column instead of many columns.
**Example**
```
SELECT disclosure.fec_fitem_sched_b.sub_id AS disclosure_fec_fitem_sched_b_sub_id 
FROM disclosure.fec_fitem_sched_b
```
-  /schedules/schedule_b/ endpoint count
-  /schedules/schedule_e/ endpoint count
branch | PR
feature/4368-modify-count-logic | …
> Use primary-key only count for Schedules B and E

- requirements.txt
- Resolves #4611 
_Upgraded flask-cors to v3.0.9._
flask_cors is imported into our rest.py. Tested the `@app.route` for swagger docs and it seems to still function ok.
- `pip install -r requirements.txt` 
- `./manage.py runserver`
> Upgraded flask-cors to v3.0.9

- data/migrations/V0213__add_leadership_pac_linkage.sql
- Resolves #4586 
- Create disclosure.cand_cmte_linkage_alternate.  This table has leadership PAC sponsor data
- Run `pytest`
- Run flyway migrate, and make sure disclosure.cand_cmte_linkage_alternate is created in cfdm_test.
- In local database,
delete from flyway_schema_history where version = '0213';
run flyway migration again, make sure no error occurs
> [Migration 0213]Add cand_cmte_linkage_alternate table

- requirements.txt
Pins greenlet@0.4.16 since 0.4.17 causes api to go down.
``` 
2020-09-23T11:34:53.41-0400 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/python/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
2020-09-23T11:34:53.46-0400 [APP/PROC/WEB/0] ERR [2020-09-23 15:34:53 +0000] [6884] [INFO] Booting worker with pid: 6
```
```
TODAY:
Collecting greenlet>=0.4.14; platform_python_implementation == "CPython"
Downloading greenlet-0.4.17-cp37-cp37m-manylinux1_x86_64.whl (45 kB)
YESTERDAY:
Collecting greenlet>=0.4.14; platform_python_implementation == "CPython"
Downloading greenlet-0.4.16-cp37-cp37m-manylinux1_x86_64.whl (45 kB)
```
> Pin greenlet@0.4.16

- data/migrations/V0214__add_ofec_pcc_conversion_exclude.sql
- data/migrations/V0215__add_ofec_pcc_to_non_pcc_mv.sql
- manage.py
- webservices/flow.py
- Resolves #4595 
Add ofec_pcc_to_pac_mv and exclude table to facilitate tracking of the committees that convert from PCC to PAC mid cycle
**To test the database change:**
- download branch to local server
- run `invoke create_sample_db`
make sure executed successfully
review the output of invoke create_sample_db, verify that ofec_pcc_to_pac_mv is in the materialized view refresh list.
- log into local cfdm_test database, verify the following 3 objects had been created in cfdm_test database
ofec_pcc_to_pac_mv
ofec_pcc_to_pac_vw
ofec_pcc_conversion_exclude
- delete 0214 and 0215 from flyway_schema_history table
run flyway migration again, make sure no error occur.
**To review the content change:**
The initial load of the ofec_pcc_conversion_exclude table is captured in the google …
> [migration 0214/215] add ofec_pcc_to_non_pcc_mv and exclude table

- .circleci/config.yml
1. Update python docker image version to match the python version given in the runtime.txt file
2. Update Postgres docker image version to match the DB version in our govcloud environment
3. Set POSTGRES_HOST_AUTH_METHOD: "trust" environment variable. Builds fail without this env variable. 
which is 10.11.
- Resolves https://github.com/fecgov/openFEC/issues/4425
- Update docker images in **circleci/config.yml file** : 
1. Python  from 3.7.4-buster to 3.7.8-buster
2. Postgres from 9.6 to 10.11
- Before upgrade:
- After upgrade:
- Rebuild or Rerun _feature/4425-update-circle-config_ branch on circleci  and notice  **Spin up  environment** and **Container** circleci tasks downloading the upgraded python and postgres docker images.
> update circle config 

- data/migrations/V0216__add_sponsor_id_ofec_committee_history_mv.sql
- data/migrations/V0217__add_sponsor_id_ofec_committee_detail_mv.sql
- Resolves #4587
- Column sponsor_candidate_ids is added to ofec_committee_history_mv and ofec_committee_detail_mv
- Run `pytest` to make sure all tests pass
- Run `flyway migrate` to make sure migration files run successfully
- Go to these two materialized views to check data for new column:  sponsor_candidate_id
ofec_committee_history_mv_tmp_hc
ofec_committee_detail_mv_tmp_hc
`select * from public.ofec_committee_history_mv_tmp_hc
where committee_id = 'C00495887'
;`
`select * from public.ofec_committee_detail_mv_tmp_hc
where committee_id = 'C00495887'
;`
> [Migration V216, V217] Add sponsor_candidate_ids to two materialized views

- requirements.txt
- Resolves #4588
- updates sqlalchemy to 1.3.19 from 1.3.1 (changelog: https://docs.sqlalchemy.org/en/13/changelog/changelog_13.html#change-1.3.19)
- check out branch, run `pytest`
- branch was also deployed to dev space with successful build/deploy
- please feel free to "poke around" at endpoints of interest to see that results are as you expect them
- I have also written a cross-environment `pytest` which you can add to and run (run when branch is deployed to dev):
- https://github.com/jason-upchurch/fec_util/blob/master/compare_endpoints.py
- recommend having an upgraded api key as an environmental variable named 'FEC_ENV_TEST_API_KEY'
- usage: cd to wherever you checked out script and run `pytest compare_endpoints.py`
- please feel free to add endpoints to this script--the basic …
> Bump sqlalchemy to 1.3.19

- data/migrations/V0218__ofec_committee_history_mv_add_pcc_to_pac_info.sql
- tests/test_committees.py
- webservices/common/models/committees.py
- webservices/docs.py
- webservices/flow.py
- webservices/resources/committees.py
- webservices/rest.py
- Resolves #4458 
The following columns will be added to the ofec_committee_history_mv:
convert_to_pac_flg,
former_cmte_name,
former_cand_id,
former_cand_name,
former_cand_election_year
With modified CommitteeHistoryView, it now return the converted committee (with all the required former_xxxx columns and convert_to_pac_flg =true).
- Download branch to local server.
- run pytest
**To test database changes:**
- Run `invoke create_sample_db`.   
1. verify migration file run successfully.
2. verify MV refresh run successfully and ofec_pcc_to_pac_mv refresh before ofec_committee_history_mv.
3. login local cfdm_test db, verify new columns had been added to ofec_committee_history_mv
**To test API changes:**
- A temp mv ofec_committee_history_mv_tmp_jj had been created in dev.
modify …
> [migration file V0218] automatic candidate to pac conversion

- .circleci/config.yml
- README.md
- tasks.py
- Resolves #4667 
**Deploy task changes**
- With cf cli version 7, `cf api <endpoint>` logs you out - this is a known issue: https://github.com/cloudfoundry/cli/issues/2075. Only set the endpoint if `deploy` task `--login True` (used for CircleCI)
- Cf cli doesn't exit with code 0 anymore, so I had to add it. (not sure where this is documented but you can read between the lines here: https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute)
**Other minor changes**
- Specify version in README because the `--command` change to `cf run-task` is backwards incompatible
- Update `cf run-task` in README to reflect new flag
- One approval required
**Through CircleCI**
- Make your own copy of this branch (please don't commit to this branch)
- Modify deploy task to deploy to a …
> Update cf cli to version 7

- tests/test_committees.py
- webservices/args.py
- webservices/common/models/committees.py
- webservices/common/views.py
- webservices/docs.py
- webservices/filters.py
- webservices/resources/committees.py
- Resolves #4613
_Add filter sponsor_candidate_id to endpoint: /committees/_
- Two developers (required) additional developer optional
- Run `pytest`
- Set SQLA_CONN to dev database and start endpoint on local
- Compare these endpoints, and sponsor_candidate_ids can be found in endpoint output.
Before change:
https://api.open.fec.gov/v1/committees/?page=1&per_page=20&sort=name&sort_nulls_last=false&api_key=DEMO_KEY&committee_id=C00692715&sort_hide_null=false&sort_null_only=false
After change:
http://127.0.0.1:5000/v1/committees/?per_page=20&page=1&sort_null_only=false&committee_id=C00692715&sort_nulls_last=false&sort=name&sort_hide_null=false
- Run this endpoint to test filter
http://127.0.0.1:5000/v1/committees/?sort_null_only=false&page=1&sort_nulls_last=false&s …
> Add sponsor_candidate_id to endpoint: /committees/

- webservices/rest.py
Modified rest.py to send RESTRICT_MESSAGE and 503 error code if IP address is blocked
- Resolves #4651 
_If IP address of request is blocked, abort with 503 error code and send message with contact details_
- Attempt to access API with blocked IP address
-  REST API
> Modified rest.py to send RESTRICT_MESSAGE and 503 error code if IP address is blocked

- .circleci/config.yml
- README.md
- manifests/manifest_api_dev.yml
- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
- manifests/manifest_celery_beat_dev.yml
- manifests/manifest_celery_beat_prod.yml
- manifests/manifest_celery_beat_stage.yml
- manifests/manifest_celery_worker_dev.yml
- manifests/manifest_celery_worker_prod.yml
- manifests/manifest_celery_worker_stage.yml
- manifests/manifest_task_dev.yml.template
- manifests/manifest_task_prod.yml.template
- manifests/manifest_task_stage.yml.template
- tasks.py
Resolves #4668
Resolves #3950 
- Reformat manifests with newer format
- Implement rolling deployments, remove references to `autopilot` and `zero-downtime-push`
- At least two reviewers please
**Through CircleCI**
- Make your own copy of this branch (please don't commit to this branch)
- Modify deploy task to deploy to a space of your choice
- Push to Github, make sure build works
**Locally:**
- Install cf cli version [following this guide](https://github.com/cloudfoundry/cli/wiki/Version-Switching-Guide) or:
```
brew install cf-cli@7
brew install cf-cli@6
brew unlink cf-cli@6 && brew unlink cf-cli@7 && brew link cf-cli@7 && cf version
```
- Do a manual deploy with `invoke deploy --space dev`
- Test with bad requirements.txt, like `Flask=2222`, make sure build fails
- Test with crashing …
> Implement rolling deployment

- tests/test_committees.py
- tests/test_filters.py
- webservices/common/models/committees.py
- Resolves #4612 
_Updated these endpoints to include sponsor_candidate_id_
'/committee/<committee_id>/history/',
'/committee/<committee_id>/history/cycle/',
'/candidate/<candidate_id>/committees/history/',
'/candidate/<candidate_id>/committees/history/cycle/'
Two developers (required), additional developer optional
- run `pytest` to make sure all tests pass
- Set SQLA_CONN to dev database, and run `./manage.py runserver`
- Check these endpoints and make sure sponsor_candidate_ids is in the output
http://127.0.0.1:5000/v1/committee/C00432104/history/?election_full=true&sort_null_only=false&sort_hide_null=false&sort=-cycle&per_page=20&page=1&sort_nulls_last=false
http://127.0.0.1:5000/v1/committee/C00497677/history/2016/?election_full=true&sort_null_only=false&sort …
> Add sponsor id to committee history endpoint

- webservices/args.py
- webservices/resources/totals.py
- Resolves #4462
Remove unnecessary filters for `/committee/committee_id/totals` 
One requested, any others appreciated
- Run this branch
- Check out swagger (http://localhost:5000/developers/#/financial/get_committee__committee_id__totals_), make sure that `/committee/committee_id/totals` doesn't have type and designation filters
- Try a query with old filters (should be ignored): http://localhost:5000/v1/committee/C00703975/totals/?type=P&designation=P
- Try a query without filters (should still work): 
http://localhost:5000/v1/committee/C00703975/totals/
http://localhost:5000/v1/committee/C00703975/totals/?page=1&sort_hide_null=false&per_page=20&sort=-cycle&sort_nulls_last=false&sort_null_only=false
- No impact to …
> Remove unnecessary filters for `/committee/committee_id/totals` 

- README.md
- manifests/manifest_api_dev.yml
- manifests/manifest_api_feature.yml
- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
- manifests/manifest_celery_beat_dev.yml
- manifests/manifest_celery_beat_feature.yml
- manifests/manifest_celery_beat_prod.yml
- manifests/manifest_celery_beat_stage.yml
- manifests/manifest_celery_worker_dev.yml
- manifests/manifest_celery_worker_feature.yml
- manifests/manifest_celery_worker_prod.yml
- manifests/manifest_celery_worker_stage.yml
- manifests/manifest_task_dev.yml.template
- manifests/manifest_task_feature.yml.template
- manifests/manifest_task_prod.yml.template
- manifests/manifest_task_stage.yml.template
- webservices/config.py
- webservices/tasks/__init__.py
Partial resolution for #4393: Use new `aws-redis-elasticache` service
Note: I deleted the old `redis32` service for testing in `dev` and it appears cloud.gov's deprecation process means creating new instances is no longer possible. I didn't realize this, so downloads won't work in the `dev` space if we rebuild the `develop` branch  
One approval requested, other reviewers welcome
- Manually deploy this branch to the dev space
- Test a download
-  Downloads
- Celery tasks - legal docs, MV refresh, elasticsearch backups
> Use new aws-redis-elasticache service

- data/migrations/V0219__update_docquery_https.sql
- tests/test_reports.py
- webservices/common/models/filings.py
- webservices/utils.py
- Resolves #4715: Use `https` for docquery links
- SQL changes: some endpoints use the SQL functions, which are used at the time of creating the MV's:
```
image_pdf_url(image_number text) RETURNS text
report_fec_url(image_number text, file_number integer) RETURNS text
report_html_url(means_filed text, cmte_id text, filing_id text) RETURNS text
report_pdf_url(image_number text) RETURNS text
```
- Python changes: some endpoints use the "`Mixin`" classes in the Python models. The "`Mixin`" use the `utils` functions.
`Mixin` code, for reference:
```python
class PdfMixin(object):
@property
def pdf_url(self):
if self.has_pdf:
return utils.make_report_pdf_url(self.beginning_image_number)
return None
@property
def has_pdf(self):
return self.report_year and self.report_year >= 1993
class …
```
> [MERGE WITH GIT FLOW] [HOTFIX] [Migration V0219] Use https for docquery

- webservices/env.py
- webservices/tasks/utils.py
- Resolves #4719: Fix public s3 bucket
The `get_credential` code in `webservices.env` that retrieves s3 credentials for the API has always taken the first s3 service in the list, which never really mattered because we only had one s3 bucket. When a separate elasticsearch backup bucket was added, this changed the behavior in `webservices.env`  to be unpredictable and, if the repository backup bucket was first in the list, was putting user downloads and public legal docs in the private elasticsearch bucket. 
This PR  either looks for the credentials for the s3 service `fec-s3-api` in the cloud.gov environment, or defaults to what the user has saved in the `AWS_PUBLIC_BUCKET` and `AWS_DEFAULT_REGION` env vars locally.
**On cloud.gov**
- Deploy to `stage` space, test downloads, OR
- branch …
> [Before release] Fix public s3 bucket settings

- requirements.txt
- webservices/legal_docs/statutes.py
- Resolves https://github.com/fecgov/fec-accounts/issues/339
Replace `xml.etree.ElementTree.parse` with its `defusedxml` equivalent
- Run `pytest`
- Test loading statutes: https://github.com/fecgov/openFEC#loading-statutes
-  Loading statutes
> Replace `xml.etree.ElementTree.parse` with its `defusedxml` equivalent

- tests/factories.py
- tests/test_committees.py
- webservices/common/models/links.py
- webservices/resources/committees.py
To display leadership PAC names on candidate profile page, we need add leadership PACs committee rows in endpoint: /candidate/<string:candidate_id>/committees/history/<int:cycle>/
- Resolves #4738
[https://docs.google.com/drawings/d/1eROcEyNgXaKsRC39gQC9AUMfnd2EvYWKGWQqD_T1j9E/edit](https://docs.google.com/drawings/d/1eROcEyNgXaKsRC39gQC9AUMfnd2EvYWKGWQqD_T1j9E/edit)
1) checkout branch, point to dev db
2) pytest
3) test / compare example endpoints on both local and prod:
[https://docs.google.com/spreadsheets/d/1cxZ1kFQP72Yi88cfjbJmV5A0s0UYD_jV/edit#gid=758020012](https://docs.google.com/spreadsheets/d/1cxZ1kFQP72Yi88cfjbJmV5A0s0UYD_jV/edit#gid=758020012)
example 1:
local: http://127.0.0.1:5000/v1/candidate/S4AR00103/committees/history/2020/	
prod: …
> Add leadership pac committee rows in return result

- tests/test_sched_d.py
- webservices/args.py
- webservices/resources/sched_d.py
Resolves #4755
- Add new filters to debts:
```
min_amount_outstanding_beginning
max_amount_outstanding_beginning
min_amount_outstanding_close
max_amount_outstanding_close
```
- Remove broken filters (formerly using `itemized` in `args.py`, copied over the working ones into `schedule_d` in `args.py`
```
min_amount
max_amount
line_number
```
- Rename `amount_incurred` filters to remove `_period` because including these in all the filters makes the names super long
```
min_amount_incurred_period -> min_amount_incurred
max_amount_incurred_period -> max_amount_incurred
```
- Fix broken tests
This style test will still be true, even if the results have extra items that shouldn't be there:
https://github.com/fecgov/openFEC/blob/ba5e5b62dabf0166d3d309878be727273ece4ef0/tests/test_sched_d.py#L70-L7 …
> Add new amount filters to debts

- tests/integration/test_advisory_opinions.py
- webservices/legal_docs/advisory_opinions.py
In entity table, `name` for a individual  type could be empty . In such scenario, the `name`  is populated by concatenating the prefix, first & last names and suffix. 
- Resolves #4744 
One developer required, @patphongs  is optional. 
(@patphongs i am not sure if you have ES setup on your local, that's why i put you as optional. if you have the setup already, please feel free to test this PR)
**In advisory_opinions.py:** 
- Update the AO_ENTITIES SQL to include the prefix, firstname, lastname and suffix columns. 
- Add logic to populate the name column for individual entity type. 
**Add  test_advisory_opinions.py :**
- Add a test case for individual entity type.
**Production (Before fix):**
**Local (After fix):**
- checkout branch: …
> 4744-show-entity-names-for-individual-types

- tests/integration/test_advisory_opinions.py
- webservices/legal_docs/advisory_opinions.py
Data reload tasks are failing - `python manage.py load_advisory_opinions` or `cf run-task api --command "python manage.py refresh_current_legal_docs_zero_downtime" -m 4G --name refresh_data` due to NULL values in prefix, suffix and firstname columns in the entity table. 
Use the COALESCE function and check for empty or null values on prefix, suffix, first and lastname columns on the entity table and replace with an empty string if found any. 
- ~Resolves~ Related #4443 
- In advisory_opinons.py,  AO_ENTITIES SQL:  check for empty or null values on prefix, suffix, first and lastname columns and replace with an empty string if found any.
- Add a test case with empty/null values in the prefix,suffix columns for individual enitity. …
> fix-ao-data-load-issue

- data/migrations/V0220__add_ofec_committee_bank_vw.sql
- data/migrations/V0221__bank_ofec_filings_all_mv.sql
- tests/test_filings.py
- webservices/common/models/filings.py
- webservices/docs.py
- Resolves #4751
- Primary bank information and additional bank names are added to filing endpoints.  The data will also be available on downloads
- ofec_committee_bank_vw is created to hold bank data.  ofec_filings_all_mv is refactored to include bank data
- Run `pytest` to make sure all tests pass
- Run `flyway migrate` to make sure migration run successfully
- To test endpoint, switch model: models/filings.py to tmp table and rub endpoint on local
`class Filings(FecFileNumberMixin, CsvMixin, db.Model):
__tablename__ = 'ofec_filings_all_mv_tmp_hc'`
api: 
http://127.0.0.1:5000/v1/filings/?sort=-receipt_date&sort_nulls_last=false&sort_hide_null=false&sort_null_only=false&per_page=20&page=1&form_type=F1
http://127.0.0.1:5000/v1/filings/?per_page=20&sort_hide_null=f …
> [WIP]Adding bank information to filing endpoint and Form 1 download

- package-lock.json
- package.json
- Resolves #4766 
Feel free to add/remove
Bumped the version of lodash from 4.17.20 to 4.17.21, just a patch-level change
None
None
- pull branch
- `npm i`
- `npm run build` will tell us if lodash failed as a devDependency
- `./manage.py runserver`
- [localhost](http://127.0.0.1:5000/) should work as expected
- Looking at the release notes for lodash, it looks like only `trim()` and `baseTrim()` were affected and they were used by `isNumber()`. It doesn't looks like swagger-tools is using any of the three
____
> 4766 bump lodash 4.17.20 > 4.17.21

- webservices/docs.py
- Resolves #4772
-  Add bulk schedule A data dump information to the API documentation
- Bulk schedule A data dump information has been added to the "receipts" section on API swagger page
**Before:**
**After:**
Or Download feature branch and ran api on local to see the change: http://127.0.0.1:5000/developers/#/receipts
> Add bulk schedule A data dump information to API documentation

- tests/integration/test_tsvector_generation.py
- tests/test_itemized.py
- webservices/common/views.py
- webservices/resources/sched_a.py
- webservices/resources/sched_b.py
- webservices/resources/sched_e.py
- Resolves #4414 and resolves #4740: Use `UNION ALL` subqueries for either committee ID **or** two-year-transaction period for Schedules A & B
The `union_all_field` values are checked in the order they're specified in the resource file. The first `union_all_field` encountered is used to keep the number of subqueries manageable.
Example: For schedule A and B, if 1 or 0 committee ID's are passed to the query and more than one two-year transaction period is being searched, use `UNION ALL` the same way we currently do for multiple committeeIDs. Because we're only doing `UNION ALL` for either committee ID **or** two-year-transaction period, the most subqueries we would ever have is 10 committee IDs OR ~26 two-year-transaction-periods. The required secondary index for multiple two-year …
> Use `UNION ALL` subqueries for 2-year-transaction-period for Schedules A and B

- webservices/resources/sched_a.py
- webservices/resources/sched_b.py
- Resolves #4820
Remove 2-year-transaction period from UNION ALL fields
@dzhang-fec and @fec-jli please
-  Schedule A and B query logic
#4802
See #4802 - this effectively reverts that change but keeps code improvements and automated tests
None
> [Merge to release] Remove 2-year-transaction period from UNION ALL fields

- data/migrations/V0223__update_report_pdf_url_or_null.sql
- data/migrations/V0224__ofec_filings_all_mv_pdfurl.sql
- tests/integration/test_filings.py
- Resolves #4821 
- Modify database function report_pdf_url_or_null to include more historical records
@pkfec @fec-jli 
Optional @fecjjeng 
"pdf_url" returned by these endpoints:
/filings/ 
/committee/<committee_id>/filings/ 
/candidate/<candidate_id>/filings/
- Checkout feature branch
- Run `pytest`;  Run `flyway migrate`
- "ofec_filings_all_mv_tmp_hc" was created to compare data change:
count change of Null pdf_url
before: 1018721  vs  after: 850320
```
select count(*)
from public.ofec_filings_all_mv
where pdf_url is  null; 
select count(*)
from public.ofec_filings_all_mv_tmp_hc
where pdf_url is null;
```
- Majority of newly added pdf_url …
> Modify report_pdf_url_or_null to generate image links

- data/migrations/V0225__add_fec_fitem_sched_ab_2021_2022.sql
Resolves #4796 
create fec_fitem_sched_a_2021_2022 and fec_fitem_sched_b_2021_2022 partition tables and related objects.
update finalize_itemized_schedule_a_tables and finalize_itemized_schedule_b_tables functions to simplify and streamline the index creation process when new child partition tables are created.
This is database work.  Only requires database team to review.
None
branch | PR
- download the branch to local machine, invoke create_sample_db process. Make sure migration executed successfully.
- Connect to local_db, verify fec_fitem_sched_a_2021_2022 and fec_fitem_sched_b_2021_2022 tables and the indexes created successfully.
select tablename
from pg_tables
where tablename …
> Add fec_fitem_sched_a/b_2021_2022 partition tables and related objects

- data/migrations/V0226__modify_report_pdf_url_or_null.sql
- tests/integration/test_filings.py
- Resolves #4821 
Replace 'report_year >=1996' with 'report_year >1996'
@fec-jli @lbeaufort 
"pdf_url" returned by these endpoints:
/filings/
/committee/<committee_id>/filings/
/candidate/<candidate_id>/filings/
- Checkout feature branch; Run pytest; Run flyway migrate
- Run api on local and check changes in endpoints.  "ofec_filings_all_mv_tmp_hc" was created to compare data change:
In models/filings.py, switch to temp mv
```
class Filings(FecFileNumberMixin, CsvMixin, db.Model):
tablename = 'ofec_filings_all_mv_tmp_hc'
```
**Before**
https://www.fec.gov/data/committee/C00302695/?tab=filings&cycle=1996
**After**
http://127.0.0.1:5000/v1/filings/?sort=-receipt_date&sort_nulls_last=false&sort_null_only=false&committee_id=C00302 …
> Modify function report_pdf_url_or_null using report_year>1996

- requirements.txt
Currently, we are using networkx==1.11 and keep getting Snyk-High Vulnerability-Deserialization of Untrusted Data. The latest version of networkx==2.5.1, which released 0n 04/03/2021. [https://pypi.org/project/networkx/](https://pypi.org/project/networkx/). so this PR is to upgrade networkx==>2.5.1, even though v2.5.1 won't fix that Vulnerability, but we are ready to upgrade to the next major release which will fix the Vulnerability by networkx's announcement. 
- Partial Resolve #4818 
one backend developer
refresh our materialized views
requirements.txt
2)`pip install -r requirements.txt`
pip freeze to check networkx==2.5.1
3)pytest
4)run: `snyk test --file=requirements.txt --package-manager=pip`
you will …
> Upgrade networkx to 2.5.1

- webservices/rest.py
Cache committee and candidate totals endpoint.
- Resolves https://github.com/fecgov/openFEC/issues/4745
In rest.py add logic to cache `/totals` endpoint
@lbeaufort @fec-jli 
-  API Umbrella cache 
**In Production, candidate and committee `/totals` endpoint are cached for 1 hour (default cache setting, max_age=3600sec):**
run: `curl -svo /dev/null "https://api.open.fec.gov/v1/candidate/H8NJ01077/totals?election_full=True&cycle=1998&api_key=DEMO_KEY"`
run: `curl -svo /dev/null "https://api.open.fec.gov/v1/committee/C00302695/totals/?per_page=20&page=1&sort_hide_null=false&sort_nulls_last=false&sort_null_only=false&sort=-cycle&api_key=DEMO_KEY"`
**In this feature branch,  candidate and committee `/totals` endpoint are cached …
>  Cache cmte and cand totals endpoint.

- README.md
- webservices/common/models/base.py
- webservices/rest.py
- Partial resolution for #4843
Simplify follower (`SQLA_FOLLOWERS`) logic. The existing "choose a random replica" and "route schedule A traffic to one replica" logic is no longer needed as we have one connection string for the AWS aurora reader endpoints. The existing logic adds complexity and a little bit of latency, so it's a win-win to simplify the logic.
I did some [double-checking Locust testing](https://docs.google.com/spreadsheets/d/19v6WS0M533zqC63h--dOZJ2HQf7edfvXQRoSmyhfm2Y/edit#gid=0) (results can vary between tests) and the results seemed slightly faster, but this amount of performance improvement should be pretty negligible. 
2 of the selected reviewers, please
-  "Under the hood" logic for connecting to …
> Simplify follower (`SQLA_FOLLOWER`) logic

- webservices/rest.py
Cache committee and candidate totals endpoint.
- Resolves https://github.com/fecgov/openFEC/issues/4745
In rest.py add logic to cache `/totals` endpoint
@lbeaufort @fec-jli 
-  API Umbrella cache 
**In Production, candidate and committee `/totals` endpoint are cached for 1 hour (default cache setting, max_age=3600sec):**
run: `curl -svo /dev/null "https://api.open.fec.gov/v1/candidate/H8NJ01077/totals?election_full=True&cycle=1998&api_key=DEMO_KEY"`
run: `curl -svo /dev/null "https://api.open.fec.gov/v1/committee/C00302695/totals/?per_page=20&page=1&sort_hide_null=false&sort_nulls_last=false&sort_null_only=false&sort=-cycle&api_key=DEMO_KEY"`
**In this feature branch,  candidate and committee `/totals` endpoint are cached …
>  cache-cmte-and-cand-totals-endpoint.

- data/migrations/V0227__modify_report_fec_url.sql
- tests/integration/test_filings.py
- Resolves #4053 
- Modify the database function to handle scenario when file number is null
Two backend developers
​/candidate​/{candidate_id}​/filings​/
​/committee​/{committee_id}​/filings​/
​/filings​/
/committee/{committee_id}/reports/
/reports/{committee_type}/
- Download feature branch to local
- Run `pytest` to make sure all tests pass
- Run `flyway migrate` to make sure migration runs no error
- Check data change in endpoints.  When file_number is null, these endpoints will not have `fec_url` in output.
- Change the below on local model file:  webservices/common/models/filings.py
```
class Filings(FecFileNumberMixin, CsvMixin, db.Model):
__tablename__ = 'ofec_filings_all_mv_tmp_hc'
```
**filing endpoint**
before change:
https://api.open.fec.gov/v1/filings/?api_key=DEMO_KEY&sort=-r …
> Modify database function report_fec_url 

- webservices/schemas.py
Schedule B efiling export downloading same row 100,000 times
- Resolves [#4825 ](https://github.com/fecgov/openFEC/issues/4825)
two backend developers
schems.py
disbursement--raw data--download 
2)two optionals to test
a)deploy to stage space, test disbursement--raw data--download 
b)follow the wiki to setup Redis, Celery-worker on local to test disbursement--raw data--download.
[Set up Redis, Celery on local and test the task](https://github.com/fecgov/openFEC/wiki/Set-up-Redis,--Celery-on-local-and-test-the-tasks)
3)ex url like this: you can filter some data to export
https://stage.fec.gov/data/disbursements/?data_type=efiling&committee_id=C00702944
> fix schedule_b efile download multi same rows

- data/migrations/V0228__modify_ofec_totals_combined.sql
- tests/test_totals.py
- webservices/common/models/totals.py
Resolves #4872: 
- Add new fields to `/totals/committee_type/` endpoint:
- `treasurer_name`
- `committee_state`
- `filing_frequency`
- `filing_frequency_full`
- `first_file_date` 
- Add tests
**Notes**
- This change only applies to types `pac-party`, `pac`, and `party`, and **not** `presidential`, `house-senate`, or `ie-only` (fields won't appear)
- I'm hoping to rename this endpoint later to `/totals/entity_type/` endpoint because `committee_type` means specifically the 1-letter code FEC uses. I didn't want this PR to get too big.
- @hcaofec if you could please review the database changes
- @fec-jli and/or @pkfec, thank you!
**fec.gov**
- Committee profile pages (totals should be unchanged, only adding fields)
- (feature in progress) PAC/Party datatable
**API**
- …
> Add fields to /totals/pac-party/

- manifests/manifest_celery_worker_dev.yml
- manifests/manifest_celery_worker_prod.yml
Allocate more memory to worker instances in Production to address worker out of memory issues happening more frequently in production.
- Related issue #4864 
- Reduce worker memory to 512M in manifest_celery_worker_dev.yml
- Increase worker memory to 1.5G  manifest_celery_worker_prod.yml
-  Any one backend developer.
-  Downloads, Scheduled tasks.
> Update celery worker memory

- tests/test_downloads.py
- tests/test_reports.py
- tests/test_totals.py
- webservices/args.py
- webservices/docs.py
- webservices/exceptions.py
- webservices/resources/reports.py
- webservices/resources/totals.py
- webservices/rest.py
- Resolves #4886
Rename `/totals/<string:entity_type>/` and `/reports/<string:entity_type>/` endpoints to use `entity_type` instead of `committee_type`
2 developers, please
-  No user impact - only under the hood.
- Try queries for `/totals/<string:entity_type>/`:  http://localhost:5000/v1/totals/pac-party/?sort_nulls_last=false&sort=-committee_id&sort_null_only=false&per_page=20&sort_hide_null=false&api_key=DEMO_KEY&cycle=2022&page=1
- Try queries  for `/reports/<string:entity_type>/` …
> Rename totals and reports endpoints to use `entity_type` instead of `committee_type`

- tests/test_totals.py
- tests/test_utils.py
- webservices/common/models/totals.py
- webservices/schemas.py
- webservices/utils.py
Resolves #4877
- Add percentages to support PAC snapshot
- Handle unusual data scenarios (see #4876)
Two developers requested, others welcome
Add 4 new fields to /committee/<committee_id/totals endpoint (feeds committee profile page totals):
- `individual_contributions_percent`
- `party_and_other_committee_contributions_percent`             
- `contributions_ie_and_party_expenditures_made_percent`                
- `operating_expenditures_percent`
- Test unusual data scenarios: https://docs.google.com/spreadsheets/d/18Wt98l1lN4tMCAzzLcQOMpCxpAT5I_zoLGZAfiKPVc4/edit#gid=0
- Test a few committees: http://localhost:5000/v1/committee/<EXAMPLE_COMMITTEE_ID>/totals/?cycle=<EXAMPLE>
> Add percentages to support PAC snapshot

- webservices/docs.py
- Resolves #4848
Fix typo in API docs
One approval requested
> Fix typo in API docs

- data/migrations/V0232__add_totals_fields.sql
- tests/factories.py
- tests/integration/test_integration.py
- tests/test_totals.py
- webservices/args.py
- webservices/common/models/totals.py
- webservices/resources/totals.py
- webservices/schemas.py
- Resolves #4878
Add filters to /totals/entity_type/ to support PAC/Party totals data table
- @hcaofec for database changes
- @fec-jli and/or @pkfec for application changes
- 1 - Modify `ofec_totals_combined_mv` and `ofec_totals_combined_vw` to add:
`treasurer_text` (replaces V0228)
- 2 - Modify `ofec_totals_pac_party_vw` to add:
`treasurer_text` (replaces V0228)
- 3 - Modify `ofec_committee_totals_per_cycle_vw` to add:
`committee_state`
`treasurer_name`,
`treasurer_text`
`filing_frequency`,
`filing_frequency_full`,
`first_file_date`
(replaces V0127)
- 4 - Modify `ofec_totals_house_senate_mv` to add:
`committee_state`
`treasurer_name`,
`treasurer_text`
`filing_frequency`,
`filing_frequency_full`,
`first_file_date`
(replaces …
> Add filters to` /totals/entity_type/`  to support PAC/Party totals data table

- README.md
- Resolves https://github.com/fecgov/openFEC/issues/4907
Remove the old elasticsearch management command from the README.md file
Atleast one backend developer
openFEC wiki, README.md
> Remove old elasticsearch command from the documentation.

- data/migrations/V0233__add_sponsors_and_org_type.sql
- data/migrations/V0234__add_ofec_pac_sponsor_candidate_list_per_cycle.sql
- tests/factories.py
- tests/test_committees.py
- tests/test_totals.py
- webservices/args.py
- webservices/common/models/candidates.py
- webservices/common/models/totals.py
- webservices/resources/totals.py
- webservices/schemas.py
- Resolves #4879
Add filters to /totals/entity_type/ to support PAC/Party totals data table: 
- `sponsor_candidate_id` filter and `sponsor_candidate_ids` output field (only entity_type `pac` and `pac-party`)
- `organization_type` output and filter, `organization_type_full` output field
- `sponsor_candidate_list` output field 
- @hcaofec for database changes
- @fec-jli and/or @pkfec for application changes
`/totals/entity_type` and PAC and party data table 
**V0233**
1 - Modify `ofec_totals_combined_mv` and `ofec_totals_combined_vw` to add:
`sponsor_candidate_ids`
`organization_type` and index
`organization_type_full`
Change index on `committee_designation_full` to `committee_designation`
Change index on `committee_type_full` …
> Add leadership sponsor and org type to /totals/by_entity/

- requirements.txt
- Resolves #4836
Upgrade networkx python package from v2.5.1 to v2.6.2
Atleast one backend developer
**With existing networkx 2.5.1:**
**After upgrading networkx 2.6.2:**
- checkout feature/4836-upgrade-networkx
- create/activate new python virtual
- run pip install -r requirements.txt
- run `snyk test --file=requirements.txt --package-manager=pip`
> Upgrade networkx to v2.6.2

- manage.py
- tasks.py
- tests/integration/test_advisory_opinions.py
- webservices/legal_docs/__init__.py
- webservices/legal_docs/advisory_opinions.py
- webservices/legal_docs/es_management.py
Currently, we are unable to delete one or more document from Elasticsearch cluster, the existing delete_from_es() is not working.
After this ticket, we are able to delete all records under a doctype or delete single record under a doctype and a doc_id.
- Resolves #4929 
1)Create two methods: 
**delete_doctype_from_es(index_name=None, doc_type=None)** 
(Deletes all records with the given `doc_type` from Elasticsearch)
**delete_single_doctype_from_es(index_name=None, doc_type=None, num_doc_id=None)**
(Deletes single record with the given `doc_type` and `doc_id` from Elasticsearch)
2)Add **doc_id** column to advisory_opinions documents (don't have before)
3)Fix test_advisory_opinions.py
4)Add one space at the beginning of each log message in es_menagement.py, it is easy for Kibana keyword …
> Create delete doc method from es

- .circleci/config.yml
- Resolves #4933 
Allow OS release info to change
From https://stackoverflow.com/questions/68802802/repository-http-security-debian-org-debian-security-buster-updates-inrelease#comment121618773_68802802
Debian just released "bullseye" (debian.org/News/2021/20210814), so Buster moves into LTS - wiki.debian.org/LTS
Bullseye is brand new and Buster LTS goes through June 2024 so we should stick with Buster for now.
One approval requested, others welcome 
-  CircleCI builds
https://app.circleci.com/pipelines/github/fecgov/openFEC/1078/workflows/c6687d4f-3c85-4fde-8665-156726045b5e/jobs/3548
https://app.circleci.com/pipelines/github/fecgov/openFEC/1079/workflows/6c56f11c-f849-4f22-bea3-87f61de1f9ed/jobs/3552
- See that this build …
> Fix circleCI builds: Allow OS release info to change

- data/migrations/V0235__first_f1_ofec_committee_detail_mv.sql
- webservices/common/models/committees.py
- webservices/docs.py
- Resolves #4928
Add `first_f1_date` to committee detail and committee history endpoints
One developer requested, other reviews welcome
-  Committee profile pages
- Test migration with `dropdb cfdm_test` / `createdb cfdm_test` / `invoke create_sample_db`
- With test data: make these changes (creation script here https://github.com/fecgov/openFEC/pull/4936#issuecomment-900665681):
openFEC/webservices/common/models/committees.py
```
class BaseConcreteCommittee(BaseCommittee):
+    __tablename__ = 'ofec_committee_detail_mv_lb'
class Committee(BaseConcreteCommittee):
__table_args__ = {'extend_existing': True}
+    __tablename__ = 'ofec_committee_detail_mv_lb'
class CommitteeHistory(BaseCommittee):
+ …
```
> Add first Form 1 date to committees endpoints

- tests/test_downloads.py
- tests/test_totals.py
- webservices/args.py
- webservices/resources/totals.py
- Resolves #4947
- Resolves #4946
Fix multi-committee ID filter and downloads
Two developers, please
-  PAC/Party datatable and download
- Either run the CMS and point to your local API or deploy to the `dev` space
- Test downloads: https://dev.fec.gov/data/committees/pac-party/?cycle=2022 and hit "export"
- Test multi-committee search: https://dev.fec.gov/data/committees/pac-party/?committee_id=C00042366&committee_id=C00075820&cycle=2022 (should have two results) …
> Fix multi-committee ID filter and downloads

- webservices/tasks/__init__.py
- webservices/tasks/legal_docs.py
- webservices/tasks/refresh.py
- webservices/tasks/utils.py
During reloading modified legal case(MUR/AF/ADR), we're experiencing two kinds of issue
- 1)miss whole single legal case. (ex: 09/16/2021, miss MUR_7133: https://fecgov.slack.com/archives/C3X34QQNQ/p1631904707013300 )
The cause of this see below explanation. We will coordinate with contractor to fix it.
- 2)miss legal cases's documents: we already put message into Kibana log.
#4364 
[https://github.com/fecgov/openFEC/issues/4361](https://github.com/fecgov/openFEC/issues/4361)
- New cron task to send Slack alerts once a day when there are modified legal case(MUR/AF/ADR) in production. 
- Add 'local' to APP_NAME when testing on local
- Add comments to each cron task.
- Clean some codes and change string value with single quote to double quote 
one backend developer is ok, two developers are …
> Send Slack alerts when found modified legal case (ADR/AF/MUR)

- webservices/tasks/refresh_db.py
When the daily refresh db materialized views fails, the error message should be posted to slack #alerts channel.
- Resolves #4901 
modify tasks/refresh_db.py exception section to send error message to Slack #alerts and #bots channels
One developer is good, more are welcome.
schedule task
Option 1: Local test:
- Following wiki setup local env, make sure Redis, celery-beat, celery-worker, api work well: https://github.com/fecgov/openFEC/wiki/Set-up-redis-and-celery-on-local-and-test-the-tasks
- Modify tasks/__init__.py file, task:refresh_materialized_views to every 2 mins.
```
"send_alert_ao": {
"task": "webservices.tasks.refresh_db.refresh_materialized_views",
"schedule": crontab(minute="*/2"),
},
```
- Modify tasks/refresh_db.py, add test code `10 * (1 / 0)` in line 27
- start celery-beat …
> Send to slack alerts and bots channels error message when refresh db fails

- requirements.txt
circleci build failed when tried to merge pr https://github.com/fecgov/openFEC/issues/4901 . From error stack trace its appear that  `psycopg2-binary` v2.7.1  is causing the build issue.
```
Running setup.py install for psycopg2-binary: finished with status 'error'
ERROR: Command errored out with exit status 1:
```
circleci builds run OK after upgrading python package `psycopg2-binary` version to 2.9.1  in requirements.txt 
one developer is must
- circleci build  on openFEC repo: cannot deploy the openFEC app to prod; cannot rerun previous builds
Here is the latest circleci build after **upgrading psycopg2-binary version from 2.7.4 to 2.9.1**: https://app.circleci.com/pipelines/github/fecgov/openFEC/1144/workflows/dd7744dc-31dd-4f12-a0f4-3baae39451a7/jobs/3624
- rebuild this feature …
> upgrade-psycopg2-binary-fix-circleci-build

- requirements.txt
circleci build failed when tried to merge pr https://github.com/fecgov/openFEC/issues/4901 . From error stack trace its appear that  `psycopg2-binary` v2.7.1  is causing the build issue.
```
Running setup.py install for psycopg2-binary: finished with status 'error'
ERROR: Command errored out with exit status 1:
```
circleci builds run OK after upgrading python package `psycopg2-binary` version to 2.9.1  in requirements.txt 
one developer is must
- circleci build  on openFEC repo: cannot deploy the openFEC app to prod; cannot rerun previous builds
Here is the latest circleci build after **upgrading psycopg2-binary version from 2.7.4 to 2.9.1**: https://app.circleci.com/pipelines/github/fecgov/openFEC/1144/workflows/dd7744dc-31dd-4f12-a0f4-3baae39451a7/jobs/3624
- rebuild this feature …
> [MERGE WITH GITFLOW] upgrade-psycopg2-binary-fix-circleci-build

- data/migrations/V0238__add_first_f1_index.sql
- tests/test_committees.py
- webservices/common/models/committees.py
- Resolves #4975 
Adds index for first_f1_date to committee history and detail to allow for registration date sorting on committees datatable. 
1-2 reviewers, but more are welcome!
-  Committees endpoint
Before:
After:
- https://fec-dev-api.app.cloud.gov/v1/committees/?sort_null_only=false&sort=first_f1_date&api_key=DEMO_KEY&sort_nulls_last=false&page=1&sort_hide_null=false&per_page=20
- http://127.0.0.1:5000/v1/committees/?sort=first_f1_date&page=1&sort_hide_null=false&sort_nulls_last=false&sort_null_only=false&per_page=20
In addition, I added a test for the sort. Any and all feedback is very welcome :)
> 4975-Make API changes to allow for registration date default sort

- data/migrations/V0239__ofec_sched_b_aggregate_recipient_mv.sql
- manage.py
- tests/test_aggregates.py
- webservices/common/models/aggregates.py
- webservices/flow.py
- webservices/schemas.py
Add the total disbursements percents to`schedule_b_by_recipient` endpoint
- Resolves #4988 
- Add a new property`recipient_disbursement_percent` and compute the percentages inside common/models/aggregates.py `ScheduleBByRecipient` class.
- Add a migration file to include committee total disbursements which will be used to calculate recipient disbursements percentages and results are added to schedule_b_by_recipent endpoint.
- Add the new migration file to the daily mv refresh list in manage.py
- Add migration file dependency in flow.py
- Add required schema/pageschema for schedule_b_by_recipent in schemas.py
- Update the existing `test_disbursement_recipient` test case to include the new output columns.
- One backend developer is must. @patphongs you are optional
- Display the …
>  Add disbursement percents to schedule_b_by_recipient endpoint

- webservices/tasks/__init__.py
- webservices/tasks/legal_docs.py
In this PR, we modify the AO reload task function to handle multiple AOs to elasticsearch
that include two functions: 
`refresh_most_recent_aos()`
`daily_reload_all_aos_when_change()`
- Resolves #4976 
modify tasks/legal_docs.py `refresh_most_recent_aos()` and `daily_reload_all_aos_when_change()` functions to handle multiple AOs and send AO detail information in Slack.
One developer is good, more are welcome.
schedule task for reload multiple modified AOs
Only local test:
- Checkout branch, create your test branch and into virtual env.
- Set SQLA_CONN to point dev read-only
- Reference wiki disable redis_url in webservices/tasks/__init__.py https://github.com/fecgov/openFEC/wiki/Set-up-redis-and-celery-on-local-and-test-the-tasks 
We only need three terminals for this PR test: Redis, …
> Modify reload AOs to handle multiple AOs to ES

- .circleci/config.yml
- Resolves #5030 
This narrows the previous CircleCI fix to just changes in the 'Suite' value. After researching the issue and reading the --allow-releaseinfo-change documentation, I confirmed the logic of the current solution and the secuirty risk of missing updates to dependencies by allowing all. I found [this addition](https://stackoverflow.com/questions/68849201/disadvantage-of-using-allow-releaseinfo-change-for-apt-get-update) to mitigate the risk by using specialties, specifically narrowing just to 'Suite' instead of all release info values.  
1-2 reviewers
-  CircleCI builds
I ran the old code to confirm the solution logic still fails:
https://app.circleci.com/pipelines/github/fecgov/openFEC?branch=circleci-test-build- …
> 5030-Narrow fix to suite value

- webservices/legal_docs/current_cases.py
Elasticsearch service throws a 404 error trying to delete a unpublish case (MUR, ADR or AF) from the website. 
- Resolves #5013 
- Remove the double quotes surrounding the id, when a case is deleted by its id.
One developer
-  Enforcements/MUR, ADR and AF 
-
> Fix 404 error when a case is unpublished

- manifests/manifest_celery_worker_dev.yml
- Resolves #5046
- upgrade worker memory to 1GB in manifest_celery_worker_dev.yml
One developer
-  Celery worker in `Dev` space
> [Dev space] upgrade worker memory to 1GB 

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5006 
This PR upgrade flyway to version 8.4.3
1-2 developer
1. Run flyway on local, with version 5.2.4, this warning message will appear:
2. Install 8.4.3 and run flyway on local, this warning is gone.
3. The feature branch was deployed to dev space and here is circleci log:
https://app.circleci.com/pipelines/github/fecgov/openFEC/1232/workflows/5ebc8c92-5fce-4396-b845-41836395b415/jobs/3726
> Upgrade flyway to 8.4.3

- data/migrations/V0242__add_3_columns_ofec_candidate_totals_mv.sql
Show totals of individual contributions, transfers from other committees and other committee contributions for all House and all Senate across time feature.
Add these three new columns into ofec_candidate_totals_mv:
1)individual_itemized_contributions (Line 11a(i))
2)transfers_from_other_authorized_committee (Line 12)
3)other_receipts (Line 11c)
- Resolves #5028 
This PR is part 1 of resolve issue #5028.
Part 2 is to modify endpoint return these three columns: candidates/totals/by_office/
1-2 database developer(s)
ofec_candidate_totals_mv
2) 
```
dropdb cfdm_unit_test
createdb cfdm_unit_test
```
3)pytest
4)Check data on test mv: public.ofec_candidate_totals_mv_tmp_jl
SELECT * FROM …
> Add three new columns into ofec_candidate_totals_mv migration file

- .circleci/config.yml
API app is running on postgres v13.14 (released on Dec 3, 2021 ). Upgrade circleci postgres docker image from v10.11 to v13.5 (this is the latest version available in 13.X, (released on Dec 7, 2021 ))
- Resolves #5004
- Ref ticket(s)
-  https://github.com/fecgov/openFEC/issues/5002
- https://github.com/fecgov/openFEC/issues/4993
- https://github.com/fecgov/openFEC/issues/5001
one developer
-  circleci postgres docker image
Before:
After:
-  rerun circleci build on `feature/upgrade-postgres-circleci-docker-image` branch. …
> upgrade postgres circleci docker image

- data/migrations/V0243__fix_columns_name_ofec_candidate_totals_mv.sql
Show totals of individual contributions, transfers from other committees and other committee contributions for all House and all Senate across time feature.
Add these three new columns into ofec_candidate_totals_mv:
1)individual_itemized_contributions (Line 11a(i))
2)transfers_from_other_authorized_committee (Line 12)
3)other_political_committee_contributions (Line 11c)
- Resolves #5028 
This PR is part 2 of resolve issue #5028.
Part 2 is to modify endpoint return these three columns: candidates/totals/by_office/
1-2 database developer(s)
ofec_candidate_totals_mv
2) 
```
dropdb cfdm_unit_test
createdb cfdm_unit_test
```
3)pytest
4)Check data on test mv: public.ofec_candidate_totals_mv_tmp_jl
SELECT * FROM …
> Switch column other_receipts to other_political_committee_contributions

- webservices/legal_docs/current_cases.py
- Resolves #5053
Add "order by dates asc" to af_dispositions query.  
One developer
The feature branch has been deployed to dev space to test the change.  Local test can be done by following these steps:
1. Download feature branch and run `pytest`
2. Follow the wiki (https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-setup-and-test-locally) set up Elasticsearch  7.4 on local, and load 4202 
`python manage.py load_admin_fines -s 4202`
3. start `./manage.py runserver`,  check this api and the af_disposition is listed chronologically
http://127.0.0.1:5000/v1/legal/docs/admin_fines/4202
**Before**:
**After**:
> Add "order by" to af_dispositions

- webservices/args.py
- webservices/docs.py
- webservices/resources/reports.py
- Resolves #5043 
Removes the old `type` filter which was replaced by the `committee_type` filter per our deprecation policy. 
1-2 devs
-  financials/reports/{entity_type} endpoint
-#[5042](https://github.com/fecgov/openFEC/pull/5042)
-Try queries for financials/reports/string:entity_type/ using the new committee_type filter, the old filter,  and check that `type` is no longer shown 
-https://api.open.fec.gov/v1/reports/presidential/?committee_type=P&sort=-coverage_end_date&sort_nulls_last=false&page=1&api_key=DEMO_KEY&sort_hide_null=false&sort_null_only=false&per_page=20
-https://127.0.0.1:5000/v1/reports/presidential/?committee_type=P&sort=-coverage_end_date&sort_nulls_last=false&page=1&api_key=DEMO_K …
> 5043- Remove type filter

- package-lock.json
- package.json
- Resolves #5075 
Upgrades braintree/sanitize-url to v.6.0.0 remediate vulnerabilities to Cross-site Scripting (XSS) due to improper sanitization in sanitizeUrl function.
1-2 devs 
-  openFEC
Before:
After:
- run `snyk test` locally on develop to confirm vulnerability
`snyk test --file=requirements.txt --package-manager=pip`
`snyk test --file=package.json`
- `npm install && npm run build`
- run `snyk test` 
you should see one less vulnerability (see screenshots above)
Also--- thank you @pkfec and @fec-jli (I got most of these snyk instructions from you both!)
> 5075-upgrade braintree/sanitize-url

- webservices/args.py
- webservices/common/models/candidates.py
- webservices/resources/candidate_aggregates.py
- webservices/rest.py
- webservices/schemas.py
This new endpoint `/candidates/totals/aggregate/` will consolidate other /candidates/totals/by_xxxx endpoints.
With passing parameters:
```
"aggregate_by": 
[
""
"office", 
"office-state", 
"office-state-district", 
"office-party"
]
```
- Resolves #5026 
**Page One** (three endpoint call)
1)aggregate_by=office; office=H; election_year=2022
sample endpoint url:
```/candidates/totals/aggregate/?aggregate_by=office&election_year=2022&election_full=true&is_active_candidate=true&per_page=100&office=H```
local url:
http://127.0.0.1:5000/v1/candidates/totals/aggregate/?aggregate_by=office&election_year=2022&election_full=true&is_active_candidate=true&per_page=100&office=H
2)aggregate_by=office-party; office=H; election_year=2022
sample endpoint url: …
> Add endpoint /candidates/totals/aggregate/

- tests/test_aggregates.py
- webservices/args.py
- webservices/docs.py
- webservices/resources/candidate_aggregates.py
- webservices/rest.py
After create new endpoint: /`candidates/totals/aggregates/`, we need add test cases.
- Resolves #5092
- Ref PR #5090 
1 developer
endpoint: /`candidates/totals/aggregates/`
- Checkout branch, point to dev db
- `pytest`
- test endpoint /`candidates/totals/aggregates/` by passing each aggregate_by parameter.
> Add test case in CandidateTotalAggregateView

- requirements.txt
When checking snyk [https://app.snyk.io/org/fecgov/project/a95ea997-b012-4b3b-a026-2fdbe6ac0398](https://app.snyk.io/org/fecgov/project/a95ea997-b012-4b3b-a026-2fdbe6ac0398), get gitPython-Regular Expression Denial of Service (ReDoS) vulnerability 
- Resolves #5065 
0ne developer
api
- Check out dev branch
- run `snyk test --file=requirements.txt`, you will see gitpython warning.
-  Checkout this branch
- `pip freeze` make sure gitpython=3.1.27, make sure install new version gitpython
- run again `snyk test --file=requirements.txt`,  gitpython issue remove.
- `pytest`
- test endpoints
> [MERGE BEFORE 4/19 RELEASE DEPLOYED]5058-upgrade GitPython from 3.1.0 to 3.1.27

- tests/test_aggregates.py
- webservices/args.py
- webservices/resources/candidate_aggregates.py
For the new endpoint: `/candidates/totals/aggregates/`, we need combination sort function (ex, sort by state and district). 
This PR will:
1) Fix combination fort
2) Add filter by `party` and test case.
3) Show how to use combination sort function.
- Resolves #5102 
1 developer. more welcome
endpoint: `/candidates/totals/aggregates/`
- Checkout branch
- `pytest`
- Test URLs:
1)Test combination sorting
How to pass multi sort arguments?
ex: `sort=-election_year&sort=state&sort=district`
(Use - for descending order)
[http://127.0.0.1:5000/v1/candidates/totals/aggregates/?sort=-election_year&sort=state&sort=district&sort_null_only=false&election_year=2020&sort_nulls_last=false&per_page=20&aggregate_by=office-state-district&is_active_candidate=true&page=1&election_full=true&office=H&sort_hide_n …
> Fix sort function for CandidateTotalAggregateView

- requirements.txt
This PR will upgrade Ujson from 1.33 to the latest 5.2.0 and try to solve the Snyk issue : Out-of-Bounds Write.
Also, Make the requirements.txt sorting alphabetically.
- Resolves #5058
Ref PR: [https://github.com/fecgov/openFEC/pull/3891](https://github.com/fecgov/openFEC/pull/3891)
replace  PR[https://github.com/fecgov/openFEC/pull/5080](https://github.com/fecgov/openFEC/pull/5080)
1-2 developers
-  Encoding Content-Security-Policy report.
- Create new virtual env and activate it:  
`pyenv virtualenv 3.7.12 api3712`
`pyenv activate api3712`
- Checkout branch
- Run these commands:
`rm -rf node_modules/`
`pip install -r requirements.txt`
`pip install -r requirements-dev.txt`
`npm install`
`npm run build`
- Check Ujson version(ujson==5.2.0) installed: `pip freeze`
- `pytest`
- `./manage.py …
> Upgrade Ujson to 520

- data/migrations/V0246__add_PK_to_dsc_sched_aggregate_tables.sql
- #5110 
add primary key to dsc_sched_a/b_aggregate tables to utilize AWS DMS to synchronize the data between PROD/STAGE/DEV databases.
This is database work. Only requires database team to review.
-  
branch | PR
download the branch to local machine, invoke create_sample_db process. Make sure migration executed successfully.
Connect to local_db, verify the primary key and corresponding index created successfully.
select tablename, indexname from pg_indexes
where schemaname = …
> add primary_key to dsc_sched_aggregate tables

- tests/test_aggregates.py
- webservices/args.py
- webservices/resources/candidate_aggregates.py
- webservices/schemas.py
Add total_debts to candidates/totals/aggregates/
- Resolves #5115 
1 developer
candidates/totals/aggregates/
- Checkout branch
- pytest
- Test candidates/totals/aggregates/ to make sure return column: total_debts_owed_by_committee
ex url: 
http://127.0.0.1:5000/v1/candidates/totals/aggregates/?sort_nulls_last=false&per_page=20&sort_hide_null=false&sort=-election_year&page=1&sort_null_only=false&is_active_candidate=true&election_year=2020&aggregate_by=office&election_full=true
> Add total debt to candidates/totals/aggregates/

- README.md
- manifests/manifest_celery_beat_dev.yml
- manifests/manifest_celery_beat_feature.yml
- manifests/manifest_celery_beat_prod.yml
- manifests/manifest_celery_beat_stage.yml
- manifests/manifest_celery_worker_dev.yml
- manifests/manifest_celery_worker_feature.yml
- manifests/manifest_celery_worker_prod.yml
- manifests/manifest_celery_worker_stage.yml
- requirements-dev.txt
- requirements.txt
**This is due 03/29/22 so we need to get it in upcoming release**
Upgrade to Celery 5.x has breaking changes:
- command to start the celery app has changed:
>      - celery --app webservices.tasks  beat 
>      - celery --app webservices.tasks worker
- minimum required kombu version is 5.0.0
- Resolves #5017
- Reference pr #4895
Upgrading Celery for Snyk recommended remediation path caused compatibility errors when installing  requirements.
So I updated Click and Vine as well,   Now requirements can be installed without error and Pytest passes, 
1. Update click python package in:   requirements-dev.txt
2. Update celery, kombu, redis python packages in:   requirements.txt
3. Update the celery startup command in dev/feature/stage and prod manifest files 
Two backend developers must. …
> [High Priority]  Fix Snyk vulnerability: Upgrade celery, vine, click

- tests/test_itemized.py
- tests/test_operations_log.py
- webservices/args.py
- webservices/docs.py
- webservices/exceptions.py
- webservices/resources/sched_a.py
- Resolves #5094
Validation is added for the input of image_number field.  This field should be numeric only. If non-numeric value is passed as image number, 422 will return by endpoint.
2 developers, more is welcome.
Any input field that is for an image number
- Run `pytest` on local
- Start api on local
1) Pass invalid ibeginning_image_number
http://127.0.0.1:5000/v1/filings/?beginning_image_number=fec-140000&sort_hide_null=false&sort_nulls_last=false&sort=-receipt_date&sort_null_only=false&per_page=20&page=1
2) Pass invalid min_image_number
http://127.0.0.1:5000/v1/schedules/schedule_c/?sort_null_only=false&per_page=20&min_image_number=FEC-77891&page=1&sort_nulls_last=true&sort_hide_null=false&sort=-incurred_date
> Add validation to image_number field

- .circleci/config.yml
- README.md
- requirements-dev.txt
- runtime.txt
Upgrade openFEC repo to use python v3.8.x 
Helpful [FEC WIki page](https://github.com/fecgov/openFEC/wiki/Updating-Python) for considerations when updating python locally and at the app level: 
- Resolves #4959
- Reference PR #5084, #3961:
1. Upgrade python runtime version to 3.8.x in setup.py
2. Update circleci python docker image version to 3.8.12-buster in circleci/config.yml
3. Update  python version in README.md file
4. Upgrade locustio  package to python 3.8.x compatible version in requirements-dev.txt
Two backend developers must
-  Circleci builds, Locust tests, API app deployment
(https://github.com/fecgov/openFEC/pull/5084) 
- `git checkout …
> 4959-upgrade-python-3.8.x

- package-lock.json
- package.json
- requirements.txt
- Resolves #5125 
Pins async to 2.6.4 to remove vulnerability to Prototype Pollution. We do not currently use the affected MapValues() method, but I thought it would be a good idea to upgrade just in case. I also pinned gevent to 20.4.0 as I could not get requirements.txt to install with pip version 22 without upgrading. 
1-2 devs
- run `snyk test` locally on develop to confirm vulnerability
`snyk test --file=package.json`
You should see the prototype pollution vulnerability
- `pyenv install 3.8.12` (if not already installed)
- `pyenv virtualenv 3.8.12 venv-api3812` 
- `pyenv activate venv-api3812`
- `npm install && npm run build`
- run `snyk test …
> 5125-Snyk Prototype Pollution upgrade async

- package-lock.json
- package.json
- Resolves #5125 
Pins async to 2.6.4 to remove vulnerability to Prototype Pollution. We do not currently use the affected MapValues() method, but I thought it would be a good idea to upgrade just in case. 
1-2 devs
- run `snyk test` locally on develop to confirm vulnerability
`snyk test --file=package.json`
You should see the prototype pollution vulnerability
- `pyenv install 3.8.12` (if not already installed)
- `pyenv virtualenv 3.8.12 venv-api3812` 
- `pyenv activate venv-api3812`
- `npm install && npm run build`
- run `snyk test --file=package.json` 
- `pytest`
> 5125- upgrade async 2.6.4

- package-lock.json
- package.json
- Resolves #5098 
Pins minimist to 2.6.4 to remove vulnerability to Prototype Pollution due to a missing handler to Function.prototype
1-2 devs 
-  OpenFEC
- run `snyk test` locally on develop to confirm vulnerability
`snyk test`
You should see the minimist vulnerability
- `pyenv install 3.8.12` (if not already installed)
- `pyenv virtualenv 3.8.12 venv-api3812` 
- `pyenv activate venv-api3812`
- `pip …
> 5098-Snyk upgrade minimist

- data/migrations/V0248__add_columns_to_real_efile_pfile_F1.sql
- #5134 
Adding two new columns to real_efile.F1 and real_pfile.F1 tables in Aurora postgresql databases
This is database work. Only requires database team to review.
-  
branch | PR
- download the branch to local machine, invoke create_sample_db process. Make sure migration executed successfully.
Connect to local_db, verify the two new columns 
super_pac_lobbyist varchar(1),
hybrid_pac_lobbyist varchar(1)
had been added to the  following two tables:
real_efile.F1 …
> Add two columns to real_efile and real_pfile f1 table

- locustfile.py
- Resolves #5132
Replaces deprecated min_wait and max_wait with wait_time. 
1-2 devs
-  locust wait times, openFEC
- `pyenv install 3.8.12` (if not already installed)
- `pyenv virtualenv 3.8.12 venv-api3812` 
- `pyenv activate venv-api3812`
- `npm install && npm run build`
- `pytest`
- `python manage.py runserver`
- run locust test (look for instruction inside locustfile.py file)
"""Load testing for the API and web app. Run from the root directory using the
`locust --host=https://api-stage.open.fec.gov/v1/` (stage)
`locust --host=https://api.open.fec.gov/v1/` (prod)
`locust …
> 5132-Update locust deprecated methods

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5168 
Fixes vulnerabilities found in the flyway command line package. 
1-2 devs
1. Confirm vulnerability on develop by running `snyk test --file=data/flyway/build.gradle`
2. Uninstall and remove your version of flyway and install Flyway 8.5.13
**brew**:
run `brew uninstall flyway` and then run `brew install flyway` confirm with `flyway -v`
find your conf file in the Cellar and update (url and locations)
**Not through brew:**
Ref: [https://github.com/fecgov/openFEC#installing-flyway](https://github.com/fecgov/openFEC#installing-flyway)
For MacOS user, open Safari browser go to [https://flywaydb.org/documentation/usage/commandline/](https://flywaydb.org/documentation/usage/commandline/)
and download [`flyway-commandline-8.5.13-macosx-x64.tar.gz`]
update flyway conf file (url and …
> 5168-Upgrade flyway 8.5.13

- package-lock.json
- package.json
- requirements.txt
- Resolves #5146, #5142 and ignored other snyk issues
Swagger-tools is no longer being updated, and it doesn't seem like we need it, so we should remove it. 
Before:
1-2 devs
- run `snyk test` on an updated develop
- `pyenv virtualenv 3.8.12 venv-test`
- `pyenv activate venv-test`
- `rm -rf node_modules`
- `pip install -r requirements.txt && pip install -r requirements-dev.txt`
- `npm i && npm run build`
-  `createdb cfdm_test`
-  `invoke create_sample_db`
- `python manage.py runserver` 
- `snyk test`
> 5146-remove swagger-tools and upgrade gevent

- requirements.txt
- Resolves #5124 
Upgrades GitPython to latest version to remove Regular Expression Denial of Service (ReDoS) vulnerability
1-2 dev
1. Confirm vulnerability on develop by running `snyk test --file=requirements.txt`
2. `gh pr checkout 5183`
4. `pip install -r requirements.txt`
5. `pip freeze`  (check that gitpython=3.1.27)
6.  run  `snyk test --file=requirements.txt`,  gitpython issue should be gone
7.  `dropdb cfdm_test`, `createdb cfdm_test`, run `invoke create_sample_db`, `pytest`, `python manage.py runserver` test endpoints
> 5124-Upgrade gitpython

- requirements.txt
- In requirements.txt -->Upgrade ujson python package to v5.4.0
- Resolves #https://github.com/fecgov/openFEC/issues/5189
1 developer
**Before:**
**After:**
- run `snyk test --file=requirements.txt` on openFEC/develop branch. (ujson vulnerability will show in the terminal logs)
-  checkout branch : `git checkout feature/5189-upgrade-ujson`
- create new python virtual env and activate: `pyenv virtualenv venv-api3813`
- activate virtual env: `pyenv activate venv-api3813`
- install requirements: `pip install -r requirements.txt`  & `pip install -r requirements-dev.txt`
- run `snyk test --file=requirements.txt` (ujson is NOT a vulnerable packages anymore)
- run `pytest`( optional )
- start server ./manage.py runserver (optional)
- test swagger-ui (local api): http://localhost:5000/ (optional)
> Upgrade ujson to v5.4.0

- tests/test_filings.py
- webservices/args.py
- webservices/resources/filings.py
This PR will be able to filter `/efile/filings/` endpoints by keyword filer_name.
This PR will resolve the part of this [https://github.com/fecgov/openfec/issues/5160](https://github.com/fecgov/openfec/issues/5160)
- Add keyword validation, at least 3 chars in length
1-2 devs
/efile/filings/
- Check out branch, point to dev db, pytest
- test api locally
- test urls
1)(without filter, return total: 71367 rows)
http://127.0.0.1:5000/v1/efile/filings/
2)(q=san, will return 634 rows)
http://127.0.0.1:5000/v1/efile/filings/?q=san
3)(q=c006, will return 9013 rows)
http://127.0.0.1:5000/v1/efile/filings/?q=c006
4) get invalid keyword error (length < 3)
http://127.0.0.1:5000/v1/efile/filings/?q=ab
> Add filer name keyword search in /efile/filings/

- data/migrations/V0249__add_function_get_committee_label.sql
- data/migrations/V0250__add_committee_label_ofec_committee_history_mv.sql
- webservices/common/models/committees.py
- webservices/docs.py
- Resolves #4915 
- Database function and new column are created to display committee type using more common names.
2 developers
New output field "committee_label" is added to endpoints
/committee/{committee_id}/history/
/committee/{committee_id}/history/{cycle}/
/candidate/{candidate_id}/committees/history/
/candidate/{candidate_id}/committees/history/{cycle}
- Run `pytest`
- Run `flyway migration`
- Switch the model below to temporary table and start api on local:
```
class` CommitteeHistory(BaseCommittee):
__tablename__ = 'ofec_committee_history_mv_tmp_hc'
```
Before the change:
https://api.open.fec.gov/v1/committee/C00000729/history/?page=1&election_full=true&sort=-cycle&sort_hide_null=false&sort_nulls_last=false&api_key=DEMO_KEY&sort_null_only=false&per_page= …
> Add committee_label to ofec_committee_history_mv

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves https://github.com/fecgov/openFEC/issues/5182
Upgrade flyway to v9.0.2
1 or 2 backend developers
-  DB migrations, `invoke create_sample_db` script
https://github.com/fecgov/openFEC/pull/5071
https://github.com/fecgov/openFEC/pull/5177
-  On develop branch: run `snyk test --file=data/flyway/build.gradle` (two vulnerabilities show up as described in issues-5182)
- uninstall flyway v8.5.13: run `brew uninstall flyway` 
-  run `brew install flyway` or or Follow the setup instructions [here](https://docs.google.com/document/d/1pMi59CQOj0dO9WyRS-tCGxHqd9CRTOU_4GaBD4VNbGk/edit)
**OR**
- MAC developers-->open Safari browser--> go to …
> upgrade flyway to v9.0.2

- tests/test_filings.py
- webservices/args.py
- webservices/common/models/filings.py
- webservices/docs.py
- webservices/exceptions.py
- webservices/resources/filings.py
- webservices/schemas.py
This PR will be able to filter `/filings/`and `/efile/filings/` two endpoints by keyword **filer_name_text**.
This PR will resolve the part of this [https://github.com/fecgov/openfec/issues/5160](https://github.com/fecgov/openfec/issues/5160)
- Create new Keyword validation function to allow at least 3 chars in length.
1-2 devs
/filings/
/efile/filings/
- Check out branch, point to dev db, pytest
- test api locally
- test urls
For test /filings/:
1)without filter, count=3198758
http://127.0.0.1:5000/v1/filings/
2)with filter:filer_name_text=san, count=24565
http://127.0.0.1:5000/v1/filings/?filer_name_text=san
3)check invalid keyword error (length < 3)
http://127.0.0.1:5000/v1/filings/?filer_name_text=ab
--------------------
For test /efile/filings/:
1)(without …
> Add filer_name_text filter in filings and efilings

- data/migrations/V0255__ofec_sched_e_mv_add_spender_name_text.sql
In order to search keyword `spender_name`, we will add one more column: `spender_name_text` in public.ofec_sched_e_mv
ref: [Endpoints to add committee name keyword search](https://docs.google.com/spreadsheets/d/1AkQjXA2XMQfxlRyinSY0uynhf2ZRMh7l_BTWdJgHzXY/edit#gid=0)
- Resolves part of #5160
1 db dev
2)
```
pytest
```
> Add spender_name_text in sched_e_mv

- tests/test_filings.py
- tests/test_reports.py
- webservices/args.py
- webservices/common/models/filings.py
- webservices/common/models/reports.py
- webservices/exceptions.py
- webservices/resources/reports.py
- webservices/schemas.py
This PR will add filter **filer_name_text** in four endpoints:
`/reports/<string:entity_type>/` under tag: `financial`
`/efile/reports/presidential/` under tag:`efiling`
`/efile/reports/house-senate/` under tag:`efiling`
`/efile/reports/pac-party/'`under tag:`efiling`
This PR will resolve the part of this [https://github.com/fecgov/openfec/issues/5160](https://github.com/fecgov/openfec/issues/5160)
- This PR refactor the function `EfilingsAmendments.next_in_chain` in models.filings.py
to handle bad data from public.efiling_amendment_chain_vw
1-2 devs
`/reports/<string:entity_type>/` under tag: `financial`
`/efile/reports/presidential/` under tag:`efiling`
`/efile/reports/house-senate/` under tag:`efiling`
`/efile/reports/pac-party/'`under tag:`efiling`
- Check out …
> Add filer_name_text filter in reports and 3 efiling reports endpoints

- tests/test_itemized.py
- webservices/args.py
- webservices/common/models/itemized.py
- webservices/docs.py
- webservices/resources/sched_e.py
- webservices/schemas.py
This PR will add keyword filter **spender_name_text** in `/schedules/schedule_e/` endpoint.
This PR will resolve the part of this [https://github.com/fecgov/openfec/issues/5160](https://github.com/fecgov/openfec/issues/5160)
[Click here to check the status of endpoint list (want to add keyword text filter)](https://docs.google.com/spreadsheets/d/1AkQjXA2XMQfxlRyinSY0uynhf2ZRMh7l_BTWdJgHzXY/edit#gid=0)
Ref PRs:
https://github.com/fecgov/openFEC/pull/5209
https://github.com/fecgov/openFEC/pull/5210
1-2 devs
`/schedules/schedule_e/`
- Check out branch, point to dev db, pytest
- test api locally
- test urls
Test `/schedules/schedule_e/`:
1)return total about 1422063 rows (without filter)
http://127.0.0.1:5000/v1/schedules/schedule_e/?
2)return about 297 rows (filter by spender_name_text=san) …
> Add spender_name_text filter in /schedules/schedule_e/

- .flaskenv
- README.md
- bin/cf_env_setup.sh
- bin/run.sh
- cli.py
- manage.py
- manifests/manifest_task_dev.yml.template
- manifests/manifest_task_feature.yml.template
- requirements-dev.txt
- requirements.txt
- tasks.py
- tests/conftest.py
- webservices/legal_docs/__init__.py
- webservices/legal_docs/es_management.py
- webservices/legal_docs/regulations.py
- webservices/legal_docs/statutes.py
- webservices/rest.py
- Resolves #4958 
This is a major version upgrade with several breaking changes. Flask-Script has been deprecated, so it was removed and the Flask in-built CLI (which runs with click) was used to replace that functionality. There were a few changes to commands and some extra variables that need to be set which are noted in the README. **They will all be in the how-to below, but note that to run the server you must now use `flask run` or `python cli.py run`**
The commands used to be run with, for example: `python manage.py refresh_materialized`, in my first commit, but if I keep the CLI decorators on those functions I get a TypeError when I run the integration tests with pytest. 
If you run `pytest tests/integration/test_advisory_opinions.py -x` on the original commit you will see the …
> 4958-upgrade flask

- requirements.txt
- Fix the current failing builds due to an issue with the most recent setuptools release and psycopg2
1-2 devs
I will deploy this today after it's been reviewed
> pin setuptools to 65.1.1

- data/migrations/V0042__add_comid_index_to_real_efile_tables.sql
- data/migrations/V0256__fix_duplicate_indexes_on_real_efile_tables.sql
[Flyway v9.1.2](https://flywaydb.org/documentation/learnmore/releaseNotes#9.1.2) hangs on `CREATE INDEX CONCURRENTLY` statements. Unlike the traditional session locking,  Flyway V9.1.2 comes with transactional level locking  which is causing the `CREATE INDEX CONCURRENTLY` statements to hang. 
This is a breaking change on [flyway](https://github.com/flyway/flyway/pull/3394#issuecomment-1201513370)
As a result of this change, in openFEC database migration [`V0042`](https://github.com/fecgov/openFEC/blob/develop/data/migrations/V0042__add_comid_index_to_real_efile_tables.sql#L1-L3) hangs  when  the following commands or tasks run:
1. `flyway migrate`
2. `invoke create_sample_db`
3. `pytest` (mostly integration tests)  
Changes include:
- Delete/Remove V0042 that has duplicate indexes on …
> Remove duplicate indexes on real_efile_sb4 table and also create index on real_efile_sa7 table

- .circleci/config.yml
- requirements.txt
- Resolves #5203
This updates the docker images and pins flake8 until we can fix our tests failing in the most recent major version. That ticket is [here. ](https://github.com/fecgov/openFEC/issues/5217)
I did rename the venv to clean cache and repair the builds, but as a bonus it now matches the CMS config file
1-2 devs
-  circleci config
https://github.com/fecgov/fec-cms/pull/5388
I tried to test run circleci config locally via their CLI tools and wasn't able to run them successfully. I got some errors that they seems to know about and aren't moving forward with right now. I did deploy to dev and everything ran successfully. 
-checkout this branch
-deploy to dev
> 5203- Upgrade circleci docker images (python 3.8 and PG 13.5), pin flake8 

- data/migrations/V0257__ofec_filings_all_mv_add_cmteid_text.sql
- data/migrations/V0258__ofec_report_presidential_mv_add_cmteid_text.sql
- data/migrations/V0259__ofec_report_house_senate_mv_add_cmteid_text.sql
- data/migrations/V0260__ofec_report_pac_party_mv_add_cmteid_text.sql
- data/migrations/V0261__ofec_sched_e_mv_add_spender_id_text.sql
- Resolves #5220 
Add committee id to newly created tsvector column to make id a searchable item.
API:
/reports/presidential/ 
/reports/house-senate/ 
/reports/pac-party/
/schedules/schedule_e/
/filings/
1-2 developers
- Run `pytest` to test all test cases
- Run `flyway migrate` to test migration
- Switch data models to mv_tmp to test api locally on text search.
**models/filings.py:**
```
class Filings(FecFileNumberMixin, CsvMixin, db.Model):
__tablename__ = 'ofec_filings_all_mv_tmp_hc'
```
**models/reports.py**
```
class CommitteeReportsHouseSenate(CommitteeReports):
__tablename__ = 'ofec_reports_house_senate_mv_tmp_hc'
class CommitteeReportsPacParty(CommitteeReports):
__tablename__ = 'ofec_reports_pac_party_mv_tmp_hc'
class …
```
> Add committee id to tsvector column in five materialized views

- tests/test_filings.py
- tests/test_itemized.py
- webservices/args.py
- webservices/common/models/filings.py
- webservices/common/models/itemized.py
- webservices/docs.py
- webservices/resources/filings.py
- webservices/resources/reports.py
- webservices/resources/sched_e.py
- webservices/schemas.py
- Resolves #5219 
After database change, api change is completed in this ticket to change the filter name to q_filer/q_spender
- 1-2 developers
[Database change PR ](https://github.com/fecgov/openFEC/pull/5231) 
- Run `pytest`
- Run `flask run` to start api on local and test these endpoints:
- /filings/
http://127.0.0.1:5000/v1/filings/?per_page=20&sort_null_only=false&sort_hide_null=false&q_filer=C00081&sort_nulls_last=false&page=1&sort=-receipt_date
http://127.0.0.1:5000/v1/filings/?per_page=20&sort_null_only=false&sort_hide_null=false&q_filer=am&sort_nulls_last=false&page=1&sort=-receipt_date
http://127.0.0.1:5000/v1/efile/filings/?sort_nulls_last=false&page=1&sort=-receipt_date&sort_hide_null=false&q_filer=amer&per_page=20&sort_null_only=false
- …
> Add committee_id to text search

- tests/test_filings.py
- webservices/common/models/filings.py
- webservices/schemas.py
- webservices/utils.py
- Resolves #5222 
In this PR, "report_type_full" is switched to use a function in utils.py to update the document name for Form 5, Form 6 and Form 24.
when form_tp in ('F24', 'F5') and rpt_tp = '24' then '24-HOUR REPORT OF INDEPENDENT EXPENDITURES'
when form_tp in ('F24', 'F5') and rpt_tp = '48' then '48-HOUR REPORT OF INDEPENDENT EXPENDITURES'
when form_tp = 'F6' then '48-HOUR NOTICE OF CONTRIBUTIONS OR LOANS RECEIVED'
1-2 developers
API: /filings/
- Download feature branch and run `pytest`
- Start api on local and test these endpoints.
- Form 5 & 24 hour report
**Before Change**
https://api.open.fec.gov/v1/filings/?sort_hide_null=false&file_number=1627780&sort_null_only=false&form_type=F5&per_page=20&sort=-receipt_date&page=1&sort_nulls_last=false&api_key=DEMO_KEY
**After change** …
> Update document name of 24- and 48-hour reports

- .circleci/config.yml
- README.md
- requirements.txt
- runtime.txt
- Upgrades python to 3.9 to match CMS (https://github.com/fecgov/fec-cms/pull/5401) CMS needed to be upgraded to upgrade cg-django-uaa most recent version released and remove wagtail login vulnerability
1-2 devs
https://github.com/fecgov/fec-cms/pull/5401
- `git checkout feature/5247-upgrade-python`
- `pyenv install 3.9.13` 
- `pyenv virtualenv 3.9.13 venv-api3913` 
- `pyenv activate venv-api3913`
- `pip install -r requirements.txt` 
- `rm -rf node_modules` (optional step)
- `npm i` (optional step)
- `npm run build` (optional step)
- `pytest`(all tests should pass)
-  `flask run` and test swagger-ui
-  deploy a this branch to `Dev` space.  Verify API on circleci build/deploys OK while running on python v3.9.13 @runtime
> Upgrade python to 3.9.13

- webservices/tasks/__init__.py
- webservices/tasks/legal_docs.py
- Resolves #5238
Updates the refresh interval for AO's and cases to 10 hours, to ensure we are looking at recently modified during the full time the script isn't running (10-23 UTC note: crontax syntax is through the hour, so it's 10-23:59 UTC)
Also updates the slack message bot to include the AO's and MUR's published in the off hours and adds a keyword to search in the kibana logs for the next time we are having celery issues.
1-2 devs
-  Refresh statements for publishing AO's and Cases
-Pushed to dev in a test branch to deploy overnight
> Update refresh interval

- .circleci/config.yml
- Resolves #5251
This PR removes the old virtual environments before creating a new one and downloading the dependencies. This will prevent future issues with the venv cache. 
1-2 devs
- Merge branch to develop, builds should now succeed. Old failing branches will need to be re-based to add change.
> Remove cached python env

- data/migrations/V0263__ofec_reports_ie_only_mv_add_filer_name_text.sql
Fix 500 error in reports/ie-only/ endpoint
- Resolves #5232 
Add one column: spender_name_text) and index
`to_tsvector(parse_fulltext(coalesce(f5.filer_nm,'')||' '||f5.indv_org_id)) as spender_name_text`
1 dev
- Download feature branch 
- Run `pytest`
- Run `flyway migrate`
> Add filer_name_text in ofec_reports_ie_only_mv

- tests/test_aggregates.py
- webservices/resources/candidate_aggregates.py
- Resolves #5164
- Invalid districts are removed from /candidates/totals/aggregates/  when "aggregate_by=office-state-district".  Districts were cross referenced with the same data source used for "elections/search/" endpoint.
1 developer
- Download feature branch, run `pytest`
- Start api page on local, and run these endpoints
**2022 Alabama House**
**Before change**: invalid districts 12, 13
https://api.open.fec.gov/v1/candidates/totals/aggregates/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&state=AL&sort=state&per_page=10&page=1&aggregate_by=office-state-district&election_year=2022&office=H&election_full=true&is_active_candidate=true
**After change:** not showing 12, 13
http://127.0.0.1:5000/v1/candidates/totals/aggregates/?election_year=2022&per_page=20&is_active_candida …
> Fix invalid districts in /candidates/totals/aggregates/

- tests/test_reports.py
- webservices/args.py
- webservices/common/models/reports.py
- webservices/resources/reports.py
- webservices/schemas.py
Fix 500 error in reports/ie-only/ endpoint
- Resolves #5232 
- Ref PR #5255 #5257 
Add two column: spender_name_text and committee_name in endpoint return
1 dev
- Download feature branch , point to dev db
- `pytest`
- `python cli.py run`
- test local api
- Sample urls:
on prod api, you will get `Internal Server Error`
https://api.open.fec.gov/v1/reports/ie-only/?q_spender=c007&sort=-coverage_end_date&api_key=DEMO_KEY
on local, you can filter by q_spender (committee_id or committee_name)
http://127.0.0.1:5000/v1/reports/ie-only/?q_spender=c007&sort=-coverage_end_date
http://127.0.0.1:5000/v1/reports/ie-only/?q_spender=bid&sort=-coverage_end_date
> Fix broken reports_ie_only endpoint

- manifests/manifest_api_dev.yml
- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
- Partially resolves #5267
Increases api memory to 2G in dev, stage, and prod
1 dev
test the requests on dev and prod that are getting the 502 errors
I tested https://fec-dev-api.app.cloud.gov/v1/committee/C00075820/reports/?api_key=DEMO_KEY&sort_null_only=false&per_page=100&page=1&sort_hide_null=false&sort=-coverage_end_date&sort_nulls_last=false
I got 502 errors after per_page=98
- deploy to dev 
- re-ran https://fec-dev-api.app.cloud.gov/v1/committee/C00075820/reports/?api_key=DEMO_KEY&sort_null_only=false&per_page=100&page=1&sort_hide_null=false&sort=-coverage_end_date&sort_nulls_last=false
No longer getting the 502
-`cf app api` (shows 2G memory)
> Increase memory

- tests/test_aggregates.py
- webservices/resources/candidate_aggregates.py
- Resolves #5162 
When displaying Senate and House candidates aggregate totals, the endpoint will cross-check election table to include only states with election during a given election year 
2 developers
All House, Senate totals table
- Download feature branch, and run `pytest`
- Test endpoints on local
**Senate**
- Test 1
Election endpoint shows there are **34** Senates elections as of 2022.
https://api.open.fec.gov/v1/elections/search/?sort_null_only=false&api_key=DEMO_KEY&sort_hide_null=false&per_page=20&cycle=2022&sort_nulls_last=false&page=1&office=senate
Candidate Aggregate endpoint displays **34**. 
http://127.0.0.1:5000/v1/candidates/totals/aggregates/?sort_null_only=false&office=S&aggregate_by=office-state&sort_hide_null=false&sort=-election_year&page=1&per_page=20&election_full= …
> Display states with election during a given election year by candidate/totals/aggregate

- manifests/manifest_api_dev.yml
- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
App metrics: https://logs.fr.cloud.gov/goto/03634cc2122630e2a86cad813ddefe52
Booting workers still a bit high: https://logs.fr.cloud.gov/goto/67b5912713e2588c523b63597baa54e8
- Partially resolves #5267
Increases api memory to 2.5G in dev, stage, and prod
1 dev
Make sure api work well.
> [MERGE WITH GITFLOW] Increase api memory to 2.5G

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5266 
- Resolves #5262
Upgrades flyway to most recent version. (Does not remove final DOS moderate vulnerability)
1-2 devs
-  DB migrations
Before:
After:
- `gh pr checkout 5276`
- upgrade flyway however you prefer (I use `brew upgrade flyway`)
- run `snyk test --all-projects`.  One vulnerability left (jackson.build)
- `createdb cfdm_test`
- run `invoke create_sample_db`. All 256 migrations should run OK against `cfdm_test` db 
- run `pytest`
- `flask run`
> 5266 & 5262 Upgrade flyway 9.7.0

- tests/factories.py
- tests/integration/test_committees.py
- tests/test_committees.py
- webservices/common/models/committees.py
- webservices/resources/committees.py
- webservices/resources/search.py
- webservices/rest.py
- webservices/schemas.py
In order to improve the api performance, this PR will 
1)Remove join `JFCCommittee` model from `CommitteeHistory` model that are used by these endpoints:
/schedules/schedule_a/
/schedules/schedule_b/
/schedules/schedule_c/
/schedules/schedule_d/
/schedules/schedule_e/
/schedules/schedule_f/
/schedules/schedule_h4/
/reports/presidential/
/reports/house-senate/
/reports/pac-party/
/filings/
/totals/
....
2)Create new model `CommitteeHistoryProfile` join `JFCCommittee` model that are used by these 4 endpoints: (resource class: CommitteeHistoryProfileView)
/committee/<string:committee_id>/history/
/committee/<string:committee_id>/history/<int:cycle>/
/candidate/<string:candidate_id>/committees/history/
/candidate/<string:candidate_id>/committees/history/<int:cycle>/
- Resolves …
> Create model CommitteeHistoryProfile and Refactor CommitteeHistory join 

- manifests/manifest_api_dev.yml
- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
Our memory usage has decreased significantly to about 1.5GB. We can now adjust to 2GB for all environments.
1 backend developer
-  API app
> Adjust API memory for all environments to 2G

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5295 
Upgrades flyway to most recent version, removes all the vulnerabilities found in the CLI, might not remove netty
1 dev
-  local migrations
Before:
After:
- `gh pr checkout 5301`
- upgrade flyway however you prefer (I use `brew upgrade flyway`) (make sure to re-set your flyway.url and flyway.locations in the conf file)
- run `snyk test --all-projects`
- `createdb cfdm_test`
- run `invoke create_sample_db`. All 256 migrations should run OK against `cfdm_test` db 
- run `pytest`
- `flask run`
NOTE: THE …
> 5295-upgrade flyway to 9.10

- requirements.txt
- Resolves #5294 
GitPython is in maintenance mode. I did some research and as we use Gitpython for our automated releases it will be challenging to switch over to Pygit2 or Dulwich, but we will probably need to do it in the future. Currently, GitPython is most widely used and have releases/patches pretty fast. 
1 dev
-  Interaction with git libraries, automated release process
Before:
After:
- `gh pr checkout 5309`
- 'pyenv virtualenv 3.9.14 api'
- 'pyenv activate api'
- run `snyk test --all-projects`
- run `pytest`
- `flask run`
> 5294 -upgrade gitpython

- requirements.txt
This is for the sprint (20.2) release.
@fec-jli  will deploy this 1/10
> [MERGE WITH GITFLOW] Release/public 20230110

- webservices/common/views.py
- webservices/resources/sched_a.py
- webservices/resources/sched_b.py
- webservices/resources/sched_e.py
- Resolves #5198 
In this PR, union all mechanism that was added to schedules endpoint are removed.  This change fixes the exclude issue. 
Locust testing was conducted to test the performance. Locust testing was applied same endpoints by comparing before vs after.   Test results shows there is no decreasing performance before and after change. Test result is here:
[Locust test result](https://docs.google.com/spreadsheets/d/1Od3u4iqRp5Y4MGNwf9AyDtJb7-vGNvksIkC8tYSJ9C8/edit#gid=1699862915)
1 -2 developers
/schedules​/schedule_a​/
/schedules​/schedule_b​/
/schedules​/schedule_e​/
- Run `pytest`
- Start api on local, and run these apis
Data example for testing.  This individual has 18 contributions to 9 committees in 2018.  Here is the list of each committee and the …
> Remove union all in schedule A, B and E endpoints

- requirements.txt
- Resolves #5286 
- Resolves #5298 
Removes two snyk vulnerabilities by un-pinning setuptools and upgrading gevent. 
Locust (formerly locustio) needs to be upgraded with gevent and certifi. I added a ticket for this change (two major versions + a lot of syntax changes) 
1-2 devs
-  Gevent library
Before:
After:
- `gh pr checkout 5320`
- 'pyenv virtualenv 3.9.16 api'
- 'pyenv activate api'
- run `pip install -r …
> 5286-Unpin setuptools, upgrade certifi and deps

- tests/integration/test_advisory_opinions.py
- tests/integration/test_current_cases.py
- webservices/args.py
- webservices/docs.py
- webservices/legal_docs/advisory_opinions.py
- webservices/legal_docs/archived_murs.py
- webservices/legal_docs/current_cases.py
- webservices/legal_docs/es_management.py
- webservices/resources/legal.py
This PR will add sorting by `case_no` (MUR/AF/ADR) number. The default setting is descending. 
This PR also add sorting by `ao_no` (advisory opinions) number. The default setting is descending. 
**Action item(s):**
Some cf task commands when reload to ES:
```
cf run-task api --command "python cli.py display_index_alias" -m 2G --name display_index_alias
cf run-task api --command "python cli.py delete_index archived_murs" -m 2G --name delete_archived_murs
cf run-task api --command "python cli.py create_index archived_murs" -m 2G --name create_archmur_index
cf run-task api --command "python cli.py load_archived_murs" -m 2G --name upload_all_arch_mur
cf run-task api --command "python cli.py display_mappings" -m 2G --name display_mappings
cf run-task api --command "python cli.py …
```
> Add sorting by case number and by advisory opinions number in legal/search

- .pre-commit-config.yaml
- requirements-dev.txt
- requirements.txt
- setup.cfg
pre-commit hook is run first, before you even type in a commit message. 
-  inspect the snapshot that's about to be committed
-  to make sure tests run
-  inspect in the code
- Resolves #5217 
pre-commit scripts run automatically every time a file is changes event occurs in a Git repository
2 or more developers
- checkout branch: `git checkout feature/5217-setup-precommit-hook`
- create new python virtualenv: `pyenv virtualenv 3.9.14 venv-api`
- install requirements and requirements-dev : `pip install -r requirements.txt` ; `pip install -r requirements-dev.txt`
- run: `pre-commit install`
- update a python file (ex:remove new line at the end of the file)
- stage the changes: `git add -p`
- commit changes:  `git commit` (this is when pre-commit hook will flag changes made to python file …
> setup pre-commit hook

- .circleci/config.yml
- package-lock.json
- package.json
- Resolves #5314 
We are getting warnings on our builds as the latest npm is no longer compatible with versions of node <14.17. We were on 14.15.5 and this upgrades us to the LTS 18.13.0
We will be able to remove the legacy node_option once we either upgrade webpack to 5 or node fixes this issue. I created a [ticket for the webpack upgrade](https://github.com/fecgov/openFEC/issues/5325) (which won't happen until after CMS is upgraded to 4) just to include a reminder about removing this language. 
I did some research on upgrading packages which are causing NPM vunerabilities. We could upgrade babel and es packages (up several years) but we need to make our footer button compatible with [eslint rule here.](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/button-has-ty …
> 5314-upgrade node 

- .pre-commit-config.yaml
flake8  flagged snytax error when `git commit` is ran on local branch before pushing the changes. Invalid argument given in pre-commit-config.yaml. 
- Replace  `--line-length` with `--max-line-length` in pre-commit-config.yaml
one developer
**Before:** 
```
(venv-api-dev) F611836M:openFEC pkasireddy$ git commit
fix end of files.........................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 2
usage: flake8 [options] file file ...
flake8: error: unrecognized arguments: --line-length=120
```
**After:**
```
(venv-api-dev) F611836M:openFEC pkasireddy$ git commit
fix end of files.........................................................Passed …
```
> fix the snytax error in pre-commit yaml file

- data/migrations/V0265__add_state_full_ofec_candidate_totals_mv.sql
- Partially Resolves #5163 
This ticket adds state_full to the ofec_candidate_totals_mv view.
I also tested this by creating ofec_candidate_totals_mv_tmp_pmp on dev (I will drop once this is merged in).
-  ofec_candidate_totals_mv
1. Check out this branch 
2. `dropdb cfdm_test`
3. `createdb cfdm_test`
4. `invoke create_sample_db`
5. `pytest`
> add state_full to ofec_candidate_totals_mv

- webservices/docs.py
- Resolves #5296 
Add interpretation for candidate_id to help users to understand more of its composition.
1 developer
Download feature branch and run pytest.
Review the text next to candidate_id.
http://127.0.0.1:5000/developers/#/candidate/get_candidate__candidate_id__
> Add interpretation for candidate_id

- tests/test_aggregates.py
- webservices/common/models/candidates.py
- webservices/resources/candidate_aggregates.py
- webservices/schemas.py
- Resolves #5163 
This ticket adds state_full to the candidates/totals/aggregates endpoint. 
-  candidates/totals/aggregates endpoint, aggregate by office-state and office-state-district 
Related PRs against other branches: 
#5345 - database portion, needs to be merged in first
1. Check out this branch
2. `pytest`
3. Test candidates/totals/aggregates endpoint on local 
Sample URLS: 
office-state sorted by state-full:
local:
http://127.0.0.1:5000/v1/candidates/totals/aggregates/?election_full=true&sort_hide_null=false&page=1&election_year=2022&aggregate_by=office-state&sort_nulls_last=false&sort_null_only=false&sort=state_full&per_page=20
compare to:
https://api.open.fec.gov/v1/candidates/totals/aggregates/?sort_nulls_last=fals …
> add state_full to candidates/totals/aggregates endpoint

- requirements.txt
- Resolves #5349 and #5350
This ticket upgrades werkzeug to remove a vulnerability. I also had to upgrade flask-sqlalchemy from version 2.4.1 because is was not compatible with werkzeug 2.2.3. 
-  requirements.txt
- webservices
Before upgrade:
After upgrade: 
2. `pip install -r requirements.txt`
3. `snyk test --file=requirements.txt --package-manager=pip`
4. `pytest`
5. `flask run`
> update werkzeug and flask-sqlalchemy

- data/migrations/V0266__add_totals_inaugural_donations_mv.sql
- manage.py
- webservices/flow.py
- Partially Resolves #5208 
This adds a new view that shows inaugural donations by donor. 
Note: There isn't a lot of data on the local database, I created a temporary view on dev called ofec_totals_inaugural_donations_mv_tmp_pmp
1. Check out this branch 
2. `dropdb cfdm_test`
3. `createdb cfdm_test`
4. `invoke create_sample_db`
> add totals_inaugural_donations_mv

- README.md
- cli.py
- manifests/manifest_api_dev.yml
- tasks.py
- tests/integration/test_advisory_opinions.py
- tests/integration/test_current_cases.py
- tests/test_legal.py
- tests/test_load_legal_docs.py
- webservices/legal_docs/__init__.py
- webservices/legal_docs/advisory_opinions.py
- webservices/legal_docs/archived_murs.py
- webservices/legal_docs/current_cases.py
- webservices/legal_docs/es_management.py
- webservices/legal_docs/regulations.py
- webservices/legal_docs/statutes.py
- webservices/resources/legal.py
- webservices/tasks/__init__.py
- webservices/tasks/legal_docs.py
This PR refactor all ES management commands, fix some function bugs, make function reliable and easy to maintain in the future.
Also fix case document category description display bug [https://github.com/fecgov/openFEC/issues/5369](https://github.com/fecgov/openFEC/issues/5369)
- Resolves #4399 
- Resolves https://github.com/fecgov/openFEC/issues/5369
1-2 devs
[Elasticsearch management (index, upload legal data, repository, snapshot.)](https://docs.google.com/drawings/d/1R7YuWqaZ3uSc8wlw15nIN4gzyDTv_vmtRM3gGyFe6co/edit)
[Update ES mapping and reload data flowchart](https://docs.google.com/drawings/d/1hpWI9WUrBojUMBOcGVyCTO7GBB8Dazz55plNaJkq9w4/edit)
**Part One:** test partial commands on local
- Follow wiki install ES7.4 locally and start it. …
> Refactor Elasticsearch management commands

- data/migrations/V0269__ofec_sched_e_mv_add_exp_purpose.sql
- tests/test_itemized.py
- Resolves #5378 
While looking into this bug, I saw that fec_fitem_f57.exp_tp_desc and nml_form_57.exp_tp_desc were null for a lot of rows. This is why the form 5 expenditure descriptions are mostly null (I will comment the queries that I ran to see this). I also created a temporary view for testing called `public.ofec_sched_e_mv_tmp_pmp`.
This migration will change the schedule_e_mv to use  exp_purpose for the description. I used exp_purpose because the user who reported the bug mentioned that that should be the description in the ticket. 
-  schedule_e_mv
1. Check out this branch
2. `dropdb cfdm_test`
3. `createdb cfdm_test`
4. `invoke create_sample_db`
5. `pytest`
Optional - In database: 
1. Run 
`select count(*) from …
> Update schedule_e_mv to use exp_purpose for description

- requirements.txt
- Resolves #5381 
This ticket upgrades Redis to the latest version to get rid of a vulnerability in requirements.txt. 
-  webservices/tasks
- requirements.txt 
1. Checkout this branch
2. `pip install -r requirements.txt`
3. `snyk test`
4. Test downloads and celery tasks on local by following the [wiki instructions](https://github.com/fecgov/openFEC/wiki/Set-up-redis-and-celery-on-local-and-test-the-tasks)
Optional: 
5. Deploy this PR to dev 
6. Test export/downloads
Example URL: https://dev.fec.gov/data/candidates/?has_raised_funds=true&is_active_candidate=true
> upgrade redis to 4.5.4

- data/migrations/V0270__add_fec_fitem_sched_ab_2023_2024.sql
- Resolves #5376 
create fec_fitem_sched_a_2023_2024 and fec_fitem_sched_b_2023_2024 partition tables and related objects.
This is database work. Only requires database team to review.
None
branch | PR
- download the branch to local machine, either invoke create_sample_db process or run flyway migrate. Make sure migration executed successfully.
- Connect to local_db, verify fec_fitem_sched_a_2023_2024 and fec_fitem_sched_b_2023_2024 tables and the indexes created successfully.
select tablename
from pg_tables
where tablename like 'fec_fitem_sched_%_2023_2024'
order by tablename;
there should be 2 rows returned
select tablename, indexname
from pg_indexes
where tablename like …
> add fec_fitem_sched_ab_2023_2024 tables

- .circleci/config.yml
- requirements.txt
- Resolves #5400 
Our deploys are failing because codecov removed/deprecated their uploader package. To fix this, we have to move to their new [universal uploader](https://docs.codecov.com/docs/codecov-uploader).
-  circleci pipeline 
- requirements.txt
- view pipeline on circleCI: https://app.circleci.com/pipelines/github/fecgov/openFEC/1888/workflows/666a4921-526a-4717-9734-93cd5a949cd4/jobs/4495
- view codecov report: https://app.codecov.io/gh/fecgov/openFEC/commit/b567acce9527b21bd65c4e05474c4333ff70035b
Other way to test: 
1. Create new branch based off of this branch : `git branch <new-branch-name> hotfix/use-new-codecov-uploader` 
2. Make any change to the code
3. Commit changes and push branch 
4. View pipeline in …
> [MERGE WITH GIT FLOW] Hotfix/use new codecov uploader

- tests/test_sched_d.py
- webservices/args.py
- webservices/common/models/itemized.py
- webservices/docs.py
- webservices/resources/sched_d.py
- Resolves #4758 
This ticket adds coverage_start_date and coverage_end_date to the debts endpoint and creates a filter for both of these fields (`min_coverage_end_date` `max_coverage_end_date` `min_coverage_start_date` `max_coverage_start_date`).  The ticket mentions that report year, and report type should also be added, but these values are already in the endpoint. 
-  debts endpoint 
#5392 - database portion, must be merged in first. 
2. `pytest`
3. `flask run`
4.  Test the endpoint
Sample URLS: 
http://127.0.0.1:5000/developers/#/debts/get_schedules_schedule_d_
sort by coverage_end_date: 
http://127.0.0.1:5000/v1/schedules/schedule_d/?sort_hide_null=false&page=1 …
> Add report info to debts endpoint

- webservices/common/models/base.py
- webservices/rest.py
- Resolves #4843
Remove schedule A routing replica logic. I'm also removing the old SQLA_FOLLOWER variable that was added to our environments. 
3 reviewers ---This specific issue caused a[ production incident](https://docs.google.com/document/d/1zcOJt-hZa5SdwPvDJJafSEj0ylsba_f4DJDp_dYLfX8/edit#) so I would love as many eyes as possible 
-  RO replicas/ Schedule A routing 
https://github.com/fecgov/openFEC/pull/4855/files
https://github.com/fecgov/openFEC/pull/4844
This has been locust tested on dev. Once this is reviewed and merged, I will remove the SQLA_FOLLOWER variable using [this method ](https://github.com/fecgov/openFEC/wiki/Switch-out-cf-environment-variables) Then I will re-test. If anyone has any further ideas on …
> Remove schedule A routing logic

- data/migrations/V0273__ofec_filings_all_mv_add_coalesce
- data/migrations/V0274__ofec_reports_presidential_mv_add_coalesce
- data/migrations/V0275__ofec_reports_house_senate_mv_add_coalesce
- data/migrations/V0276__ofec_reports_pac_party_mv_add_coalesce
- Resolves #5416 
When committee name is null, the concatenation that includes committee name will return null.  Coalesce function is added to handle this scenario.
1 developer
2. Run pytest
3. Run `flyway migrate`
4. Test **filings endpoint** on local by switching model to tmp mv
In common/models/filings.py, set 
> class Filings(FecFileNumberMixin, CsvMixin, db.Model):
__tablename__ = 'ofec_filings_all_mv_tmp_hc'
**Before change, no rows returned**
https://api.open.fec.gov/v1/filings/?sort=-receipt_date&sort_hide_null=false&sort_nulls_last=false&per_page=20&page=1&sort_null_only=false&q_filer=C00780197&api_key=DEMO_KEY
**After change, 9 rows returned**
http://127.0.0.1:5000/v1/filings/?page=1&sort_nulls_last=false&q_filer=C00780197&sort=-receipt_date&sort_hide_n …
> Add coalesce to committee_name in ts_vector column

- data/migrations/V0273__ofec_filings_all_mv_add_coalesce.sql
- data/migrations/V0274__ofec_reports_presidential_mv_add_coalesce.sql
- data/migrations/V0275__ofec_reports_house_senate_mv_add_coalesce.sql
- data/migrations/V0276__ofec_reports_pac_party_mv_add_coalesce.sql
- Resolves #5416 
When committee name is null, the concatenation that includes committee name will return null. Coalesce function is added to handle this scenario.
1 developer
2. Run pytest
3. Run `flyway migrate`
4. Test filings endpoint on local by switching model to tmp mv
In common/models/filings.py, set
> class Filings(FecFileNumberMixin, CsvMixin, db.Model):
> tablename = 'ofec_filings_all_mv_tmp_hc'
**Before change, no rows returned**
https://api.open.fec.gov/v1/filings/?sort=-receipt_date&sort_hide_null=false&sort_nulls_last=false&per_page=20&page=1&sort_null_only=false&q_filer=C00780197&api_key=DEMO_KEY
**After change, 9 rows returned**
http://127.0.0.1:5000/v1/filings/?page=1&sort_nulls_last=false&q_filer=C00780197&sort=-receipt_date&sort_hide_null=fals …
> Add coalesce to ts_vector column used by q_filer

- data/migrations/V0277__ofec_filings_all_mv_fix_coalesce.sql
- Resolves #5416 
Fix the coalesce error.
1 developer
2. Run `pytest` 
3. Run `Flyway migrate`
4. Test filings endpoint on local by switching model to tmp mv
In common/models/filings.py, set
> class Filings(FecFileNumberMixin, CsvMixin, db.Model):
> tablename = 'ofec_filings_all_mv_tmp_hc'
**Before change, no rows returned**
https://api.open.fec.gov/v1/filings/?sort=-receipt_date&sort_hide_null=false&sort_nulls_last=false&per_page=20&page=1&sort_null_only=false&q_filer=C00780197&api_key=DEMO_KEY
**After change, 9 rows returned**
http://127.0.0.1:5000/v1/filings/?page=1&sort_nulls_last=false&q_filer=C00780197&sort=-receipt_date&sort_hide_null=false&per_page=20&sort_null_only=false
> Fix coalesce error in ofec_filings_all_mv

- requirements.txt
- Resolves #5393 
This ticket upgrades prance to get rid of the the warning from `pytest`. 
Version [0.22.11.4.0](https://prance.readthedocs.io/en/latest/) of prance replaces distutils.version with packaging.version which is what was causing the warning. I had to unpin jsonschema because prance requires jsonschema >= 4.0.0 
-  pytest
2. Activate your virtual environment
3. `pip install -r requirements.txt`
4. `pytest`
> Upgrade prance to version 0.22.11.4.0 and unpin jsonschema

- data/migrations/V278__h4_add_sort.sql
- Partially Resolves #5430 
This alters the MV for the H4 MV to include cmte info and adds indexes for those fields. It also adds an index on disbursement_amount. 
It uses this logic as the cmte info is not is the H4 datatable:
cmte.cmte_nm AS cmte_nm,
cmte.cmte_tp AS cmte_tp,
cmte.cmte_dsgn AS cmte_dsgn
FROM disclosure.fec_fitem_sched_h4 h4
LEFT OUTER JOIN disclosure.cmte_valid_fec_yr cmte
ON h4.filer_cmte_id = cmte.cmte_id AND h4.election_cycle = cmte.fec_election_yr;
1-2 devs
-  H4 MV
- activate your pyenv and pull this branch
- make sure you're pointing to cfdm_test (export SQLA_CONN= )
- invoke create_sample_db
-  check dbeaver... etc. you should …
> 5430-add cmte_nm, cmte_tp, cmte_dsgn to MV

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5417 and #5418 
This ticket upgrades flyway to the latest version to remove security vulnerabilities. 
- readme 
2. Uninstall flyway `brew uninstall flyway`
Method Two: Follow the [readme](https://github.com/fecgov/openFEC#installing-flyway) to install flyway version 9.17.0 manually 
4. Confirm version 9.17.0 was downloaded `flyway -v` 
5. Find your flyway.conf file in your Cellar and add URL and locations  
6. `dropdb cfdm_test`
7. `createdb cfdm_test`
8. `invoke create_sample_db`
9. `pytest`
10. `flask run` (check endpoints) 
11. Run`snyk test --file=data/flyway/build.gradle` and confirm …
> upgrade flyway v9.17.0

- tests/test_itemized.py
- webservices/filters.py
Resolves #5135 
When filtering for an employer with null value, the endpoint returns rows with string null or just null.
2 developers
[This worksheet](https://docs.google.com/spreadsheets/d/1AkQjXA2XMQfxlRyinSY0uynhf2ZRMh7l_BTWdJgHzXY/edit#gid=676443644) lists all the endpoints that use this filter
```
SELECT disclosure.fec_fitem_sched_a.cmte_id AS disclosure_fec_fitem_sched_a_cmte_id, disclosure.fec_fitem_sched_a.rpt_yr AS disclosure_fec_fitem_sched_a_rpt_yr, disclosure.fec_fitem_sched_a.rpt_tp AS disclosure_fec_fitem_sched_a_rpt_tp, disclosure.fec_fitem_sched_a.image_num AS disclosure_fec_fitem_sched_a_image_num, disclosure.fec_fitem_sched_a.line_num AS disclosure_fec_fitem_sched_a_line_num, disclosure.fec_fitem_sched_a.tran_id AS disclosure_fec_fitem_sched_a_tran_id, …
```
> Refactor filter_fulltext 

- .pre-commit-config.yaml
- .prettierrc
- package-lock.json
- package.json
- src/components/Footer.js
- Resolves #5453 
@jmetev1 found an issue in our build scripts. He noticed we were running format before lint during npm run build which allows us to ignore issues as they are being fixed, but not committed. I used his code changes and then also added prettier to our pre-commit hooks and upgraded prettier. 
Thank you @jmetev1, for your contribution and for catching this issue for us!
2 developers
-  npm run build, pre-commit hooks
(https://github.com/fecgov/openFEC/pull/5451)
- start your virtualenv
- pull recent develop
- rm -rf node_modules
- npm i && npm run develop
-  (should see footer issue) 
- npm run build 
- (should see footer change is made but not committed) 
- rm -rf node_modules
- npm i && npm …
> 5453-Add jmetev1's build script fix and add prettier to pre-commit

- tests/test_costs.py
- webservices/args.py
- webservices/docs.py
- webservices/resources/costs.py
When filtering for description in endpoint /electioneering/, it does not filter correctly. This PR will fix the issue and change filter name `description` to `disbursement_description`.
(because no api user use filter `description` so far, so we don't need send email to user.
- Resolves #5441 
1 dev
/electioneering/
2) pytest
3) test and compare endpoint /electioneering/  on local and prod.
Test urls:
(1) return 29 rows
http://127.0.0.1:5000/v1/electioneering/?per_page=20&disbursement_description=house&sort_hide_null=false&sort_nulls_last=false&page=1&sort_null_only=false
return 1055 rows
https://api.open.fec.gov/v1/electioneering/?per_page=20&description=house&sort_hide_null=false&sort_nulls_last=false&page=1&sort_null_only=false&api_key=DEMO_KEY
(2) return 41 rows …
> Fix description fulltext filter in /electioneering/

- tests/test_itemized.py
- tests/test_sched_c.py
- webservices/args.py
- webservices/exceptions.py
- Resolves #5442 
Update full_text field to [Keyword](https://github.com/fecgov/openFEC/blob/develop/webservices/args.py#L80) type to enforce validation
1 -2 developers
full_text field in endpoints
- Run `pytest`
- Start endpoints on local and compare these endpoints:
http://127.0.0.1:5000/v1/names/committees/?q=fut
http://127.0.0.1:5000/v1/names/committees/?q=fu
http://127.0.0.1:5000/v1/committees/?page=1&sort_hide_null=false&per_page=20&sort_nulls_last=false&sort_null_only=false&treasurer_name=Pa&sort=name
http://127.0.0.1:5000/v1/candidates/totals/?election_full=true&sort_nulls_last=false&sort_null_only=false&page=1&per_page=20&sort_hide_null=false&q=bi
http://127.0.0.1:5000/v1/candidates/totals/?election_full=true&sort_nulls_last=false&sort_null_only=false&pag …
> Update full_text field to keyword type

- webservices/common/models/itemized.py
- Resolves #5364
Adding the python portion of 5364, adding pdf_url to the model so the show image button will automatically show up on the datatable. This was a change in response to UAT testing of the H4 data table. 
1 dev
-  H4 endpoint
The migration file should be merged to dev, so either re-run the latest migrations on your local cfdm_test or point to dev
- flask run
You should see pdf_url and it should link to docquery
> 5364 add pdf_url to h4 endpoint results

- data/migrations/V0279__add_presidential_2008_tables.sql
- data/migrations/V0280__add_presidential_2012_tables.sql
- data/migrations/V0281__update_presidential_views_to_include_2008_2012_data.sql
- Resolves #5447 
This PR requires a reviewer from database team.
None
-  
branch | PR
- download this branch to local server. Run flyway migrate (or create_sample_db). 
- Make sure migration finish successfully.
- log into cfdm_test, make sure the following 18 tables created:
disclosure.pres_ca_cm_sched_a_join_08d
disclosure.pres_nml_ca_cm_link_08d
disclosure.pres_ca_cm_sched_state_08d
disclosure.pres_ca_cm_sched_link_sum_08d
disclosure.pres_nml_sched_a_08d …
> add presidential tables for 2008 and 2012 cycles

- .gitignore
- requirements.txt
- tests/integration/test_candidates.py
- tests/integration/test_tsvector_generation.py
- tests/test_aggregates.py
- tests/test_committees.py
- tests/test_dates.py
- tests/test_itemized.py
- tests/test_reports.py
- tests/test_sched_e.py
- tests/test_utils.py
- webservices/args.py
- webservices/common/models/dates.py
- webservices/common/models/filings.py
- webservices/common/models/itemized.py
- webservices/exceptions.py
- webservices/resources/dates.py
- webservices/resources/reports.py
- webservices/resources/totals.py
- webservices/rest.py
- webservices/schemas.py
- webservices/spec.py
- webservices/tasks/download.py
- webservices/utils.py
- Resolves #5440 
This ticket upgrades Flask to version 2.2.5. It also upgrades the following dependencies: 
API spec 0.39 -> 4.0
webargs 5.5.3 -> 7.0.0
flask-apispec 0.7.0 -> 0.11.4
marshmallow 2.16.3 -> 3.0.0 
marshmallow-sqlalchemy 0.15.0 -> 0.23.1
-  webservices/Schemas
- webservices/Resources
- webservices/args
- automated tests 
[Marshmallow Pagination](https://github.com/fecgov/marshmallow-pagination/pull/6) PR - upgrade marshmallow to v3 
2. `pip install -r requirements.txt`
3.  `snyk test --file=requirements.txt --package-manager=pip`
4. `pytest`
5. `flask run`
6. Test all endpoints
>  Flask upgrade to 2.2.5

- webservices/resources/legal.py
- Resolves #5440 
This pull request fixes legal dates to allow MM/DD/YYYY.
-  legal search
This can be tested locally or on dev 
local: 
1. Follow the [wiki](https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-setup-and-test-locally) to setup and test elastic search locally
2. `flask run`
3. Test date fields under the legal search endpoint including:
- af_max_fd_date
- af_min_fd_date
- af_max_rtb_date
- af_min_rtb_date
- case_max_close_date
- case_min_close_date
- case_max_open_date 
- case_min_open_date
- ao_max_request_date
- ao_min_request_date
- ao_max_issue_date
- ao_min_issue_date
on dev: 
Test date filters on legal search pages and compare to prod
example urls: …
> Format Legal Date

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
Upgrade flyway to v9.20.0
- Resolves #5482 
One developer 
-  Database migrations
-  checkout develop
- run `snyk test --file=data/flyway/build.gradle` (snyk flags io.netty:netty-handler)
- checkout feature/upgrade-flyway
- run `brew install flyway` (v9.20.0 will be downloaded)
- run `flyway -v` (verify the downloaded flyway v9.20.0)
- run `dropdb cfdm_test`
- run `createdb cfdm_test`
- run `flyway migrate` **OR** - run `invoke create_sample_db`
- run `snyk test --file=data/flyway/build.gradle` (snyk no longer flags snyk flags io.netty:netty-handler vulnerability)
- run `pytest` (all tests PASS)
> upgrade flyway to v9.20.0

- requirements.txt
This PR points marshmallow pagination requirement back to master instead of develop.
Required reviewers 1 developer
> update marshmallow pagination to point to master

- data/migrations/V0279__add_presidential_2008_tables.sql
- data/migrations/V0280__add_presidential_2012_tables.sql
- data/migrations/V0281__update_presidential_views_to_include_2008_2012_data.sql
- Resolves #5447 
This PR requires a reviewer from database team.
None
-  
branch | PR
- download this branch to local server. Run flyway migrate (or create_sample_db). 
- Make sure migration finish successfully.
- log into cfdm_test, make sure the following 18 tables created:
disclosure.pres_ca_cm_sched_a_join_08d
disclosure.pres_nml_ca_cm_link_08d
disclosure.pres_ca_cm_sched_state_08d
disclosure.pres_ca_cm_sched_link_sum_08d
disclosure.pres_nml_sched_a_08d …
> Remerge presidential tables for 2008 and 2012 cycles

- requirements.txt
- Resolves #5477
Upgrading locust and gevent resulted in package errors. Had to pin setuptool==68.0.0 in requirements.txt to remediate ReDoS snyk vulnerability
1 developer
Before:
- run `git checkout feature/5477-snyk-redos`
- run `pyenv virtualenv venv-api-5477`
- run `pyenv activate venv-api-5477`
- run `pip install -r requirements-dev.txt`
- run `snyk test --file=requirements.txt --package-manager=pip` (ReDos vulnerability no longer flagged)
- run `snyk test --file=requirements-dev.txt --package-manager=pip` (ReDos vulnerability no longer flagged)
- run `pytest`
> Pin setuptool to remediate ReDoS

- data/migrations/V0282__add_sched_d_line_num_index.sql
- Partially resolves #5510 
Adds the sched_d line_num index so that we can do the back-end work for the line_num filter ASAP
1 dev
Debts MV
Debts filter comings soon
-dropdb cfdm_test
-createdb cfdm_test
-invoke create_sample_db
should run successfully and you should see the line num index.
> 5510-add sched d line number index

- webservices/resources/candidate_aggregates.py
- Resolves #5479 
Limit sortable fields to: ['election_year', 'cycle',  'state', 'office']. Add validation to sortable fields, and set status code to 422 when invalid sorting field is selected.
1 developer
- Download feature branch and run `pytest`
- run `flask run` to start api on local and test these endpoints:
**sort = -test**
http://127.0.0.1:5000/v1/candidates/totals/?page=1&per_page=20&election_full=true&sort=-test&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
**sort = -election_year**
http://127.0.0.1:5000/v1/candidates/totals/?page=1&per_page=20&election_full=true&sort=-election_year&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
> Add validation to sorting option

- .gitignore
- requirements.txt
- tests/integration/test_candidates.py
- tests/integration/test_tsvector_generation.py
- tests/test_aggregates.py
- tests/test_committees.py
- tests/test_dates.py
- tests/test_itemized.py
- tests/test_reports.py
- tests/test_sched_e.py
- tests/test_utils.py
- webservices/args.py
- webservices/common/models/dates.py
- webservices/common/models/filings.py
- webservices/common/models/itemized.py
- webservices/exceptions.py
- webservices/resources/dates.py
- webservices/resources/reports.py
- webservices/resources/totals.py
- webservices/rest.py
- webservices/schemas.py
- webservices/spec.py
- webservices/tasks/download.py
- webservices/utils.py
- Resolves #5440 
This PR upgrades flask. This is a continuation of the previous [PR](https://github.com/fecgov/openFEC/pull/5463).
The only unreviewed  changes are in utils.py 
- webservices/Schemas
- webservices/Resources
- webservices/args
- automated tests
branch | PR
Marshmallow pagination | [PR](https://github.com/fecgov/marshmallow-pagination/pull/11) 
2. `pip install -r requirements.txt`
3.  `snyk test --file=requirements.txt --package-manager=pip`
4. `pytest`
5. `flask run`
6. Test all endpoints
> [WIP] upgrade flask

- webservices/resources/legal.py
- Resolves #5531 
This PR fixes the issue we are having with legal dates. These changes somehow got lost when rolling back the initial Flask deployment and deploying the flask hotfix. Here is the previous PR https://github.com/fecgov/openFEC/pull/5489
-  legal.py
This can be tested locally or on dev 
local: 
1. Follow the [wiki](https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-setup-and-test-locally) to setup and test elastic search locally
2. `flask run`
3. Test date fields under the legal search endpoint including:
- af_max_fd_date
- af_min_fd_date
- af_max_rtb_date
- af_min_rtb_date
- case_max_close_date
- case_min_close_date
- case_max_open_date 
- case_min_open_date
- ao_max_request_date
- ao_min_request_date
- …
> add legal date formats

- webservices/resources/candidate_aggregates.py
- Resolves #5528 
Add party_full to sortable list of endpoint /candidates/totals/ 
This PR will merge into current release branch to avoid broken page on prod website
1 dev
[5519](https://github.com/fecgov/openFEC/pull/5509)
- Download feature branch and run `pytest`
- Start api on local by running `flask run`
http://127.0.0.1:5000/v1/candidates/totals/?page=1&per_page=20&election_full=true&sort=party_full&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
> Add sortable field: party_full in /candidates/totals/

- tests/test_sched_d.py
- webservices/args.py
- webservices/common/models/itemized.py
- webservices/docs.py
- webservices/resources/sched_d.py
- Resolves #5510 
This PR adds the line_number filter to the debts endpoint. 
2 devs
-  Debts endpoint
- flask run
- test debts line_num filter with (9, 10, 11, 12,) (valid lines)
> 5510 add line_num filter

- webservices/utils.py
- Resolves #5540 
Rename Document YYYY as "Debt Settlement Plan YYYY"
When report_type, document_type and form_types data is not available then the document_description text is defaulted/hard coded to "Document" + report_year. In this PR, document_description text for debt settlement is changed as  "Debt Settlement Plan YYYY"
UX - 1  
Frontend  - 1
Backend - 1
-  Committee profile page-->Filings --> Other documents section
**Before (In Prod):**
**After (In this PR):**
1. Test local cms-->local api
**Terminal#1:** (fec-cms repo)
- git checkout develop
- pyenv activate venv-cms
- cd fec
- export FEC_API_URL=http://localhost:5000
- ./manage.py runserver
**Terminal#2:** (openFEC repo)
- git checkout feature/rename-document-label
- git pull
- pyenv activate venv-api
- flask run
Here are few …
> Rename Document YYYY as "Debt Settlement Plan YYYY"

- setup.cfg
- Resolves #5546 
This ticket suppresses the pytest warnings related to sqlalchemy since we are holding off on the sqlalchemy upgrade. Documentation on how to suppress pytest warnings can be found [Here](https://docs.pytest.org/en/stable/how-to/capture-warnings.html#controlling-warnings). 
-  pytest
1. `git checkout feature/5546-remove-pytest-warnings`
2. `pytest`
You can also look at the circleci [build](https://app.circleci.com/pipelines/github/fecgov/openFEC/2188/workflows/3f839de4-9883-4f09-8c43-e6ac85e87082/jobs/4837) for this branch
> suppress specific pytest warnings

- webservices/decoders.py
- webservices/utils.py
- Resolves #5540 
This PR fixes a bug where the label "Debt Settlement Plan" is being applied to other documents incorrectly.
Frontend - 1
Backend - 1
-  committee profile page 
- filings datatable 
https://github.com/fecgov/openFEC/pull/5541
dev.fec.gov (incorrect) 
fec.gov (correct)
1. Test local cms-->local api
**Terminal#1:** (fec-cms repo)
- git checkout develop
- pyenv activate venv-cms
- cd fec
- export FEC_API_URL=http://localhost:5000
- ./manage.py runserver
**Terminal#2:** (openFEC repo)
- git checkout this branch
- git pull
- pyenv activate venv-api
- flask run
Here are few sample URLs to test. Clink the links to make sure that the correct document names are being used.
Test that …
> re-label debt settlement plan

- data/migrations/V0283__add_sched_d_idx.sql
This is the fixed migration file for the issue below. I needed to add another field for the second join so that I could use sub_id as unique. 
- Partially Resolves #5522
This migration file refactors our debts endpoint output for the two tickets above. I found two filters without indexes in the process of completing these tickets, so I'm adding those indexes as well. 
The null value fields are being removed in response to feedback from UAT testing of the debts datatable from RAD. They would prefer less null value fields in the exports. 
Adds indexes for new filters: cmte_tp, filing_form
Adds indexes for current filters without  indexes: cmte_id, image_num
Removes mostly null fields: cred_dbtr_id, cand_nm, cand_nm_first, cand_nm_last, cand_office, cand_office_st, cand_office_st_desc, …
> 5522-add idx, remove null fields on sched D endpoint

- tests/test_aggregates.py
- Resolves #5534 
Add test case for sorting validation that was added in this [PR](https://github.com/fecgov/openFEC/pull/5509)
1 -2 developer
> Add test case for sorting validation

- requirements.txt
Upgrade python packages in requirements.txt: 
-  gitpython to v3.1.32
- certifi to v2023.7.22 
- Resolves #5525 #5550 
1 developer
**Before:**
- run `git checkout develop`
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output show gitpython and certifi as vulnerable packages)
- run `git checkout feature/upgrade-gitpython-and-certifi-pkgs`
- run `pyenv activate venv-api`
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output **no longer shows** gitpython and certifi as vulnerable packages)
- run `pytest`
> upgrade gitpython and certifi

- data/migrations/V0284__increase_size_pres_nml_b_disb_desc.sql
- Resolves #5554 
Increase disb_desc from varchar(40) to varchar(100) in the following 5 tables:
disclosure.pres_nml_sched_b_08d
disclosure.pres_nml_sched_b_12d
disclosure.pres_nml_sched_b_16
disclosure.pres_nml_sched_b_20d
disclosure.pres_nml_sched_b_24d
Require review from database team prior to merge
None
None
- download this branch to local server. Run flyway migrate (or create_sample_db).
- Make sure migration finish successfully.
- log into cfdm_test, run the following query to check size of disb_desc in pres_nml_sched_b_x tables had been changed to varchar(100) .
SELECT relname as table_name, a.attname as column_name, format_type(a.atttypid, a.atttypmod) as data_type
FROM pg_attribute a
JOIN pg_class t on a.attrelid = t.oid
JOIN pg_namespace s on t.relnamespace = s.oid
WHERE …
> Increase size of disb_desc in pres_nml_sched_b_x tables

- tests/test_filings.py
- webservices/args.py
- webservices/common/models/filings.py
- webservices/docs.py
- webservices/resources/filings.py
- Resolves #5497 
Adds a form_type to efilings. This is a new type of filter so that the functionality remains similar to the processed filings. A user can add just the form type ie F3X and it will filter by all F3X's. Because raw filings form_types have the new/amendment/termination letter appended to this field I wanted to make sure that users could also search for just F3XN or just F2A's-- so this functionality should work as well. 
1-2 devs
-  Efilings endpoint
- pull the branch
- activate your virtualenv
- pytest
- flask run 
- http://127.0.0.1:5000/v1/efile/filings/?page=1&per_page=20&form_type=F2&sort=-receipt_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false  [count:1046]
- …
> 5497- add form_type filter

- requirements.txt
- Resolves #5594 
Since we already have setuptools pinned to v68, this ticket upgrades Gevent to remove the ReDOS vulnerability. 
-  requirements.txt
For some reason, my local snyk test does not show what is on the online snyk [dashboard](https://app.snyk.io/org/fecgov/project/7382e6c8-8f69-4afb-b910-ff61101c54fb). 
However, by looking at the dashboard I can see that the issue is coming from setuptools and Gevent. Setuptools is already pinned to v68 so I upgraded Gevent. 
1. run `snyk test --file=requirements-dev.txt --package-manager=pip` on an updated develop
2. checkout this branch
3. `pyenv virtualenv  (your environment)`
4. `pyenv activate (your environment)`
5. `pip install -r requirements.txt && pip install -r …
> Upgrade Gevent to remove ReDOS vulnerability 

- .circleci/config.yml
- Resolves #5570
We have been installing the latest version of npm (`npm install -g npm`) after installing node with nvm in circleci.  Nvm already installs npm with node, so we are re-installing the latest npm version which can break the builds. This happened when npm 10 was released. We use the nvm recommended version (and specify it) in production, so this PR will remove the upgrade command and make the circleci config match production.
There is an argument to keeping the configuration the same and letting the circle builds fail to force us to upgrade, but I think we should just regularly upgrade without it. CMS runs the nvm recommended version in circleci, so that is why API deploy failed when CMS did not last week.
If we make this change, I will put in a ticket to remove the line from …
> 5570- remove re-install of npm (LTS)

- tests/common.py
- tests/factories.py
- tests/test_totals.py
- webservices/common/models/totals.py
- webservices/resources/totals.py
- webservices/schemas.py
- Resolves #3930 
This PR adds automated tests for CandidateTotalsView and refactors CandidateTotals. 
We couldn't test this view before because CandidateCommitteeTotalsHouseSenate and CandidateCommitteeTotalsPresidential  had `{'extend_existing': True}` and repeated fields which caused a duplicate error when creating all of the database tables. [Here](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Table.params.extend_existing) is the documentation explaining how extend_existing works. So I merged the three models into one and created two separate schemas instead. 
Also when writing the tests I noticed a few data types were incorrect. This was caused by the marshmallow_sqlalchemy upgrade. Any field declared as Numeric in the model is automatically converted to a …
> Refactor CandidateTotals and Add Automated Tests for CandidateTotalsView

- requirements.txt
Upgrade gitpython to v3.1.32 in requirements.txt to remediate snyk vulnerability
- Resolves #5574 
one developer
- run `git checkout develop`
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output shows gitpython as vulnerable package)
- run `git checkout feature/5574-upgrade-gitpython`
- run `pyenv activate venv-api`
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output **no longer shows** gitpython as vulnerable package)
- run `pytest`
> Upgrade gitpython to 3.1.35

- tests/test_sched_d.py
- webservices/args.py
- webservices/common/models/itemized.py
- webservices/docs.py
- webservices/resources/sched_d.py
- Resolves #5605 
Remove deprecated candidate_id filter from the schedule_d endpoint. This change was approved by PM's when the first dep notice was added and sent out August 22nd 2023.
1-2 devs 
-  sched D endpoint
- Pull this PR
- flask run
- http://127.0.0.1:5000/developers/#/debts/get_v1_schedules_schedule_d_
-  http://127.0.0.1:5000/v1/schedules/schedule_d/?committee_type=H&page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
-  http://127.0.0.1:5000/v1/schedules/schedule_d/?filing_form=F3X&page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
- pytest
> 5577-remove deprecated filter from schedule_d endpoint

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5612 
This ticket upgrades flyway to the latest version to remove security vulnerabilities. 
- readme 
2. Uninstall flyway `brew uninstall flyway`
Method Two: Follow the [readme](https://github.com/fecgov/openFEC#installing-flyway) to install flyway version 9.22.3 manually 
4. Confirm version 9.22.3 was downloaded `flyway -v` 
5. Find your flyway.conf file in your Cellar and add URL and locations  
6. `dropdb cfdm_test`
7. `createdb cfdm_test`
8. `invoke create_sample_db`
9. `pytest`
10. Run`snyk test --file=data/flyway/build.gradle` and confirm vulnerabilities are gone
> Upgrade flyway v9.22.3

- tests/test_aggregates.py
- tests/test_spending_by_others.py
- webservices/args.py
- webservices/resources/candidate_aggregates.py
- webservices/resources/spending_by_others.py
After this PR, when pass Invalid sort options, api will return 422, not 500 error code.
- Resolves #5588 
- #5626
1 dev
Completion criteria
/v1/candidates/totals/aggregates/
/v1/schedules/schedule_a/by_size/by_candidate/
/v1/schedules/schedule_a/by_state/by_candidate/
/v1/schedules/schedule_a/by_state/by_candidate/totals/
/v1/schedules/schedule_e/totals/by_candidate/
/v1/communication_costs/totals/by_candidate/
/v1/electioneering/totals/by_candidate/
2) pytest
3) test urls, compare with prod api and make sure not return 500 error instead 422 error.
**[receipts](https://api.open.fec.gov/developers/#/receipts)**
**/v1/schedules/schedule_a/by_size/by_candidate/** …
> Fix sort validation to skip 500 error

- webservices/legal_docs/es_management.py
- webservices/tasks/__init__.py
- webservices/tasks/legal_docs.py
- Resolves #5610 
This ticket fixes two issues we are having with our snapshots. 
The first issue is that we have to manually delete old snapshots. This ticket creates a celery task to automatically delete any snapshots older than 30 days.
The second issue we're having is that two snapshots cannot be created at the same time. To fix this I set `wait_for_completion` to true when creating a snapshot. This makes the request wait until the operation has completed before returning. [Here](https://elasticsearch-py.readthedocs.io/en/7.6.0/api.html#snapshot) is the documentation on that.
-  celery tasks 
1. checkout this branch or you can refer to my [test branch ](https://github.com/fecgov/openFEC/commit/5e189f15f9d263af5b097fdea198f …
> Create celery task to delete snapshots 

- tests/factories.py
- tests/integration/test_amendment_chain.py
- tests/integration/test_candidate_committee_totals.py
- tests/integration/test_committees.py
- tests/integration/test_filings.py
- tests/test_aggregates.py
- tests/test_committees.py
- tests/test_costs.py
- tests/test_filing_resources.py
- tests/test_filings.py
- tests/test_inaugural_donations.py
- tests/test_itemized.py
- tests/test_reports.py
- tests/test_sched_d.py
- tests/test_spending_by_others.py
- tests/test_totals.py
- webservices/args.py
- webservices/docs.py
- webservices/exceptions.py
- webservices/resources/candidates.py
- webservices/resources/committees.py
- webservices/resources/filings.py
- webservices/resources/reports.py
- webservices/resources/totals.py
- webservices/utils.py
- Resolves #5603 
This ticket adds validation to the committee_id field by adding a custom field in args.py and adding validation to committee_id in paths (for instance: v1/committee/C00429613/filings/).  It checks that the length is exactly 9, that it begins with a capital 'C', and that the characters after 'C' are digits. 
-  all committee_id fields 
- all automated tests that use committee_id 
- args.py
- flask run 
- test all endpoints that use committee_id. I will include a list of endpoints and test urls in the comments.
> Add committee_id validation

- tests/test_itemized.py
- tests/test_sched_c.py
- tests/test_sched_d.py
- webservices/args.py
- webservices/common/models/itemized.py
- webservices/docs.py
- webservices/exceptions.py
- webservices/resources/sched_c.py
- webservices/resources/sched_d.py
- webservices/resources/sched_e.py
- webservices/resources/sched_f.py
- webservices/resources/sched_h4.py
- webservices/schemas.py
- webservices/utils.py
- Resolves #5609 
This PR will allow line_number to support multiple user inputs for schedules C, D, E, F, and H4. This will fix the current bug on the debts tables where multiple line number filters can't be selected. To fix this issue I needed to add form_line_number as a hybrid_property as it is a composite field of filing_form and line_number.  This required a deprecation notice (sent Oct 18th) as the filter will change from line_number to form_line_number. I kept the line_number logic to allow a grace period for our users. I will be removing the line_number logic in a follow-up ticket.
During the research for this ticket, I discovered that line_number is not currently working for E and F endpoints and all efiling endpoints. This PR fixes E & F.  The CMS PR should be released with …
> 5609-add form_line_number to Schedule_CDEFH

- tests/factories.py
- tests/integration/test_candidate_committee_totals.py
- tests/integration/test_candidates.py
- tests/integration/test_filings.py
- tests/test_aggregates.py
- tests/test_candidates.py
- tests/test_committees.py
- tests/test_costs.py
- tests/test_filings.py
- tests/test_itemized.py
- tests/test_presidential.py
- tests/test_sched_e.py
- tests/test_spending_by_others.py
- tests/test_totals.py
- webservices/args.py
- webservices/exceptions.py
- webservices/resources/candidates.py
- webservices/resources/committees.py
- webservices/resources/filings.py
- webservices/resources/reports.py
- webservices/resources/sched_e.py
- webservices/resources/totals.py
- webservices/utils.py
This ticket adds validation to the candidate_id as filter by adding a custom field in args.py and adding validation to candidate_id in paths (for instance: v1/[candidate/S6LA00029/]. It checks that the length is exactly 9, that it begins with a capital 'P' or 'S' or 'H' and following are char and number.
- Resolves #5602 
2 dev
- all endpoints with filter by candidate_id or include {candidate_id} in the path
- all automated tests that use candidate_id 
- args.py
- flask run 
- pytest
- test all endpoints that use candidate_id. 
go through  the 'test api urls' column in google sheet. modify candidate_id to invalid value.
[test urls](https://docs.google.com/spreadsheets/d/1AkQjXA2XMQfxlRyinSY0uynhf2ZRMh7l …
> Add candidate_id validation

- webservices/rest.py
- Resolves #5648 
Cloud.gov needs us to add the reCAPTCHA URLs to our CSP (content-security-policy).
Adding the reCAPTCHA paths to the `script-src` rule is pretty straightforward (tells the browser that we're cool with script requests made to those paths).
**Maybe tricky**: They requested that we add the reCAPTCHA to our `frame-src` rule but we didn't have one. Without a rule for `frame-src`, browsers would have used `default-src` as a fallback. Because of that, I copied our standard values for `default-src` into a new `frame-src` rule and added the new values for reCAPTCHA. We may not need the non-Google values in `frame-src`.
Best to review it on not-localhost
2 devs?
Theoretically every page, but only comes into play when requesting
- script files from
- …
> 5648 - Update CSP for cloud.gov API

- tests/test_filters.py
- webservices/args.py
- webservices/resources/reports.py
This PR will fix bug for endpoint '/reports/<string:entity_type>/', will support multi candidate_id search.
- Resolves #5646 
1-2 dev
'/reports/<string:entity_type>/'
'/committee/<string:committee_id>/reports/'
- Check out branch
- pytest
- test api urls compare local and prod
- setup cms locally that point local api, test front-end reports page.
Test api urls:
1)(pass one candidate_id= S6MI00103, return 222 rows)
https://api.open.fec.gov/v1/reports/house-senate/?candidate_id=S6MI00103&api_key=DEMO_KEY
http://127.0.0.1:5000/v1/reports/house-senate/?candidate_id=S6MI00103
2)(pass one candidate_id=S2TX00106, return 228 rows)
https://api.open.fec.gov/v1/reports/house-senate/?candidate_id=S2TX00106&api_key=DEMO_KEY
http://127.0.0.1:5000/v1/reports/house-senate/?candidate_id=S2TX00106
3)(pass …
> Fix filter by multi candidate_id for reports/entity_type

- webservices/resources/candidates.py
- webservices/resources/committees.py
- webservices/utils.py
This PR will allow committee_id and candidate_id with '-' exclude search.
- Resolves #5657 
1 dev
endpoints with committee_id and candidate_id validation
1)Check out branch
2)pytest
3)Test some endpoint committee_id and candidate_id validation with exclude '-'
1)(return total 79820 rows)
http://127.0.0.1:5000/v1/committees/
(return 1 row)
http://127.0.0.1:5000/v1/committees/?committee_id=C00855759
(return 79820-1 = 79819 rows, that excluded committee_id=C00855759)
http://127.0.0.1:5000/v1/committees/?committee_id=-C00855759
2)(return total 49083 rows)
http://127.0.0.1:5000/v1/candidates/
(return1 row)
http://127.0.0.1:5000/v1/candidates/?candidate_id=S2TX00106
(return 49083-1=49082 rows)
http://127.0.0.1:5000/v1/candidates/?candidate_id=-S2TX00106
3)some endpoints don't support '-' filter …
> Update committee_id and candidate_id validation

- tests/test_itemized.py
- webservices/args.py
- webservices/exceptions.py
- Resolves #4628 
This ticket adds validation to two_year_transaction_period fields and auto-tests. 
- schedule_a endpoint 
- schedule_b endpoint 
- `pyenv activate (your virtual environment)`
- `pytest`
- `flask run`
- test /schedules/schedule_a/ and /schedules/schedule_b endpoints 
Sample URLs: 
schedule_a: 
http://127.0.0.1:5000/v1/schedules/schedule_a/?two_year_transaction_period=2026
 
http://127.0.0.1:5000/v1/schedules/schedule_a/?two_year_transaction_period=1976
 
http://127.0.0.1:5000/v1/schedules/schedule_a/?two_year_transaction_period=1974
 
http://127.0.0.1:5000/v1/schedules/schedule_a/?two_year_transaction_period=2003
 
schedule_b: 
http://127.0.0.1:5000/v1/schedules/schedule_b/?two_year_transaction_period=2026
 
http://127.0.0.1:5000/v1/schedules/schedule_b/?two_year_transacti …
> add validation to two_year_transaction_period

- tests/test_itemized.py
- tests/test_sched_c.py
- tests/test_sched_d.py
- webservices/args.py
- webservices/common/models/itemized.py
- webservices/docs.py
- webservices/exceptions.py
- webservices/resources/sched_c.py
- webservices/resources/sched_d.py
- webservices/resources/sched_e.py
- webservices/resources/sched_f.py
- webservices/resources/sched_h4.py
- Resolves #5621 
Removes line_number from CDEFH4 endpoints (has been replaced with form_line_number)  and removes the dep notices. 
I confirmed there's no users right now hitting this filter on these endpoints in the last 120 days (besides me)
1-2 devs
- activate your virtual environment
- flask run (check the line_number is present for A and B, and form_line_number is present for CDEFH4)
- http://127.0.0.1:5000/v1/schedules/schedule_b/?line_number=F3X-21B&two_year_transaction_period=2012&per_page=20&sort=-disbursement_date&sort_hide_null=false&sort_null_only=false
- http://127.0.0.1:5000/v1/schedules/schedule_a/?line_number=F3X-15&two_year_transaction_period=2016&per_page=20&sort=-contribution_receipt_date&sort_hide_null=false&sort_null_only=false
- …
> 5621- Remove line_number functionality CDEFH4

- tests/test_candidates.py
- tests/test_costs.py
- webservices/common/counts.py
- webservices/common/views.py
- webservices/docs.py
- webservices/resources/elections.py
- webservices/resources/reports.py
- webservices/resources/totals.py
- webservices/utils.py
- Resolves #4003
This ticket adds a count_type indicator field to every endpoint with pagination. Counts are estimated if the estimated count (counts.py get_estimated_count) is greater than 500000. Counts are exact when the estimated count is less than 500000 or `is_estimated_count = false`. Counts for ElectionsListView, ReportsView, CommitteeReportsView, TotalsByEntityTypeView, TotalsCommitteeView, and CandidateTotalsDetailView are always exact. 
Note: The Marshmallow Pagination PR must be merged first. This branch will not pass CircleCI until marshmallow pagination is merged. 
- counts.py
- all endpoints with pagination
[Marshmallow Pagination PR …
> Add Count Type Indicator 

- tests/factories.py
- tests/test_sched_f.py
- webservices/common/models/itemized.py
- Resolves #5619 
This ticket adds test coverage to the schedule F endpoint. To add test coverage I had to fix the n + 1 query performance bug that we were getting by switching to[ joined loading](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html). 
-  schedule f endpoints 
1. checkout this branch 
2. `pytest`
3. `flask run` (compare changes to prod to make sure `committee` and `subordinate_committee` fields are the same. 
Sample URLs: 
example 1:
https://api.open.fec.gov/v1/schedules/schedule_f/?page=1&per_page=20&sort=expenditure_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&api_key=DEMO_KEY
http://127.0.0.1:5000/v1/schedules/schedule_f/?page=1&per_page=20&sort=expenditure_date&sort_hide …
> add schedule_f test coverage

- requirements.txt
- Resolves #5694 
This ticket upgrades gitpython to remove a security vulnerability.
-  automated release process/interaction with git libraries
- run `git checkout develop`
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output shows gitpython as vulnerable package)
- run `git checkout feature/5694-upgrade-gitpython`
- run `pyenv activate venv-api`
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output **no longer shows** gitpython as vulnerable package)
- run `pytest`
> Upgrade gitpython

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5699 
This ticket upgrades Flyway to the latest version 10.7.1.
2. Uninstall flyway `brew uninstall flyway`
Method Two: Follow the [readme](https://github.com/fecgov/openFEC#installing-flyway) to install flyway version 10.7.1 manually 
4. Confirm version 10.7.1 was downloaded `flyway -v` 
8. `pytest`
> Upgrade flyway v10.7.1

- data/migrations/V0289__last_file_ofec_committee_detail_history_mv.sql
- Resolves #5712 
Adds the indexes for last file date and adds a missing index for last f1 date that should have already been added. 
1-2 devs
-  migration files
python filter PR:
- start your venv
- invoke create_sample_db
OR
Change the mv and view to a new name and run the file
> add last file and f1 indexes (migration file)

- webservices/common/models/itemized.py
- Resolves #5722 
This ticket fixes a bug with `conduit_committee_zip` where the data type in the model was an Integer but the zip code in the database contained alphanumeric characters because it is a Canadian zip code. 
Here are some links in docquery for reference: 
https://docquery.fec.gov/cgi-bin/fecimg/?202307129582515808
https://docquery.fec.gov/cgi-bin/fecimg/?202212069547174185
https://docquery.fec.gov/cgi-bin/fecimg/?202204089495979742
https://docquery.fec.gov/cgi-bin/fecimg/?202201259475160806
I changed all `conduit_committee_zip` fields to a string and cross referenced this with the database tables. I changed Schedule C `loan_source_zip` as well because it is a varchar data type in the database. 
-  Schedule A, B, …
> Change conduit_committee_zip to string

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5730 & #5732 & #5731 
This PR upgrades Flyway to the latest version 10.8.1.
2. Uninstall flyway `brew upgrade flyway`
Method Two: Follow the [readme](https://github.com/fecgov/openFEC#installing-flyway) to install flyway version 10.8.1 manually 
4. Confirm version 10.8.1 was downloaded `flyway -v` 
8. `pytest`
> 5730-upgrade flyway 10.8.1

- tests/test_aggregates.py
- tests/test_itemized.py
- webservices/args.py
- webservices/resources/aggregates.py
- Resolves #5736 
This PR changes the purpose filter in ScheduleBByPurposeView from filter_fulltext to filter_multi. I also changed from a text search to a multi-select in both schedule b and schedule b by purpose.
- schedule b endpoint
- schedule b by purpose endpoint
1. checkout this branch 
2. activate you virtualenv 
3. `flask run`
> Change purpose filter from fulltext to multi

- .circleci/config.yml
- README.md
- requirements.txt
- runtime.txt
- Resolves #5682 
This ticket upgrades python to version 3.10.13. 
Note: CircleCI will not pass until the marshmallow-pagination PR is merged in 
- pytest
- circleci 
- marshmallow_pagination 
| branch           | PR       |
| ---------------- | -------- |
| marshmallow_pagination PR   | [link](https://github.com/fecgov/marshmallow-pagination/pull/17) |
1. `pyenv virtualenv 3.10.13 <new env name>`
2. `pyenv activate <new env name>`
3. Open …
> Upgrade python v3.10

- tests/test_aggregates.py
- webservices/common/views.py
- webservices/resources/candidate_aggregates.py
This PR will remove the per_page cap for these three endpoints:
ScheduleABySizeCandidateView
ScheduleAByStateCandidateView
ScheduleAByStateCandidateTotalsView
- Resolves #5734 
1-2 devs
schedules/schedule_a/by_state/by_candidate/
schedules/schedule_a/by_state/by_candidate/totals
schedules/schedule_a/by_size/by_candidate/
- Check out branch
- pytest
- Test 3 endpoints will allow return more than 100 rows (per_page >100)
compare with on prod, will get 422 error: "Parameter 'per_page' must be between 1 and 100"
1)ScheduleAByStateCandidateView
http://127.0.0.1:5000/v1/schedules/schedule_a/by_state/by_candidate/?sort=state&candidate_id=P00014530&candidate_id=P80000722&candidate_id=P80001571&cycle=2020&election_full=true&per_page=200
https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_c …
> Remove per_page cap on ScheduleABySizeCandidateView, ScheduleAByStateCandidateView, and ScheduleAByStateCandidateTotalsView

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5763 
Upgrades flyway to 10.10.0
1 dev
-flyway
2. Uninstall flyway `brew upgrade flyway`
Method Two: Follow the [readme](https://github.com/fecgov/openFEC#installing-flyway) to install flyway version 10.10.0
4. Confirm version 10.10.0 was downloaded `flyway -v` 
8. `pytest`
> upgrade flyway 10.10

- cli.py
- manage.py
- Resolves #5755 
This PR adds commands to manually check for and clear long running queries. Due to ongoing discussion with db team, I did not make it a celery task yet. I also have concerns with being able to support this kind of celery task. 
Here's the [dashboard](https://logs.fr.cloud.gov/app/dashboards#/view/0fd6ea60-f5b6-11ee-927c-73315d2dd7b2?_g=) for check_queries 
3 devs
- cf tasks, db
Locally: 
-**unset SQLA_CONN**
- Remove the datname and usename portions of the SQL for both commands
they should read
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE lower(query) like 'select %'
and lower(query) not like '%refresh%'
and lower(query) not like '%rollback%'
and (now() - pg_stat_activity.query_start) >= …
> 5755-add check and clear queries commands

- manifests/manifest_api_dev.yml
- manifests/manifest_api_feature.yml
- manifests/manifest_api_prod.yml
- manifests/manifest_api_stage.yml
- manifests/manifest_celery_beat_dev.yml
- manifests/manifest_celery_beat_feature.yml
- manifests/manifest_celery_beat_prod.yml
- manifests/manifest_celery_beat_stage.yml
- manifests/manifest_celery_worker_dev.yml
- manifests/manifest_celery_worker_feature.yml
- manifests/manifest_celery_worker_prod.yml
- manifests/manifest_celery_worker_stage.yml
- manifests/manifest_task_dev.yml.template
- manifests/manifest_task_feature.yml.template
- manifests/manifest_task_prod.yml.template
- manifests/manifest_task_stage.yml.template
- Resolves #5761 
This ticket adds the new creds service to the manifest files. I moved all of the API only variables into a separate service including: `API_UMBRELLA_SIGNUP_KEY , ES_SNAPSHOT_ROLE_ARN , FEC_FEATURE_PRESIDENTIAL , SQLA_FOLLOWERS,  SLACK_HOOK, SQLA_CONN,  FEC_EREGS_API`
- manifest files
- Remove the API only variables from fec-creds-dev: `API_UMBRELLA_SIGNUP_KEY , ES_SNAPSHOT_ROLE_ARN , FEC_FEATURE_PRESIDENTIAL , SQLA_FOLLOWERS,  SLACK_HOOK, SQLA_CONN,  FEC_EREGS_API` using [this](https://github.com/fecgov/openFEC/wiki/Switch-out-cf-environment-variables) wiki article as reference.
- Deploy a test branch based off of this PR. You can use [this](https://github.com/fecgov/openFEC/tree/test-new-creds-service) one. …
> Add New Creds Service

- webservices/rest.py
- webservices/static/robots.txt
- Resolves #5754 
This PR adds the robots.txt to our API so that search engines know we don't want them crawling our endpoints. 
1-2 devs
-API 
- pyenv activate api (or your env)
- flask run
- http://127.0.0.1:5000/robots.txt
deploy to a space
-you can use my branch here to deploy to dev https://app.circleci.com/pipelines/github/fecgov/openFEC/2633/workflows/7211175f-67ba-4fd1-9fad-d65a2c8f8536/jobs/5387
-test the robots.txt using the tool here:
https://technicalseo.com/tools/robots-txt/
(select any user-agent like google-bot and try any url for an endpoint (v1) and it should disallow.)
> 5754-add robots.txt

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5784  
Upgrades flyway to 10.11.1
1 dev
-flyway
2. Uninstall flyway `brew upgrade flyway`
Method Two: Follow the [readme](https://github.com/fecgov/openFEC#installing-flyway) to install flyway version 10.11.1
4. Confirm version 10.11.1 was downloaded `flyway -v` 
8. `pytest`
> upgrade to 10.11.1

- tests/test_aggregates.py
- webservices/common/models/aggregates.py
- webservices/common/views.py
- webservices/filters.py
- webservices/resources/aggregates.py
- webservices/schemas.py
This PR will fix fulltext search and N/A search issue in these three endpoints
ScheduleAByEmployerView
ScheduleAByOccupationView
ScheduleBByRecipientView
- Resolves #3885 
- Related https://github.com/fecgov/openFEC/pull/5790
cms ticket: [https://github.com/fecgov/fec-cms/issues/5220](https://github.com/fecgov/fec-cms/issues/5220)
1-2 devs
"/schedules/schedule_a/by_employer/"
"/schedules/schedule_a/by_occupation/"
"/schedules/schedule_b/by_recipient/"
- Check out branch
- pytest
- test urls for three endpoints
—[1]ScheduleAByEmployerView
Test 1-1) when employer=amazon.com, return two rows:
employer=[amazon.com](http://amazon.com/)
employer=amazon com
http://127.0.0.1:5000/v1/schedules/schedule_a/by_employer/?cycle=2020&employer=amazon.com&committee_id=C00003418
When …
> Fix sched-a by-employer,by-occupation and schedule_b/by_recipient fulltext and n/a search issue

- requirements.txt
- Resolves #5793
This ticket upgrades gunicorn to remove a software vulnerability. 
- [run.sh ](https://github.com/fecgov/openFEC/blob/develop/bin/run.sh)
- Deploy this [test branch](https://github.com/fecgov/openFEC/tree/test-gunicorn) to dev. Gunicorn is not used locally
> upgrade gunicorn v22

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5808 
Upgrades flyway to 10.12.0
1 dev
-flyway
2. Uninstall flyway `brew upgrade flyway`
Method Two: Follow the [readme](https://github.com/fecgov/openFEC#installing-flyway) to install flyway version 10.12.0
4. Confirm version 10.12.0 was downloaded `flyway -v` 
8. `pytest`
> 5808- upgrade flyway 10.12.0

- tests/test_filters.py
- webservices/resources/sched_a.py
- webservices/resources/sched_b.py
This PR fix N/A fulltext search issue for `/schedules/schedule_a/` and `/schedules/schedule_b/`
also add auto test for filter by fulltext_NA function.
- Resolves #5812 
- will partially fix cms ticket: [https://github.com/fecgov/fec-cms/issues/5220](https://github.com/fecgov/fec-cms/issues/5220)
1-2 devs
/schedules/schedule_a/
/schedules/schedule_b/
- Checkout branch and 'pytest'
- test two endpoints
1)test endpoint: schedules/schedule_a
Test 1_1: contributor_employer=N/A(take 2mins), return correct rows: 610 rows
http://127.0.0.1:5000/v1/schedules/schedule_a/?committee_id=C00003418&contributor_employer=N/A&two_year_transaction_period=2020
Compare on Prod: contributor_employer=N/A, return 9717 wrong data 
https://api.open.fec.gov/v1/schedules/schedule_a/?committee_id=C00003418&contributor_ …
> Fix N/A fulltext search for schedule a and b

- data/migrations/V0297__add_ofec_totals_national_party_mv.sql
- manage.py
- webservices/flow.py
- Resolves #5787 
The new MV includes aggregate contribution and disbursement of national party accounts.  This MV will be used for committee profile page.
1-2 developers
1. Download feature branch and run `pytest`
2. Run `flyway migrate` to test migration
3. Run these commands to test MV refreshing.  Make sure `ofec_totals_national_party_mv` is refreshed after `ofec_sched_a_national_party_mv` and `ofec_sched_b_national_party_mv`
> Add MV for national party aggregate data

- locustfile.py
- webservices/resources/legal.py
- Resolves #5817 
This ticket increases the inner hit size so that it can return up to 100 hits. If we want more than 100 hits we'd have to change the [max_inner_result_window](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html) setting in elasticsearch. This is not recommended because it would have negative impacts on performance because inner_hits can be costly.
[Here](https://docs.google.com/spreadsheets/d/11UqvbnAJPxt9iPVFY9QdDPEXbGlf9MANhV4NjOjALXg/edit#gid=0) is a document showing the load testing results. I see a bit of an increase in the average response time. 
- legal search
1. deploy this branch to dev
2. check that document highlights return more than three results: …
> Increase size for inner hits

- .gitignore
- cli.py
- manage.py
- Resolves #5802 
This ticket adds a the new `update_public_api_key` task. The PMs decided that this task should only create a new API key and add it to our environment variables. After that, the developer can manually re-stage the app and disable the old key. [Here](https://github.com/fecgov/openFEC/wiki/Rotating-Public-API-Key-Using-Task) is the wiki page. 
The new command is: 
`cf run-task api --command "python cli.py update_public_api_key <space> <service_instance> '$(< token.txt)'  <first_rate_limit> <first_rate_limit_duration> <second_rate_limit> <second_rate_limit_duration>" --name update_public_api_key`
The arguments are: 
`space`: [Required] the space that you want to update
`service_instance`: [Required] the user provided service you want to update
`token`: [Required] your cf …
> Add task to create new public api keys

- webservices/common/models/national_party.py
- Resolves #5859 
Update column name for spender_committee_type_full in model file
1 developer
- Download feature branch and run `pytest`
- Start api on local and run endpoint:
http://127.0.0.1:5000/v1/national_party/schedule_b/?page=1&per_page=20&sort=-disbursement_date&sort_hide_null=false&sort_null_only=false
> Fix column name in model file

- tests/test_national_party.py
- webservices/args.py
- Resolves #5849 
Adds image number filter to national party schedule b endpoint
1 dev
- National party schedule b endpoint
- start your API virtualenv
- pytest tests/test_national_party.py
- flask run
- test image number filter
http://127.0.0.1:5000/v1/national_party/schedule_b/?page=1&per_page=20&image_number=202405209646237729&image_number=202405209646237803&sort=-disbursement_date&sort_hide_null=false&sort_null_only=false
http://127.0.0.1:5000/v1/national_party/schedule_b/?page=1&per_page=20&image_number=202405209646237729&sort=-disbursement_date&sort_hide_null=false&sort_null_only=false
http://127.0.0.1:5000/v1/national_party/schedule_b/?page=1&per_page=20&sort=-disbursement_date&sort_hide_null=false&sort_null_only=false
> 5849 add image number filter

- webservices/legal_docs/es_management.py
- Resolves #5690 
This PR fixes a bug with the citation endpoint where no results are being returned. This was happening due to the AO mappings not including the citation fields, so they weren't searchable. Once this PR is merged I will go through the process of updating our mappings on dev. 
- ES mappings 
Before: 
1. Setup and start elastic search by following [this](https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-setup-and-test-locally) wiki 
2. In another terminal: `git checkout develop`
3. `python cli.py create_index ao_index`
4. `python cli.py load_advisory_opinions 2020-05`
5. See that citation_type does not exist as a field for AOs: http://localhost:9200/ao_index/_field_caps?fields=citation_type
8. `flask …
> Update AO mapping to include citation fields

- data/migrations/V0302__add_test_efile_schema_and_table.sql
- Part of #5860 
Add new `test_efile` schema and `test_f1` table for future test webforms table/endpoint in #5860. Adding just the schema and the table so we can test the EFO inserts
Schema: `test_efile` 
Table: `test_f1`
- None yet
WIP PR: https://github.com/fecgov/openFEC/pull/5861 (will remove migration)
- Run migrations
> Release branch PR - Add test efile migration release edition

- data/migrations/V0302__add_test_efile_schema_and_table.sql
- Part of #5860 
Add missing columns to  `test_efile` schema and `test_f1` table for future test webforms table/endpoint in #5860 
- None yet
WIP PR: https://github.com/fecgov/openFEC/pull/5861 (will remove migration)
- Run migrations
> Release PR -  Add missing columns to test efile table

- requirements.txt
- Resolves #5807 
Upgrades flask-cors to remove snyk vulnerability
1-2 devs
- locust, cors (flask-cors was added to fix a cors safari issue)
- activate your venv
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- (if you get a posix subprocess error you may need to re-create your virtualenv)
- pytest
- flask run
- I did a quick load test just to make sure locust is running ok
- https://docs.google.com/document/d/1ru6Qg0ErTQLD7a86qxW7kbaKbzkayt_X9PmGjZdC_nY/edit
> 5807 upgrade flask-cors

- webservices/legal_docs/es_management.py
- webservices/resources/legal.py
This PR will switch Elasticsearch English analyzer to the Standard analyzer. This analyzer performs exact string matching without altering terms by stemming and ignoring common words.
Also comment out some debug option in legal.py.
- Resolves #5872 
1 dev
legal search
1) Setup local Elastic search to Standard analyzer.
2) Test legal keyword search without altering terms by stemming and ignoring common words.
> Switch analyzer to standard

- requirements.txt
- Resolves #5907 
This PR upgrades setuptools to v70.3 to remove a snyk vulnerability. We need to make changes to marshmallow pagination if we ever want to upgrade to 71 or above. I created a ticket [here](https://github.com/fecgov/marshmallow-pagination/issues/18). 
- package installation during deploy
- activate your virtualenv 
- `snyk test --file=requirements.txt --package-manager=pip` (vulnerability should be gone)
- deploy to dev or stage. You can use [this](https://app.circleci.com/pipelines/github/fecgov/openFEC?branch=test-unpin-setuptools-stage) test branch
> Upgrade setuptools to v70.3

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
- Resolves #5936 
Upgrades flyway to 10.17.1
1 dev
-flyway
2. Update flyway `brew update flyway`
3. Install the latest version of flyway through brew
`brew install flyway`
4. Confirm flyway version 10.17.1: `flyway -v` 
8. `pytest`
9. run `snyk test --file=data/flyway/build.gradle` and make sure no vulnerability.
> Upgrade flyway to 10.17.1

- data/migrations/V0303__add_disbursement_dt_sched_e.sql
- webservices/common/models/itemized.py
- Resolves #5902 
Add disbursement date in database mv and schedule E endpoint
1 developer
2. Run `flyway migrate` to test migration file
3. Run `pytest`
4. In models/itemized.py, switch table `ofec_sched_e_mv` to `ofec_sched_e_mv_tmp_hc`,  run api on local to check the `disursement_dt` field in output
http://127.0.0.1:5000/v1/schedules/schedule_e/?cycle=2002&committee_id=C00000422&per_page=20&sort=-expenditure_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
> Add disbursement_date in schedule E

- manage.py
- Resolves #5917 
This PR modifies the api key creation task to set the `Restrict Access to HTTP Referers` setting.
- api key creation task
Link to branch for testing: https://github.com/fecgov/openFEC/tree/test-update-referrers
1. checkout test branch `git checkout test-update-referrers`
2. set the UMBRELLA_ADMIN_AUTH_TOKEN env var `export UMBRELLA_ADMIN_AUTH_TOKEN="<your umbrella token>"`
3. set the FEC_WEB_API_KEY_PUBLIC env var `export FEC_WEB_API_KEY_PUBLIC="<your api key>"`
5. Run the task `python cli.py update_public_api_key dev fec-creds-dev fake-token123`
6. Check that the `Restrict Access to HTTP Referers` setting is set to `*` in API umbrella
7. disable the api key in API umbrella
> Set allowed allowed referers in api key creation task

- tests/test_aggregates.py
- webservices/common/views.py
- webservices/resources/candidate_aggregates.py
This PR will add filter by "candidate_id" limitation (max =10) on three endpoints:
ScheduleABySizeCandidateView
ScheduleAByStateCandidateView
ScheduleAByStateCandidateTotalsView
Blocking https://github.com/fecgov/fec-cms/issues/6226
- Resolves #5753 
1-2 devs
ScheduleABySizeCandidateView
ScheduleAByStateCandidateView
ScheduleAByStateCandidateTotalsView
- pytest
- test urls
1)/schedules/schedule_a/by_size/by_candidate/:
pass 10 candidate_ids:
http://127.0.0.1:5000/v1/schedules/schedule_a/by_size/by_candidate/?sort=size&candidate_id=P80001571&candidate_id=S2TX00106&candidate_id=H6IL09061&candidate_id=H8IA01094&candidate_id=H8MO03164&candidate_id=P80003338&candidate_id=H6MT01095&candidate_id=H4CA12055&candidate_id=S6CT00042&candidate_id=S2ND00099&cycle=2020&election_full=tru …
> Add candidate_id limitation on schedule a aggregate

- tests/integration/test_current_cases.py
- webservices/args.py
- webservices/docs.py
- webservices/legal_docs/current_cases.py
- webservices/legal_docs/es_management.py
- webservices/resources/legal.py
Add filter by **mur_disposition_category_id** in the /legal/search/ endpoint. 
Here is the list of [Mur dispostion category list](https://fecgov.slack.com/files/U3R9P66LC/F07NJETRRK7/mur_disposition_category_list.csv)
- Resolves #5966 
2 devs
/legal/search/
1)Checkout branch
2)Setup local ES
3Upload legal doc on local ES.
These commands for reference:
`python cli.py create_index case_index`
`python cli.py delete_index case_index`
`python cli.py load_adrs`
`python cli.py load_admin_fines`
`python cli.py load_current_murs`
you can terminate(Ctr+C) in the middle of loading.
4)`pytest` and `flask run`
5)Test urls
http://127.0.0.1:5000/v1/legal/search/?type=murs&mur_disposition_category_id=12
http://127.0.0.1:5000/v1/legal/search/?type=murs&mur_disposition_category_id=7 …
> Add Mur disposition category filter

- webservices/args.py
- webservices/docs.py
- webservices/legal_docs/advisory_opinions.py
- webservices/legal_docs/es_management.py
- webservices/resources/legal.py
- Resolves #5961 
Adds ao_doc_category_id field and switches the filter to use ao_doc_category_id 
2 devs
- AOs 
- You must reload your AO's to see these changes
- activate your venv
- activate ES 
- python cli.py initialize_legal_data ao_index
- flask run
- http://127.0.0.1:5000/v1/legal/search/?ao_doc_category_id=C
- http://127.0.0.1:5000/v1/legal/search/?ao_doc_category_id=D
- http://127.0.0.1:5000/v1/legal/search/?ao_doc_category_id=validation error
> 5961 add ao_doc_category_id filter

- tests/integration/test_current_cases.py
- webservices/args.py
- webservices/docs.py
- webservices/legal_docs/current_cases.py
- webservices/legal_docs/es_management.py
- webservices/resources/legal.py
- Resolves #5965 
This PR adds primary and secondary subject filters for ADR and MUR subjects 
2 devs
- ADR and MUR (current cases)
1)Checkout branch
2)Setup local ES
3Upload legal doc on local ES.
These commands for reference:
`python cli.py create_index case_index`
`python cli.py delete_index case_index`
`python cli.py load_adrs`
`python cli.py load_admin_fines`. (Don't really need to load these for this work) 
`python cli.py load_current_murs`
you can terminate(Ctr+C) in the middle of loading.
4)`pytest` and `flask run`
5)Test urls
http://127.0.0.1:5000/v1/legal/search/?primary_subject_id=18
http://127.0.0.1:5000/v1/legal/search/?primary_subject_id=7
http://127.0.0.1:5000/v1/legal/search/?primary_subject_id=7&primary_subjec …
> 5965-add subject filters

- webservices/resources/legal.py
- Resolves #6003 
fixes issue with if statement so archived murs show when disposition keyword argument is not added
2 devs
- legal search 
| branch           | PR       |
| ---------------- | -------- |
| fix/other_pr     | [link]() |
| feature/other_pr | [link]() |
- https://fec-dev-api.app.cloud.gov/v1/legal/search/
- https://fec-dev-api.app.cloud.gov/v1/legal/search/?
- start your venv
- flask run
- http://127.0.0.1:5000/v1/legal/search/?q=sheila
- http://127.0.0.1:5000/v1/legal/search/?
-  http://127.0.0.1:5000/v1/legal/search/?mur_disposition_category_id=7
(If this pull request changes our [current system diagram](https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram), include a …
> [MERGE WITH GITFLOW] Hotfix/6003 fix dispositions

- webservices/args.py
- webservices/docs.py
- webservices/legal_docs/advisory_opinions.py
- webservices/legal_docs/es_management.py
- webservices/resources/legal.py
- Resolves #5979 
This ticket adds a doc_type filter to the` legal/citation` endpoint. Currently there are no MUR or ADR citations, this follow up ticket will populate them https://github.com/fecgov/openFEC/issues/5996.
- AO mappings 
- legal/citations endpoint 
- start your virtualenv 
- start elasticsearch in new terminal 
- `python cli.py create_index ao_index`
- `python cli.py load_advisory_opinions 2020-05`
- `flask run`
- Test endpoint
Sample URLs: 
http://127.0.0.1:5000/v1/legal/citation/regulation/100.13
http://127.0.0.1:5000/v1/legal/citation/statute/10
http://127.0.0.1:5000/v1/legal/citation/statute/10/?doc_type=advisory_opinions
http://127.0.0.1:5000/v1/legal/citation/regulation/100.13/?doc_t …
> Add doc_type filter to citations

- webservices/legal_docs/es_management.py
- Resolves #6001 
This ticket fixes the citation autosuggest by changing the `citation_text` field to keyword. We can now enter letters and receive results. 
- ao mappings 
- citation mappings
- start your virtualenv 
- start elasticsearch in new terminal 
- `python cli.py create_index ao_index`
- `python cli.py load_advisory_opinions 2024-11`
- `flask run`
- Test endpoint
Sample URLs: 
http://127.0.0.1:5000/v1/legal/citation/regulation/CFR%20%C2%A7100.5
http://127.0.0.1:5000/v1/legal/citation/statute/52%20U
http://127.0.0.1:5000/v1/legal/citation/statute/52%20U.S.C
http://127.0.0.1:5000/v1/legal/citation/statute/2%20U.S.C
http://127.0.0.1:5000/v1/legal/citation/regulation/29%20CFR
> Change citation_text to keyword field

- webservices/args.py
- webservices/docs.py
- webservices/resources/legal.py
- Resolves #6012
Adds back deprecated ao_category filter 
2 devs
-ao category legal search
- start your venv
- flask run
- check your totals
- pytest
- flask run
- 127.0.0.1:5000/v1/legal/search/?ao_doc_category_id=V should equal
127.0.0.1:5000/v1/legal/search/?ao_category=V
- 127.0.0.1:5000/v1/legal/search/?q=many&ao_doc_category_id=V  should equal
127.0.0.1:5000/v1/legal/search/?q=many&ao_category=V
- 127.0.0.1:5000/v1/legal/search/?q=two&ao_doc_category_id=D  should equal
127.0.0.1:5000/v1/legal/search/?q=two&ao_category=D
- 127.0.0.1:5000/v1/legal/search/?ao_doc_category_id=W  should equal
127.0.0.1:5000/v1/legal/search/?ao_category=W
- 127.0.0.1:5000/v1/legal/search/?ao_doc_category_id=D&ao_doc_category_id=S  should …
> Hotfix to add ao_category deprecated filter

- tests/test_legal.py
- webservices/legal_docs/archived_murs.py
- webservices/legal_docs/current_cases.py
- webservices/resources/legal.py
This PR will fix incorrect order for current MURs and Arch MURs.
1)after merge, we should reload all case legal document and archived MURs documents in dev
2)after cut, we should reload all case legal document and archived MURs documents in stage
3)after deploy production, we should reload all case legal document and archived MURs documents in prod.
- Resolves #5982 
1-2 devs
'/legal/search/'
current_cases.py
archived_murs.py
legal.py
Ref [add test in legal/search](https://github.com/fecgov/openFEC/issues/6009)
1)Check branch
2)setup local ES
3)load some arch mur and current mur data to local ES
```
python cli.py display_index_alias
python cli.py create_index case_index
python cli.py create_index arch_mur_index
python cli.py …
```
> 5982-Fix arch mur and current mur sort

- webservices/args.py
- webservices/docs.py
- webservices/resources/legal.py
- Resolves #5987 
This pull request gives the ability to  filter by AO and case document dates at the legal/search/ endpoint. It allows for minimum and maximum date ranges to filter by using the `ao_min_document_date` and `ao_max_document_date`  columns for AOs and `case_min_document_date` and `case_max_document_date` columns for cases (MUR, ADR, and AF).
2 backend developers
- `legal/search` endpoint
Terminal #1: 
-  follow the [wiki](https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-setup-and-test-locally#1-install-elasticsearch-7x0-locally-both-740-and-760-work-well) to start elasticsearch service on local 
- delete and create indexes from scratch:
ao_index:
- python cli.py delete_index ao_index
- python cli.py create_index ao_index
case_index:
- python cli.py delete_index …
> Filter by document date (AO, AF, ADR and MUR documents)

- tests/integration/test_current_cases.py
- webservices/args.py
- webservices/docs.py
- webservices/legal_docs/current_cases.py
- webservices/legal_docs/es_management.py
- webservices/resources/legal.py
- Resolves #6006, #6019, #5986
- Renames adr_dispositions and af_dispositions to dispositions,  
- moves adr citations to dispositions 
- changes arch mur respondents from respondent to respondents to fix case_respondents filter
- adds min/max penalty filters 
This needs to be merged with CMS changes [here](https://github.com/fecgov/fec-cms/pull/6529)
Switched data type to [scaled-float](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html) as the most efficient way to deal with a few penalties with cents
`For floating-point types, it is often more efficient to store floating-point data into an integer using a scaling factor, which is what the scaled_float type does under the hood. For instance, a price field could be stored in a scaled_float with a scaling_factor …
> 6006/6019/5986--Move adr citations to dispositions, add filters

- tests/test_downloads.py
- webservices/resources/candidates.py
- webservices/resources/committees.py
This PR will fix sql error in slack #bots-db-alerts-aurora
- Resolves #6043 
1-2 developer
`/candidates/` and `candidate/search`
`/committees/` and `committee/search`
1) checkout branch, run 'pytest'
2) test urls
test CandidateList urls: without 'q' should get 422
http://127.0.0.1:5000/v1/candidates/?sort=receipts
http://127.0.0.1:5000/v1/candidates/?&sort=-receipts
tet CandidateList urls: should return some results
http://127.0.0.1:5000/v1/candidates/?q=joh&sort=receipts
http://127.0.0.1:5000/v1/candidates/?q=joh&sort=-receipts
http://127.0.0.1:5000/v1/candidates/?q=joh&sort=name
test CommitteeList urls: without 'q' should get 422
http://127.0.0.1:5000/v1/committees/?sort=receipts
http://127.0.0.1:5000/v1/committees/?sort=-receipts
tet CommitteeList urls: should return some results …
> Fix bug in CandidateList and CommitteeList when passing q and sort by receipts

- data/migrations/V0305__add_ref_case_disposition_category.sql
- tests/integration/test_current_cases.py
- webservices/args.py
- webservices/docs.py
- webservices/legal_docs/current_cases.py
This PR add a new table (**fecmur.ref_case_disposition_category**)  to store displayed final disposition categories for three cases (MUR, ADR and AF)
The new MUR disposition category list:
[ref_case_disposition_category.csv](https://github.com/user-attachments/files/17682305/ref_case_disposition_category.csv)
- Resolves #6041 
1-2 developers
legal search endpoint
[https://github.com/fecgov/openFEC/pull/5988](https://github.com/fecgov/openFEC/pull/5988)
[https://github.com/fecgov/openFEC/pull/5991](https://github.com/fecgov/openFEC/pull/5991)
1)Checkout branch
2)Setup local ES
3Upload legal doc on local ES.
These commands for reference:
`python cli.py create_index case_index`
`python cli.py delete_index case_index`
`python cli.py load_adrs`
`python cli.py load_admin_fines`
`python cli.py …
> Remove undisplay MUR disposition category

- tests/integration/test_cases_elasticsearch.py
Fix test_mur_disposition_filter
- Resolves #6047 
1 dev
2) `pytest`
> fix test mur disposition filter category

- tests/integration/test_advisory_opinions.py
- webservices/legal_docs/advisory_opinions.py
- Resolves #6031 
Some name fields for AO entites are not populating correctly for individuals. There's currently a ticket in with ITSS to fix the name field, but this needs to be fixed now so this PR uses the parsed name fields for requestor_names, commenter_names, and representative_names. It also improves the logic for combining the name fields so that there are no longer leading and trailing whitespaces. 
1 dev
- AO requestor_names, representative_names, commenter_names
BEFORE:
https://api.open.fec.gov/v1/legal/search/?api_key=DEMO_KEY&ao_no=2024-15
AFTER:
start elasticsearch
- python cli.py delete_index ao_index
- python cli.py create_index ao_index
- python cli.py load_advisory_opinions 2024-15
- python cli.py …
> 6031- fix requestor_names bug with individual entities

- requirements.txt
- Resolves #6045 
This PR upgrades gevent to remediate a security vulnerability. 
- run `snyk test --file=requirements.txt --package-manager=pip` on an updated develop
- `pyenv activate your-env`
-  `createdb cfdm_test`
-  `invoke create_sample_db` 
- `snyk test --file=requirements.txt --package-manager=pip`   
- `flask run`
> Upgrade gevent v24(24.11.1)

- tests/common.py
- tests/integration/test_ao_elasticsearch.py
- tests/integration/test_cases_elasticsearch.py
- tests/integration/test_statute_elasticsearch.py
- tests/test_legal_data.py
- webservices/resources/legal.py
- Resolves #6027 
This PR adds integration testing for AOs and Statutes. I also make a small change for the mur_disposition_category since they are stored as numbers and not strings.
- pytest
- start elasticsearch 
- test AOs: `pytest tests/integration/test_ao_elasticsearch.py -s`
- test cases: `pytest tests/integration/test_cases_elasticsearch.py -s`
- test statutes: `pytest tests/integration/test_statute_elasticsearch.py -s`
- test all: `pytest`
> Add integration tests for AOs and Statutes

- tests/common.py
- tests/integration/test_cases_elasticsearch.py
- tests/integration/test_citations_elasticsearch.py
- tests/integration/test_legal_docs_elasticsearch.py
- tests/test_legal_data.py
- Resolves #6028 
This PR adds tests for the legal/docs and legal/citations endpoints. 
- pytest
- start elasticsearch 
- test legal/docs: `pytest tests/integration/test_legal_docs_elasticsearch.py -s`
- test legal/citations: `pytest tests/integration/test_citations_elasticsearch.py -s`
- test all: `pytest`
> add tests for legal/docs and legal/citations endpoints

- webservices/resources/legal.py
- Resolves #6080
This branch adds a check to ensure that empty filters will return all results in legal search 
- legal search
This branch is on dev, test the filters to ensure results are still returned when the field is blank (make sure to look at total count). 
Sample URLs: 
https://fec-dev-api.app.cloud.gov/v1/legal/search?ao_entity_name=
https://fec-dev-api.app.cloud.gov/v1/legal/search?case_no=
https://fec-dev-api.app.cloud.gov/v1/legal/search?af_name=
https://fec-dev-api.app.cloud.gov/v1/legal/search?ao_no=
https://fec-dev-api.app.cloud.gov/v1/legal/search?ao_name=
> FIx empty filter bug 

- tests/integration/test_ao_elasticsearch.py
- webservices/args.py
- webservices/docs.py
- webservices/resources/legal.py
- Resolves #6078 
ao_category has been deprecated and should be removed. ao_doc_category_id is being used by the FE 
1 dev
- ao_category filter 
- activate your venv
- start ES and load docs if needed (./bin/elasticsearch) [ES instructions](https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-management-instruction)
- flask run on dev, check totals for each doc type
- pytest
- flask run
- check your totals 
- 127.0.0.1:5000/v1/legal/search/?ao_doc_category_id=V
- 127.0.0.1:5000/v1/legal/search/?q=committee&ao_doc_category_id=V
- 127.0.0.1:5000/v1/legal/search/?ao_doc_category_id=W
- 127.0.0.1:5000/v1/legal/search/?ao_doc_category_id=D&ao_doc_category_id=S
> 6078- remove deprecated filter

- tests/conftest.py
This PR fix issue that backend develop have to drop and recreate their local test database every time run pytest.
Note: 
When we add new schema, remember to add schema name into reset_schema() of tests/conftest.py
- Resolves #6070 
1 dev
pytest
2) run `pytest` twice (don't need drop cfdm_unit_test)
> 6070-Fix pytest test_efile issue

- tests/test_dates.py
- webservices/args.py
- webservices/exceptions.py
- Resolves #6081 
Adds ISO8601 as an option for calendar-dates and calendar-dates/export
My current understanding is that election-dates and reporting-dates are not to be changed yet--but can be changed easily using this class later. 
2-3 devs, would like FE to take a look
-calendar-dates
-calendar-dates/exports
- activate your venv
- pytest
- flask run
- [Here's the branch](https://app.circleci.com/pipelines/github/fecgov/openFEC/3210/workflows/be4317c9-61c8-498c-b656-ccf23271d3a0/jobs/6073) pushed to dev (feel free to rebuild)
Old format YYYY-MM-DD:
- http://127.0.0.1:5000/v1/calendar-dates/?page=1&per_page=20&min_start_date=2018-12-27&sort=-start_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
- …
> 6081- add ISO8601 validation

- .circleci/config.yml
- README.md
- requirements.txt
- runtime.txt
- Resolves #5937 
This PR upgrades python to version 3.11 which requires an invoke upgrade. 
- task.py 
- deploy
| branch           | PR       |
| ---------------- | -------- |
| cms   | https://github.com/fecgov/fec-cms/pull/6627 |
- install python 3.11: `pyenv install 3.11`
- create new virtual environment: `pyenv virtualenv 3.11 <new env>`
- activate virtual environment: `pyenv activate <new env>`
- install dependencies: `pip install -r requirements.txt` and  `pip install -r requirements-dev.txt`
- Note: I had to upgrade pip, setuptools, packaging, and wheel locally
-   `pytest`
- test invoke commands: 
- `invoke add-hooks`
- `invoke create-sample-db`
- test api: `flask run`
- test …
> Feature/5937 Upgrade python v3.11

- tests/integration/test_ao_elasticsearch.py
- webservices/args.py
- webservices/docs.py
- webservices/resources/legal.py
- Resolves #6092 
This removes the entity filter and adds commenter and representative filters to match the ao_requestor filter. I confirmed with design that this should not be a list input filter. 
I checked for any usage (to send a dep notice) and there was a singular external use in the last three months that was pretty clearly a bot (added all filters empty) so I think we should be ok to make this change. 
1-2 devs
-AO filters
activate pyenv
gh pr checkout 6098
pytest
python cli.py create_index ao_index
python cli.py create_index arch_mur_index
python cli.py create_index case_index
python cli.py load_advisory_opinions 2024-03
python cli.py load_archived_murs
python cli.py load_current_murs
flask run …
> 6092 split entity filters

- tests/common.py
- tests/integration/test_ao_elasticsearch.py
- tests/integration/test_cases_elasticsearch.py
- tests/integration/test_citations_elasticsearch.py
- tests/integration/test_legal_docs_elasticsearch.py
- tests/integration/test_statute_elasticsearch.py
- webservices/legal_docs/__init__.py
- webservices/legal_docs/es_management.py
- Resolves #6099 
This PR fixes the issue where documents and indices are deleted after running pytest. Now when running pytest, new test indices will be created then deleted after the tests have completed 
- pytest
- check out this branch 
- activate your virtual environment 
- start elasticsearch in another terminal 
- create an index: `python cli.py create_index case_index`
- load some documents: `python cli.py load_current_murs`
- `pytest`
- check that case_index and documents are still there and test indices are gone: https://app.elasticvue.com/cluster/0/indices
- try to create a test index: `python cli.py create_index test_case_index` (Should get an error)
> Add test indices for pytest

- tests/integration/test_ao_elasticsearch.py
- webservices/args.py
- webservices/docs.py
- webservices/filters.py
- webservices/resources/legal.py
- Resolves #6024
- Update the [type=all](https://github.com/fecgov/openFEC/blob/develop/webservices/resources/legal.py#L132) logic to return all types when the search is empty
- Update `ao_requestor_type` filter from int to  a string 
- Validate filters: type, mur_type, ao_requestor_type, primary_subject_id, secondary_subject_id 
- Update tests
- Update docs.py
2 developers
- legal/search endpoints
- `git checkout feature/6024-legal-search-validate-dropdown-filters`
- pyenv activate <your python  virtual env>
- run elasticsearch service 
- run `pytest`
- run `python cli.py create_index ao_index`
- run  `python cli.py create_index arch_mur_index`
- run `python cli.py create_index case_index`
- run `python cli.py load_advisory_opinions 2023-01` (13 AO's upload to local ES service)
- run …
> validate legal/search endpoint filters

- webservices/common/models/large_aggregates.py
- webservices/docs.py
- webservices/schemas.py
- Resolves #5765
Add description to contributor_aggregate_ytd
1 dev
3. Start API on local, and test with these endpoints. Scroll down and click on `model` to check the description.
4. Schedule A endpoint, check `contributor_aggregate_ytd`
http://127.0.0.1:5000/developers/#/receipts/get_v1_schedules_schedule_a_
5. Election endpoint, check these two fields in model
`candidate_pcc_id`
`candidate_pcc_name`
http://127.0.0.1:5000/developers/#/financial/get_v1_elections_
6. /v1/totals/by_entity/,  check `end_date`
http://127.0.0.1:5000/developers/#/financial/get_v1_totals_by_entity_
> Add description to contributor_aggregate_ytd

- webservices/schemas.py
`total` property in`schedules/schedule_a/by_size` endpoint was returning `total` as string data type in the result set. After adding `total` property to `schemas.py`, `schedules/schedule_a/by_size` returns float value. Fixed 4 other SA endpoints that share the same `total` property.
| Endpoint  | Prod URL |
| ------------- | ------------- |
| schedules/schedule_a/by_size | https://api.open.fec.gov/v1/schedules/schedule_a/by_size?committee_id=C00703975&cycle=2024&api_key=DEMO_KEY |
| schedules/schedule_a/by_state | https://api.open.fec.gov/v1/schedules/schedule_a/by_state?committee_id=C00703975&cycle=2024&api_key=DEMO_KEY  |
| schedules/schedule_a/by_zip | https://api.open.fec.gov/v1/schedules/schedule_a/by_zip?committee_id=C00703975&cycle=2024&api_key=DEMO_KEY  |
| …
> Add 'total' property to schema to return a float data type instead of string type

- .circleci/config.yml
The Cloud.gov v2 API for Cloud Foundry is reaching its end-of-life. CF CLI versions 6 and 7 still rely on Cloud Foundry API v2 and will no longer work at some point with foundations that have disabled it. However, CF CLI v8 no longer uses Cloud FoundryAPI v2. For more details, refer to this [link](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0032-cfapiv2-eol.md#impact-and-consequences).
circleci/config.yml, is upgraded to CF CLI v8.9.0. This version supports Cloud Foundry API v3. Deploying to a cloud.gov space should work smoothly with this update.
1 developer
- install cf cli section
- deploy api (to cloud.gov space)
**Before:**
[cf cli v7.1.0 circleci build …
> upgrade cf cli 

- tests/test_legal.py
- webservices/resources/legal.py
- Resolves #6119 
This PR fixes the proximity search and allows us to determine which document the hit came from. 
When a user inputs q_proximity only, document_highlights and highlights will be empty and source will contain the documents that matches the proximity query. 
When a user inputs both a q_proximity and q the highlights will be from q only and source will contain the documents that match the proximity query. 
- legal search
- start elasticsearch `./elasticsearch`
- `pytest`
- create case index: `python cli.py create_index case_index`
- create ao index: `python cli.py create_index ao_index`
- load sample data for ao, mur, af, and adrs(at least three of each) : `python cli.py load_current_murs` `python cli.py load_admin_fines` `python cli.py …
> Combine nested queries

- tests/integration/test_ao_elasticsearch.py
- tests/integration/test_cases_elasticsearch.py
- webservices/resources/legal.py
- Resolves #6127 
This PR changes the meaning of the proximity_filter to mean that the proximity_filter_term comes before or after the q_proximity terms.
- legal search
- start elasticsearch `./elasticsearch`
- `pytest`
- create case index: `python cli.py create_index case_index`
- load sample data for mur ) : `python cli.py load_current_murs`
- see test URLs below 
Test URLs reference the following documents: MUR 8285
http://127.0.0.1:5000/v1/legal/search/?q_proximity=Dowell%20daunting&max_gaps=2&proximity_filter=after&proximity_filter_term=remediation
http://127.0.0.1:5000/v1/legal/search/?q_proximity=Dowell%20daunting&max_gaps=2&proximity_filter=before&proximity_filter_term=remediation
> Change before and after filters in legal proximity search

- webservices/resources/legal.py
- Resolves #6121 
This PR fixes a bug where inputting zero returns all results in legal search. This affects `max_gaps` (fixed in other PR),  `af_rtb_fine_amount`, and `af_fd_fine_amount`. 
- legal search
- activate virtualenv
- `pytest`
- load admin fines `python cli.py load_admin_fines`
- flask run 
Example URLs:
http://127.0.0.1:5000/v1/legal/search/?af_rtb_fine_amount=0
http://127.0.0.1:5000/v1/legal/search/?af_fd_fine_amount=0
Compare to dev:
https://fec-dev-api.app.cloud.gov/v1/legal/search/?af_rtb_fine_amount=0
https://fec-dev-api.app.cloud.gov/v1/legal/search/?af_fd_fine_amount=0
> Allow zero input from integer filters in legal search

- data/migrations/V0308__add_parsed_name_candidate_detail_mv.sql
- webservices/common/models/candidates.py
- Resolves #6084 
Add candidate first name, last name, middle name, prefix and suffix to ofec_candidate_detail_mv and related endpoint.
/candidate/{candidate_id}/
1 dev
3. Run `flyway migrate`
4. Test endpoints on local
Test APIs:
http://127.0.0.1:5000/v1/candidate/H8CA05035/
http://127.0.0.1:5000/v1/candidate/H0IL13074/
> 60847-Add parsed candidate name to candidate detail

- tests/test_candidates.py
- webservices/common/models/candidates.py
- Resolves #6084
- Ref PR: #6129 
Add test case for the 5 new fields: 
candidate_first_name, candidate_last_name, candidate_middle_name, candidate_prefix and candidate_suffix in endpoint /candidate/{candidate_id}/
1 dev
1. Checkout feature branch
3. Test endpoints on local
Test APIs:
http://127.0.0.1:5000/v1/candidate/H8CA05035/
http://127.0.0.1:5000/v1/candidate/H0IL13074/
> Add test candidate parsed name

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
upgrade flyway to v11.3.1 to remediate snyk vulnerability
1 Developer
- DB migrations
1. run `git checkout feature/6135-upgrade-flyway`
2. Update flyway run:  `brew upgrade flyway`
4. Confirm flyway version 11.3.1: `flyway -v` 
5. run `dropdb cfdm_test`
6. run `createdb cfdm_test`
7. run `invoke create-sample-db`
8. run `pytest`
9. run `snyk test --file=data/flyway/build.gradle`  (snyk no longer flags flyway as vulnerable pkg )
> upgrade flyway 

- webservices/resources/legal.py
- Resolves #6133 
This PR fixes q_exclude filter for statutes
1-2 devs
-statutes keyword search q_exclude filter
- start elasticsearch
- pytest
- python cli.py load_statutes
-  http://127.0.0.1:5000/v1/legal/search/?q=%22federal%20funds%22 (1 result)
-  http://127.0.0.1:5000/v1/legal/search/?q=%22federal%20funds%22&q_exclude=prohibition (0 results) 
compare with prod:
https://api.open.fec.gov/v1/legal/search/?q=%22federal%20funds%22&q_exclude=prohibition&api_key=DEMO_KEY
- try out another query with q_exclude
> fix q_exclude for statutes

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
flyway v11.3.1 comes with  `netty-common@4.1.115.Final` and `netty-handler@4.1.94.Final`  JARs  and snyk flagged this two JARs as vulnerable. Upgrading flyway to v11.3.3  to resolves snyk vulnerability. 
Local path of these two jars: `/opt/homebrew/Cellar/flyway/11.3.X/libexec/lib/netty`
| flyway v11.3.1 vulnerable jars |  flyway v11.3.3 upgraded jars |
| ------------- | ------------- |
| netty-common@4.1.115.Final | netty-common@4.1.118.Final |
netty-handler@4.1.94.Final | netty-handler@4.1.118.Final  |
- Resolves #https://github.com/fecgov/openFEC/issues/6143
1 Developer
- DB migrations
1. run `git checkout feature/6143-upgrade-flyway`
2. Update flyway run:  `brew upgrade flyway`
4. Confirm flyway version 11.3.3: `flyway -v` 
5. run `dropdb cfdm_test`
6. run `createdb cfdm_test`
7. run …
> upgrade flyway to V11.3.3

- webservices/resources/legal.py
- Resolves #6131 
This PR adds q_exclude to simple_query_string which will allow users to set fuzziness and do phrase negation
You should be able have a singular term, multiple terms, phrases, or any of the above with a fuzziness set at the end of the string for q_exclude
EX: q_exclude=Limon
`q_exclude=Limon Federa`
`q_exclude=Limon Federa~1`
`q_exclude=Limon~2`
2 devs
-legal search exclusions for the keyword search 
-pull this branch
-start your venv
-pytest
-python cli.py delete_index ao_index 
-python cli.py delete_index case_index 
-python cli.py delete_index arch_mur_index
-python cli.py create_index ao_index 
-python cli.py create_index case_index 
-python cli.py create_index arch_mur_index
-python cli.py load_statutes …
> 6131 switch q_exclude to SQS

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
Upgrading flyway to v11.4.0  to resolves snyk vulnerability. 
- Resolves #https://github.com/fecgov/openFEC/issues/6143
1 Developer
- DB migrations
1. run `git checkout feature/6143-upgrade-flyway`
2. Update flyway run:  `brew upgrade flyway`
4. Confirm flyway version 11.4.0: `flyway -v` 
5. run `dropdb cfdm_test`
6. run `createdb cfdm_test`
7. run `invoke create-sample-db`
8. run `pytest`
9. run `snyk test --file=data/flyway/build.gradle`  (snyk no longer flags flyway as vulnerable pkg )
> upgrade flyway

- webservices/resources/legal.py
Update ao_commenter, ao_requestor and ao_representative filter parameters from match to use simple query string search type. This update will ensure that both exact match and partial match results are returned.
- Resolves #6146 
2 or more 
legal/search endpoint ao filter parameters, ao_commenter, ao_requestor and ao_representative
- Feel free to deploy a test branch to Dev space and test this PR with a broader data set
- To set up the local Elasticsearch service, please follow this wiki [here](https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-setup-and-test-locally#1-install-elasticsearch-7x0-locally-both-740-and-760-work-well)
- git checkout feature/6146-ao-commenter-representative-requestor-sqs
- run `pytest`
- run `python cli.py create_index ao_index` (create ao_index on local …
> Change ao_commenter, ao_requestor and ao_representative to use simple query string search type

- tests/integration/test_advisory_opinions.py
- tests/integration/test_ao_elasticsearch.py
- tests/test_legal.py
- tests/test_legal_data.py
- webservices/args.py
- webservices/docs.py
- webservices/legal_docs/advisory_opinions.py
- webservices/legal_docs/archived_murs.py
- webservices/legal_docs/current_cases.py
- webservices/legal_docs/es_management.py
- webservices/resources/legal.py
- Resolves #6155 
Adds filename field and filter
1-2 devs
- Legal search 
You will need to reload your documents
- Checkout branch
- `pytest`
- `python cli.py delete_index ao_index`
- `python cli.py delete_index case_index`
- `python cli.py delete_index arch_mur_index`
- `python cli.py create_index case_index`
- `python cli.py create_index ao_index`
- `python cli.py create_index arch_mur_index`
Load some of each document type (I wait for ~5 to be loaded of each)
- `python cli.py load_adrs`
- `python cli.py load_advisory_opinions`
- `python cli.py load_current_murs`
- `python cli.py load_statutes`
- `python cli.py load_archived_murs`
- `flask run`
- http://127.0.0.1:5000/v1/legal/search/?filename=4777_01
- …
> 6155- add filename filter and tests to legal search

- tests/integration/test_ao_elasticsearch.py
- webservices/resources/legal.py
- Resolves #6167 
Add logic to sort advisory opinions by `issue_date` parameter 
2 or more developers
- legal/search api endpoint
- ao datatables in cms
- run `git checkout feature/6167-add-ao-sort-by-issue-date`
- run `pytest`
- run `python cli.py delete_index ao_index` (delete existing index from local elasticsearch service)
- run `python cli.py create_index ao_index` (create new ao_index on local elasticsearch service)
- **Note: switch SQLA_CONN to point to Stage database. Dev data is not clean.**
- run `python cli.py load_advisory_opinions` (load few advisory_opinion documents from 2025-05 to 2023-12)
- run `flask run` (start server)
- test urls to sort by ao_no and issue_date for advisory_opinion document type
- ### test the following urls when `ao_status=final` parameter is set:
- …
> add functionality to sort advisory opinions by issue_date

- .circleci/config.yml
- README.md
- data/flyway/build.gradle
- data/flyway/manifest_headless_flyway.yml
Upgrading flyway to v11.6.0  to resolves snyk vulnerability. There are no breaking changes with this new version: https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine
- Resolves #https://github.com/fecgov/openFEC/issues/6159
1 Developer
- DB migrations
1. checkout this branch 
2. start your virtualenv 
3. Update flyway run:  `brew upgrade flyway`
4. Confirm flyway version 11.6.0: `flyway -v` 
5. run `dropdb cfdm_test`
6. run `createdb cfdm_test`
7. run `invoke create-sample-db`
8. run `pytest`
9. run `snyk test --file=data/flyway/build.gradle`  (snyk no longer flags flyway as vulnerable pkg )
> upgrade flyway v11.6

- requirements.txt
- Resolves #6176 
Upgrades gunicorn to 23.0.0 to remediate snyk vulnerability
[Breaking Changes ](https://docs.gunicorn.org/en/latest/news.html)
refuse requests where the uri field is empty 
refuse requests with invalid CR/LR/NUL in heade field values 
remove temporary --tolerate-dangerous-framing switch from 22.0
1 dev
-  gunicorn servers
https://github.com/fecgov/fec-cms/pull/6743
- gh pr checkout 6187
- gunicorn --access-logfile - --error-logfile - --log-level info --timeout 300 -k gevent -w 4 'webservices.rest:create_app()'
- http://127.0.0.1:8000
- http://127.0.0.1:8000/v1/schedules/schedule_d/?page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nul …
> 6176- upgrade gunicorn  to v.23.0.0

- tests/integration/test_ao_elasticsearch.py
- tests/integration/test_cases_elasticsearch.py
- webservices/args.py
- webservices/docs.py
- webservices/resources/legal.py
- Resolves #6164 
This PR adds the `proximity_preserve_order` boolean filter that determines if order matters between multiple `q_proximity` phrases.
- legal proximity search 
- start a virtualenv
- start elasticsearch `./elasticsearch`
- `pytest`
- create case index: `python cli.py create_index case_index`
- create ao index: `python cli.py create_index ao_index`
- load sample data for ao, mur, af, and adrs: `python cli.py load_current_murs` `python cli.py load_admin_fines` `python cli.py load_advisory_opinions` `python cli.py load_adrs`
- `flask run`
- see test URLs below 
Test URLs reference the following documents: MUR 8282, AO 2024-10
MUR 8282
Default false: …
> Add proximity_preserve_order filter

- .circleci/config.yml
- Resolves #6195 
This PR upgrades postgres to v13.16 in our circleci pipeline.
- circleci pipeline 
- rerun this [branch](https://app.circleci.com/pipelines/github/fecgov/openFEC?branch=feature%2F6195-upgrade-pg-circleci) in circleci
> Upgrade postgres in circleci pipeline

- webservices/docs.py
- webservices/resources/legal.py
For advisory opinions, sort by issue_date asc works as expected. However, when sort_by issue_date desc, the results are inconsistent. This PR fixes the inconsistent results when sort by issue_date.
Update the description of SORT constant in docs.py 
- Resolves issue #6196 
- Related pr # https://github.com/fecgov/openFEC/pull/6173
2 or more developers
- legal/search api endpoint
- run `git checkout feature/6196-update-sort-issue_date`
- run `pytest`
- run `python cli.py delete_index ao_index` (delete existing index from local elasticsearch service)
- run `python cli.py create_index ao_index` (create new ao_index on local elasticsearch service)
- **Note: switch SQLA_CONN to point to Stage database. Dev data is not clean.**
- run `python cli.py load_advisory_opinions` (load few …
> Update logic to sort by issue_date

- tests/test_swagger.py
- webservices/docs.py
- webservices/legal_docs/responses.py
- webservices/resources/legal.py
- webservices/rest.py
- Resolves #6179
Add legal/docs endpoint to swagger, fix swagger validation test
1-2 dev
- swagger docs legal endpoint
- pytest
- test swagger docs:
http://127.0.0.1:5000
- http://127.0.0.1:5000/v1/legal/docs/statutes/9001/
- http://127.0.0.1:5000/v1/legal/docs/advisory_opinions/2025-05/
- http://127.0.0.1:5000/v1/legal/docs/murs/8353/
- http://127.0.0.1:5000/v1/legal/docs/adrs/1203/
- http://127.0.0.1:5000/v1/legal/docs/admin_fines/4777/
-
- Test 404:
http://127.0.0.1:5000/v1/legal/docs/statutes/test
http://127.0.0.1:5000/v1/legal/docs/statutes/test
> 6179-add legal/docs to swagger

- tests/test_monitoring.py
- webservices/api_setup.py
- webservices/resources/monitoring.py
- webservices/rest.py
- webservices/tasks/__init__.py
- webservices/tasks/celery.py
- webservices/tasks/service_status_checks.py
- webservices/tasks/utils.py
- Resolves #6191
This PR creates an endpoint to monitor the status of `celery-beat`, `celery-worker`, and `redis`. This method was borrowed from [fecfile](https://github.com/fecgov/fecfile-web-api/pull/1292/files). Once merged I will create the pingdom check! 
- tasks 
- celery 
On dev 
- Deploy this [branch](https://app.circleci.com/pipelines/github/fecgov/openFEC?branch=test-celery-dev) and test the endpoint: https://fec-dev-api.app.cloud.gov/v1/monitoring/celery_check/. 
locally: 
Terminal One:
- start your virtual environment 
- `pytest`
- `flask run` (keep running)
- comment out `broker_use_ssl`, `redis_backend_use_ssl`, and + `?ssl=true `
Terminal Two: 
- start redis `redis-server`
Terminal …
> Create task and endpoint to monitor celery

- tests/integration/test_ao_elasticsearch.py
- webservices/args.py
- webservices/docs.py
- webservices/resources/legal.py
- Resolves #6206 
adds ao_year filter
2 devs
- legal endpoint
- start your venv and elasticsearch
- python cli.py load_advisory_opinions
- load multiple years advisory opinions (at least one of 2024) 
- flask run
- http://127.0.0.1:5000/v1/legal/search/?ao_year=2024
- http://127.0.0.1:5000/v1/legal/search/?ao_year=2025
> 6206 add ao_year filter

- requirements.txt
- webservices/tasks/celery.py
- Resolves #6194 
Fixes max broker_connection_max_retries to match documentation [here](https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-broker_connection_max_retries) and upgrades kombu to lts. In upgrading kombu, we should unpin vine (a kombu dependency).  
I tried recreating an issue where redis was disconnected locally and found that our celery-worker gets stuck in the mingle process after being disconnected from redis. I think this is what happened with our recent outages. 
Here's some helpful threads on this issue:
[celery worker](https://github.com/celery/celery/pull/8796)
[kombu](https://github.com/celery/kombu/pull/2007)
PR about max_retries
[broker_connection_max_retries](https://github.com/celery/celery/pull/8626) 
2-3 devs
General components of the …
> 6194-upgrade kombu

- data/migrations/V0309__add_published_flg_to_aouser_ao.sql
- Resolves #6213 
Add published_flg column to aouser.ao table to reflect the change and facilitate Elasticsearch reloading.
1 dev
2. Run these command for testing
`pytest`
`flyway migrate`
3. Test flyway rerun
delete this version from flyway_schema_history, and run `flyway migrate` again. There should no error message.
> Add published_flg column 

- requirements.txt
- Resolves #6216 
This PR upgrades setuptools to v78.1.1 to remove a snyk vulnerability. 
2-3 developers
- package installation during deploy
- activate your virtualenv 
- `snyk test --file=requirements.txt --package-manager=pip` (vulnerability should be gone)
- deploy to dev or stage. You can use [this](https://app.circleci.com/pipelines/github/fecgov/openFEC?branch=test-setuptools-dev) test branch
> 6216- upgrade setuptools

- webservices/common/counts.py
- webservices/resources/candidates.py
- webservices/resources/committees.py
- webservices/resources/reports.py
- webservices/resources/totals.py
- webservices/tasks/download.py
This hotfix fixes an issue with candidate and committee table downloads when there are multiple cycles or election years chosen combined with a filter that utilizes `in_`. 
- downloads
- test downloads on stage: https://stage.fec.gov/
Test URLs: 
https://stage.fec.gov/data/committees/?cycle=2010&cycle=2018&cycle=2024&party=DEM
https://stage.fec.gov/data/candidates/?election_year=2018&election_year=2025&election_year=2027&election_year=2028&is_active_candidate=true&has_raised_funds=true&party=DEM
> [MERGE WITH GITFLOW] Hotfix/fix candidate committee download

- webservices/resources/legal.py
- Resolves #6297
This PR sorts the AO source documents by category id (with final opinions first) then by relevance score. 
- AO legal search
- start virtualenv 
- start elasticsearch
- `flask run`
- test AO proximity search and ensure source documents are sorted correctly 
Sample URLs:
http://127.0.0.1:5000/v1/legal/search/?type=advisory_opinions&q_proximity=responding&q_proximity=request&max_gaps=10000&ao_no=2024-05
> Add sort to AO _source documents

- requirements.txt
- tests/test_swagger.py
- webservices/args.py
- webservices/resources/dates.py
- webservices/resources/download.py
- webservices/schemas.py
- webservices/utils.py
- Resolves #6279 & #6281 
This PR upgrades `marshmallow`, `apispec`, and `marshmallow_sqlalchemy` to reduce warnings and allow us to upgrade python in the future. 
- swagger docs 
- all fields
- create and activate a new virtualenv 
- `pytest`
- `flask run`
- Test swagger:
http://127.0.0.1:5000/swagger/
(ensure metadata for descriptions and refs is correct)
- Run queries using frontend to ensure default values are loaded correctly
- Run some queries to ensure there's no change to schemas.
Here is the documentation for the upgrades:
marshmallow: https://marshmallow.readthedocs.io/en/latest/changelog.html
- `missing` is replaced with `load_default`
- `default` is …
> Upgrade marshmallow

- webservices/legal_docs/es_management.py
- webservices/resources/legal.py
- Resolves #6325
We need to switch filename filter to keyword/term due to hyphens. This is the more efficient query than match_phrase. 
We need to make this change ASAP for saos decommission, but might want to do follow-up changes with the rulemakings filename search before that's available. 
1-2 devs
- legal
Rebuild this branch on dev, dev has already been reindexed
- https://app.circleci.com/pipelines/github/fecgov/openFEC/3720
- https://fec-dev-api.app.cloud.gov/v1/legal/search/?filename=4666
- https://fec-dev-api.app.cloud.gov/v1/legal/search/?filename=1976-06
- https://fec-dev-api.app.cloud.gov/v1/legal/search/?filename=4854_01
- https://fec-dev-api.app.cloud.gov/v1/legal/search/?filename=1199_02
You can also pull this …
> 6325- fix filename search
